### ISSUE TITLE
Can't toggle windows between tiling/floating modes

### ISSUE THREAD

**Issue by ghost** [swaywm/sway#3079] opened 2018-11-05 19:43 UTC
Sway version: sway version 1.0-beta.1-145-gd0bb4506 (Nov  5 2018, branch 'master')
sway config https://pastebin.com/yeaLr5Qx
sway log https://pastebin.com/d0gZnVpa

Can't toggle windows between floating tiling modes unless I comment out my keyboard input in config file or "bindsym $mod+space focus mode_toggle".

Steps to reproduce:
1.Open any window
2.Press $mod+Shift+space

**Comment by ppascher** [comment] 2018-11-05 20:06
Duplicate of #2797 ?

**Comment by emersion** [comment] 2018-11-05 20:15
Yeah, but it definitely should work.

**Comment by k2tsu** [comment] 2018-11-05 21:04
Everything works fine until I change keyboard keymap as you can see in my config file.

**Comment by ppascher** [comment] 2018-11-06 09:58
I have the same problem using the following keymap:
```export XKB_DEFAULT_OPTIONS=
 export XKB_DEFAULT_LAYOUT=de
 export XKB_DEFAULT_VARIANT=adnw
 export XKB_DEFAULT_MODEL=pc105
```
I always blamed it on the error I reported in issue #1573 : 
`xkbcommon: ERROR: Key "<LFSH>" added to modifier map for multiple modifiers; Using Lock, ignoring Shift`
so mod+shift+space and mod+space are considered the same. That's probably why commenting the mod+space key binding makes mod+shift+space work. Just guessing though.

**Comment by lephe** [comment] 2018-11-20 20:21
> This seems to only happen on non-US keyboards. Another user reported that it also happens with `fr`.

For what it's worth, I have `XKB_DEFAULT_LAYOUT=fr` (variant and model unset) and the two commands are properly differentiated.

**Comment by emersion** [comment] 2018-11-20 20:57
@lephe Ah, interesting. What are the relevant lines of your config? (Maybe capitalization matters)

**Comment by lephe** [comment] 2018-11-21 07:21
Nothing in the config file, only environment variables in my login script:

    WLR_DRM_DEVICES=/dev/dri/card0 XKB_DEFAULT_LAYOUT=fr exec sway

**Comment by 0xdec** [comment] 2019-01-17 05:56
Any chance this can get fixed before 1.0? I'm experiencing it on both US and US Colemak. Happy to post any other relevant info.

**Comment by emersion** [comment] 2019-01-17 08:43
Please help us investigate the issue.

**Comment by Ninja3047** [comment] 2019-02-15 22:28
Same issue here

I'm also using US and US Colemak

[sway.log](https://sr.ht/yNGV.log)
[sway config](https://sr.ht/dDe2.config)

Relevant portions of the log files seem to be
```
2019-02-15 16:59:20 - [sway-1.0-rc2/sway/config.c:729] Read line 178:     bindsym $mod+Shift+space floating toggle
2019-02-15 16:59:20 - [sway-1.0-rc2/sway/commands.c:357] Config command: bindsym $mod+Shift+space floating toggle
2019-02-15 16:59:20 - [sway-1.0-rc2/sway/commands.c:145] find_handler(bindsym)
2019-02-15 16:59:20 - [sway-1.0-rc2/sway/commands.c:377] After replacement: bindsym Mod4+Shift+space floating toggle
2019-02-15 16:59:20 - [sway-1.0-rc2/sway/commands/bind.c:315] bindsym - Bound Mod4+Shift+space to command `floating toggle` for device '*'
2019-02-15 16:59:20 - [sway-1.0-rc2/sway/config.c:729] Read line 179:
2019-02-15 16:59:20 - [sway-1.0-rc2/sway/config.c:729] Read line 180:     # Swap focus between the tiling area and the floating area
2019-02-15 16:59:20 - [sway-1.0-rc2/sway/config.c:729] Read line 181:     bindsym $mod+space focus mode_toggle
2019-02-15 16:59:20 - [sway-1.0-rc2/sway/commands.c:357] Config command: bindsym $mod+space focus mode_toggle
2019-02-15 16:59:20 - [sway-1.0-rc2/sway/commands.c:145] find_handler(bindsym)
2019-02-15 16:59:20 - [sway-1.0-rc2/sway/commands.c:377] After replacement: bindsym Mod4+space focus mode_toggle
2019-02-15 16:59:20 - [sway-1.0-rc2/sway/commands/bind.c:315] bindsym - Bound Mod4+space to command `focus mode_toggle` for device '*'
...
2019-02-15 16:59:23 - [sway-1.0-rc2/sway/input/keyboard.c:184] encountered duplicate bindings 51 and 50
2019-02-15 16:59:23 - [sway-1.0-rc2/sway/commands/bind.c:331] running command for binding: focus mode_toggle
2019-02-15 16:59:23 - [sway-1.0-rc2/sway/commands.c:253] Handling command 'focus mode_toggle'
2019-02-15 16:59:23 - [sway-1.0-rc2/sway/commands.c:145] find_handler(focus)
2019-02-15 16:59:23 - [sway-1.0-rc2/sway/commands/bind.c:339] could not run command for binding: focus mode_toggle (Failed to find a floating container in workspace)
2019-02-15 16:59:24 - [sway-1.0-rc2/sway/input/keyboard.c:184] encountered duplicate bindings 51 and 50
2019-02-15 16:59:24 - [sway-1.0-rc2/sway/commands/bind.c:331] running command for binding: focus mode_toggle
2019-02-15 16:59:24 - [sway-1.0-rc2/sway/commands.c:253] Handling command 'focus mode_toggle'
2019-02-15 16:59:24 - [sway-1.0-rc2/sway/commands.c:145] find_handler(focus)
2019-02-15 16:59:24 - [sway-1.0-rc2/sway/commands/bind.c:339] could not run command for binding: focus mode_toggle (Failed to find a floating container in workspace)
2019-02-15 16:59:26 - [sway-1.0-rc2/sway/commands/bind.c:331] running command for binding: focus mode_toggle
2019-02-15 16:59:26 - [sway-1.0-rc2/sway/commands.c:253] Handling command 'focus mode_toggle'
2019-02-15 16:59:26 - [sway-1.0-rc2/sway/commands.c:145] find_handler(focus)
2019-02-15 16:59:26 - [sway-1.0-rc2/sway/commands/bind.c:339] could not run command for binding: focus mode_toggle (Failed to find a floating container in workspace)
2019-02-15 16:59:26 - [sway-1.0-rc2/sway/commands/bind.c:331] running command for binding: focus mode_toggle
2019-02-15 16:59:26 - [sway-1.0-rc2/sway/commands.c:253] Handling command 'focus mode_toggle'
2019-02-15 16:59:26 - [sway-1.0-rc2/sway/commands.c:145] find_handler(focus)
2019-02-15 16:59:26 - [sway-1.0-rc2/sway/commands/bind.c:339] could not run command for binding: focus mode_toggle (Failed to find a floating container in workspace)
2019-02-15 16:59:26 - [sway-1.0-rc2/sway/commands/bind.c:331] running command for binding: focus mode_toggle
2019-02-15 16:59:26 - [sway-1.0-rc2/sway/commands.c:253] Handling command 'focus mode_toggle'
2019-02-15 16:59:26 - [sway-1.0-rc2/sway/commands.c:145] find_handler(focus)
2019-02-15 16:59:26 - [sway-1.0-rc2/sway/commands/bind.c:339] could not run command for binding: focus mode_toggle (Failed to find a floating container in workspace)
```

This switching the shortcut to something else works fine and removing the keyboard variant customization section of the config also seems to work fine

**Comment by lephe** [comment] 2019-02-16 08:46
I noticed this also depends on the selected variant in `fr` layouts. Earlier in this thread I mentioned the shortcut worked for me, this was the case when the variant was unset.

I currently have two variants, namely `oss` and `bepo`, and I can only use `shift+super+space` with the second one. It is very clear that `shift+super+space` in `oss` variant executes the binding for `super+space`, whatever it is.

The only relevant difference I see is that in `oss`, `shift+space` is just a space, but in `bepo`, `shift+space` is a non-breakable space. But I figure sway's key bindings are at a lower level.

**Comment by ronchaine** [comment] 2019-02-26 08:02
```xkb_layout fi``` also makes me unable to bind both ```shift+space``` and ```mod+shift+space```

**Comment by exastion** [comment] 2019-03-04 14:40
Same issue here using de,neo and also under de without variant, but with both configured.
```
input '*' {
    xkb_layout  de,de
    xkb_variant neo,
    xkb_options grp:alt_shift_toggle
}
```

**Comment by ddevault** [comment] 2019-03-04 14:48
Less "I can reproduce", more "here's a patch", please.

**Comment by emersion** [comment] 2019-03-04 16:21
Note: someone started investigating the issue: https://github.com/swaywm/sway/issues/3705#issuecomment-469008357

**Comment by RedSoxFan** [comment] 2019-03-11 02:53
Closing via #3855

**Closed by RedSoxFan** 2019-03-11 02:53 UTC
Labels: bug
