### ISSUE TITLE
Very large outer gaps make the view disappear

### ISSUE THREAD

**Issue by pedrocr** [swaywm/sway#4300] opened 2019-07-02 13:47 UTC
* Sway Version: 1.1-rc1-51-gf5d1c272 (Jul  2 2019, branch 'master')
* Debug Log: https://gist.github.com/pedrocr/1e8c8b463db9c95ac94f76222b0885a5
* Configuration File: default config

Setting some very large outer gaps breaks the layout making all the views disappear. To replicate just open a terminal and then do:

```
swaymsg gaps outer all set 10000
```

Just like with inner gaps in issue #4294 the view will completely disappear.

**Comment by RedSoxFan** [comment] 2019-08-01 04:56
Closed by #4310 _(#4308 was technically a duplicate of this one)_

**Closed by RedSoxFan** 2019-08-01 04:56 UTC

**Comment by pedrocr** [comment] 2019-08-01 06:58
Ah, I opened the bug twice. Sorry
