### ISSUE TITLE
Reloading config doesn't set new modes/scale/etc

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#1656] opened 2018-03-30 13:15 UTC

**Comment by emersion** [comment] 2018-04-06 03:07
Cannot reproduce anymore, likely fixed in the last 7 days.

**Closed** 2018-04-06 03:07 UTC
Labels: wlroots

**Comment by SirCmpwn** [comment] 2018-04-06 03:11
```
output X11-1 scale 2
```

Start sway, edit config to remove that line, reload

Probably not wlroots-specific

**Comment by emersion** [comment] 2018-04-06 03:25
Hum, I'm not sure how to fix this. Not specifying an ouput option means "don't change it".

**Comment by SirCmpwn** [comment] 2018-04-06 03:27
At runtime, sure. At reload time we should probably reset everything imo.

**Comment by emersion** [comment] 2018-04-06 03:31
#1752
