### ISSUE TITLE
GTK3 settings do not apply

### ISSUE THREAD

**Issue by pat-s** [swaywm/sway#4323] opened 2019-07-12 09:17 UTC
None of the approaches listed in the [wiki](https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland) works for me.

Tested on Sway 1.1.1 and latest master.

I verified that the the values were set/changed correctly using `gsettings` but it seems they are not picked up by the applications.

**Comment by asahaf** [comment] 2019-07-12 09:40
Put this in your sway config file:

```
exec_always {
    gsettings set $gnome-schema gtk-theme 'theme name'
    gsettings set $gnome-schema icon-theme 'icon theme name'
    gsettings set $gnome-schema cursor-theme 'cursor theme name'
    gsettings set $gnome-schema font-name 'Sans 10'
}
```

**Comment by pat-s** [comment] 2019-07-12 10:24
I tried this already since its mentioned in the linked post.
Also you're missing defining `$gnome-schema` in your example.

As said, changing the `gsettings` values works. Even if I do it manually apps do not pick up the change.

**Comment by asahaf** [comment] 2019-07-12 10:34
That's right. you need this before you call exec_always:

`set $gnome-schema org.gnome.desktop.interface`

you can try using the env var option, for the theme.
`
export GTK_THEME=theme-name`

**Comment by RedSoxFan** [comment] 2019-07-23 04:40
Duplicate of #4118

**Closed by RedSoxFan** 2019-07-23 04:40 UTC

**Comment by pat-s** [comment] 2019-07-23 09:21
It's not a duplicate since I tried all the workarounds mentioned in the linked issue and in the sway wiki...

**Comment by emersion** [comment] 2019-07-23 10:00
Well, in any case, sway doesn't have anything to do with GTK+ config.

**Comment by colemickens** [comment] 2019-07-25 02:24
You're likely suffering from the same root cause as this issue: https://github.com/swaywm/sway/issues/4112#issuecomment-509465006

I just removed the cursor packages from my system and found myself in the same situation again. Make sure you have some cursor theme, and make sure it's set in the gtk-3.0 settings.ini.

**Comment by pat-s** [comment] 2019-07-25 08:02
Thanks for the hint. That sounded promising because I did not have a cursor theme set indeed in settings.ini.

However, I still cannot get it to work.

In `settings.ini` I have

```
gtk-theme-name=Adwaita-dark
gtk-icon-theme-name=ArchLabs-Dark
gtk-font-name=Cantarell 11
gtk-cursor-theme=Adwaita
```

which I import from the sway config via

```
exec_always import-gsettings \
    gtk-theme:gtk-theme-name \
    icon-theme:gtk-icon-theme-name \
    cursor-theme:gtk-cursor-theme-name
```

where `import-gsettings` is the script from the [Sway wiki](https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland)

I can query the values and they seem to be correct

```
gsettings get org.gnome.desktop.interface gtk-theme                                            
'Adwaita-dark'
gsettings get org.gnome.desktop.interface cursor-theme                                         
'Adwaita'
gsettings get org.gnome.desktop.interface icon-theme                                           
'ArchLabs-Dark'
```

but still the themes are not picked up by the GTK apps.


@emersion 	

> Well, in any case, sway doesn't have anything to do with GTK+ config.

While I understand your policy here, I think there is no other place where users can talk about such issues which are related to sway (even if they do not fall under Sways responsibility). I do not mind whether the issue is closed or open as long as I can browse for a solution at the most likely place :)

**Comment by progandy** [comment] 2019-07-25 09:58
Are you using flatpak applications (or the file ```/.flatpak-info``` exists or ```GTK_USE_PORTAL=1``` is exported) that then will try to get their settings from an xdg-portal and you have the gnome portal installed and it gets started? 

One solution is to complete [xdg-desktop-portal-wlr](https://github.com/emersion/xdg-desktop-portal-wlr) and run it. Otherwise make sure that the gnome portal is not running and can't be autostarted by dbus.

**Comment by pat-s** [comment] 2019-07-25 14:45
> Are you using flatpak applications (or the file /.flatpak-info exists or GTK_USE_PORTAL=1 is exported) 

both negative

**Comment by colemickens** [comment] 2019-08-29 15:20
Actually, I'm seeing this too. I can execute the script from a bash terminal and see my cursor immediately change in my GTK3 apps.

But, if I manually set the cursor theme to a bad one, and then run this via `exec_always` and reload sway, it absolutely does not work.

I'm wondering if `gsettings` when run by Sway isn't able to talk to the right backend or something?

**Comment by teackot** [comment] 2024-02-10 22:51
I am also facing a similar problem. I am trying to change the `text-scaling-factor` setting by running

```
gsettings set org.gnome.desktop.interface text-scaling-factor 1.38
```

This setting works with native apps, but flatpaks don't pick it up. I tried installing `xdg-desktop-portal-wlr` like @progandy suggested, but it didn't fix anything.

**Comment by progandy** [comment] 2024-02-10 23:07
You probably also need `xdg-desktop-portal-gtk` as the wlroots portals do not include an implementation for the settings portal.

**Comment by teackot** [comment] 2024-02-10 23:16
False alarm, I just didn't install it properly, I had to do this: https://github.com/emersion/xdg-desktop-portal-wlr/issues/80#issuecomment-787034115
