### ISSUE TITLE
SIGSEGV when navigating menus in libreoffice (and zim)

### ISSUE THREAD

**Issue by fdlamotte** [swaywm/sway#5385] opened 2020-05-26 05:53 UTC
I've had a strange behaviour last month with sway (currently using sway version 1.4-5d13f647 (May 25 2020, branch 'master'))

Once in the menu of some applications (libreoffice, zim), if I leave the window without closing the menu (leaving it to the titlebar for instance) sway crashes. Don't know if it is related to sway or wlroots, but since I experience this in sway I report it here.

I managed to get some time to grab a backtrace, here it is :

```
(gdb) bt full
#0  0x00007fe93798c8b0 in xdg_pointer_grab_enter (grab=0x55d12643ee28, surface=0x0, sx=0, sy=0) at ../types/xdg_shell/wlr_xdg_popup.c:21
        popup_grab = 0x55d12643ee20
#1  0x00007fe9379801ea in wlr_seat_pointer_notify_enter (wlr_seat=0x55d12609a4d0, surface=0x0, sx=0, sy=0) at ../types/seat/wlr_seat_pointer.c:335
        grab = 0x55d12643ee28
#2  0x000055d123f27884 in handle_pointer_motion (seat=0x55d12609a2f0, time_msec=607323872, dx=0, dy=-1.7578125) at ../sway/input/seatop_default.c:482
        e = 0x55d126440230
        cursor = 0x55d12609a910
        surface = 0x0
        sx = 4.6618440994583485e-310
        sy = 97.390625
        node = 0x55d126396000
        drag_icon = 0x7fe93799418d <wlr_cursor_move+194>
#3  0x000055d123f26031 in seatop_pointer_motion (seat=0x55d12609a2f0, time_msec=607323872, dx=0, dy=-1.7578125) at ../sway/input/seat.c:1463
#4  0x000055d123f1bc54 in pointer_motion (cursor=0x55d12609a910, time_msec=607323872, device=0x55d1260ecc10, dx=0, dy=-1.7578125, dx_unaccel=0, dy_unaccel=-2) at ../sway/input/cursor.c:327
#5  0x000055d123f1bcd2 in handle_pointer_motion_relative (listener=0x55d12609aa40, data=0x7ffcef218b30) at ../sway/input/cursor.c:335
        cursor = 0x55d12609a910
        e = 0x7ffcef218b30
#6  0x00007fe9379b85ac in wlr_signal_emit_safe (signal=0x55d12609abf8, data=0x7ffcef218b30) at ../util/signal.c:29
        pos = 0x55d12609aa40
        l = 0x55d12609aa40
        cursor = {link = {prev = 0x55d12609aa40, next = 0x7ffcef218a10}, notify = 0x7fe9379b8505 <handle_noop>}
        end = {link = {prev = 0x7ffcef218a30, next = 0x55d12609abf8}, notify = 0x7fe9379b8505 <handle_noop>}
#7  0x00007fe937994314 in handle_pointer_motion (listener=0x55d1263916c0, data=0x7ffcef218b30) at ../types/wlr_cursor.c:355
        event = 0x7ffcef218b30
        device = 0x55d126391690
#8  0x00007fe9379b85ac in wlr_signal_emit_safe (signal=0x55d1261542f8, data=0x7ffcef218b30) at ../util/signal.c:29
        pos = 0x55d1263916c0
        l = 0x55d1263916c0
        cursor = {link = {prev = 0x55d1263916c0, next = 0x7ffcef218ab0}, notify = 0x7fe9379b8505 <handle_noop>}
        end = {link = {prev = 0x7ffcef218ad0, next = 0x55d1261542f8}, notify = 0x7fe9379b8505 <handle_noop>}
#9  0x00007fe9379723bb in relative_pointer_handle_relative_motion
    (data=0x55d1260ecc10, relative_pointer=0x55d12630eb00, utime_hi=141, utime_lo=1733483264, dx=0, dy=-450, dx_unaccel=0, dy_unaccel=-512) at ../backend/wayland/seat.c:469
        input_device = 0x55d1260ecc10
        wlr_dev = 0x55d1260ecc10
        time_usec = 607323872000
        wlr_event = {device = 0x55d1260ecc10, time_msec = 607323872, delta_x = 0, delta_y = -1.7578125, unaccel_dx = 0, unaccel_dy = -2}
#10 0x00007fe936e7eccd in  () at /lib/x86_64-linux-gnu/libffi.so.7
#11 0x00007fe936e7e25a in  () at /lib/x86_64-linux-gnu/libffi.so.7
#12 0x00007fe936db61c0 in  () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#13 0x00007fe936db2ad8 in  () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#14 0x00007fe936db408c in wl_display_dispatch_queue_pending () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#15 0x00007fe93796e689 in dispatch_events (fd=4, mask=1, data=0x55d125944370) at ../backend/wayland/backend.c:46
        wl = 0x55d125944370
        count = 0
#16 0x00007fe937a0d402 in wl_event_loop_dispatch () at /lib/x86_64-linux-gnu/libwayland-server.so.0
#17 0x00007fe937a0b9e5 in wl_display_run () at /lib/x86_64-linux-gnu/libwayland-server.so.0
#18 0x000055d123f0de1a in server_run (server=0x55d123f7e240 <server>) at ../sway/server.c:225
#19 0x000055d123f0d402 in main (argc=1, argv=0x7ffcef2192e8) at ../sway/main.c:409
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options =
            {{name = 0x55d123f61088 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55d123f6108d "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55d123f61094 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55d123f6109d "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55d123f610a3 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55d123f610ab "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55d123f610b3 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55d123f610c2 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55d123f610d2 "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55d123f60b60 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```

regards,

**Comment by emersion** [comment] 2020-05-26 05:55
Duplicate of https://github.com/swaywm/sway/issues/5294

**Closed by emersion** 2020-05-26 05:55 UTC
