### ISSUE TITLE
Mouse pointer still effective in window after cursor left window

### ISSUE THREAD

**Issue by Moonlight-Angel** [swaywm/sway#3409] opened 2019-01-11 11:41 UTC
Hello,
The title was kind of hard to find for this issue, if you can think of a better title, please let me know and I'll edit it. The steps to reproduce are pretty easy to understand the issue here.

* Sway Version: 1.0-beta.2-148-g33d9de88 (Jan 11 2019, branch 'master')
* Debug Log: Cannot get debug logs (Don't use options with the IPC client)
* Configuration File: Reproducible with the default configuration
* Steps to reproduce:
  * Open Firefox and some tabs (make sure the Firefox tabs are rendered right at the edge of the window, which is the case with Firefox Quantum's default theme)
  * Move the cursor out of Firefox by the top, so the cursor hovers onto a tab before going out the Firefox window
  * Notice the tooltip is shown although the cursor went out of the Firefox window
  * If a second window is available on the workspace, the Firefox tooltip is still shown even when the cursor (and thus the focus) is moved to the other window on the workspace

**Comment by Emantor** [comment] 2019-01-11 15:42
Probably a duplicate of #2529

**Comment by Moonlight-Angel** [comment] 2019-01-11 21:08
Not sure, the issue you're referencing talks about persistent tooltips after switching workspace. I do get those too from time to time, but I'm talking more about the fact that Firefox still thinks the "mouse pointer" is hovering over one of its tabs, and triggers the tab tooltip even after the mouse has left the window.
Maybe the underlying problem is the same in both cases ? Can't tell.

**Comment by emersion** [comment] 2019-01-11 22:18
Yeah, it's the same issue, it's just triggered differently.

Duplicate of #2529

**Closed by emersion** 2019-01-11 22:18 UTC
