### ISSUE TITLE
Popups made shown by menu selections disappear immediately in JetBrains IDEs

### ISSUE THREAD

**Issue by luispabon** [swaywm/sway#4370] opened 2019-07-25 10:19 UTC
* Sway Version:
Sway master 36aa67e
Wlroots master [76ef089](https://github.com/swaywm/wlroots/commit/76ef089f52b20a2def3dd1f8a8564af165050dcb)

* Debug Log:
https://pastebin.com/Zx0DqhmF

* Configuration File:
https://github.com/luispabon/sway-dotfiles/tree/master/configs/sway 
(happens too on default config)

* Wat
  * Open a jetbrains IDE - in my case either phpstorm, pycharm or goland
  * Menu help > about
  * The about page appears for like 1 frame (sometimes not even that)

`_JAVA_AWT_WM_NONREPARENTING=1` is on my environment
Jetbrains bundled Java 11

* Stack Trace, if sway crashes:

n/a

**Comment by ChrisLane** [comment] 2020-04-19 11:53
Just came across this issue myself.

Arch Linux 5.6.4-arch1-1
IntelliJ Idea 2020.1
Sway 1.4
wlroots 0.10.1
Wayland 1.18.0
java-13-openjdk

_JAVA_AWT_WM_NONREPARENTING=1

**Comment by jc7n** [comment] 2020-06-07 09:18
I took a look at this after @Xyene's recent Jetbrains-related fixes (thanks for those btw). Looks like it's a consequence of https://github.com/swaywm/sway/pull/2103, and in particular the call to `seat_set_focus(seat, NULL);` (`sway/desktop/xwayland.c:117`). Removing this call makes the About popup & other popups from triggered menu items (such as Run -> Run...) work again, but the test case from the PR with `i3-input` then fails.

It seems to be the `seat_send_unfocus()` portion of the `seat_set_focus(seat, NULL)` call that causes problems for IntelliJ and the `seat->has_focus = false` line that make the `i3-input` case work.

I don't understand the internals here enough to make a PR and this is not a proper fix in any sense, but anecdotally, replacing the `seat_set_focus(seat, NULL);` call with `seat->has_focus = false;` seems to make the use cases I care about work and I haven't seen any adverse effects.

**Comment by dynaxis** [comment] 2020-06-11 11:03
Might be better to change the title of this issue. "Popups made shown by menu selections disappear immediately in JetBrains IDEs."

**Comment by Xyene** [comment] 2020-06-13 00:05
@jc7n: I haven't looked into this issue further since it's no longer on the critical path of my day-to-day work, but I noticed what you have described as well while fixing the other menu issues.

Here's a crazy idea (which might make sense, but maybe not): if the `struct sway_node *previous` that we are going to refocus is an Xwayland view _and_ it belongs to the same process as the unmanaged view we just unmapped, don't do the whole unfocusing logic and try what you did instead.

This might break things (particularly in other apps?); I don't have much insight into how X11 focusing is supposed to work. But it's probably worth trying, at least -- it sounds like it wouldn't break the `i3-input` case, at least (since the processes wouldn't be the same).

**Comment by Xyene** [comment] 2020-10-13 23:48
I can no longer reproduce this in PyCharm on sway/wlroots master, despite not having updated it since my last comment. I suspect https://github.com/swaywm/sway/commit/7ca9ef12f8b6a00b8020a500433fabc6b645d85c or https://github.com/swaywm/sway/commit/657587964e5d8e444ac64829a0aab309c25ff50f may have fixed it. Does the issue still occur?

**Comment by jc7n** [comment] 2020-10-14 00:27
I'm unable to reproduce any of the original issues with IntelliJ 2020.3 EAP on sway/wlroots master. Looks like the i3-input test from the original PR is still working as well. Thanks for the comments!

The following still reliably repro's for me, but it's an extreme corner case and easily solved by switching workspaces:

> 1. Open Run -> Edit Configurations...
> 2. Click anywhere outside the Edit Configurations dialog
> 3. Close the Edit Configurations dialog with the Escape key
> 4. Open Run -> Run...
> 
> Expected: the Run -> Run... modal opens and stays open.
> Actual: the Run -> Run.. modal briefly flashes and then closes. 

So there's still something off with the reparenting but feels like we're well into diminishing returns territory here.

**Comment by ChrisLane** [comment] 2020-10-14 08:24
I can also confirm that these issues with windows disappearing don't happen on sway d6ac30753ded44c5f1921a3bbccb5856d5ef6539 with wlroots afeb941ca027995530d940b81f28421456c77640

**Comment by itspngu** [comment] 2020-12-08 18:35
Not specific to sway/wlroots, but I can confirm that after upgrading from Ubuntu 20.04 LTS to 20.10, things seem to work fine. Before that, all the menus were behaving rather funky. Don't need any of the proposed hacks with regards to changing JRE, setting environment variables or compiling sway/wlroots from a specific commit either, it just works™

Hoping this isn't utterly misplaced and might save people arriving here from Google some work. I do run a custom Kernel but everything else that could potentially matter is stock. Not really sure how things are set up with Canonical but perhaps somebody could propose throwing 1.5 into focal-backports?

```
pngu@smol:~$ sway -d
[...] Sway version v1.5
[...] Linux smol 5.9.12-xanmod1-cachy #0~git20201202.5bede9a SMP PREEMPT Wed Dec 2 17:28:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[...] Contents of /etc/lsb-release:
[...] DISTRIB_ID=Ubuntu
[...] DISTRIB_RELEASE=20.10
[...] DISTRIB_CODENAME=groovy
[...] DISTRIB_DESCRIPTION="Ubuntu 20.10"
```

Cheers

**Comment by tsdh** [comment] 2021-01-05 08:35
I also have the issue of disappearing popup-dialogs or popup-dialogs which cannot get input focus using sway 1.5.1, wlroots 0.12.0, wayland 1.18.0, and xorg-xwayland 1.20.0.r800.ge4a9f0bb4 with IntelliJ IDEA 2020.3 on an up-to-date Arch install.

I also have `_JAVA_AWT_WM_NONREPARENTING=1`.

Here is a screencast demonstrating the issues I'm aware of: https://www.tsdh.org/sway-intellij.mp4

- The **Navigate > File Structure** popup immediately disappears again.
- The **Generate...** context menu action popup immediately disappears again.
- The **New > Java Class** context menu action popup stays visible but cannot receive input focus.

Also, the Help > About screen immediately disappears (not shown in the screencast).

There are similar popups which work just fine, i.e., they don't disappear and are able to receive mouse and keyboard input, e.g., **Navigate > File Path**, **Refactor > Move Members...**, or **Show Context Actions** you get when hitting `Alt+Return` on some code element.

Interestingly, there are also many popups which work fine when invoked by keyboard shortcut but immediately disappear when invoked from the menu bar using the mouse, e.g., Navigate > **Search everywhere**, **Navigate > Class**, etc.  In fact, the context menu **Generate...** action can also be invoked using a shortcut, and then it works.  In contrast, the **Navigate > File Structure** popup also disappears immediately when invoked by its keyboard shortcut.

**Comment by tsdh** [comment] 2021-01-20 13:22
This issue is solved for me using the current git master branches of sway and wlroots thanks to the latest PRs of @BrassyPanache.  Thanks a lot!
The relevant PRs are #5948 and https://github.com/swaywm/wlroots/pull/2605

**Comment by Xyene** [comment] 2021-01-30 06:56
Closing as per the above. Please reopen if the issue persists despite #5948.

**Closed by Xyene** 2021-01-30 06:56 UTC
Labels: client-compat, xwayland

**Comment by crafter999** [comment] 2021-03-12 08:17
I had the same problem with 1.5 and fixed it after I compiled from source the latest master. Thank you so much guys, I was about switching to other mainstream WMs cause I couldn't work with Android Studio.
