### ISSUE TITLE
Can't interact with firefox under wayland backend

### ISSUE THREAD

**Issue by aenda** [swaywm/sway#2101] opened 2018-06-03 15:49 UTC
When running firefox from the https://firefox-flatpak.mojefedora.cz/ repository, which uses the WIP wayland backend, I cannot interact with it whatsoever - no mouse or keyboard actions seem to get through - sway actions like resizing or killing it work fine, however. When I run it under weston, it works fine. I've attached a debug log of me starting sway, opening a terminal and launching firefox, and exiting sway. Also, other flatpak apps run fine, so I don't think that's the issue.

[swaylog.txt](https://github.com/swaywm/sway/files/2066097/swaylog.txt)

**Comment by emersion** [comment] 2018-06-03 17:07
Duplicate of https://github.com/swaywm/wlroots/issues/1023

**Closed by emersion** 2018-06-03 17:07 UTC
