### ISSUE TITLE
swaylock laggy and not allowing me to type after resume from suspend

### ISSUE THREAD

**Issue by The-King-of-Toasters** [swaywm/sway#2706] opened 2018-09-24 14:16 UTC
I've been tracking the git release of sway using `sway-wlroots-git`. I'm currently running `sway version 1.0-alpha.6-43-ga032925a (Sep 24 2018, branch 'makepkg')` and the latest wlroots as of this issue.

Today I noticed that when I resume my laptop from suspend, the following things happen:
- The first character does not register on the dial. But clearing the character later does.
- The first password entry is not laggy, but it is always wrong.
- The entries after that only allow me to put in ~two chars in before putting up the wrong wheel again.

I remember this happening on the late hours of the 23rd, AEST. Also, I currently run [go-luks-suspend](https://github.com/guns/go-luks-suspend) to re-encrypt my drive contents before suspending. My swayidle config is:
```
exec swayidle \
        timeout 600 "$Locker" \
        timeout 300 'swaymsg "output * dpms off"' \
        resume 'swaymsg "output * dpms on"' \
        before-sleep "$Locker"
```
and `$Locker` is `set $Locker swaylock -c 90a4ae --indicator-radius 100 --font 'Prelude WGL'`, but I've confirmed that the error happens using normal swaylock.

[Here's a log of the problem](https://pastebin.com/ZjjgiNhF). The resume happens at around 38secs.

**Comment by foxxx0** [comment] 2018-09-24 18:01
I've run into the same issue, although i'm not using go-luks-suspend and just do a "normal" `systemctl suspend`.

**Comment by The-King-of-Toasters** [comment] 2018-09-29 02:54
Can someone please mark this as a bug? Because this is a pretty serious issue.

**Comment by limadm** [comment] 2018-10-01 11:07
This seems to be the same as #1214.
The developers closed that issue because it was not a priority.

**Comment by emersion** [comment] 2018-10-01 16:14
>This is a regression, and a pretty big one at that.

This isn't particularly helpful. Please try to point out which commit caused the regression (you can try `git bisect`). Please debug what happens, since you're able to reproduce. Please send patches to fix the issue.

**Comment by emersion** [comment] 2018-10-01 16:17
And, and just as a reminder: alpha builds _will_ contain bugs and _will_ break, that's expected. If you're not prepared to face big regressions, don't use it. From the release notes:

>You are strongly encouraged to remain on sway 0.15.x if you are not prepared to deal with constant breakage and keep quiet about it. Please do not submit bug reports for this version of sway. Submit patches instead.

**Comment by emersion** [comment] 2018-10-01 17:29
Can you try attaching GDB (or running swyalock inside GDB, really) to find out? Running `env WAYLAND_DEBUG=1 swaylock` might prove helpful. If that doesn't work, maybe using `perf` could give us a hint.

**Comment by limadm** [comment] 2018-10-01 17:35
Okay, I'll try to gdb/record after work. See you tomorrow.

**Comment by SirCmpwn** [comment] 2018-10-01 17:53
If this is a regression, git bisect will help, but it's up to you folks to dig into this. We don't deal with entitled users here, everyone is a volunteer and if none of the sway devs are available to investigate, then its up to you to.

**Comment by The-King-of-Toasters** [comment] 2018-10-01 23:34
So I've compiled a debug build and I've run it in gdb, but I'm wondering how to actually save something in gdb to pass on, being that I can't unlock my screen to go to my terminal.

**Comment by martinetd** [comment] 2018-10-01 23:43
You can run swaylock in a screen and look at it from another tty, or ssh in from another machine.

I'm not sure what is expected of gdb here though, a log with `WAYLAND_DEBUG=1` (which has timestamps and might help understand what's so slow) might be a better start; once we have an idea of what area is slow adding more debug statements will be possible

**Comment by The-King-of-Toasters** [comment] 2018-10-02 00:07
Ok, I've got my logs and a generated core dump [here](https://my.mixtape.moe/abwtyn.txz). The `sha256sum` is `3664bc74367d802de33962f536ac946642fb38d23358f4cf0fbe5a1353f08e84`. Also, I've replicated the issue just by switching back and forth between sway and `tty2`, no suspend needed. It seems swaylock is constantly trying to authenticate after one bad password is accepted.

**Comment by martinetd** [comment] 2018-10-02 00:46
I'm glad we're asking for logs with `WAYLAND_DEBUG=1` and you're giving a core dump... A core dump without the associated binaries is pretty much useless so you're the only one who can do anything with it (sway at least compiles the date in `--version` so it's not a reproductible build, we won't get the same binary as you without trying very, very hard)

Anyway I just tried, can reproduce, and found something interesting, it looks like swaylock is a second firefox and it grabs new inputs again everytime it gets a chance, leading to things like this:
```
[3524923.247] wl_seat@8.capabilities(3)
[3524923.406]  -> wl_seat@8.get_pointer(new id wl_pointer@85)
[3524924.983]  -> wl_seat@8.get_keyboard(new id wl_keyboard@103)
[3524925.157] wl_seat@8.capabilities(3)
[3524925.244]  -> wl_seat@8.get_pointer(new id wl_pointer@104)
[3524925.390]  -> wl_seat@8.get_keyboard(new id wl_keyboard@105)
[3524925.541] wl_seat@8.capabilities(3)
[3524925.650]  -> wl_seat@8.get_pointer(new id wl_pointer@106)
[3524925.773]  -> wl_seat@8.get_keyboard(new id wl_keyboard@107)
[3524926.057] wl_keyboard@102.key(464, 876721680, 29, 0)
[3524926.646] wl_keyboard@100.key(464, 876721680, 29, 0)
[3524927.148] wl_keyboard@98.key(464, 876721680, 29, 0)
[3524927.600] wl_keyboard@97.key(464, 876721680, 29, 0)
[3524928.129] wl_keyboard@96.key(464, 876721680, 29, 0)
[3524928.497] wl_keyboard@95.key(464, 876721680, 29, 0)
[3524928.779] wl_keyboard@94.key(464, 876721680, 29, 0)
[3524929.184] wl_keyboard@93.key(464, 876721680, 29, 0)
[3524929.473] wl_keyboard@91.key(464, 876721680, 29, 0)
```

A print statement in `swaylock_handle_key` confirms that unlike firefox it handles all of these events; no wonder your password is wrong (unless it's `aaaaaaaaaa` and you type a single `a` :D) ; the apparent lag just is here because it tries to render many frames on every keystroke.

wlroots is resending a wl_seat@capabilities events because when you switch tty (or suspend), logind unplugs and replugs all your input devices, so we have to tell the program we lost some capabilities then got them back...
You can either add some logic to remember the old keyboard it got (from `wl_seat_get_keyboard` in `seat_handle_capabilities`) and call `wl_keyboard_destroy` on it if it exists... or remember it got a keyboard from the seat already  and don't get a new one; I think that would work as this keyboard has no relation to the input devices but is just a way to get keyboard events from the seat.

I have no idea why that problem is new though, feel free to bisect if you're curious.

Waiting for your patches now we know what happens, feel free to ask more questions if I wasn't clear.

**Comment by The-King-of-Toasters** [comment] 2018-10-02 01:29
Ok, bisect complete, it was 271b24ddfb4ab06452c90a680aaa81385cf88407:
```
271b24ddfb4ab06452c90a680aaa81385cf88407 is the first bad commit
commit 271b24ddfb4ab06452c90a680aaa81385cf88407
Author: Ryan Dwyer <ryandwyer1@gmail.com>
Date:   Sun Sep 23 22:00:18 2018 +1000

    Fix GtkMenuBar always opening first item

    It seems like advertising that we support touch when we don't, while
    using SSD, makes GtkMenuBar misbehave. Please don't ask me why...

:040000 040000 cc0c5873899c6f0681952a48113d7d461c770a60 ed56ac81f4194f56a3e72f7a638175baeb2e57fb M      sway
```

**Comment by RyanDwyer** [comment] 2018-10-02 01:34
That commit makes it so we re-advertise the new seat capabilities every time a device is added or removed. We previously only did it once when creating the seat.

**Comment by RyanDwyer** [comment] 2018-10-05 23:53
@The-King-of-Toasters Can you please try the latest master and see if it's fixed?

**Comment by RyanDwyer** [comment] 2018-10-06 09:14
Can you reproduce it without using go-luks-suspend? Can you also try suspending without running swaylock, and see if the first keypress after restore is also ignored?

**Comment by The-King-of-Toasters** [comment] 2018-10-06 09:59
Ok, it seems that disabling `go-luks-suspend` stops the eat-the-first-char behaviour. When enabled, it seems that the first char on any input is eaten. I tested this by having a terminal open and striking the `a` key.

**Comment by RyanDwyer** [comment] 2018-10-06 10:33
Can you also test it on another compositor and see if it happens there?

**Comment by The-King-of-Toasters** [comment] 2018-10-06 10:35
One that isn't based on wlroots?

**Comment by RyanDwyer** [comment] 2018-10-06 10:36
Yes please. I want to rule out it being a bug in sway or wlroots.

**Comment by The-King-of-Toasters** [comment] 2018-10-06 10:43
Any suggestions? I only know of GNOME and KDE.

**Comment by RyanDwyer** [comment] 2018-10-06 10:44
Either of those should be fine. Make sure they're operating as Wayland compositors and not X11 compositors/WMs.

**Comment by The-King-of-Toasters** [comment] 2018-10-06 11:14
Both of them immediately crash on me when trying their wayland sessions, any others?

**Comment by The-King-of-Toasters** [comment] 2018-10-06 11:30
Locks up my laptop.

**Comment by The-King-of-Toasters** [comment] 2018-10-07 00:33
Ok, now I'm paranoid. Is there any way to verify I'm running under Wayland? XDG_SESSION_TYPE isn't set for me.

**Comment by martinetd** [comment] 2018-10-07 02:48
"running under wayland" only makes sense for desktop environments that implement both X11 WM or wayland compositors like Gnome or KDE; sway only is a wayland compositor so you won't get anything else.

That said I have no idea why weston or the wayland implementation of both of the others fail for you, you'd need to do some debugging...

**Comment by RyanDwyer** [comment] 2018-10-20 06:53
Closing this because the original issue was fixed, and the second issue looks very much like a problem with go-luks-suspend. We have no reason to believe there is a problem with sway here.

**Closed by RyanDwyer** 2018-10-20 06:53 UTC
Labels: bug
