### ISSUE TITLE
Cannot start after upgrade: drmModePageFlip failed: Device or resource busy

### ISSUE THREAD

**Issue by manio** [swaywm/sway#8465] opened 2024-11-18 15:52 UTC
- **Sway Version:**

Arch Linux, after upgrading sway from `1:1.9-5 to 1:1.10-1` it cannot start.
I have a black screen on all 6 monitors. I can only press Win+Shift+E to exit.

After downgrade:
`[ALPM] downgraded sway (1:1.10-1 -> 1:1.9-5)`
It is working fine back again.

- **Debug Log:**

It is showing this errors:
```
00:00:01.026 [ERROR] [wlr] [backend/drm/legacy.c:175] connector DP-1: drmModePageFlip failed: Device or resource busy
00:00:01.026 [ERROR] [sway/config/output.c:923] Backend commit failed
```
Full debug log is here:
https://skyboo.net/temp/sway/sway-not-starting.log

**Comment by emersion** [comment] 2024-11-22 10:46
Duplicate of https://github.com/swaywm/sway/issues/8442

**Closed by emersion** 2024-11-22 10:46 UTC
Labels: bug

**Comment by manio** [comment] 2024-11-27 03:22
> @manio, sounds like a separate issue, could you open a new one?

If this is not a duplicate so just please reopen this one.

**Comment by emersion** [comment] 2024-11-27 03:50
@manio, I already explained that this issue is about `drmModePageFlip()`, not about the unrelated bug you're getting here: https://github.com/swaywm/sway/issues/8442#issuecomment-2495545574
