### ISSUE TITLE
client.<class> doesn't work well with for_window

### ISSUE THREAD

**Issue by keithbowes** [swaywm/sway#5005] opened 2020-02-12 01:22 UTC
When I started to use Sway, I wanted to give the titles of legacy X apps a special style using `for_window` and `client.<class>`, but it didn't work, so I used a (not completely satisfactory) hack of using Pango markup with `title_format`.  Well, I tried using `for_window` and `client.<class>` again in 1.4 and it's still not working as I'd expect it to.  A relevant excerpt from my Sway config file:
```cfg
for_window [shell="xwayland"] client.focused #4c7899 #ff0000 #ffff00
for_window [shell="xdg_shell"] client.focused #4c7899 #285577 #ffffff
```

What I expect to happen is X windows to have the xwayland styles and Wayland windows to have the xdg_shell styles, but what happens is the styles of the most recently opened window get applied to all windows; i.e. if I open an X window, all the other windows (including Wayland windows) get the xwayland style, and if I open a Wayland window, all the other windows (including the X windows) get the xdg_shell style.  Perhaps this behavior is intentional, but it strikes me as counterintuitive.

**Comment by RedSoxFan** [comment] 2020-02-12 01:24
There is no support for per window borders. Duplicate of #3177

**Closed by RedSoxFan** 2020-02-12 01:24 UTC
