### ISSUE TITLE
when resizing a window, its content resizes before its border.

### ISSUE THREAD

**Issue by Al-Caveman** [swaywm/sway#4317] opened 2019-07-10 23:13 UTC
Try creating to tiles.  Then try to enlarge one by the keyboard.  You will notice that the window's content jumps out of the window's border (enlarges 1st), then the border expands to follow it.

In `i3`, they resize in a synchronized manner.  I guess this is a bug, or a performance issue.

**Comment by RedSoxFan** [comment] 2019-07-11 00:57
Duplicate of #4078

**Closed by RedSoxFan** 2019-07-11 00:57 UTC
