### ISSUE TITLE
Crash showing scratchpad after ipc focusing a window in a hidden container in scratchpad

### ISSUE THREAD

**Issue by edrex** [swaywm/sway#4824] opened 2019-12-19 06:34 UTC
Another scratchpad crash CC @RedSoxFan :trollface: 

Focusing a window in the scratchpad shows the scratchpad.

Focusing a window in a container in the scratchpad:
 1. doesn't show the scratchpad
 2. causes sway to crash on scratchpad show, I think because the window isn't expected to have focus but it does.

Steps to repro:

 1. start a couple of terms and put their parent in scratchpad
 2. With scratchpad hidden, `swaymsg "[con_id=$(swaymsg -t get_tree|jq '.. | objects | select(.name == "__i3_scratch").floating_nodes[0].nodes[0].id')] focus"` (focus first scratchpad window)
 3. Attempting to show scratchpad crashes.

```
❯ coredumpctl gdb sway
...
       Message: Process 244256 (sway) of user 1000 dumped core.
                
                Stack trace of thread 244256:
                #0  0x000055f8d8088eee arrange_workspace (sway + 0x5aeee)
                #1  0x000055f8d808ef67 root_scratchpad_hide (sway + 0x60f67)
                #2  0x000055f8d807c632 scratchpad_toggle_auto (sway + 0x4e632)
                #3  0x000055f8d807ca60 cmd_scratchpad (sway + 0x4ea60)
                #4  0x000055f8d803eb84 execute_command (sway + 0x10b84)
                #5  0x000055f8d8071164 seat_execute_command (sway + 0x43164)
                #6  0x000055f8d805e566 handle_key_event (sway + 0x30566)
                #7  0x000055f8d805e727 handle_keyboard_group_key (sway + 0x30727)
                #8  0x00007f9b9fd45fb7 wlr_signal_emit_safe (libwlroots.so.3 + 0x94fb7)
                #9  0x00007f9b9fd2c44b wlr_keyboard_notify_key (libwlroots.so.3 + 0x7b44b)
                #10 0x00007f9b9fd2cf74 handle_keyboard_key (libwlroots.so.3 + 0x7bf74)
                #11 0x00007f9b9fd45fb7 wlr_signal_emit_safe (libwlroots.so.3 + 0x94fb7)
                #12 0x00007f9b9fd2c44b wlr_keyboard_notify_key (libwlroots.so.3 + 0x7b44b)
                #13 0x00007f9b9fcf918d keyboard_handle_key (libwlroots.so.3 + 0x4818d)
                #14 0x00007f9b9e82569a ffi_call_unix64 (libffi.so.6 + 0x669a)
                #15 0x00007f9b9e824fb6 ffi_call (libffi.so.6 + 0x5fb6)
                #16 0x00007f9b9f3bdf8f n/a (libwayland-client.so.0 + 0x8f8f)
                #17 0x00007f9b9f3ba6ba n/a (libwayland-client.so.0 + 0x56ba)
                #18 0x00007f9b9f3bbbfc wl_display_dispatch_queue_pending (libwayland-client.so.0 + 0x6bfc)
                #19 0x00007f9b9fcf5a67 dispatch_events (libwlroots.so.3 + 0x44a67)
                #20 0x00007f9b9f6c17f2 wl_event_loop_dispatch (libwayland-server.so.0 + 0xa7f2)
                #21 0x00007f9b9f6c039c wl_display_run (libwayland-server.so.0 + 0x939c)
                #22 0x000055f8d804d30c server_run (sway + 0x1f30c)
                #23 0x000055f8d804c92c main (sway + 0x1e92c)
                #24 0x00007f9b9f49c153 __libc_start_main (libc.so.6 + 0x27153)
                #25 0x000055f8d803e22e _start (sway + 0x1022e)
                
                Stack trace of thread 244260:
                #0  0x00007f9b9ed0cc45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                #1  0x00007f9b9645976c n/a (i965_dri.so + 0x4f676c)
                #2  0x00007f9b96459368 n/a (i965_dri.so + 0x4f6368)
                #3  0x00007f9b9ed064cf start_thread (libpthread.so.0 + 0x94cf)
                #4  0x00007f9b9f5742d3 __clone (libc.so.6 + 0xff2d3)
                
                Stack trace of thread 244258:
                #0  0x00007f9b9ed0cc45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                #1  0x00007f9b9645976c n/a (i965_dri.so + 0x4f676c)
                #2  0x00007f9b96459368 n/a (i965_dri.so + 0x4f6368)
                #3  0x00007f9b9ed064cf start_thread (libpthread.so.0 + 0x94cf)
                #4  0x00007f9b9f5742d3 __clone (libc.so.6 + 0xff2d3)
                
                Stack trace of thread 244259:
                #0  0x00007f9b9ed0cc45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                #1  0x00007f9b9645976c n/a (i965_dri.so + 0x4f676c)
                #2  0x00007f9b96459368 n/a (i965_dri.so + 0x4f6368)
                #3  0x00007f9b9ed064cf start_thread (libpthread.so.0 + 0x94cf)
                #4  0x00007f9b9f5742d3 __clone (libc.so.6 + 0xff2d3)
                
                Stack trace of thread 244261:
                #0  0x00007f9b9ed0cc45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                #1  0x00007f9b9645976c n/a (i965_dri.so + 0x4f676c)
                #2  0x00007f9b96459368 n/a (i965_dri.so + 0x4f6368)
                #3  0x00007f9b9ed064cf start_thread (libpthread.so.0 + 0x94cf)
                #4  0x00007f9b9f5742d3 __clone (libc.so.6 + 0xff2d3)
```

**Comment by edrex** [comment] 2019-12-19 06:36
Ref #4816 although I haven't cherry picked to see if this is a new regression

**Comment by RedSoxFan** [comment] 2019-12-19 11:39
Duplicate of #4788

**Closed by RedSoxFan** 2019-12-19 11:39 UTC
