### ISSUE TITLE
Unable to bind media key with other key

### ISSUE THREAD

**Issue by Moonlight-Angel** [swaywm/sway#3806] opened 2019-03-02 10:07 UTC
* Sway Version: sway version 1.0-rc1-138-g43035951 (Mar  2 2019, branch 'master')
* Steps to reproduce
1. Set a binding on a media key that also includes another key (example : `bindsym Shift+XF86AudioMute exec somecommand`)
2. Reload configuration
3. Try to trigger the binding
4. If there is already a binding on XF86AudioMute alone, that binding will be triggered, even when Shift is pressed

**Comment by RedSoxFan** [comment] 2019-03-02 18:16
Duplicate of #2897

**Closed by RedSoxFan** 2019-03-02 18:16 UTC
