### ISSUE TITLE
Mouse events crash screen, when the device gets activated

### ISSUE THREAD

**Issue by brandsimon** [swaywm/sway#5018] opened 2020-02-16 10:17 UTC
Good morning,

I have a little script which deactivates my mouse/touchpad.
```
#!/usr/bin/env bash
mouse_off() {
	swaymsg input type:touchpad events disabled
	swaymsg input type:mouse events disabled
}
mouse_on() {
	swaymsg input type:touchpad events enabled
	swaymsg input type:mouse events enabled
}
```

When I use  the touchpad, while it is disable and enable it during movement, sway crashes.
This is reproducible with this setup:
config:
```
set $mod Mod4
font pango:Monospace Sans 15
bindsym $mod+Return exec xfce4-terminal
```

I reproduce it with the following steps:
- I start sway
- open xfce4-terminal via $mod+Return
- source the file above
- run `mouse_off && sleep 1 && mouse_on`
- immediately move the mouse
- sway crashes.

Sometimes I need to run the command twice to get sway crashing.
Here is my debug log: http://sprunge.us/GEa66S

I am running an uptodate a Arch Linux.
```
 $ swaymsg -t get_version
sway version 1.4
```

Here is also the stack trace with `bt full`:
```
#0  0x00007fadd2fb8ce5 in raise () at /usr/lib/libc.so.6
#1  0x00007fadd2fa2857 in abort () at /usr/lib/libc.so.6
#2  0x00007fadd2fa2727 in _nl_load_domain.cold () at /usr/lib/libc.so.6
#3  0x00007fadd2fb1426 in  () at /usr/lib/libc.so.6
#4  0x00007fadd2e027a9 in  () at /usr/lib/libinput.so.10
#5  0x00007fadd2e0a1db in  () at /usr/lib/libinput.so.10
#6  0x00007fadd2e09b3f in libinput_dispatch () at /usr/lib/libinput.so.10
#7  0x00007fadd290aee3 in  () at /usr/lib/libwlroots.so.5
#8  0x00007fadd298cfaa in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#9  0x00007fadd298b4e7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#10 0x000055a8083e55ff in  ()
#11 0x00007fadd2fa4023 in __libc_start_main () at /usr/lib/libc.so.6
#12 0x000055a8083e594e in  ()
```

If there is information missing, I am happy to provide them.

**Comment by emersion** [comment] 2020-02-16 10:26
Duplicate of https://github.com/swaywm/sway/issues/5017

**Closed by emersion** 2020-02-16 10:26 UTC
