### ISSUE TITLE
Using split in fullscreen causes odd behavior

### ISSUE THREAD

**Issue by sauyon** [swaywm/sway#4332] opened 2019-07-15 14:20 UTC
* Sway Version: 1.0
* Debug Log: https://pastebin.com/Ru6mH58w (relevant section, will upload full log if req'd)

Running `split {v,h}` while an app is in fullscreen starts to tile the fullscreen container. This also resizes the window when fullscreen is exited by pressing the fullscreen binding two times.

I'd be happy to try to fix this if somebody pointed me in the right general file region for the changes.

**Comment by sauyon** [comment] 2019-07-15 14:40
This actually seems to be a combination of #3547 and the fact that split creates a parent container.

Because a child container is focused, when fullscreen is run, that child is fullscreened. On the second press fullscreen is exited.

I'm not 100% sure this is a bug but I'll leave it up regardless.

**Comment by RedSoxFan** [comment] 2019-07-15 16:55
So I see three points here:
1. Allowing containers to be split while fullscreen
    - This is intended behavior. Layouts are supported while fullscreen _(unlike in i3)_
2. The sizing of the container being changed when exiting fullscreen
    - This should be fixed by #4293, which was merged yesterday
3. Running fulllscreen on a child of the fullscreen container causes the child to become fullscreen
    - To change this, in `cmd_fullscreen`, you would just need to walk `container->parent` to check to see if any of the ancestors are fullscreen and operate on that instead.

**Comment by sauyon** [comment] 2019-07-15 17:12
So 3 is something that should be fixed?

Re: 1, I personally feel like containers with only one child shouldn't cause borders to appear in fullscreen.

**Comment by RedSoxFan** [comment] 2019-07-15 18:27
> So 3 is something that should be fixed?

The change sounds reasonable to me so I'd say yes.
 
> Re: 1, I personally feel like containers with only one child shouldn't cause borders to appear in fullscreen.

The borders will not show until the container is split. At this point, the split indicator is shown along with the rest of the borders (`hide_edge_borders` will alter what borders are visible). If you aren't going to be spawning another view, I don't see why you would split the container in the first place.

**Comment by sauyon** [comment] 2019-07-15 18:43
> The borders will not show until the container is split. At this point, the split indicator is shown along with the rest of the borders (`hide_edge_borders` will alter what borders are visible). If you aren't going to be spawning another view, I don't see why you would split the container in the first place.

This has mostly stemmed from me accidentally hitting a split shortcut whist in fullscreen, which admittedly is probably PIBKAC.

**Closed** 2019-07-17 13:25 UTC
