### ISSUE TITLE
Sway crashes when closing mpv with the kill command/keybinding

### ISSUE THREAD

**Issue by PyroLagus** [swaywm/sway#1176] opened 2017-04-16 23:42 UTC
### Sway version

`sway -v`

> sway version  (2017-04-12, branch "")

### System information

`uname -a`

> Linux wheatley 4.10.9-1-ARCH #1 SMP PREEMPT Sat Apr 8 12:39:59 CEST 2017 x86_64 GNU/Linux

`lspci -v`

> 00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09) (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. Device 117d
	Flags: bus master, fast devsel, latency 0, IRQ 27
	Memory at f7800000 (64-bit, non-prefetchable) [size=4M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at f000 [size=64]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915

### Log and config

`sway -d`

> http://sprunge.us/cEEf

config

> http://sprunge.us/GPdI

### Steps to reproduce

1. Open (weston) terminal
2. run `mpv http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_720p_h264.mov`
  (any video should work)
3. close the mpv window using the sway kill command or keybinding.

### Possibly related issue

#1036

**Comment by Timidger** [comment] 2017-04-17 03:04
Hm, we had a similar problem in Way Cooler which was fixed with [this patch](https://github.com/way-cooler/way-cooler/pull/259). The gist was that we weren't cleaning up the reference to the `WlcView` in the layout tree code properly, causing a crash when trying to use a free-d `WlcView`

**Comment by SirCmpwn** [comment] 2017-12-18 03:47
I can't reproduce this. Is it still an issue?

**Closed** 2018-07-25 15:49 UTC
