### ISSUE TITLE
Negative output position causes X applications to not receive mouse inputs

### ISSUE THREAD

**Issue by paul-ri** [swaywm/sway#4867] opened 2020-01-02 16:52 UTC
`sway version 1.2-d510684c (Jan  2 2020, branch 'master')`

Applications using xwayland displayed on an output with a negative x position fail to react to mouse inputs.

Reproduction steps:
1. configuration example
  ```
  xwayland enable
  output 'eDP-1' {
      # Main output on the right
      position 0 0
  }
  output 'HDMI-A-1' {
      # External output on the left
      position -1920 0
  }
  exec {
      # Example of apps failing to register mouse clicks
      code  # Visual Studio Code
      spotify
  }
  ```
2. Move the opened windows on the left screen
3. Clicks are not registered neither is hovering

* The debug output is the same regardless of the position of the window and shows the clicks are registered by Sway.
* If the window if set in floating mode and moved in between both outputs: the right side is responsive but not the left side

I'm not sure where to look at in the code to fix this. Pointers would be appreciated :)

**Comment by Emantor** [comment] 2020-01-02 16:59
Duplicate of #4260, known xwayland bug.

**Comment by paul-ri** [comment] 2020-01-02 17:04
Cheers, didn't see it when doing a search :/ my bad

**Closed** 2020-01-02 17:04 UTC

**Comment by progandy** [comment] 2020-01-02 17:18
This is the upstream bug:
https://gitlab.freedesktop.org/xorg/xserver/issues/899
