### ISSUE TITLE
Configuration reload leaves orphaned swaybg processes

### ISSUE THREAD

**Issue by CameronNemo** [swaywm/sway#2952] opened 2018-10-24 04:07 UTC
After reloading my configuration, I am seeing some orphaned swaybg processes hanging about. In fact each reload generates two of them.

I am running Void Linux, glibc, kernel 4.18.16, with elogind.

Please tell me if there is any more information you need.

**Comment by madblobfish** [comment] 2018-10-27 15:15
I could not reproduce your issue, could you post your configuration?

**Comment by CameronNemo** [comment] 2018-10-27 20:16
I can reproduce with the default configuration.

**Comment by madblobfish** [comment] 2018-10-28 00:43
Please provide a debug log and the exact sway version. (see https://github.com/swaywm/sway/wiki#how-do-i-report-issues)

**Comment by CameronNemo** [comment] 2018-10-28 03:04
http://ix.io/1qfm

**Comment by emersion** [comment] 2018-11-23 22:17
Hmm, just realized I still have swaybar processes left behind when I Ctrl+C sway.

**Comment by RedSoxFan** [comment] 2019-02-11 07:54
Is anyone still able to replicate this?

**Comment by CameronNemo** [comment] 2019-02-11 18:18
FWIW I have not seen this exact behavior, but I did see a zombie swaybg recently.

**Comment by emersion** [comment] 2019-02-23 10:52
I'm going to close this, as we now disconnect swaybg instead of killing it.

**Closed by emersion** 2019-02-23 10:52 UTC
