### ISSUE TITLE
electron with wayland flags

### ISSUE THREAD

**Issue by Iss-in** [swaywm/sway#6567] opened 2021-10-02 05:50 UTC
sway version 1.6-ff468584 (Oct  2 2021, branch 'master')
wlroots-git 0.14.0.r284.g323b8498-1
electron 15.1.0-1

No issue on sway/wlroots release version, possibly a regression in wlroots-git

- **Debug Log:**
- https://gist.github.com/Iss-in/e822c757cf50aaa2d5ce0841680811ab
cant launch vscode/edge/spotify with ozone flags anymore, no gui opens while vscode process run in background for a short while and closes eventually. spotify and edge just crashes with  trace trap (core dumped) 

all works fine with xwayland

**Comment by emersion** [comment] 2021-10-02 08:20
Duplicate of https://github.com/swaywm/wlroots/issues/3168

**Closed by emersion** 2021-10-02 08:20 UTC
Labels: bug
