### ISSUE TITLE
Sway crashes when toggling floating mode in Firefox Developer Edition

### ISSUE THREAD

**Issue by pauk1** [swaywm/sway#4021] opened 2019-04-06 11:26 UTC
* Sway Version: 1.0
* Debug Log: https://gist.github.com/pauk1/2eebe92b788711809cdac643d99de587
* coredumpctl gdb sway: https://gist.github.com/pauk1/4b0f3e17840bf73bf59660f18e2184ae

Steps to reproduce:
1. Install Firefox Developer Edition
2. Open this shit
3. Toggle floating mode
4. **Crash!**

**Comment by RedSoxFan** [comment] 2019-04-06 13:59
Duplicate of #3870

**Closed by RedSoxFan** 2019-04-06 13:59 UTC
