### ISSUE TITLE
Cannot Duplicate Monitors

### ISSUE THREAD

**Issue by ibrokemypie** [swaywm/sway#2953] opened 2018-10-24 06:45 UTC
sway version 1.0-beta.1-38-gbdb17686 (Oct 24 2018, branch 'master')
config: https://paste.pound-python.org/show/tMf75fV1nPYNPuKkmNqa/
debug log: https://gist.github.com/ibrokemypie/1344beade1592f1b4721d92ddd0943e8

I have two 1920x1080 screens which I wish to duplicate, so I added them each to the config with the same resolution and position, however this instead of duplicating the contents of the screen creates two workspaces with the mouse shared between them, but not contents. This also makes windows on one window randomly get de-selected when moving the mouse.

**Comment by emersion** [comment] 2018-10-24 06:55
Related to https://github.com/swaywm/sway/issues/1666

**Comment by SirCmpwn** [comment] 2018-10-24 13:36
Duplicate of https://github.com/swaywm/sway/issues/1666

**Closed by SirCmpwn** 2018-10-24 13:36 UTC
Labels: enhancement
