### ISSUE TITLE
exec command doesnt escape commas

### ISSUE THREAD

**Issue by dwma** [swaywm/sway#4628] opened 2019-10-12 04:11 UTC
Hello,

I've added the following line to my config file

`exec "/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh"`

but it doesn't work.

Executing `swaymsg exec "/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh"` shows that sway is splitting the command in each comma and parsing the resulting parts as separate commands, despite being enclosed in double quotes. Using single quotes has the same result, as does adding `--` before `exec`.

However, if I do this
```
set $keyring "/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh"
exec $keyring
```
the command is parsed correctly and it works as expected.

sway version 1.2 (Sep 26 2019, Arch Linux)

**Comment by RPigott** [comment] 2019-10-12 07:54
I can't reproduce on the current master. Your top example works as expected for me.

Your second example I _can_ reproduce, however this is the expected behavior. Your shell will consume the quotes, so you must double quote the argument to give the command equivalent to the one in your config with swaymsg.

Are you sure the first one fails? Do you have a log excerpt or something indicating how it was parsed and what was executed?

**Comment by RedSoxFan** [comment] 2019-12-15 22:15
Duplicate of #4541

**Closed by RedSoxFan** 2019-12-15 22:15 UTC

**Comment by mcku** [comment] 2020-05-19 22:21
Hi @RPigott, I know it is a duplicate, but the comma is very common to gnome-keyring therefore mentioning it here

> Do you have a log excerpt or something indicating how it was parsed and what was executed?

My relevant line was:

`exec systemctl --user import-environment && gnome-keyring-daemon --components=ssh,secrets,pkcs11 --start`

Here is a journal entry:
`May 19 23:51:32 manjaro /usr/lib/gdm-wayland-session[121887]: 2020-05-19 23:51:32 - [sway/config.c:651] Error on line 'exec systemctl --user import-environment && gnome-keyring-daemon --components=ssh,secrets,pkcs11 --start': Unknown/invalid command 'secrets'`

This one does not cause errors in the log:
`exec systemctl --user import-environment && gnome-keyring-daemon --components=ssh\,secrets\,pkcs11 --start`

Using quotes is just fine but this works fine, too.

**Comment by basedtho** [comment] 2020-08-08 04:11
@mcku could you please share what's inside your `import-environment.service`? I'm trying to make gnome-keyring agent work with sway
