### ISSUE TITLE
Cursor disappears when hovering over a surface

### ISSUE THREAD

**Issue by CharlieBra7o** [swaywm/sway#4723] opened 2019-11-13 10:19 UTC
**System information**
archlinux vm
sway 1:1.2-5
open-vm-tools 6:11.0.0-1

ran via VMware Workstation 15 Pro (15.0.2 build-10952284) @ Windows 10

**Description**
After I run sway from either a tty directly or gdm, I can see the mouse cursor.
Once and whenever I hover over anything but the empty desktop - e.g.:
- waybar
- termite
- rofi
- chromium
the mouse cursor disappears irreversibly (can only get it back by restarting sway).
dmesg shows the following output the moment I move the cursor over anything but the empty desktop (wallpaper):
`[drm:vmw_du_cursor_plane_atomic_check [vmwgfx]] *ERROR* surface not suitable for cursor`
Hovering from a "non-suitable surface" back over the empty desktop, dmesg does not show this error.

**What's very interesting** is that this issue does not exist when I run sway from gnome-shell. Here, I can hover any surface that would usually result in the above error and the mouse cursor keeps acting as it should.

**Additional information**
- I tried using both the default sway config and one working perfectly on my native arch machine.
- I tried the latest sway code from git

**Debug log**
`sway -dV --config /etc/sway/config`
then moved cursor over waybar
[sway.log](https://github.com/swaywm/sway/files/3840729/sway.log)

**Comment by emersion** [comment] 2019-11-13 10:48
Your bug report is missing debug logs. Please add a link to the full debug log file.

**Comment by CharlieBra7o** [comment] 2019-11-13 11:02
Sorry for that - I added the log to the first post

**Comment by RedSoxFan** [comment] 2019-12-16 00:38
Duplicate of #3814

**Closed by RedSoxFan** 2019-12-16 00:38 UTC
