### ISSUE TITLE
Black output with Amlogic SoC (meson)

### ISSUE THREAD

**Issue by L-as** [swaywm/sway#5310] opened 2020-05-07 17:15 UTC
Using the latest commit a811c1fa0a02c062555b54651065899437bacdbe of Linux, running sway will produce a black output. The session is functional, as I can open a terminal in it by setting the appropriate keybindings and thus interact with the system though without any visual feedback. The system is not using the new panfrost driver, but instead just llvmpipe. I have attached the dmesg output with DRM debugging enabled, the drm_info output, and the sway log. An empty configuration file was used to test this.

[dmesg.txt](https://github.com/swaywm/sway/files/4594618/dmesg.txt)
[drminfo.json](https://github.com/swaywm/sway/files/4594620/drminfo.json.txt)
[stderr.txt](https://github.com/swaywm/sway/files/4594621/stderr.txt)

**Comment by emersion** [comment] 2020-05-07 17:41
Duplicate of https://github.com/swaywm/wlroots/issues/2166

**Closed by emersion** 2020-05-07 17:41 UTC
