### ISSUE TITLE
Several applications appear too large on hidpi after un/plugging ext. display

### ISSUE THREAD

**Issue by wilecoyote2015** [swaywm/sway#4019] opened 2019-04-05 16:03 UTC
* Sway Version:
sway version 1.0-rc1-221-g4b892a79 (Apr  5 2019, branch 'master')

* Configuration and Log:
https://gist.github.com/wilecoyote2015/a5279f504ff4529b1ffa16555f74de42

## Description
I'm using a notebook with an hidpi monitor (intel graphics). 
As soon as an external monitor (mine is 1280x720) is plugged, unplugged and then plugged again, several applications that are started from then on are rendered too large. 
I use myhidpi display with scale 1, and as the issue occurs, the scale factor seems to change to at least 2.
The issue also occurs if I set the scale factor to 1 in the config explicitly for the hidpi display.
Affected applications include TexStudio, Gimp, Krita and Blender 2.8

## Steps to reproduce:
0. Install the Blender 2.8 Beta version
A compiled version can be obtained at https://builder.blender.org/download/
1. Start sway with the provided config file with a primary hidpi monitor (mine is the 2550x1440 display of a Lenovo X1 Carbon)
2. Plug an external monitor in (mine is 1280x720)
3. Unplug the external monitor
4. Plug the monitor in again
5. Start blender.

**Comment by emersion** [comment] 2019-04-05 16:16
Duplicate of https://github.com/swaywm/wlroots/issues/1119

**Comment by emersion** [comment] 2019-04-16 10:17
Yes, please do.

**Closed** 2019-04-16 13:32 UTC

**Comment by wilecoyote2015** [comment] 2019-04-19 07:54
I've added a note to the wiki
