### ISSUE TITLE
Crash with Intellij

### ISSUE THREAD

**Issue by mnd999** [swaywm/sway#8060] opened 2024-03-12 10:47 UTC
### Please fill out the following:
- **Sway Version:**
sway version 1.9

- **Description:**
- This seems to be a fairly random sway crash when using Intellj, I'm not able to reproduce at present reliably, but it's happened a few times over the last couple of days. It seems to relate to drawing popups / windows.  Possibly the same crash as https://github.com/swaywm/sway/issues/8041

- **Stack Trace:**
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000073554eb02f5f in wl_list_remove (elm=elm@entry=0x57ee00e810e8) at ../wayland-1.22.0/src/wayland-util.c:56
56		elm->prev->next = elm->next;
[Current thread is 1 (Thread 0x73554d9d19c0 (LWP 17362))]
(gdb) bt
#0  0x000073554eb02f5f in wl_list_remove (elm=elm@entry=0x57ee00e810e8) at ../wayland-1.22.0/src/wayland-util.c:56
#1  0x000057edfff806c2 in unmanaged_handle_dissociate (listener=0x57ee00e810d0, data=<optimized out>) at ../sway-1.9/sway/desktop/xwayland.c:156
#2  0x000073554eb0301e in wl_signal_emit_mutable (signal=signal@entry=0x57ee019596a0, data=data@entry=0x0)
    at ../wayland-1.22.0/src/wayland-server.c:2241
#3  0x000073554ea86ab7 in xwayland_surface_dissociate (xsurface=xsurface@entry=0x57ee01959490) at ../wlroots-0.17.1/xwayland/xwm.c:398
#4  0x000073554ea888f0 in xwm_handle_unmap_notify (ev=0x57ee00da4b30, xwm=0x57ee017482b0) at ../wlroots-0.17.1/xwayland/xwm.c:1124
#5  x11_event_handler (fd=<optimized out>, mask=<optimized out>, data=<optimized out>) at ../wlroots-0.17.1/xwayland/xwm.c:1678
#6  x11_event_handler (fd=<optimized out>, mask=<optimized out>, data=<optimized out>) at ../wlroots-0.17.1/xwayland/xwm.c:1632
#7  0x000073554eb04b8f in post_dispatch_check (loop=0x57ee0028f110) at ../wayland-1.22.0/src/event-loop.c:943
#8  wl_event_loop_dispatch (loop=0x57ee0028f110, timeout=timeout@entry=-1) at ../wayland-1.22.0/src/event-loop.c:1034
#9  0x000073554eb052d7 in wl_display_run (display=0x57ee0028f020) at ../wayland-1.22.0/src/wayland-server.c:1493
#10 0x000057edfff34c5e in server_run (server=<optimized out>) at ../sway-1.9/sway/server.c:398
#11 main (argc=<optimized out>, argv=0x7fff24023608) at ../sway-1.9/sway/main.c:415
(gdb) bt full
#0  0x000073554eb02f5f in wl_list_remove (elm=elm@entry=0x57ee00e810e8) at ../wayland-1.22.0/src/wayland-util.c:56
#1  0x000057edfff806c2 in unmanaged_handle_dissociate (listener=0x57ee00e810d0, data=<optimized out>) at ../sway-1.9/sway/desktop/xwayland.c:156
        surface = 0x57ee00e81020
#2  0x000073554eb0301e in wl_signal_emit_mutable (signal=signal@entry=0x57ee019596a0, data=data@entry=0x0)
    at ../wayland-1.22.0/src/wayland-server.c:2241
        pos = 0x57ee00e810d0
        l = 0x57ee00e810d0
        cursor = {link = {prev = 0x57ee00e810d0, next = 0x7fff24023080}, notify = 0x73554eb00110 <handle_noop>}
        end = {link = {prev = 0x7fff240230a0, next = 0x57ee019596a0}, notify = 0x73554eb00110 <handle_noop>}
#3  0x000073554ea86ab7 in xwayland_surface_dissociate (xsurface=xsurface@entry=0x57ee01959490) at ../wlroots-0.17.1/xwayland/xwm.c:398
#4  0x000073554ea888f0 in xwm_handle_unmap_notify (ev=0x57ee00da4b30, xwm=0x57ee017482b0) at ../wlroots-0.17.1/xwayland/xwm.c:1124
        xsurface = 0x57ee01959490
        xsurface = <optimized out>
#5  x11_event_handler (fd=<optimized out>, mask=<optimized out>, data=<optimized out>) at ../wlroots-0.17.1/xwayland/xwm.c:1678
        count = <optimized out>
        event = 0x57ee00da4b30
        xwm = <optimized out>
        count = <optimized out>
        event = <optimized out>
        xwm = <optimized out>
#6  x11_event_handler (fd=<optimized out>, mask=<optimized out>, data=<optimized out>) at ../wlroots-0.17.1/xwayland/xwm.c:1632
        event = <optimized out>
        xwm = <optimized out>
#7  0x000073554eb04b8f in post_dispatch_check (loop=0x57ee0028f110) at ../wayland-1.22.0/src/event-loop.c:943
        dispatch_result = <optimized out>
        ep = {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}
        source = <optimized out>
        next = 0x57ee0028f108
        needs_recheck = false
        ep = {events = <optimized out>, data = {ptr = <optimized out>, fd = <optimized out>, u32 = <optimized out>, u64 = <optimized out>}}
        source = <optimized out>
        next = <optimized out>
        needs_recheck = <optimized out>
        dispatch_result = <optimized out>
#8  wl_event_loop_dispatch (loop=0x57ee0028f110, timeout=timeout@entry=-1) at ../wayland-1.22.0/src/event-loop.c:1034
        ep = {{events = 1, data = {ptr = 0x57ee00c120d0, fd = 12656848, u32 = 12656848, u64 = 96679726489808}}, {events = 4, data = {ptr = 0x57ee018eb9b0, fd = 26130864, u32 = 26130864, u64 = 96679739963824}}, {events = 1967493888, data = {ptr = 0x57ee25e8d657, fd = 636016215, u32 = 636016215, u64 = 96680349849175}}, {events = 1, data = {ptr = 0x3c, fd = 60, u32 = 60, u64 = 60}}, {events = 23728960, data = {ptr = 0x24023290000057ee, fd = 22510, u32 = 22510, u64 = 2594691929375528942}}, {events = 32767, data = {ptr = 0x57ee016a4358, fd = 23741272, u32 = 23741272, u64 = 96679737574232}}, {events = 23733064, data = {ptr = 0x240232d0000057ee, fd = 22510, u32 = 22510, u64 = 2594692204253435886}}, {events = 32767, data = {ptr = 0x73554eb01500 <wl_connection_flush+304>, fd = 1320162560, u32 = 1320162560, u64 = 126810229576960}}, {events = 0, data = {ptr = 0x3c00000000, fd = 0, u32 = 0, u64 = 257698037760}}, {events = 0, data = {ptr = 0x7fff240232f0, fd = 604123888, u32 = 604123888, u64 = 140733797511920}}, {events = 1216, data = {ptr = 0x977584, fd = 9926020, u32 = 9926020, u64 = 9926020}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x4030, fd = 16432, u32 = 16432, u64 = 16432}}, {events = 23734476, data = {ptr = 0x3c000057ee, fd = 22510, u32 = 22510, u64 = 257698060270}}, {events = 0, data = {ptr = 0x57ee016a2348, fd = 23733064, u32 = 23733064, u64 = 96679737566024}}, {events = 24, data = {ptr = 0x1400000000, fd = 0, u32 = 0, u64 = 85899345920}}, {events = 0, data = {ptr = 0x100000001, fd = 1, u32 = 1, u64 = 4294967297}}, {events = 267, data = {ptr = 0xe000007355, fd = 29525, u32 = 29525, u64 = 962072703829}}, {events = 0, data = {ptr = 0x57ee01922780, fd = 26355584, u32 = 26355584, u64 = 96679740188544}}, {events = 1317036808, data = {ptr = 0x4e945ac000007355, fd = 29525, u32 = 29525, u64 = 5662250412191806293}}, {events = 29525, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 2682984, data = {ptr = 0xfff90500000057ee, fd = 22510, u32 = 22510, u64 = 18444779246430738414}}, {events = 22509, data = {ptr = 0x57ee00bf7d10, fd = 12549392, u32 = 12549392, u64 = 96679726382352}}, {events = 1317037673, data = {ptr = 0x19226b000007355, fd = 29525, u32 = 29525, u64 = 113195477993812821}}, {events = 22510, data = {ptr = 0x73554e863bed <__GI___close+77>, fd = 1317420013, u32 = 1317420013, u64 = 126810226834413}}, {events = 604124036, data = {ptr = 0x18f5db000007fff, fd = 32767, u32 = 32767, u64 = 112411526203211775}}, {events = 0, data = {ptr = 0xfffffffffffffdd8, fd = -552, u32 = 4294966744, u64 = 18446744073709551064}}, {events = 1967493888, data = {ptr = 0x28f06825e8d657, fd = 636016215, u32 = 636016215, u64 = 11523329171707479}}, {events = 22510, data = {ptr = 0x57ee00c95d90, fd = 13196688, u32 = 13196688, u64 = 96679727029648}}}
        source = <optimized out>
        i = <optimized out>
        count = <optimized out>
        has_timers = <optimized out>
#9  0x000073554eb052d7 in wl_display_run (display=0x57ee0028f020) at ../wayland-1.22.0/src/wayland-server.c:1493
#10 0x000057edfff34c5e in server_run (server=<optimized out>) at ../sway-1.9/sway/server.c:398
#11 main (argc=<optimized out>, argv=0x7fff24023608) at ../sway-1.9/sway/main.c:415
        config_path = 0x0
        c = <optimized out>
        validate = false
        debug = false
        allow_unsupported_gpu = true
--Type <RET> for more, q to quit, c to continue without paging--
        verbose = false
```

**Comment by emersion** [comment] 2024-03-12 10:51
Duplicate of https://github.com/swaywm/sway/issues/7895

wlroots 0.17.2 fixes this.

**Closed by emersion** 2024-03-12 10:51 UTC
Labels: bug
