### ISSUE TITLE
Drag-and-drop causes Firefox on Wayland to ignore keypresses

### ISSUE THREAD

**Issue by SwayUser** [swaywm/sway#3820] opened 2019-03-05 09:41 UTC
* Sway Version:
sway version 1.0-rc1-144-ga6711740 (Mar  5 2019, branch 'master')

* Debug Log:
https://0x0.st/zo2t.log (firefox-wayland.log)
https://0x0.st/zo2v.log (sway.log)

* Configuration File:
https://0x0.st/zo2y.txt (config)

* Steps to Reproduce
1. Start Firefox
2. Go to a site where drag-and-drop is used, in example https://catbox.moe
3. Start Nautilus
4. Drag an image into Firefox.
5. Notice that typing has no effect anymore, like for example in the address bar.

It works again when changing to a different window and then back to Firefox.

**Comment by kamiyaa** [comment] 2019-03-14 13:26
Not sure if this is related, but `Alt+Left` and `Alt+Right` doesn't work on Firefox on wayland either.

**Comment by NilsIrl** [comment] 2019-12-15 22:48
Can someone confirm this is specific to Firefox?

Because I have to problem with:

* Firefox -> Firefox
* Firefox -> Anki

**Comment by kchibisov** [comment] 2019-12-25 06:09
>Can someone confirm this is specific to Firefox?

No, it also happens with `mpv` for me (`Thunar -> mpv`). mpv just ignores everything from keyboard unless you refocus it (mouse works fine).

**Comment by nickdiego** [comment] 2020-04-10 00:07
This seems to be a general DND issue, it happens with any client. Just came across it with an app I'm developing and then tested dragging files between 2 nautilus windows and it is reproducible always. The keyboard input just works after switching focus to another client and then getting it back to it.

This is the [debug log](https://gist.github.com/nickdiego/308d615c30acaf094cef1cbd19a0841f) for the nautilus test I describe above, hope it helps to analyzing it.

**Comment by NilsIrl** [comment] 2020-12-06 10:59
This seems to be fixed on Sway 1.5. I no longer have this issue

**Comment by NilsIrl** [comment] 2020-12-06 11:01
https://github.com/swaywm/sway/pull/5489 Seems to have fixed it

**Closed** 2020-12-06 11:13 UTC
Labels: bug, input/keyboard
