### ISSUE TITLE
Title bar chinese character is cutted

### ISSUE THREAD

**Issue by sbwtw** [swaywm/sway#1508] opened 2017-12-09 14:03 UTC
![1](https://user-images.githubusercontent.com/3384652/33796315-c45e513e-dd2c-11e7-95db-7795560d8b95.png)

**Comment by thejan2009** [comment] 2017-12-09 18:52
https://github.com/i3/i3/issues/2871

**Comment by 4e554c4c** [comment] 2017-12-09 19:00
https://github.com/swaywm/sway/blob/7c3b0ffc324d913dd1c58b2497c9c36c74580ded/sway/border.c#L99-L107

The problem is just that we assume the text will never be larger than the height of "Gg". The solution would be to set the size of the titlebar to be the actual hight of the text plus a certain number of pixels each time it changes.

**Comment by SirCmpwn** [comment] 2018-07-25 15:40
I'm closing issues that are resolved by the yet-unrelated sway 1.0.

**Closed by SirCmpwn** 2018-07-25 15:40 UTC
