### ISSUE TITLE
Gajim Breaks Drag and Drop

### ISSUE THREAD

**Issue by SwayUser** [swaywm/sway#3736] opened 2019-02-20 11:44 UTC
When starting Gajim and setting it to floating mode, drag and drop breaks for Sway and things can't be dragged anymore.

* Sway Version:
`sway version 1.0-beta.2-403-gbe0588ef (Feb 19 2019, branch 'master')`

* Debug Log:
https://0x0.st/zip1.log

* Configuration File:
https://0x0.st/zipQ.txt

* Nautilus Wayland Debug Log:
https://0x0.st/zipj.log

* Gajim Wayland Debug Log:
https://0x0.st/zip2.log

* Steps to Reproduce:
1. Start Gajim.
2. Set Gajim to floating mode.
3. Start Nautilus.
4. Try to drag a file from Nautilus into Gajim.

**Comment by emersion** [comment] 2019-02-20 12:46
Can you reproduce with https://github.com/swaywm/sway/pull/3700 and https://github.com/swaywm/wlroots/pull/1517?

**Comment by SwayUser** [comment] 2019-02-20 14:25
It still happens for me with these branches.
https://0x0.st/ziOH.log (gajim-wayland.log)
https://0x0.st/ziOX.log (nautilus-wayland.log)
https://0x0.st/ziO8.log (sway.log)

**Comment by emersion** [comment] 2019-02-20 14:42
Seems like this is the culprit:

```
2019-02-20 15:22:33 - [sway/input/seat.c:322] Ignoring start_drag request: could not validate pointer or touch serial 62
```

**Comment by emersion** [comment] 2019-02-23 18:18
I'm going to close this as a duplicate of https://github.com/swaywm/sway/issues/3538. Apparently it's related to floating mode.

**Closed by emersion** 2019-02-23 18:18 UTC
