### ISSUE TITLE
for_window [title="Scratchpad"] move container to workspace 6

### ISSUE THREAD

**Issue by kristoferus75** [swaywm/sway#4127] opened 2019-05-05 15:11 UTC
Hi !

I use sway version 1.0

if i use this in the config sway crashed if i start :

termite -t Scratchpad

`for_window [title="Scratchpad"] move container to workspace 6`

Should this work ?

I can provide also a debug if nessacery !

kind regards

kristoferus75

**Comment by emersion** [comment] 2019-05-05 15:16
Please provide a stack trace. You can do so by running `coredumpctl gdb` and then `bt full`.

**Comment by kristoferus75** [comment] 2019-05-05 15:34
Hi !

```
coredumpctl gdb
           PID: 32663 (sway)
           UID: 1000 (kristofers75)
           GID: 100 (users)
        Signal: 8 (FPE)
     Timestamp: Sun 2019-05-05 16:52:44 CEST (39min ago)
  Command Line: /usr/bin/sway
    Executable: /usr/bin/sway
 Control Group: /user.slice/user-1000.slice/session-29.scope
          Unit: session-29.scope
         Slice: user-1000.slice
       Session: 29
     Owner UID: 1000 (kristofers75)
       Boot ID: 2ef5583d080b4e7bb3f45e05b68981a4
    Machine ID: 68a64125f1414002a43d9b0866b297d6
      Hostname: HOME
       Storage: /var/lib/systemd/coredump/core.sway.1000.2ef5583d080b4e7bb3f45e05b68981a4.32663.1557067964000000.lz4
       Message: Process 32663 (sway) of user 1000 dumped core.
                
                Stack trace of thread 32663:
                #0  0x000056162c1d8228 n/a (sway)
                #1  0x000056162c207550 n/a (sway)
                #2  0x000056162c207e26 n/a (sway)
                #3  0x000056162c207741 n/a (sway)
                #4  0x000056162c1fef65 n/a (sway)
                #5  0x000056162c1d5422 n/a (sway)
                #6  0x000056162c204908 n/a (sway)
                #7  0x000056162c205690 n/a (sway)
                #8  0x00007f8fe7dcf7f2 wl_event_loop_dispatch (libwayland-server.so.0)
                #9  0x00007f8fe7dce39c wl_display_run (libwayland-server.so.0)
                #10 0x000056162c1ce562 n/a (sway)
                #11 0x00007f8fe83cdce3 __libc_start_main (libc.so.6)
                #12 0x000056162c1ce9ae n/a (sway)
                
                Stack trace of thread 32665:
                #0  0x00007f8fe7c92bac pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f8fe5d4e254 n/a (i965_dri.so)
                #2  0x00007f8fe5d4df78 n/a (i965_dri.so)
                #3  0x00007f8fe7c8ca92 start_thread (libpthread.so.0)
                #4  0x00007f8fe84a4cd3 __clone (libc.so.6)
```

**Comment by emersion** [comment] 2019-05-05 15:36
Gah. Can you build sway with debug info? (If you'r using arch temporarily installing `sway-git` should do it)

**Comment by kristoferus75** [comment] 2019-05-05 15:46
Hi !
Here the debug log -> if it help something !

[sway.log](https://github.com/swaywm/sway/files/3145721/sway.log)

kind regrads

**Comment by RedSoxFan** [comment] 2019-05-06 02:36
Duplicate of #3870

**Closed by RedSoxFan** 2019-05-06 02:36 UTC
