### ISSUE TITLE
xwayland apps wont open at all

### ISSUE THREAD

**Issue by GreyXor** [swaywm/sway#5568] opened 2020-07-22 09:44 UTC
### Please fill out the following:
- **Sway Version:**
sway version v1.5 b5139813

- **Debug Log:**
https://termbin.com/y794

- **Configuration file:**
I have this problem with both default configuration and my perso configuration

- **Description:**
Hello, i can't open xwayland application 

```
GDK_BACKEND=x11 xeyes                                                                                                                                                          
Error: Can't open display: :0
```
i have the same problem with, vscodium, goland, virtualbox

**Comment by emersion** [comment] 2020-07-22 09:46
```
00:00:05.902 [sway/desktop/xwayland.c:428] handle_unmap:Cannot unmap unmapped view
```

**Comment by GreyXor** [comment] 2020-07-22 09:50
I can't reproduce the bug since i just recompile wlroots master and sway master

**Comment by RedSoxFan** [comment] 2020-07-22 22:59
> I can't reproduce the bug since i just recompile wlroots master and sway master

I'm going to take a guess that this was due to an ABI change from swaywm/wlroots#2337 and close this. If you can reproduce, feel free to re-open.

**Closed by RedSoxFan** 2020-07-22 22:59 UTC
Labels: bug, xwayland
