### ISSUE TITLE
Segmentation fault during server_fini

### ISSUE THREAD

**Issue by tobiasblass** [swaywm/sway#2149] opened 2018-06-20 21:07 UTC
Terminating sway using the _exit_ command causes a segmentation fault due to a stray function pointer. This happens consistently as long as at least one window has been opened. The core dump I have is for a Xwayland window, but I have been able to reproduce the issue with a native wayland window as well.

I've attached the stacktrace. The 7f1e* memory range belongs to wlroots, the 55b8* range to sway. Since the bogus pointer points into sway memory I think it is a sway issue (as opposed to an wlroots issue).
[stacktrace.txt](https://github.com/swaywm/sway/files/2120986/stacktrace.txt)

*Sway version*: [This pull request](https://github.com/swaywm/sway/pull/2146). Since the server is up and running at the point of this crash, this should be equivalent to the current master.(202ee511503bc7c6a18dec440ac3cdb8d5e8f859)
*Wlroots version*: master (4a5e2671663ffad61c637b1c5c3908319e7d2e0f)

I'll further look into it myself over the next couple of days, but here is what I got so far:
The culprit is the texture->impl->destroy call in wlroots/render/wlr_tecture.c:16.
<pre> 
(gdb) p *texture->impl
$2 = {get_size = 0x55b878158f20, write_pixels = 0x41, destroy = 0x55b87891bcb0} 
</pre>
Disassembling the destroy-pointer target shows, that the pointer does not point into any code:
<pre>
(gdb) x/16i 0x55b87891bcb0
   0x55b87891bcb0:	jl     0x55b87891bcf2
   0x55b87891bcb2:	adc    %al,0x40000010(%rcx)
   0x55b87891bcb8:	add    %al,(%r8)
   0x55b87891bcbb:	add    %al,(%rax)
   0x55b87891bcbd:	add    %al,(%rax)
   0x55b87891bcbf:	add    %al,-0x15(%rax)
   0x55b87891bcc2:	(bad)  
...
(gdb) x/16i 0x55b87891bcf2
   0x55b87891bcf2:	add    (%rax),%ah
   0x55b87891bcf4:	(bad)  
...
</pre>

Hexdumping the destination yields something that looks like pointers (but none of them belongs to a symbol, unfortunately).
<pre>
(gdb) x/8g 0x55b878704400
0x55b878704400:	0x000055b878158f20	0x0000000000000041
0x55b878704410:	0x000055b87891bcb0	0x000055b878a6f008
0x55b878704420:	0x000055b878a6efe0	0x000055b878a6edb0
0x55b878704430:	0x00007f1e20027540	0x00007f1e2002c850
</pre>

**Comment by emersion** [comment] 2018-06-20 21:09
Duplicate of https://github.com/swaywm/sway/issues/1859

**Closed by emersion** 2018-06-20 21:09 UTC
