### ISSUE TITLE
Sway won't start after upgrade

### ISSUE THREAD

**Issue by jezek** [swaywm/sway#6253] opened 2021-05-04 21:05 UTC
- **Sway Version:**
  - sway version 1.6

- **Debug Log & Configuration File:**
  - https://gist.github.com/jezek/988d16cf9b9566d4d529baa05b4cb373  

- **Stack Trace:**
  - I don't know if it crashes, but i won't start

- **Description:**
  - I updated sway via package manager & restarted.
  - The device is an ARM device ```pinebook 1080p``` & the system is ```manjaro linux```. In forum I read that there is problem with swaybar bluetooth module on ```pinebook pro```, which won't start sway, but this seems not to be the issue here. I've tried to downgrade sway with wlroots (to wlroots-0.12.0-1-aarch64, sway-1:1.5.1-2-aarch64) and it started successfully (I've incloded the working log to gist too). For the logs I've used [default config found in repo](https://github.com/swaywm/sway/blob/d7ec66d563adcc069c3ba09c4cdeaf1281f1670c/config.in).

**Comment by emersion** [comment] 2021-05-05 07:12
The relevant part of the logs is:

```
00:00:02.926 [DEBUG] [wlr] [backend/drm/util.c:233] Unable to add DRM framebuffer, trying legacy method: No such file or directory
00:00:02.927 [ERROR] [wlr] [backend/drm/util.c:198] Unable to add DRM framebuffer: No such file or directory
00:00:02.927 [ERROR] [wlr] [backend/drm/util.c:237] Unable to add DRM framebuffer
00:00:02.927 [DEBUG] [wlr] [backend/drm/renderer.c:417] Failed to import GBM BO in KMS
00:00:02.927 [ERROR] [wlr] [backend/drm/renderer.c:323] Failed to import buffer
```

So, given that

```
00:00:01.794 [INFO] [wlr] [render/gles2/renderer.c:871] GL vendor: lima
```

this seems to be a duplicate of https://github.com/swaywm/wlroots/issues/2795.

**Comment by jezek** [comment] 2021-05-06 03:56
Wow, what a prompt answer.

So, basically, what they agreed in swaywm/wlroots#2795 is, that there is a bug in lima drivers (renderer?), becasue they mistook somehing for something and are reporting wrong values.

My question is, why the bug in lima doesn't affect the previous sway version? Is there any (compile) switch to revert to previous way of using the lima thing, so that sway doesn't crash?

Thank for your time.

**Comment by emersion** [comment] 2021-05-07 10:03
wlroots 0.13.0 has been refactored to use DMA-BUFs all across the board, which causes the lima bug to make Sway unusable. There's no way to revert, no.

Closing since we have another issue to track this.

**Closed by emersion** 2021-05-07 10:03 UTC
Labels: bug
