### ISSUE TITLE
Android Studio Not working

### ISSUE THREAD

**Issue by incrypt0** [swaywm/sway#4455] opened 2019-08-15 10:00 UTC
Android Studio Shows a grey thingy only not working even after exporting the _JAVA_AWT_WM_NONREPARENTING=1 
![2019-08-15-150449_grim](https://user-images.githubusercontent.com/44740264/63088129-a1e72300-bf71-11e9-8ae4-b33676deef9d.png)

**Comment by vl-underworld** [comment] 2019-08-16 10:25
As far as i know, android-studio awfully supports tiling and maximizing in window managers. What if you try to run it floating?

**Comment by panaman67** [comment] 2019-08-16 14:10
https://www.reddit.com/r/swaywm/comments/cqnmb8/java_applications_not_working_properly_in_my_case/

seems to be a solution

**Comment by RPigott** [comment] 2019-08-19 05:28
Setting _JAVA_AWT_WM_NONREPARENTING=1 fixes AS for me. I don't think you've successfully set it in sway's environment.

**Comment by daanjderuiter** [comment] 2019-08-19 10:26
Not so much a solution, but a workaround (similar to setting _JAVA_AWT_WM_NONREPARENTING) is to install a tool called wmname and run `wmname LG3D`. See also [the Arch Wiki](https://wiki.archlinux.org/index.php/Java#Impersonate_another_window_manager). It seems to be an issue with other Java-based GUIs as well, including Jetbrains products and Matlab, to name a few. However, after using this command, I still encountered some glitches in their GUIs, though they are mostly usable.

**Comment by Xyene** [comment] 2020-04-29 19:21
Going to close this since while annoying, there's not much that can be done on sway's end -- the issue is on Java's end, and whatever fixes happen there (i.e. real Wayland support) will trickle down into Jetbrains IDEs.

There's a note regarding the `_JAVA_AWT_WM_NONREPARENTING` workaround in https://github.com/swaywm/sway/wiki/Running-programs-natively-under-Wayland

**Closed by Xyene** 2020-04-29 19:21 UTC

**Comment by xyproto** [comment] 2020-08-26 11:09
Using Java 14 for Android Studio, but keeping Java 8 for development, solved the issue for me:

```bash
# For Android Studio
export _JAVA_AWT_WM_NONREPARENTING=1
export STUDIO_JDK=/usr/lib/jvm/java-14-openjdk

# For Gradle
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
```

I'm on Arch Linux. Adjust the paths so that they point to a valid location on your system.
