### ISSUE TITLE
Virt-manager right click menu spawns on wrong monitor, and is unclickable until virt-manager is resized

### ISSUE THREAD

**Issue by GSF1200S** [swaywm/sway#3996] opened 2019-03-30 05:46 UTC
Sway version 1.0. Arch Linux up-to-date.

I've had this problem for awhile, but the bug has changed in some recent change where it is harder to work around. I can provide pictures if it would help you to picture my problem.

Before getting into the bug itself, its worth noting that Sway seems to think my right monitor is my primary monitor. This is despite the fact that my video-card/bios only powers the left screen until the linux framebuffer kicks in. This leads to a situation where I cannot move the mouse from the right side of the left screen to the right screen- instead I have to move the mouse from the left side of the left screen where it then pops up on the right side of the right screen. I know this seems like a different bug, but I'm mentioning it here because it seems to me like perhaps its related. I can fix this problem by putting in my config: exec_always swaymsg output DVI-I-1 pos 1920 0 res 1920x1080

Onto the problem I'm reporting. I have Sway launch virt-manager on my left monitor upon startup (on workspace 1: WebVM). If I launch VMs they spawn on 1: WebVM as they should, and I can use the virt-manager menubar without issue. If I right click on a VM however, the context menu spawns on the second monitor. Interestingly, if I go to the "Shut Down..." submenu (which spawns another menu), it then pops up on the right side of the left screen. Prior to some recent change, I could still click on these menus and their functions would work- it is worth noting that no gtk highlighting of the menu options would appear when mousing over, but they would nonetheless work.

Now, trying to select a menu item causes the resize icon to appear. I cannot select any of the items on the menu unless I resize virt-manager to span both displays where the virt-manager window is "underneath" the menu on the second screen. Once that configuration is accomplished, the menu works (though again no gtk theming works). Here's the logs- let me know if you need pics...

[virterror.log](https://github.com/swaywm/sway/files/3025189/virterror.log)

**Comment by RedSoxFan** [comment] 2019-03-30 05:59
>  putting in my config: exec_always swaymsg output DVI-I-1 pos 1920 0 res 1920x1080

No need for the `exec_always swaymsg`. Having `output DVI-I-1 pos 1920 0 res 1920x1080` in the config should work fine

> If I right click on a VM however, the context menu spawns on the second monitor.
> ```
> 2019-03-30 00:00:56 - [sway-1.0/sway/config/output.c:316] Set DVI-I-1 position to 1920, 0                                                                                                 
> 2019-03-30 00:00:56 - [sway-1.0/sway/tree/arrange.c:190] Usable area for ws: 1920x1080@0,0                                                                                                
> 2019-03-30 00:00:56 - [sway-1.0/sway/tree/arrange.c:221] Arranging workspace '1: WebVM' at 1920.000000, 0.000000                                                                          
> 2019-03-30 00:00:56 - [sway-1.0/sway/tree/arrange.c:190] Usable area for ws: 1920x1080@0,0                                                                                                
> 2019-03-30 00:00:56 - [sway-1.0/sway/tree/arrange.c:221] Arranging workspace '6: Music' at 3840.000000, 0.000000
> ```

It looks like your left-most output is at 1920,0 and virt-manager is a gtk3 app using xdg-shell. Closing as a duplicate of #3135

**Closed by RedSoxFan** 2019-03-30 05:59 UTC

**Comment by GSF1200S** [comment] 2019-03-30 22:41
Understood, and thanks for letting me know pertaining to the output command I was using.

Link to virt-manager bug report in case anyone experiences similar or is curious of progress on that front: https://bugzilla.redhat.com/show_bug.cgi?id=1694379
