### ISSUE TITLE
stack on start when nvidia installed but blacklisted

### ISSUE THREAD

**Issue by yw662** [swaywm/sway#3265] opened 2018-12-06 12:25 UTC
I understand it but, I blacklisted the nvidia driver, in a file inside /etc/modprobe.d, by

````
blacklist nvidia
blacklist nvidia_drm
blacklist nvidia_modeset
````

So nvidia is not loaded. And I can confirm it by `lsmod | grep nvidia`.

The problem is, when I start sway, it prints several lines of debug information and spin.
I use nvidia for cuda, so I dont want to just remove it. But I guess there is a way to let sway get rid of it while I can still use it.

sway version: 0.15.2
cannot get debug log because it just cannot start.

**Comment by progandy** [comment] 2018-12-06 12:38
Try to set WLR_DRM_DEVICES to your intel/amd graphics card.

https://github.com/swaywm/sway/wiki#i-have-a-multi-gpu-setup-like-intelnvidia-or-intelamd-and-sway-does-not-start

**Comment by yw662** [comment] 2018-12-06 12:56
Thanks, but there is only one card called card0, which is the i915 card, since I blacklisted nouveau as well.

And I set WLR_DRM_DEVICES=card0, it still stack.

**Comment by RyanDwyer** [comment] 2018-12-06 13:02
> sway version: 0.15.2

Try the latest version in master, along with wlroots. It's pretty much a rewrite and solves many problems in 0.15.

**Comment by yw662** [comment] 2018-12-06 13:18
Thanks RyanDwyer, I tried the master version,
Since I do not use logind,
It now gives out

````
Failed to get session id: No data available
Do not have CAP_SYS_ADMIN, cannot become DRM master
Failed to load session backend
Failed to start a DRM session
Unable to create backend
````

After I give sway CAP_SYS_ADMIN, it stacks.

**Comment by ddevault** [comment] 2018-12-20 15:11
Don't give it CAP_SYS_ADMIN. Clear all caps and give it setuid (chmod a+s /usr/bin/sway)

**Comment by emersion** [comment] 2018-12-20 15:48
>give it setuid

No. It seems you have logind installed and it fails to use that.

```
Failed to get session id: No data available
```

Are you sure you have a working dbus setup? Which distribution are you using?

**Comment by emersion** [comment] 2018-12-20 15:50
>Since I do not use logind,

Eh. Then you have compiled wlroots with logind support, but don't want to use it. Weird.

Please try what @ddevault suggested.

**Comment by yw662** [comment] 2018-12-20 15:58
These errors only occur when there is neither srtuid nor CAP_SYS_ADMIN. I guess this is related to libglvnd since I still have nvidia-dkms installed. Or it is rrlated to i915, maybe.

It is arch but I simply masked logind. Whatever it is not related to dbus and logind.

**Comment by manio** [comment] 2018-12-21 05:04
Hi guys,
I don't know if it is related but I also have similar problem. I was just trying to run sway on new machine. It's debian sid. I just cloned and installed wlroots and sway as usual (master git). The host have two gpu's:
- radeon
- nvidia (using nouveau)

When i just type 'sway -d' then I've got:
```2018-12-21 05:54:55 - [sway/server.c:34] Preparing Wayland server initialization```
```2018-12-21 05:54:55 - [backend/session/logind.c:494] Failed to get session id: No data available```
```2018-12-21 05:54:55 - [backend/session/direct-ipc.c:47] Do not have root privileges; cannot become DRM master```
```2018-12-21 05:54:55 - [backend/session/session.c:91] Failed to load session backend```
```2018-12-21 05:54:55 - [backend/backend.c:265] Failed to start a DRM session```
```2018-12-21 05:54:55 - [sway/server.c:40] Unable to create backend```

After making sway binary setuid it just stack on startup with black screens (on one screen the console logs are frozen). When I masked systemd-logind and rebooted, similar error as above log appear and it doesn't start.

Do i need to compile wlroots without logind support?

**Comment by ascent12** [comment] 2018-12-21 05:10
@manio: You definitely want to use logind. Our direct session is crap (I know: I wrote it).
I'm going to guess that you're trying run sway as root or through an otherwise "improper" login session (e.g. using su or sudo). Make sure you're running sway without setuid or setcap, and log in as a normal user.
Otherwise, something about your logind/dbus session is screwed up.

**Comment by manio** [comment] 2018-12-21 05:16
@ascent12
No, I was trying to run it from normal user... (I logged from regular getty from VT - system is booted to text mode). Now I am running sway without setuid (I did it only once for testing as pointed in this issue).

**Comment by yw662** [comment] 2018-12-21 05:54
@manio
give it setuid or CAP_SYS_ADMIN will solve it. You issue is not related with this one.

**Comment by yw662** [comment] 2018-12-21 05:55
@manio

Lets you get stacked with no output after give it setuid, right?

If so, I am not sure whether it is telated or not, if not, it is not related.

**Comment by manio** [comment] 2018-12-21 07:13
In my case i don't need to do REISUB, I can login remotely via ssh

**Comment by manio** [comment] 2018-12-21 21:13
My problem was that loginctl list-sessions was returning 'no sessions'. I reinstalled pam because the problem was with systemd-pam. After fixing this, the sessions are registered properly and I can run sway from normal user (and without any setuid workarounds).
It is running perfectly fine on two gpu (radeon, nouveau) and 3 displays :)

thank you for help/tips :)

**Comment by emersion** [comment] 2021-09-12 07:10
Closing because this is old and missing debug logs. Re-open if you can still reproduce.

**Closed by emersion** 2021-09-12 07:10 UTC
