### ISSUE TITLE
Can click through window

### ISSUE THREAD

**Issue by kchibisov** [swaywm/sway#5125] opened 2020-03-19 20:43 UTC
if I launch one of the examples from https://github.com/smithay/client-toolkit with

```
cargo run --example kbd_input
```

make it float, and toggle CSD, you'll be able to click through the window on some area at the very bottom of it.

![pic](https://user-images.githubusercontent.com/27620401/77112623-5e3e2580-6a3a-11ea-81d1-ede3a9a277de.png)

This text cursor is from alacritty, that was behind this client. It's also noticeable with borders, since you can drag them to resize the window, however you can't click on some of them at all. You can also notice that it jumps a bit if you hover mouse over its title bar.

weston/gnome works fine with these clients.

sway version:
version 1.4-fcd524bb (Mar 18 2020, branch 'HEAD')

`WAYLAND_DEBUG=1` log from this client.
[wayland-debug.txt](https://github.com/swaywm/sway/files/4356819/wayland-debug.txt) 

sway log:
[sway.log](https://github.com/swaywm/sway/files/4356805/sway.log)

**Comment by wisp3rwind** [comment] 2020-03-27 14:40
Same here, e.g. using KeepassXC: `border normal` works, but `border csd` will trigger the issue. Let me know if I can help debugging.

**Comment by chron-isch** [comment] 2020-05-19 13:16
I can also reproduce this with mpv and any border settings.
Just enable borders, resize the window and you'll see that the borders end before the actual window does.

![Screenshot 2020-05-19 15-11-08](https://user-images.githubusercontent.com/1332352/82330863-a5697800-99e3-11ea-8b2f-cdf577c647e1.png)

**Comment by kchibisov** [comment] 2020-05-19 13:19
Try latest mpv, like `v0.32.0`+, probably fixed there. The original issue is about CSD and a bit different, in your issue mpv draws outside the borders.

**Comment by kennylevinsen** [comment] 2020-06-03 13:28
Should be fixed by https://github.com/swaywm/sway/pull/5403.

**Comment by kchibisov** [comment] 2020-06-03 14:11
While the clicking through window part is solved, it's actually not entirely fixed due to decorations around the window, since they're not clickable, however there's an invisible border of 12 logical pixels for resizing. without that patch it seems like there were at least on border on top, however now it seems like there's no one of them, but the surface doesn't jump and you can't click through it.

**Comment by kennylevinsen** [comment] 2020-06-03 14:45
Might be a wlroots bug? See this debug state:

![screenshot](https://user-images.githubusercontent.com/176245/83651015-4dbd3600-a5b9-11ea-9a5c-a5bc73707eeb.png)

We can see that there are indeed subsurfaces at positions like -12x-42. However, for this state, wlr_xdg_surface_get_geometry returns:
```
wlr_box {
    x: 0,
    y: -30,
    width: 1280,
    height: 720,
}
```

This is only accounting for the titlebar CSD.

**Comment by wisp3rwind** [comment] 2020-11-25 14:01
With https://github.com/swaywm/sway/pull/5812, this seems to be fixed for me :tada:

**Closed** 2020-11-25 14:09 UTC
