### ISSUE TITLE
bindsym Shift+Alt+Print depends on modifier release order

### ISSUE THREAD

**Issue by YaLTeR** [swaywm/sway#4208] opened 2019-06-03 09:22 UTC
* Sway Version: `1.1-rc1-23-g5ff330e6 (Jun  2 2019, branch 'master')`
* Debug Log: https://gist.github.com/YaLTeR/11b54c30b8b6dcc412269a72c85fbc67
* Configuration File: default with:
```
bindsym Alt+Print exec swaynag -m "Alt+Print"
bindsym Shift+Alt+Print exec swaynag -m "Shift+Alt+Print"
```
Binding Shift+Alt+Print doesn't trigger with a specific button release order (Print, then Shift, then Alt). Instead, Alt+Print is triggered.

In the provided debug log I press Alt+Print first, then Shift+Alt+Print and release Print, then Alt, then Shift (triggers Shift+Alt+Print as it should) and finally I press Shift+Alt+Print and release Print, then Shift, then Alt (triggers Alt+Print instead of Shift+Alt+Print). Binding Alt+Shift+Print instead of Shift+Alt+Print doens't change the behavior.

**Comment by schauveau** [comment] 2019-06-08 10:20
On most keyboards, the Print key also the SysRq key. You may just be experiencing a side effect of ux kernel intercepting some key events to implement its Magic SysRq actions. 
https://en.wikipedia.org/wiki/Magic_SysRq_key
http://tldp.org/HOWTO/Remote-Serial-Console-HOWTO/security-sysrq.html
To summarize: Using Alt+Print is probably a bad idea unless you want to kill you system in some very unexpected ways. If you think that this is a dangerous feature that you will never need to use then you may want to disable it as indicated in the second link above.

**Comment by YaLTeR** [comment] 2019-06-08 10:25
Oh, I see, that could be the case I suppose. I have specifically enabled SysRq so that I can get out of hangs with SysRq+R and switching to a different VT.

**Comment by schauveau** [comment] 2019-06-08 11:17
I have to admin that I haven't used SysRq for years. There is nothing that I cannot resolve from a console by login in via ssh. And even if I had no other machine available, I would probably not remember the SysRq shortcuts :-) 
And a totally unrelated remark: I can infer from you question that you are probably using Alt as your primary modifier in Sway. I know that this is the default but why not use the Win key instead (so Mod4)? I have been doing that for ages in Sway and other X11 WM. It is now pretty much available on all keyboards and that makes the Alt key available for the application private shortcuts.

**Comment by YaLTeR** [comment] 2019-06-08 11:27
I do use Mod4 as my modifier. I just have a set of Print, Shift+Print, Ctrl+Print shortcuts and I wanted a set of Alt+the same shortcuts so it's easy to press (on my keyboard the left Mod4 is not available, only the right one).

**Comment by RedSoxFan** [comment] 2019-07-11 05:21
Looks like schauveau was right. These are the events from libinput:

1. Pressed Alt, Shift, Print. Released in opposite order (Triggers: Alt+Print)
```
event3   KEYBOARD_KEY      +2.78s  KEY_LEFTALT (56) pressed
event3   KEYBOARD_KEY      +3.07s  KEY_LEFTSHIFT (42) pressed
event3   KEYBOARD_KEY      +3.63s  KEY_LEFTSHIFT (42) released
event3   KEYBOARD_KEY      +3.76s  KEY_LEFTALT (56) released
event3   KEYBOARD_KEY      +3.76s  KEY_LEFTALT (56) pressed
event3   KEYBOARD_KEY      +3.76s  KEY_SYSRQ (99) pressed
# Alt+Print triggered
event3   KEYBOARD_KEY      +3.76s  KEY_SYSRQ (99) released
event3   KEYBOARD_KEY      +3.76s  KEY_LEFTALT (56) released
```

2. Pressed Shift, Alt, Print. Released in opposite order (Triggers: Shift+Alt+Print)
```
event3   KEYBOARD_KEY      +4.29s  KEY_LEFTSHIFT (42) pressed
event3   KEYBOARD_KEY      +4.60s  KEY_LEFTALT (56) pressed
event3   KEYBOARD_KEY      +5.14s  KEY_LEFTALT (56) released
event3   KEYBOARD_KEY      +5.14s  KEY_LEFTALT (56) pressed
event3   KEYBOARD_KEY      +5.14s  KEY_SYSRQ (99) pressed
# Shift+Alt+Print triggered
event3   KEYBOARD_KEY      +5.14s  KEY_SYSRQ (99) released
event3   KEYBOARD_KEY      +5.14s  KEY_LEFTALT (56) released
event3   KEYBOARD_KEY      +5.15s  KEY_LEFTSHIFT (42) released
```

Unfortunately, this is just caused by the events given and there is nothing we can do about it

**Closed by RedSoxFan** 2019-07-11 05:21 UTC
