### ISSUE TITLE
scale of some softwares changed after switch to another tty and switch back

### ISSUE THREAD

**Issue by yw662** [swaywm/sway#1532] opened 2017-12-23 07:38 UTC
1. switch to another tty (which is probably not logged in)
2. switch back
3. try to open some softwares and the scale may change

affected: dmenu_run, vscode, pcmanfm, vlc, clion, gimp, blender
not affected: termite, min
distro: archlinux
wayland version:1.14.0
sway version: 0.15.0
card: intel
screen designed scale: 1.5
sway setting scale: 1

*not solved in version 0.15.1*

**Comment by SirCmpwn** [comment] 2017-12-28 02:37
Try this on sway 0.15.1 (just released).

**Comment by Timidger** [comment] 2017-12-28 02:52
This sounds like that scaling issue on wlc that affects Way Cooler as well and will be fixed with the move to wlroots.

**Comment by martinetd** [comment] 2017-12-28 07:19
I can actually reproduce with rootston and urxvt, so wlroots has the same issue.
Might want to open an issue there as well (or instead)

**Comment by yw662** [comment] 2017-12-28 09:58
update : version 0.15.1 wont solve this issue.

**Comment by Timidger** [comment] 2017-12-28 15:23
I can confirm this also happens in rootson with the same applications that affect it in Sway and Way Cooler.

This looks like a bug that might have been accidentally copied over from wlc to wlroots.

I noticed this only happens for xwayland apps, so the bug is probably in there. I'm going to try to dig around to find the cause, but someone more knowledgeable than me will probably find it first.

**Comment by SirCmpwn** [comment] 2017-12-28 15:24
It's probably an artifact of poor hotplugging code in both. IIRC tty switching "unplugs" all displays, then replugs them when you return. We need to reapply the output config (setting the scale factor) and send a surface_enter to all relevant clients.

**Comment by Timidger** [comment] 2017-12-28 15:38
Update: did a bisect and found the commit that introduced this regression (because it wasn't always like this): `bf1f461eba320cdeded1d5d8ae80caaa9d4cef98`.

**Comment by SirCmpwn** [comment] 2017-12-28 15:45
What repo is that commit in?

**Comment by martinetd** [comment] 2017-12-28 15:45
wlroots'

**Comment by SirCmpwn** [comment] 2017-12-28 15:45
Ah, thanks.

**Closed** 2018-07-25 15:40 UTC
