### ISSUE TITLE
Apps signed to another workpace

### ISSUE THREAD

**Issue by trmendes** [swaywm/sway#2351] opened 2018-07-24 22:16 UTC
Before today's version (sway version 1.0-alpha.493-g817d37c95032 (Jul 24 2018, branch 'master')) whenever I open an app that is signed to a different workspace I would see the new workspace icon on my swaybar straigh away but not anymore.

before sway version 1.0-alpha.493-g817d37c95032 (Jul 24 2018, branch 'master'):

sway bar: ------- 1. W1 -------- time
then I open an app from W1 that is assigned to show up at W2 and I have
sway bar: ------- 1. W1 2. W2 -------- time

now I'm using sway version 1.0-alpha.493-g817d37c95032 (Jul 24 2018, branch 'master')
the sway bar will only show the new workspace when I switch to it

sway bar: ------- 1. W1 -------- time
then I open an app from W1 that is assigned to show up at W2 and I have
sway bar: ------- 1. W1 -------- time
then I switch to W2 and I can see my app is there and now I have W2 on my sway bar
sway bar: ------- 1. W1 2. W2 -------- time

config example:
assign [class="^Firefox$"] $WS2

**Comment by RyanDwyer** [comment] 2018-07-25 13:40
I think what was happening was we would focus the new workspace, which triggers a `workspace::focus` IPC event which causes swaybar to update. But this focus-stealing is not the intended behaviour and was fixed in a recent commit.

There will be a `workspace::init` IPC event which causes swaybar to update. This isn't implemented yet - it's in #2264.

**Closed** 2018-07-25 16:47 UTC
