### ISSUE TITLE
Segfault after resuming from sleep

### ISSUE THREAD

**Issue by luispabon** [swaywm/sway#4725] opened 2019-11-13 13:13 UTC
* Sway Version:

sway version 1.2-1-gb62d83d6 (Jul 18 2019, branch 'v1.2')

* Debug Log:
Unfortunately sway cli logs were lost upon sway restart

* Configuration File:
https://github.com/luispabon/sway-dotfiles/tree/master/configs/sway

* What
After resuming from suspend and while testing for https://github.com/swaywm/swaylock/issues/90 (swaylock did crash too, will post on the other ticket the coredump and bt), sway came back. The active window was terminator (gtk3 wayland native). I have focus on click. Terminator could not be focused upon. Sway crashed after opening a second terminator instance via the sway keyboard shortcut (mod+enter).

* Stack Trace, if sway crashes:
coredump: https://pastebin.com/vGYnTbAu
bt: https://pastebin.com/TBVF17Xj

**Comment by JonnyMako** [comment] 2019-11-15 16:31
@luispabon , looks like debug symbols are missing in your build.

**Comment by rumpelsepp** [comment] 2019-11-22 07:26
I tried it a few times to reproduce with a recent build from git with enabled address sanitizer. The issue was not triggered. Is it fixed on master? @luispabon can you test it with a build from master (do not forget to build wlroots es well)?

**Comment by luispabon** [comment] 2019-11-22 10:54
Made a build of both and running it now, will report back.

Debug symbols are automatically built by debhelper, but even after installing it doesn't seem like they work. If anybody knows about debian packaging I could do with some help on this.

**Comment by rumpelsepp** [comment] 2019-11-22 11:17
Just build it yourself and drop the binary in /usr/local/bin or something. Debian packaging is so much pain.

**Comment by RedSoxFan** [comment] 2020-01-06 06:41
Duplicate of #4599 
Fixed by #4801

**Closed by RedSoxFan** 2020-01-06 06:41 UTC

**Comment by luispabon** [comment] 2020-01-06 11:56
Thank you!

**Comment by luispabon** [comment] 2020-01-09 13:29
I can confirm that fixed this problem.
