### ISSUE TITLE
firefox crashes with subwindow flickering

### ISSUE THREAD

**Issue by cherti** [swaywm/sway#7011] opened 2022-05-17 20:50 UTC
- **Sway Version:** 1.7

- **Debug Log:** https://gist.github.com/cherti/ae182d55d380cd853c37c0777a670197

- **Configuration File:** https://gist.github.com/cherti/e4002cfa7378059210629bdd6edfbb84

- **Description:**

### Steps to reproduce:

    1. get Firefox 100
    2. set MOZ_ENABLE_WAYLAND=1
    3. go to about:preferences
    4. scroll down to Language, click "Set Alternatives…"
    5. "Select a language to add"
    6. Select "search more languages"
    7. repeatedly* click on the dropdown with the languages

*) because it doesn't always, just mostly, crash upon first try, but does so reliably after a few (fast consecutive) tries

### Actual results:

Firefox either crashes, show the Crash Reporter window (production instances) or exits with code 11 (mozregression instances).
I found this behavior to be most reliably triggered in the language submenu, but I observed it on other menus as well, however not reliably enough to point to them.
From impression it looks like the language selection window is there, but always flickered to invisibility. I can select languages (but don't see which one until the window closes again) and a couple of tries later Firefox goes down crashing. So it seems the window is there, just constantly invisible.

### Expected results:

Firefox should not crash, instead let me select a language.

### Further information

mozregression tells me for where this was introduced:

9:18.19 INFO: No more integration revisions, bisection finished.
9:18.19 INFO: Last good revision: 9d480acd20a346ec47053b589f352e5d3191840d
9:18.19 INFO: First bad revision: 6697eafee26f909744265c9211b0b831622a1a85
9:18.19 INFO: Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=9d480acd20a346ec47053b589f352e5d3191840d&tochange=6697eafee26f909744265c9211b0b831622a1a85

Closed upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1769366 for reference.

This might be related to https://github.com/swaywm/sway/issues/7009 , originating in different code segments/changesets in Firefox, but maybe triggering the same bug.

**Comment by 9p4** [comment] 2022-05-18 00:24
https://bugzilla.mozilla.org/show_bug.cgi?id=1769457

**Comment by ndren** [comment] 2022-05-20 22:18
Hi! I was having the same issue before but after I built sway from git (1.8-dev-a3a82efb) solved it on my end. Hope that helps.

**Comment by cherti** [comment] 2022-06-02 19:34
That's good to know! I tried to test, but the current checkout of sway, while compiling, seems to misbehave, so I cannot verify this. But that sounds like the issue is resolved. You don't happen to know which commit that is, by any chance?

**Comment by ndren** [comment] 2022-06-10 23:15
I do not know which specific commit fixed the issue, but I do know that it works on the version I built, a3a82efbf6b5b3af840c70038b1b599ba29003ac (i.e. 1.8-dev-a3a82efb).

**Comment by mephitisdeux** [comment] 2022-07-04 10:23
> I am also having this issue on Firefox 101 and nightly (103 as of now) and Sway 1.7. I was able to isolate Sway as the cause by running Firefox in mutter and not being able to reproduce the bug. I've had this bug for a while but recently it is resulting in consistent crashes.
> 
> Associated Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1776619 (this has several crash dumps associated with it that might be useful for debugging)
> 
> I am trying to build sway from HEAD (when I started it was [a55472c](https://github.com/swaywm/sway/commit/a55472c6d882d806e9d6fc0a78a7f7d8f888492e)) to see if that fixes the issue.

Please let us know if you have any luck, because this has been driving me mad for months now.

**Comment by Relected** [comment] 2022-07-16 21:12
yeah for me context menus and drop downs are always flickering and cause firefox to crash

this only happened after i updated ff to 100

**Comment by Noah-Huppert** [comment] 2022-07-17 00:01
Yea I've had the issue on and off got a year or two now. But the crashes have only starter around ff 100 as well.

I never got the build succeeding that day but I'm going to try again soon. Mainly just bc I've been busy and not worked on my laptop for a bit.

**Comment by schauveau** [comment] 2022-07-19 20:10
After several experiments, I came to the conclusion that, on my laptop, the flickering of the context menu  (and the associated crashes) is only happening when the menu is so long that cannot be entirely opened above nor below the mouse cursor. Simply speaking, that is when the menu height is more than 50% of the screen height and the mouse click was close to the center of the screen.  When that happens, Firefox opens the context menu below the mouse thus causing it to overstep the bottom of the screen and, for whatever reason, flickering occurs and sometime a crash.

Most users are probably unaffected because context menus are often small. Some features (e.g Sync, Pocket, ...) and some add-ons can add entries to the context menus. On my laptop the screen is only 1024x768, I have a Sync account, and one add-on to send video links to my kodi server. Youtube is especially problematic for me because the video miniatures are both images and links which add several entries to the context menu. Its height is slightly more than 50% of the screen thus causing numerous crashes when I open it too close to the screen center.

Some options can help reduce the number of entries in context menus ( **devtools.inspector.enabled=false** and **extensions.pocket.enabled=false**) but unfortunately some actions such as selecting text can also add a few entries so this is never entirely safe.

Fortunately, I recently discovered **gtk.native-context-menus=true** 
As the name indicates that option makes FF use GTK to draw the context menus. No crashes to far.

**Comment by lilydjwg** [comment] 2022-07-20 04:22
> Most users are probably unaffected because context menus are often small.

I get it a lot on my laptop, but it doesn't crash (using wlroots git version and wayfire).

**Comment by schauveau** [comment] 2022-07-21 10:41
`widget.wayland.use-move-to-rect=false` seems to solve the problem. However, some menus may be rendered partially off-screen.

**Comment by 528-491** [comment] 2022-07-21 18:50
> `widget.wayland.use-move-to-rect=false` seems to solve the problem. However, some menus may be rendered partially off-screen.

Thanks, at least it won't crash anymore. Sufficient as a workaround until the next release for me.

**Comment by schauveau** [comment] 2022-07-21 19:04
I would not bet on a real fix soon. According to https://gitlab.gnome.org/GNOME/gtk/-/issues/1986 , the required features exist in gtk4 but are unlikely to be backported to gtk3.

**Comment by 528-491** [comment] 2022-07-23 15:25
I tried it on arch with sway-git and the problem is fixed there. So if I understand the idea of -git packages correctly, the fix will most likely be included in the next release.
![20220722_14h40m07s_grim](https://user-images.githubusercontent.com/106540875/180611544-f9b321a9-b923-450e-8785-1217c02f7975.png)

**Comment by schauveau** [comment] 2022-07-23 16:33
@528-491 Thanks. I managed to build the git version and this is indeed far better. When there is not enough space, the "right click" context menus are now constrained with scrolling arrows above or below the mouse pointer. This is not as good as allowing them to overlap with the mouse pointer (as done for the "button menu" in your screenshot) but this better than being partially off-screen. 
However, this is not perfect. I still managed to get flickering with a tall context menu by opening it exactly at the middle of the screen. The computations to constrain the context menus are probably off by a few pixels.

**Comment by tmccombs** [comment] 2022-11-02 06:18
I think I'm running into this as well, with a lot of my bookmark menus in firefox (I have a lot of bookmarks). 

There's another issue though that seems like it is related, but maybe it isn't where when I try to save a bookmark, if I edit the tag box, then the edit bookmark dialog disappears, but the suggestions popup appears, and I can still interact with the edit bookmark dialog, I just can't see it. Similar thing happens if I select the drop down for the location.

**Comment by tmccombs** [comment] 2022-11-02 06:20
I think I'm running into this as well, with a lot of my bookmark menus in firefox (I have a lot of bookmarks). 

There's another issue though that seems like it is related, but maybe it isn't where when I try to save a bookmark, if I edit the tag box, then the edit bookmark dialog disappears, but the suggestions popup appears, and I can still interact with the edit bookmark dialog, I just can't see it. Similar thing happens if I select the drop down for the location. 

Using `widget.wayland.use-move-to-rect=false` seems to sort of fix both issues (but now menus can be cut off because they are drawn outside of the parent window's bounding box).

**Comment by bl4ckb0ne** [comment] 2022-11-02 15:32
There's no ETA for 1.8 yet, but we're working on it. I will close the issue if its fixed on master, reopen it if it persists.

**Closed by bl4ckb0ne** 2022-11-02 15:32 UTC
Labels: bug
