### ISSUE TITLE
titlebar hiding not respected after closing last sibling

### ISSUE THREAD

**Issue by avrelaun** [swaywm/sway#2987] opened 2018-10-26 08:12 UTC
This one is a bug and a regression from i3 behaviour.

**Required config:**

new_window pixel 2
new_float pixel 2
workspace_layout default
hide_edge_borders smart (this one is probably not be related)

**Current behaviour:**

- Open a window on an empty workspace (titlebar is hidden)
- Open a second window on the same workspace (titlebars are visible)
- Put them into stack or tabbed (titlebars are visible)
- Close one window, leaving only one -> **titlebar is visible but should be hidden**

When there is only one window in a workspace, it should have only one container (previous parents should be removed) and title bar should be hidden if configured so.

**Comment by RedSoxFan** [comment] 2018-10-26 16:45
Duplicate of #2912

**Closed by RedSoxFan** 2018-10-26 16:45 UTC

**Comment by avrelaun** [comment] 2019-01-14 14:59
I still have this issue even though #3031 was merged. Can someone reopen or shall I create another ticket ?
