### ISSUE TITLE
Some XWayland windows are not being focused

### ISSUE THREAD

**Issue by rhysperry111** [swaywm/sway#5373] opened 2020-05-22 20:16 UTC
# Info:
- Sway version: 1.4
- Wlroots version: 0.10.1
- xorg-server-xwayland version: 1.20.8
- Debug log and config: https://gist.github.com/rhysperry111/8857df55d507081a4c595b14437617eb

# Issue:
Certain XWayland windows are:
- Not being focused
- Not obeying workspaces (stay on screen even when change workspaces)
- Not receiving any input
- "Invisible" (I can focus other windows through them)

Windows that have this problem (that I could find) are:
- Some steam popups
- Microsoft FSX Menu (running with Steam Proton)

This does not happen to the same window run in a standard Xorg server.

Recording of issue: https://youtu.be/V7Kcl6jCTp8

**Comment by progrestian** [comment] 2020-05-23 12:03
Same problem, mostly with games that have launchers (e.g. Warframe, Civ6, Ashes of the Singularity, etc.)

**Comment by Xyene** [comment] 2020-05-23 13:20
I've noticed this happening frequently in clicking buttons in Jetbrains IDE dialogs, sometimes clicks on buttons appear to be ignored.

`xtrace` of a click being ignored:

```
000:>:1c33e: Event ButtonPress(4) button=left button(0x01) time=0x02034081 root=0x00000214 event=0x01200015 child=None(0x00000000) root-x=1555 root-y=868 event-x=144 event-y=822 state=0 same-screen=true(0x01)
000:<:1c33f: 12: Request(42): SetInputFocus revert-to=PointerRoot(0x01) focus=0x012004df time=0x02034081
000:>:1c33f: Event ButtonRelease(5) button=left button(0x01) time=0x020340e3 root=0x00000214 event=0x01200015 child=None(0x00000000) root-x=1555 root-y=868 event-x=144 event-y=822 state=Button1 same-screen=true(0x01)
```
`xtrace` of a click being handled correctly:

```
000:>:1d8ad: Event ButtonPress(4) button=left button(0x01) time=0x0205b082 root=0x00000214 event=0x012004fd child=None(0x00000000) root-x=1044 root-y=852 event-x=953 event-y=781 state=0 same-screen=true(0x01)
000:<:1d8ae:  4: Request(43): GetInputFocus 
000:>:d8ae:32: Reply to GetInputFocus: revert-to=PointerRoot(0x01) focus=0x012004ff
000:<:1d8af: 12: Request(42): SetInputFocus revert-to=PointerRoot(0x01) focus=0x012004ff time=0x0205b082
000:<:1d8b0: 24: Request(20): GetProperty delete=false(0x00) window=0x012004fb property=0x13d("_NET_FRAME_EXTENTS") type=0x6("CARDINAL") long-offset=0x00000000 long-length=0x00000004
000:>:d8b0:32: Reply to GetProperty: type=None(0x0) bytes-after=0x00000000 
000:<:1d8b1:  8: Request(3): GetWindowAttributes window=0x012004fd
000:<:1d8b2:  8: Request(14): GetGeometry drawable=0x012004fd
```

It's pretty easy to reproduce this. Given some instance:

![image](https://user-images.githubusercontent.com/1403503/82731584-0a6be900-9cd6-11ea-8c19-5d09fde364a4.png)

Open up some dialog, and it will immediately gain focus regardless of the current mouse position.

![image](https://user-images.githubusercontent.com/1403503/82731605-2e2f2f00-9cd6-11ea-987a-365d3554a470.png)

At this point, clicking buttons (e.g. "Cancel") works fine (second `xtrace`). However, if you move the mouse into the dialog, out of it, and then back in, some broken state is entered where clicks no longer work (first `xtrace). However, if the button region overlaps another window under it, it'll work fine.

**Comment by rhysperry111** [comment] 2020-05-23 13:55
>  sometimes clicks on buttons appear to be ignored.
In the case of the FSX main window it is 100% percent of the time

**Comment by Xyene** [comment] 2020-05-23 14:55
Could you try building wlroots with https://github.com/swaywm/wlroots/pull/2219 applied?

```
$ cd /path/to/wlroots; curl -L https://github.com/swaywm/wlroots/pull/2219.diff | patch -p1
```

It's a hack (and a bad one that shouldn't be necessary), but it does resolve the issue with Jetbrains dialogs. With any luck it'd resolve your issues too, since they seem very similar in involving floating Xwayland windows.

**Comment by rhysperry111** [comment] 2020-05-23 15:12
@Xyene That did not fix my issue.
Just checking I did it right: what I did was install sway-git and wlroots-git from the AUR, but in the wlroots pkgbuild i changed the source to "github.com/Xyene/wlroots#branch=xwm-send-focus"

**Comment by Xyene** [comment] 2020-05-23 15:54
I'm not familiar with Arch, but that sounds about right. That's unfortunate, I hoped this might be a two-birds-with-one-stone kind of issue. Unfortunately, I'm running a weird mix of packages that preclude installing the 32-bit graphics stack that Steam needs to run, so I can't dig deeper myself.

That said, looking more closely, this looks a lot like https://github.com/swaywm/sway/issues/4600 and https://github.com/swaywm/sway/issues/4857. There are some workarounds in those threads that might be worth trying, if you haven't already.

I'm going to close this issue since the buggy behavior described is already covered by those existing issues.

**Closed by Xyene** 2020-05-23 15:54 UTC

**Comment by rhysperry111** [comment] 2020-09-02 10:40
I am hoping that #5650 will fix this issue

**Comment by rhysperry111** [comment] 2020-11-09 00:03
Update: #5650 did fix this issue. Thanks @junglerobba
