### ISSUE TITLE
Sway segfaults if the first action after reloading a config is swapping tiles by dragging

### ISSUE THREAD

**Issue by AMNatty** [swaywm/sway#7461] opened 2023-02-19 21:36 UTC
- **Sway Version:**
  - `1.8.1-68d620a8`
  - Also happens with the Arch Linux sway `1:1.8.1-1` build

- **Debug Log:**
[https://pastebin.com/npWDZ9hF](https://pastebin.com/npWDZ9hF)

- **Configuration File:**
Configuration agnostic

- **Stack Trace:**
```
               #0  0x0000559139d7dcb5 seat_get_focus (sway + 0x43cb5)
                #1  0x0000559139d7de3d seat_get_focused_container (sway + 0x43e3d)
                #2  0x0000559139d9e312 container_swap (sway + 0x64312)
                #3  0x0000559139d83089 finalize_move (sway + 0x49089)
                #4  0x0000559139d832a8 handle_button (sway + 0x492a8)
                #5  0x0000559139d7e214 seatop_button (sway + 0x44214)
                #6  0x0000559139d73047 dispatch_cursor_button (sway + 0x39047)
                #7  0x0000559139d73136 handle_pointer_button (sway + 0x39136)
                #8  0x00007fec468e9f6e wl_signal_emit_mutable (libwayland-server.so.0 + 0x9f6e)
                #9  0x00007fec468e9f6e wl_signal_emit_mutable (libwayland-server.so.0 + 0x9f6e)
                #10 0x00007fec4682dfc3 n/a (libwlroots.so.11 + 0x4ffc3)
                #11 0x00007fec45f364f6 n/a (libffi.so.8 + 0x74f6)
                #12 0x00007fec45f32f5e n/a (libffi.so.8 + 0x3f5e)
                #13 0x00007fec45f35b73 ffi_call (libffi.so.8 + 0x6b73)
                #14 0x00007fec45d7a645 n/a (libwayland-client.so.0 + 0x7645)
                #15 0x00007fec45d7ae03 n/a (libwayland-client.so.0 + 0x7e03)
                #16 0x00007fec45d7affc wl_display_dispatch_queue_pending (libwayland-client.so.0 + 0x7ffc)
                #17 0x00007fec46831675 n/a (libwlroots.so.11 + 0x53675)
                #18 0x00007fec468eb9e2 wl_event_loop_dispatch (libwayland-server.so.0 + 0xb9e2)
                #19 0x00007fec468ec197 wl_display_run (libwayland-server.so.0 + 0xc197)
                #20 0x0000559139d62a54 server_run (sway + 0x28a54)
                #21 0x0000559139d61abe main (sway + 0x27abe)
                #22 0x00007fec4658f790 n/a (libc.so.6 + 0x23790)
                #23 0x00007fec4658f84a __libc_start_main (libc.so.6 + 0x2384a)
                #24 0x0000559139d51a25 _start (sway + 0x17a25)
```

- **Description:**
  - Open window 1 (Konsole in this case)
  - Open window 2 (Konsole in this case)
  - `swaymsg reload`
  - Drag one of the window tiles over the other, to perform a tile swap
  - Segmentation fault (`config->handler_context.seat` is NULL [here](https://github.com/swaywm/sway/blob/788118f1944ca23a7f9a7d19537b7756f3518f55/sway/commands/swap.c#L137))

This crash is consistently reproducible.

**Comment by rpigott** [comment] 2023-02-19 23:52
Dupe of #5939?

**Comment by AMNatty** [comment] 2023-02-20 00:31
Seems like it, your comment at [https://github.com/swaywm/sway/issues/5939#issuecomment-758492315](https://github.com/swaywm/sway/issues/5939#issuecomment-758492315) matches my observed behavior as well. I introduced a short-term fix similar to #5950 in my system, however I suppose a short-term fix would be beneficial as such crashes may be disruptive.

**Comment by rpigott** [comment] 2023-02-20 00:38
Is #7462 enough to fix the crash for you?

**Comment by AMNatty** [comment] 2023-02-20 01:02
> Is #7462 enough to fix the crash for you?

Yes, this fixes the crash

**Closed** 2023-02-20 01:11 UTC
Labels: bug
