### ISSUE TITLE
Drag'n'drop session does not get cancelled when drop happens outside toplevel surfaces 

### ISSUE THREAD

**Issue by nickdiego** [swaywm/sway#5199] opened 2020-04-09 18:31 UTC
**Version:** Sway version 1.4
**Debug output:** [sway-dnd-issue.log](https://gist.github.com/nickdiego/5becea1a865a96d56a3b14ca1381c39e)
**Steps to repro:** 
1. Open Nautilus and put it in floating mode, for example (but it can be reproducible with other apps)
2. Drag a file to outside nautilus boundaries (ie: the desktop shell) and release the mouse button (drop)
**Expected result:** The dnd session should get cancelled (ie: wl_data_source::cancelled event, etc)
**Actual result:** It gets stuck with the dnd session (drag icon, etc.).

**Comment by emersion** [comment] 2020-04-09 18:57
Duplicate of https://github.com/swaywm/sway/issues/3932

**Closed by emersion** 2020-04-09 18:57 UTC

**Comment by nickdiego** [comment] 2020-04-09 20:09
> Duplicate of #3932

Yeah. Thanks for handling it.
