### ISSUE TITLE
Sway crashes in relative_pointer_manager_v1_handle_get_relative_pointer() when suspending / resuming

### ISSUE THREAD

**Issue by mirko** [swaywm/sway#7010] opened 2022-05-17 11:35 UTC
- **Sway Version:**
  - `sway version 1.8-dev-ffc603d4 (May 16 2022, branch 'master')`

- **Stack Trace:**
```
                Stack trace of thread 1377585:
                #0  0x00007f10b24380e6 relative_pointer_manager_v1_handle_get_relative_pointer (libwlroots.so.11 + 0x9b0e6)
                #1  0x00007f10b19237ea n/a (libffi.so.8 + 0x77ea)
                #2  0x00007f10b1922923 n/a (libffi.so.8 + 0x6923)
                #3  0x00007f10b24af751 n/a (libwayland-server.so.0 + 0xd751)
                #4  0x00007f10b24aab9a n/a (libwayland-server.so.0 + 0x8b9a)
                #5  0x00007f10b24ad64a wl_event_loop_dispatch (libwayland-server.so.0 + 0xb64a)
                #6  0x00007f10b24ab2b5 wl_display_run (libwayland-server.so.0 + 0x92b5)
                #7  0x000055a866a5820e server_run (sway + 0x2220e)
                #8  0x000055a866a5743a main (sway + 0x2143a)
                #9  0x00007f10b215b7fd __libc_start_main (libc.so.6 + 0x237fd)
                #10 0x000055a866a487da _start (sway + 0x127da)
```

- **Description:**
Since quite a few weeks -- always building wlroots/sway from master/HEAD -- sway crashes or crashed every second or so time, when resuming my notebook from suspend with above segmentation fault. I only notice when resuming, but could have crashed already when suspending.
I'm on Debian bookworm/testing.

**Comment by emersion** [comment] 2022-05-23 06:14
Duplicate of #6998

**Closed by emersion** 2022-05-23 06:14 UTC
Labels: bug
