### ISSUE TITLE
Some Electron apps (Xwayland) freeze mysteriously and randomly

### ISSUE THREAD

**Issue by klardotsh** [swaywm/sway#2508] opened 2018-08-23 19:38 UTC
So far I've noticed this with Signal and Pulse SMS (Discord does not do this). After anywhere from a few seconds to a few minutes, the GUI of these Electron (Xwayland) apps completely stops. It doesn't look like the underlying process dies or anything, it just stops knowing how to render anything. My best guess is that this is somehow related to having at least one output scaled or perhaps a difference in graphics driver, as I only see this behaviour on my laptop (Intel iGPU, display scale 1.35, though it happened at 1.25 and 1.5 as well, and happens on my 1.0-scaled external monitor), and not on my desktop (which runs at 1.0 normal scale always).

No output from the program in the terminal when this happens to indicate any runaway threads or other app-side crash states. Given two Electron apps both fail in the same way in similar timeframes, I'm guessing the bug is somewhere between Sway, WLRoots, or Electron itself.

I haven't yet tested running the laptop panel at 1.0 to see if the issue persists, partly because I enjoy not having to squint at my screen. I'll probably get around to it at some point.

This problem was not a thing on the same system yesterday with Xorg+Awesome+Compton.

**Comment by klardotsh** [comment] 2018-08-23 23:50
It might not just be Xwayland stuff that's freezing: I've so far lost two Termite (VTE, GTK3 so I'm assuming Wayland natively. They scale correctly, so probably) windows to the void, too...

**Comment by emersion** [comment] 2018-08-24 07:10
Could you open it in rootston with `WAYLAND_DEBUG=client`? It could be useful to have a Wayland log.

**Comment by RyanDwyer** [comment] 2018-08-24 07:37
It appears to only freeze if I start it from rofi or from a terminal. I can't reproduce it if I start it from a keybind.

https://gist.github.com/RyanDwyer/3ae2e8e2b49f44f27f46160e1b13fe5d

In this session I opened terminator from a keybind, then ran slack from the terminal. Note there is a "loading" window which appears and disappears before the main chat window appears. After the main chat window appeared, I used Ctrl+1 and Ctrl+2 to switch between two teams until it froze. Then I copied the log so it wouldn't be spammed with unmap and shutdown messages.

The freeze occurred at some point after the last "Redacted Team 1".

**Comment by martinetd** [comment] 2018-08-24 07:53
Apps starting from rofi/dmenu that freeze after a while usually do so because they write something to stdout and at some point the pipe is full (because nothing reads their stdout)

You can confirm that with strace -p on the will-hang process, it'll block on a `write(1, ...)` or `write(2, ...)`

I guess we could close the fds before execve in exec_always...?

**Comment by emersion** [comment] 2018-08-24 07:56
We should probably close stdin. But stdout is inherited from rootston so it shouldn't cause issues?

**Comment by martinetd** [comment] 2018-08-24 08:00
hmm. I just remember some other issue exactly like this ... right #2090 it was, they were starting it from qutebrowser and not rofi though but I have no idea how they started qutebrowser, presumably a key binding?

Anyway it can't hurt to strace or to check killing the output of this app like the other report, if that is the case we can investigate on why

**Comment by martinetd** [comment] 2018-08-24 10:08
Actually I can't read, he said rofi or terminal and terminal will have its own output handling, so it has to be something else.
I'm curious what's different with keybind though... @RyanDwyer what's this slack client you're using, I might want to play with that next week?

**Comment by RyanDwyer** [comment] 2018-08-24 11:49
The strace output stops when the freeze happens. The last line of strace output is:

    futex(0x7ffd10037b90, FUTEX_WAIT_PRIVATE, 0, NULL

@martinetd It's the slack-desktop AUR package (version 3.2.1-5). I tested it with empty configuration and it also freezes on the login window.

**Comment by smlx** [comment] 2018-08-24 11:59
https://github.com/electron/electron/issues/9485 looks similar.. could this be unrelated to wlroots / sway?

**Comment by martinetd** [comment] 2018-09-03 01:41
I don't think it's the same, unless Ryan didn't wait long enough to get ETIMEDOUT multiple times... It could be on their side though, definitely, but if it doesn't happen on X11 (or when started from keybind?!) then it might still be something we do.

That said, I just tried with empty configuration and login window opened as you said it still freezes with that and nothing happened in about an hour, do you do anything with that window? floating or tiling? (I'm on fedora so might be different, but they ship binary only so I think we'd have the same stuff.. Well the aur packages takes the .deb and not the .rpm but I doubt it's different)

**Comment by RyanDwyer** [comment] 2018-09-03 01:49
Okay, I checked again with the bindsym and it froze again. So the bindsym is not related.

When it freezes the following gets logged:

    2018-09-03 11:46:06 - [subprojects/wlroots/xwayland/xwm.c:797] XCB_DESTROY_NOTIFY (12582913)
    2018-09-03 11:46:06 - [subprojects/wlroots/xwayland/xwm.c:797] XCB_DESTROY_NOTIFY (10485766)
    2018-09-03 11:46:06 - [subprojects/wlroots/xwayland/xwm.c:783] XCB_CREATE_NOTIFY (12582913)
    2018-09-03 11:46:06 - [sway/desktop/xwayland.c:550] New xwayland surface title='(null)' class='(null)'
    2018-09-03 11:46:06 - [subprojects/wlroots/xwayland/xwm.c:783] XCB_CREATE_NOTIFY (10485762)
    2018-09-03 11:46:06 - [sway/desktop/xwayland.c:550] New xwayland surface title='(null)' class='(null)'
    2018-09-03 11:46:06 - [subprojects/wlroots/xwayland/xwm.c:797] XCB_DESTROY_NOTIFY (10485762)
    2018-09-03 11:46:06 - [subprojects/wlroots/xwayland/xwm.c:783] XCB_CREATE_NOTIFY (10485764)
    2018-09-03 11:46:06 - [sway/desktop/xwayland.c:550] New xwayland surface title='(null)' class='(null)'
    2018-09-03 11:46:06 - [subprojects/wlroots/xwayland/xwm.c:797] XCB_DESTROY_NOTIFY (10485764)
    2018-09-03 11:46:06 - [subprojects/wlroots/xwayland/xwm.c:783] XCB_CREATE_NOTIFY (10485766)
    2018-09-03 11:46:06 - [sway/desktop/xwayland.c:550] New xwayland surface title='(null)' class='(null)'

The window is tiling. The md5sum of my slack binary is 982274db1365c1cdc1a0802108d9bb62.

**Comment by martinetd** [comment] 2018-09-03 04:14
Thanks for checking, at least it's rather reassuring that bindsym isn't related.

I tried again, logging in and actually interacting with it but the hang really doesn't happen here, no clue what's different (the hash of the binary is different, but there are dozens of reasons this could happen - fedora rpm building with slightly different flags for example, or build containing a build timestamp somewhere)
I'll just pass on this one, sorry

**Comment by RyanDwyer** [comment] 2018-09-04 00:56
I think this is related to glibc 2.28. The last two commits for slack-desktop in the AUR apply a patch to make it use glibc 2.27, then reverts the patch and adds a dependency on glibc>=2.28-4. I cannot reproduce the freeze when using the glibc 2.27 patch.

Maybe Electron is doing something that doesn't play nicely with glibc 2.28. But I'm still stumped as to why it locks up in wlroots compositors, but not in gnome-shell.

The `FUTEX_WAIT` stuff in my strace output is a non-issue. Apparently that happens when you strace a process which uses threads.

**Comment by RyanDwyer** [comment] 2018-09-04 01:09
Related issues:

* https://github.com/electron/electron/issues/13972
* https://bugs.archlinux.org/task/59550

I checked coredumpctl and found Slack/Electron is actually crashing when it freezes, which matches what those issues describe.

Closing this, as I'm pretty sure it's not related to sway or wlroots any more.

**Comment by klardotsh** [comment] 2018-10-03 20:51
I'm... not sure this is (1) fixed, as those tickets imply, and (2) actually unrelated to sway/wlroots/wayland. I still have this issue despite Arch claiming to have fixed it, but ONLY on my laptop running Sway (I basically can't run anything Electron-based on this machine other than, for some reason, Discord). My desktop running AwesomeWM (Xorg) can run everything just fine, and both machines are kept fully up to date at least every few days.

What can I do to give reasonable debug output that would help here? Absolutely nothing ends up in the console when running Slack or Riot.im from there.

**Comment by coredump** [comment] 2018-11-13 08:52
I don't know how much this helps, but on slack the freezing seems to get better when you disable (or enable) hardware acceleration. Case in point, it was working fine on last version with the hardware accel turned on, today started to lock up seconds after starting, so I tried disabling the hardware accel and has been running without issues for a few minutes already. :man_shrugging:

**Comment by RyanDwyer** [comment] 2018-11-13 10:39
@coredump Oh, sweet! I disabled hardware acceleration and it appears to work fine now :)

For anyone else who wants to disable hardware acceleration in Slack, open up `~/.config/Slack/local-settings.json` and set `useHwAcceleration` to false.

**Comment by SWW13** [comment] 2018-11-13 10:49
Thanks for the hint. `--disable-gpu` works for signal (see also https://github.com/signalapp/Signal-Desktop/issues/2442)

**Comment by emersion** [comment] 2018-11-13 10:57
Other users running xorg-xserver have issues too, so it's probably not a sway bug.

**Comment by klardotsh** [comment] 2018-11-13 20:34
The `useHwAcceleration` flag toggle fixed Slack in Sway for me (despite it working great in Xorg this whole time), awesome!

`--disable-gpu` works for Riot.im as well - I made some wrappers to make this launcher-friendly: https://github.com/klardotsh/dotfiles/commit/ed1bb60103d7b13e4c580107c3c969da4910a018

**Comment by coredump** [comment] 2018-11-13 21:23
That makes a lot of stuff slow as a dog tho.

I agree with emersion that this sounds more like a bug on the underlying
graphics/driver system

**Closed** 2018-11-29 08:50 UTC

**Comment by alethenorio** [comment] 2021-04-27 07:45
I have been having issues with VS Code. Opening 1 VS Code instance works well, opening 2 VS Code instances side by side works well but as soon as you put either in fullscreen or set them on a tabbe layout, they become nearly unresponsive.

Disabling HW Acceleration (https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration) finally fixed those issues.

Thanks for the tip

**Comment by ttys3** [comment] 2022-04-12 10:24
> I've noticed this with Slack recently, which also uses Electron. It freezes a few seconds after loading the main chat window and doesn't respond to configures. As a test, I opened it in rootston and it froze there too. So we can remove sway from the equation.

its 2022 now, slack under Wayland still lagging and slow.

**Comment by ttys3** [comment] 2022-04-12 10:27
> I don't know how much this helps, but on slack the freezing seems to get better when you disable (or enable) hardware acceleration. Case in point, it was working fine on last sway/slack version (installed from AUR packages) with the hardware accel turned on, today started to lock up seconds after starting, so I tried disabling the hardware accel and has been running without issues for a few minutes already. man_shrugging

thanks for the tips, I tried this, and now it seems works fine
