### ISSUE TITLE
there is no action on clicking icon in tray

### ISSUE THREAD

**Issue by varshitgithub** [swaywm/sway#4126] opened 2019-05-04 13:06 UTC
i installed blueman.
when `blueman-applet` is executed,icon shows up but on clicking it nothing happens.Whereas in waybar,a menu containing options pops up.

**Comment by emersion** [comment] 2019-05-04 13:14
Duplicate of https://github.com/swaywm/sway/issues/3799

**Closed by emersion** 2019-05-04 13:14 UTC
