### ISSUE TITLE
sway kills all workspaces when connecting external monitor; gray background

### ISSUE THREAD

**Issue by tbm** [swaywm/sway#4713] opened 2019-11-08 10:58 UTC
First up, maybe the connection between my laptop and my external monitor is a bit flaky because sometimes the external monitor doesn't show up or briefly shows up and then disappears.  I can usually solve this by plugging the USB C to HDMI dongle out and in again. (BTW, it's just a USB C to HDMI converter; it has no graphics logic in it).

But this issue is more serious: in *some* cases, when I plug in the external monitor, nothing shows up there but all my workspaces on the internal screen get killed and I end up with a gray background.  I can then open a new workspace / terminal, but everything that was running previously is gone.

The logs show:

```
2019-11-08 12:36:55 - [backend/drm/atomic.c:56] DP-2: Atomic commit failed (modeset): Invalid argument
2019-11-08 12:36:55 - [backend/drm/atomic.c:62] DP-2: Atomic commit without new changes failed (modeset): Invalid argument
```

Maybe in some cases you don't handle kernel errors properly?

I tried plugging the external screen in and out in order to reproduce this.  I've attached sway-good where plugging in worked fine and sway-bad where everything was killed and I ended up with a gray screen (I then opened a new terminal).

I think I can reproduce this issue by plugging the monitor in and out eventually, so I can add more details if needed.

Thanks.

This is with sway 1.2

**Comment by tbm** [comment] 2019-11-08 10:59
Successful log: [sway-good.txt](https://github.com/swaywm/sway/files/3824233/sway-good.txt)

Failure log: 
[sway-bad.txt](https://github.com/swaywm/sway/files/3824234/sway-bad.txt)

**Comment by tbm** [comment] 2019-11-08 11:00
Since there are kernel errors, I should mention I'm running Linux 5.2 from Debian.

**Comment by ascent12** [comment] 2019-11-08 11:29
Can you post a kernel DRM debug log?
```sh
echo 0xfe | sudo tee /sys/module/drm/parameters/debug
sway # i.e. reproduce your issue
echo 0x00 | sudo tee /sys/module/drm/parameters/debug
```
You'll find the log in `dmesg`.

**Comment by tbm** [comment] 2019-11-08 17:38
> Can you post a kernel DRM debug log?

I had to plug in and out for about 5 times until I hit the bug again.

I'll just attach the whole log, even though it's probably way more than you need (I trimmed the sway log a bit).

  
I think the relevant line is at 19:24:19:

```
[drm:intel_dp_start_link_train [i915]] Clock recovery check failed, cannot continue channel equalization
[drm:intel_dp_start_link_train [i915]] [CONNECTOR:91:DP-1] Link Training failed at link rate = 270000, lane count = 2
```

[dmesg.txt](https://github.com/swaywm/sway/files/3825614/dmesg.txt)

[sway-bad2.txt](https://github.com/swaywm/sway/files/3825617/sway-bad2.txt)

**Comment by tbm** [comment] 2019-11-08 17:55
I'm attaching another log.  This time the scenario was slightly different:

* All workspaces on internal screen were killed
* But eventually I think the external monitor was initialized
* dmesg shows the failure I mentioned several times

[dmesg3.txt](https://github.com/swaywm/sway/files/3825664/dmesg3.txt)

[sway-bad3.txt](https://github.com/swaywm/sway/files/3825665/sway-bad3.txt)

**Comment by tbm** [comment] 2019-11-08 18:29
Ok, I played around some more and I think there are 2 related scenarios:

* In both cases, all workspaces, background, and bar get killed on the internal monitor
* In one case, the external monitor stays blank
* In the other case, the external monitor works
* In both cases, I believe that sway knows about the external monitor
* I was able to move windows to the external monitor, even though it was blank

**Comment by JonnyMako** [comment] 2019-11-08 21:13
I can consistently reproduce the blank external monitor part of this issue if the workspaces that exist on external monitors are populated. If I clear the workspaces belonging to external workspaces of any content and then re-hotplug, the monitors come back to life. I believe I even reported an issue a while back.

**Comment by ascent12** [comment] 2019-11-08 21:50
A link training failure is a transient hardware issue.
A monitor is plugged in, we configure it with a mode (i.e. resolution), the kernel fails to actually set the mode later (for a variety of different reasons), it tells us that "link-status=bad", and we try the whole thing again with a lower resolution.
I wouldn't be surprised if that "try again" part doesn't work very well. It's a failure case that is pretty difficult to test. This does count as a bug for us; we should be handling this better.

Sometimes link training failures can be fixed by not using inferior cables: https://www.displayport.org/cables/how-to-choose-a-displayport-cable-and-not-get-a-bad-one/
I use a DP MST setup, and once I switch to some certified cables, I never ran into any problems with that.
But it may not be a cable issue in your case, especially since you mentioned a USB-C to HDMI converter.

**Comment by tbm** [comment] 2019-11-09 09:42
@ascent12 thanks for your comments and for looking into this!

I wouldn't mind so much if the external monitor doesn't show up if the link is bad, but the real problem is that everything on my internal laptop screen (which is stable) gets killed.  Can you tell from the logs why this is happening?

**Comment by emersion** [comment] 2019-11-09 10:27
Apps getting killed is probably caused by a `wl_output` quickly appearing and disappearing. Maybe you can try https://github.com/swaywm/wlroots/pull/1765.

**Comment by tbm** [comment] 2019-11-22 10:32
Thanks. I can't try this patch right now, but based on this it sounds like my issue is the same as or related to sway issue #3625

**Comment by emersion** [comment] 2019-11-22 10:47
Closing as a duplicate of #3625.

**Closed by emersion** 2019-11-22 10:47 UTC
