### ISSUE TITLE
Tablet pen position bug with 90/270 rotated output screen 

### ISSUE THREAD

**Issue by gdolle** [swaywm/sway#4776] opened 2019-12-02 17:10 UTC
Hi, I think I might have found a small bug with tablets.

## Description

If the output is in portrait mode, the pen cursor position is constantly switching between the current pad position and the border of the screen making it unusable.

- 90 degree: current pos <-> left border of the screen
- 270 degree: current pos <-> top border of the screen

## To reproduce: 

I use a 3 screens configuration (1 screen rotated should be enough)
```
output eDP-1 resolution 3840x2160 scale 2;output DP-4 scale 2 transform 270; output DP-3 scale 1;
```
I mapped the tablet to a specific output which is 270 degree rotated,
```
input 1386:886:Wacom_Intuos_BT_S_Pen map_to_output DP-4
```
In landscape mode, everything is fine.

OS: archlinux
Sway version 1.2
The tablet:  wacom intuos S tablet.

**Comment by deadly-platypus** [comment] 2019-12-30 00:02
This also happens on the Dell XPS 13 7390 2-in-1 running Ubuntu 19.10 and Sway 1.2.

In the attached screenshot from Xournal++, the top half was created when the screen was in landscape, and the bottom portion was made with the screen rotated 90 degrees.  Notice that only portions of the loops are present.

![screenshot_20191229_190006](https://user-images.githubusercontent.com/3614772/71564357-7cb10800-2a6d-11ea-9d98-0543f0f94613.png)

**Comment by chron-isch** [comment] 2019-12-31 21:47
Hm, I just tried this on my tablet(MS Surface Go with stylus) and the results are a little diffrent but . After `sway-msg output eDP-1 transform 90`  dragging the pen from left to right from the top left corner causes xournalpp to draw a line from top right corner to the bottom right corner, dragging from the top left corner to bottom draws a line from the top right corner to the left one. 

![tablet_tool_after_transform_90](https://user-images.githubusercontent.com/1332352/71634783-4f0bc080-2c1f-11ea-8586-c3ffdc504914.png)

**Comment by deadly-platypus** [comment] 2020-01-30 16:37
This issue appears to be fixed in Sway 1.4.

**Comment by gdolle** [comment] 2020-01-30 16:49
> This issue appears to be fixed in Sway 1.4.
Still the bug for me with 1.4

**Comment by gergelypolonkai** [comment] 2020-04-23 13:05
Same problem here. With my screen rotated by 270 degrees, i drew a straight(ish) vertical line in Krita, but that’s what i got:

![bamboo pen problem](https://user-images.githubusercontent.com/264485/80102814-d8465a80-8562-11ea-970e-fee55db7c74a.jpg)

According to libwacom devs i should report it here:

linuxwacom/libwacom#234

**Comment by Xyene** [comment] 2020-04-27 03:45
I was able to reproduce this on my system.

The issue isn't so much the rotated screen as it is the `map_to_output` directive not taking that rotation into account when doing the mapping (everything works fine without it). It's definitely a tablet bug, though, since reproducing the same steps with a mouse device doesn't lead to the same issues. My guess would be it's around these lines:

https://github.com/swaywm/wlroots/blob/326c8bc818a483bad30f7c2233a8f9e36c73d2c6/types/wlr_cursor.c#L303-L304

Tablets call `wlr_cursor_warp_absolute` while mice call `wlr_cursor_move`, and a call to `wlr_cursor_absolute_to_layout_coords` is where the paths diverge. The (x, y) coordinates passed have already been transformed through `apply_output_transform`, and I'm guessing that mapping _isn't_, leading to incorrect logical coordinates being computed.

**Closed** 2020-04-27 16:34 UTC
Labels: bug
