### ISSUE TITLE
it's possible to get rounded window decoration ?

### ISSUE THREAD

**Issue by mh4nx7net** [swaywm/sway#4595] opened 2019-09-30 00:46 UTC
i've seen i3-gaps rounded windows decoration on reddit. it's possible we implement this on wayland based compositor too ?
or you guys had scheme about this ?
thanks for reply

**Comment by ghishadow** [comment] 2019-09-30 02:36
#3583 there was feature request

**Comment by emersion** [comment] 2019-09-30 03:26
Indeed. Duplicate of #3583.

**Closed by emersion** 2019-09-30 03:26 UTC
