### ISSUE TITLE
Spurious crash on config reload

### ISSUE THREAD

**Issue by YaLTeR** [swaywm/sway#4464] opened 2019-08-18 00:27 UTC
* Sway Version: `1.2-rc1-15-g84417119 (Aug 16 2019, branch 'makepkg')`
* Stack Trace, if sway crashes: https://gist.github.com/YaLTeR/386767b84b85f8912995f90bf0fc18d8

Enabled the debug log, if this happens again I'll attach it.

**Comment by RedSoxFan** [comment] 2019-08-18 03:13
Duplicate of #3914

**Closed by RedSoxFan** 2019-08-18 03:13 UTC
