### ISSUE TITLE
Certain webpages cause flickering

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#3719] opened 2019-02-18 21:26 UTC
Not sure if this is a Firefox issue or a Sway one, but when using Firefox (wayland) certain webpages *seem* to reload sway. Clicking on the tab with these websites, creates a visible flicker on all monitors (probably due to resizing of windows). Here is the relevant portion of the log when I switch in (or out) of a tab with one such website, if it of any use:

```
2019-02-18 15:02:56 - [subprojects/wlroots/types/wlr_surface.c:609] New wlr_surface 0x556ba46d1220 (res 0x556ba4693260)
2019-02-18 15:02:56 - [subprojects/wlroots/types/wlr_surface.c:609] New wlr_surface 0x556ba465dae0 (res 0x556ba465ae80)
2019-02-18 15:02:56 - [sway/tree/arrange.c:190] Usable area for ws: 1920x1059@0,0
2019-02-18 15:02:56 - [sway/tree/arrange.c:221] Arranging workspace '1' at 0.000000, 0.000000
2019-02-18 15:02:56 - [sway/tree/arrange.c:38] Arranging 0x7ffd01b72d30 horizontally
2019-02-18 15:02:56 - [sway/tree/arrange.c:78] Arranging 0x7ffd01b72c40 vertically
2019-02-18 15:02:56 - [sway/tree/arrange.c:190] Usable area for ws: 1280x1003@0,0
2019-02-18 15:02:56 - [sway/tree/arrange.c:221] Arranging workspace '12' at 6400.000000, 56.000000
2019-02-18 15:02:56 - [sway/tree/arrange.c:190] Usable area for ws: 1920x1179@0,0
2019-02-18 15:02:56 - [sway/tree/arrange.c:221] Arranging workspace '11' at 4480.000000, 240.000000
2019-02-18 15:02:56 - [sway/tree/arrange.c:190] Usable area for ws: 2560x1419@0,0
2019-02-18 15:02:56 - [sway/tree/arrange.c:221] Arranging workspace '9' at 1920.000000, 0.000000
2019-02-18 15:02:56 - [sway/tree/arrange.c:38] Arranging 0x7ffd01b72d30 horizontally
2019-02-18 15:02:56 - [sway/tree/arrange.c:78] Arranging 0x7ffd01b72c40 vertically
2019-02-18 15:02:56 - [sway/tree/arrange.c:190] Usable area for ws: 2560x1419@0,0
2019-02-18 15:02:56 - [sway/tree/arrange.c:221] Arranging workspace '10' at 1920.000000, 0.000000
2019-02-18 15:02:56 - [sway/tree/arrange.c:38] Arranging 0x7ffd01b72d30 horizontally
```
Firefox (wayland) examples:
[webpage example 1](https://www.nytimes.com/2019/02/15/t-magazine/hermes.html)
[webpage example 2](https://daringfireball.net/thetalkshow/2017/03/31/ep-185)

`sway version 1.0-rc1-85-gc939453b (Feb 18 2019, branch 'master')`

EDIT: Add another problem webpage example.

**Comment by ddevault** [comment] 2019-02-18 21:39
Can you share your sway config?

**Comment by JonnyMako** [comment] 2019-02-18 21:46
> Can you share your sway config?

Attached.
[config.txt](https://github.com/swaywm/sway/files/2877491/config.txt)

**Comment by JonnyMako** [comment] 2019-02-18 23:46
Ok, so this seems to also happen with Chromium running under xwayland. Oddly, it is a different set of webpages that trigger this behavior with Chromium. The examples provided above don't cause the reload in Chromium. In Chromium, inbox.google.com triggers a reload.

**Comment by emersion** [comment] 2019-02-19 08:08
I can't reproduce.

**Comment by JonnyMako** [comment] 2019-02-19 17:34
> I can't reproduce.

ok, I'll try and further isolate the problem, if I can.

**Comment by JonnyMako** [comment] 2019-02-20 00:39
It looks like the text in the tilebar when I switch to the two webpage examples in my first post seem to have some special characters/icons which may be forcing the title bar to adjust the width. I don't know how i3 handles this, but would it be possible to do the resizing on a per window/container basis.

(The amount of resizing required may also vary depending on what default font is chosen)

**Comment by RedSoxFan** [comment] 2019-02-20 03:52
I think this is a duplicate of #3114

**Comment by JonnyMako** [comment] 2019-02-20 04:11
Maybe. I don't have a problem with the size of the bar per se. It is just that all title bars in all work spaces and monitors seem to get adjusted causing the flicker effect on all screens. This is quite distracting.

**Comment by RedSoxFan** [comment] 2019-05-03 16:25
Duplicate of #3114

**Closed by RedSoxFan** 2019-05-03 16:25 UTC
