### ISSUE TITLE
Ability to specify WAYLAND_DISPLAY

### ISSUE THREAD

**Issue by csergi** [swaywm/sway#8398] opened 2024-10-20 15:46 UTC
Trying to use sway in headless mode to automate some gui testing. One thing that would be helpful would be to run multiple instances of sway simultaneously, and have different wayland sockets to connect to. For example, in weston, weston --no-config **--socket=wl-test-env** --backend=headless will change the wayland socket that it is listening on, and applications can then be launched in the headless backend using by setting the WAYLAND_DISPLAY environmental variable. Right now, it appears to be hardcoded as wayland-1.

**Comment by emersion** [comment] 2024-10-20 17:34
Duplicate of https://github.com/swaywm/sway/issues/7586

**Closed by emersion** 2024-10-20 17:34 UTC
Labels: enhancement
