### ISSUE TITLE
Black screen on multi screen setup

### ISSUE THREAD

**Issue by anelam** [swaywm/sway#3444] opened 2019-01-16 15:39 UTC
My laptop is attached to a docking station. When I start sway from the tty, sometimes all screen stay black. When using the laptop without the attached displays (docking station) I have no problems. (I will provide logs later)

Additionally one of the two attached displays stay black after unlocking from swaylock with dpms management via swayidle. ([log](https://gist.github.com/anelam/711e599e60b6db40985ae63e84d4b907))

I use the latest master versions.

_Originally posted by @anelam in https://github.com/swaywm/sway/issues/3442#issuecomment-454789511_

**Comment by yory8** [comment] 2019-02-01 16:11
I can confirm the second issue (black screen after unlocking), I'm on latest master too, with a single monitor (laptop).

**Comment by tomsmalley** [comment] 2019-08-09 05:14
I'm not on a laptop, but I do see one of my two monitors (plugged in to separate graphics cards) will have a black screen after sway starts the first time. If I restart sway, it seems to work. This was working in an earlier beta, but might have been a driver change.

**Comment by Emantor** [comment] 2019-08-09 05:27
For most modern laptops, connections to multiple external monitors are done using the DisplayPort MST protocol. For most i915 hardware, AFAIR MST was more or less broken until kernel version 5.1 or 5.2. Which kernel versions are you running on your hardware and am I right in assuming these are intel integrated graphics?

**Comment by opuk** [comment] 2019-08-09 08:05
I'm on intel gfx and just upgraded to a 5.2 kernel on Fedora 30 and got this problem as well. Reverted to the previous 5.1 kernel again and it works.

**Comment by Emantor** [comment] 2019-08-09 08:34
There is also a current issue with 5.2 where the laptop screen stays black unless PSR is disabled. This will be fixed with 5.2.8, but for now to fix this issue `i915.enable_psr=0` is required on the kernel commandline.

**Comment by emersion** [comment] 2019-08-12 12:35
Seems like this is a kernel issue?

**Comment by opuk** [comment] 2019-08-12 21:25
> There is also a current issue with 5.2 where the laptop screen stays black unless PSR is disabled. This will be fixed with 5.2.8, but for now to fix this issue `i915.enable_psr=0` is required on the kernel commandline.

Tried `i915.enable_psr=0` but it didn't help on 5.2.7.

**Comment by opuk** [comment] 2019-08-15 12:43
The issue is still present in kernel 5.2.8 for me, reverting to 5.1 and it works

**Comment by opuk** [comment] 2019-08-15 18:30
Strange, got it to work again now under 5.2.8 but I had to be very specific and use the refresh rate reported by swaymsg -t get_outputs. Before in kernel 5.1 it was enough to just specify the resolution.

For example, swaymsg output DP-5 resolution 2560x1440@59.951000Hz position 0 0

**Comment by emersion** [comment] 2020-02-08 10:17
Closing because it sounds like a kernel issue.

**Closed by emersion** 2020-02-08 10:17 UTC

**Comment by gnzlbg** [comment] 2020-12-21 22:25
I can reproduce this with: 5.9.14-arch1-1
