### ISSUE TITLE
Moving between containers will change the timeline of a video on Udemy

### ISSUE THREAD

**Issue by trmendes** [swaywm/sway#3196] opened 2018-11-26 18:04 UTC
sway version 1.0-beta.1-239-gaf7a97623bf1 (Nov 26 2018, branch 'master')

When I'm watching videos on udemy using firefox and I swtich to another containter using for example the shortcut SUPER+3 to code something then I switch back to my browser container using, for example, the shortcut SUPER+2 the video on firefox will move to another time on the timeline. Moving back to the container using SUPER+2 will have the same behavior as when I'm watching the video and press the key 2 at any time.

**Comment by FreeFull** [comment] 2019-08-01 02:00
Interesting things to note:
1) The same sort of bug happens with X11 and i3wm
2) I mostly have seen this happen in sway with clients running under XWayland (For example, it happens reliably with sunvox).

Testing with both xev and weston-eventdemo, when switching to the workspace they are running in, there is a key release event (without a corresponding key press event).

**Comment by RedSoxFan** [comment] 2019-08-15 02:14
Related to #3063. This is not a duplicate of it though. The key press is being sent via wl_keyboard_enter here so if there isn't a corresponding release, the client's state will be corrupt

**Closed** 2019-08-20 02:14 UTC
Labels: bug
