### ISSUE TITLE
Moving windows to new workspace segfaults

### ISSUE THREAD

**Issue by ppascher** [swaywm/sway#2588] opened 2018-09-06 09:31 UTC
Sometimes moving window to new empty workspace works if output stays the same but not always - but moving to new workspace on different output seems to always segfault. If the workspace already exists with a window moving always works.

coredumpctl gdb:
```
#0  0x000055e4c1ed52d9 in render_containers_linear (output=0x55e4c2d4e220, damage=0x7ffc101eb1b0, parent=0x7ffc101eb080) at ../sway/desktop/render.c:574
574		for (int i = 0; i < parent->children->length; ++i) {
```
coredumpctl info:
```
Stack trace of thread 4903:
                #0  0x000055e4c1ed52d9 render_containers_linear (sway)
                #1  0x000055e4c1ed5922 render_containers (sway)
                #2  0x000055e4c1ed5ace render_workspace (sway)
                #3  0x000055e4c1ed61d7 output_render (sway)
                #4  0x000055e4c1ed2a34 damage_handle_frame (sway)
                #5  0x00007f284f147365 wlr_signal_emit_safe (libwlroots.so.0)
                #6  0x00007f284f133670 output_handle_frame (libwlroots.so.0)
                #7  0x00007f284f147365 wlr_signal_emit_safe (libwlroots.so.0)
                #8  0x00007f284f136bbd wlr_output_send_frame (libwlroots.so.0)
                #9  0x00007f284f1053fd page_flip_handler (libwlroots.so.0)
                #10 0x00007f284c6a26a5 drmHandleEvent (libdrm.so.2)
                #11 0x00007f284f10546e handle_drm_event (libwlroots.so.0)
                #12 0x00007f284f184702 wl_event_loop_dispatch (libwayland-server.so.0)
                #13 0x00007f284f1832ac wl_display_run (libwayland-server.so.0)
                #14 0x000055e4c1ecfe6f server_run (sway)
                #15 0x000055e4c1ecf5ea main (sway)
                #16 0x00007f284eabe223 __libc_start_main (libc.so.6)
                #17 0x000055e4c1ec3a1e _start (sway)
```

**Comment by RyanDwyer** [comment] 2018-09-06 09:38
I'm having problems reproducing this. Can you please confirm which commit you're using (should be latest master), describe your setup in terms of outputs and workspace assignments, and provide the command you're running that triggers the crash?

**Comment by ppascher** [comment] 2018-09-06 10:00
I am using: `1.0-alpha.5-284-gbea9f9c6` (should be latest master). This started about a day or two ago.
 
 I open any window (termite, qutebrowser, keepass) on empty workspace 1 on output DVI-D-1. I press 'mod+shift+7' to move said window to new empty workspace 7 on HDMI-A-1. Sway segfaults with stacktrace above. Sometimes I can move a window several times before it segfaults. Sometimes it happens on the first move. I just tested some more and it does not seem to matter if the target workspace is on a different output or not.
 
 sway config:
 ```
  output DVI-D-1 resolution 2560x1440 pos 0,0
  output HDMI-A-1 resolution 1920x1080@60Hz pos 2560,370
 ...
  set $ws7 7
  workspace $ws1 output DVI-D-1
  workspace $ws2 output DVI-D-1
  workspace $ws3 output DVI-D-1
  workspace $ws4 output DVI-D-1
  workspace $ws5 output DVI-D-1
 
  workspace $ws6 output HDMI-A-1
  workspace $ws7 output HDMI-A-1
  workspace $ws8 output HDMI-A-1
  workspace $ws9 output HDMI-A-1
  workspace $ws10 output HDMI-A-1
 ...
 bindsym $mod+Shift+7 move container to workspace $ws7;workspace $ws7
 ```

Also coredumctl info lists alot of those threads:
```
#0  0x00007f812b7a9afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f81268a4404 n/a (radeonsi_dri.so)
#2  0x00007f81268a40f8 n/a (radeonsi_dri.so)
#3  0x00007f812b7a3a9d start_thread (libpthread.so.0)
#4  0x00007f812b8b8a43 __clone (libc.so.6)
```

**Comment by RedSoxFan** [comment] 2018-09-06 10:12
I'm able to replicate this 100% of the time with the following:
- Have two views open on a workspace
- Run `move container to workspace empty; workspace empty` on one of them

I was actually looking into this a few hours ago. In `render_workspace`, `ws->current.tiling` is `NULL` so when it tries to access `length` in `render_containers_linear`, the SIGSEGV occurs.

As a naive solution, I have https://github.com/swaywm/sway/compare/master...RedSoxFan:fix-move-switch-ws-crash, but I was trying to figure out if there is a bigger issue/better solution since the SIGSEGV did not occur before typesafety was merged.

**Closed** 2018-09-06 10:30 UTC
