### ISSUE TITLE
[1.10][Regression] Output not detected, black screen, duplicated screens

### ISSUE THREAD

**Issue by andreesteve** [swaywm/sway#8428] opened 2024-11-03 21:19 UTC
**Sway Version:** 1.10

- **Debug Log:** [debug logs here](https://gist.github.com/andreesteve/459d535e631882531db0f682e29111c2)

- **Configuration File:**
```
output DP-1 pos    0 0 res 3440x1440@100Hz
output DP-2 pos 3440 0 res 3440x1440@100Hz adaptive_sync on
workspace 1 output DP-2
workspace 2 output DP-1
# Focus on main monitor on startup
focus output DP-2
bar {
    swaybar_command waybar
}
include /etc/sway/config.d/*
```

- **Description:**
 - I have a 3 monitor setup ([swaymsg -t get_outsputs](https://gist.github.com/andreesteve/20f5876ba359f6f985f22207a944506b))
 - After updating from 1.9 to 1.10, it seems my center monitor is not recognized and I get a black screen with the sway bar (see image below). The two monitors on the side seem to get mirrored, whereas the expected setup is that they are independent (see 1.9 screenshot for working scenario).

**Problematic example in 1.10**
![v1 10](https://github.com/user-attachments/assets/256f00ef-0054-4522-a8a0-acf035579a28)

**Working example in 1.9**
![screenshot](https://github.com/user-attachments/assets/02a98eab-5b8b-4cfa-922c-5527c8074510)

**Comment by Nefsen402** [comment] 2024-11-03 21:30
Your log doesn't appear to set the position of the third monitor. Sway might think they are placed in the same spot thus rendering the same thing.

**Comment by klaasjanelzinga** [comment] 2024-11-04 13:14
Hi,

I probably have a related issue to this. The result is that in my dual monitor (laptop + HDMI) the screens get mixed up, or so it seems:

![image](https://github.com/user-attachments/assets/f90e60ef-cc58-42b1-951f-d7eee62c0f5f)

Image above is showing my HDMI monitor after turned off and on again.

The log file:
[sway.log](https://github.com/user-attachments/files/17618562/sway.log)

**Comment by Firwanaa** [comment] 2024-11-05 05:43
It seems that Sway `1.10` doesn't detect output configurations at startup, however reloading Sway configurations using `swaymsg reload`, output configurations will be detected. 

Downgrading to Sway `1.9` seems to solve the issue as well.

**Comment by Nefsen402** [comment] 2024-11-05 05:44
@kennylevinsen

**Comment by kennylevinsen** [comment] 2024-11-05 12:10
@andreesteve your issue appears to just be that you're not specifying the position of one output, while you at the same time have an output that is positioned at 0,0. Depending on order, the automatic positioning might use 0,0 first, with the explicit 0,0 output then placed on top. Explicit position of the remaining output should fix that.

@Firwanaa Your config is setting `eDP1`, which does not exist and so by accident you hit OPs issue. Try updating your config to set `eDP-1`.

**Comment by mukul1729** [comment] 2024-11-05 13:24
Same issue, my multi monitor setup is misbehaving badly with 1.10 update. Downgrading to 1.9 fixes it

**Comment by Firwanaa** [comment] 2024-11-05 13:33
> @andreesteve your issue appears to just be that you're not specifying the position of one output, while you at the same time have an output that is positioned at 0,0. Depending on order, the automatic positioning might use 0,0 first, with the explicit 0,0 output then placed on top. Explicit position of the remaining output should fix that.
> 
> @Firwanaa Your config is setting `eDP1`, which does not exist and so by accident you hit OPs issue. Try updating your config to set `eDP-1`.

Not sure If you meant to reply to me as I didn't mention my output config, however I actually found a mistake in one of my monitor names 😬, still, having some issues with Sway 1.10, downgrading to Sway 1.9 works just fine.

**Comment by klaasjanelzinga** [comment] 2024-11-05 14:08
@kennylevinsen There was an error in my config as well, eDP1 => eDP-1. Issue seems fixed. Thanks!

**Comment by kennylevinsen** [comment] 2024-11-05 14:40
Could anyone with the original issue try to reproduce with: https://github.com/swaywm/sway/pull/8431?

If you have already fixed your issue by adjusting your config file, do please test with config file undone to test the original problem.

**Comment by andreesteve** [comment] 2024-11-06 04:01
@kennylevinsen - thank you for the fix. I could test it but I can't build it locally. Is there a way I could download it from the build system? https://builds.sr.ht/~emersion/job/1363306

Also, on 1.1.0 sans patch, explicitly adding the other display to the config solves the initial rendering issue, but I found a couple of other issues, in case it helps: (1) the focus command in the config after start up seems to fail, as the focus is not set to the target output; and (2) setting background color in 1.10 does not work. I always get a black background.

**Comment by ya-isakov** [comment] 2024-11-08 22:04
I bisected this issue to https://github.com/swaywm/sway/commit/2879260f797f679954746bfff6a38365328b3929 (I was finding #8435 first, but it seems that it's duplicate of current one). Adding deleted lines back fixes the issue for me.

**Comment by Sinaaaa** [comment] 2024-11-09 09:13
Does #8431 work for you all even if  `sway -D noatomic` is used?

**Comment by ya-isakov** [comment] 2024-11-09 09:37
@Sinaaaa yes, still works

**Comment by emersion** [comment] 2024-11-28 20:03
Closing since this appears to have been fixed in https://github.com/swaywm/sway/pull/8431. Please re-open if you can reproduce with that commit applied.

**Closed by emersion** 2024-11-28 20:03 UTC
Labels: bug
