### ISSUE TITLE
Segfault while using qalculate-gtk

### ISSUE THREAD

**Issue by mssdvd** [swaywm/sway#5329] opened 2020-05-11 14:28 UTC
* Step to reproduce
1) Open qalculate-gtk (3.10.0)
2) Click the menu bar
3) Move the cursor over the menus
4) Sway should crash

* Sway Version:
sway version 1.4-a8a6ed66 (May 11 2020, branch 'master')

* Debug Log:
https://gist.github.com/mssdvd/edc94c6f337edc090a71e3ea48fc58d5

* Configuration File:
default

* Stack Trace:
https://gist.github.com/mssdvd/af5de67fe9d9a6d249d69c4dad6ed92b

**Comment by emersion** [comment] 2020-05-11 14:34
Duplicate of https://github.com/swaywm/sway/issues/5294

**Closed by emersion** 2020-05-11 14:34 UTC
