### ISSUE TITLE
make stacked tiles visible (not hidden), so we could see through transparent terminals the terminals behind them (like i3)

### ISSUE THREAD

**Issue by Al-Caveman** [swaywm/sway#4318] opened 2019-07-10 23:18 UTC
**Feature request:** make stacked windows visible (not hidden).  So when the top window is transparent, we can see the windows behind it.

-----
**Details**

One of the great utilities of transparent terminals that are stacked is that, while you are working on a terminal, you can see what is behind.  This way, you can immediately know should there be a change.

I do this with `i3`, and it helps me to react faster.  For example, I tun a batch job in a terminal, and then stack on top of it another terminal where I program something.  Since my terminals are 25% transparent, while I'm programming, I can immediately notice then the batch job in the stacked-underneath terminal completes.

This helps me be more productive.  It's about the utility, not the looks.

But unfortunately, with `sway`, stacked transparent terminals are _only_ going to show you the pretty wallpaper behind.  Which makes transparency pretty much useless with `sway`.

**Comment by RedSoxFan** [comment] 2019-07-11 00:56
Duplicate of #973

**Closed by RedSoxFan** 2019-07-11 00:56 UTC
