### ISSUE TITLE
Only one output is active after switching TTY in multi-output setup

### ISSUE THREAD

**Issue by sorpaas** [swaywm/sway#7006] opened 2022-05-16 14:16 UTC
- **Sway Version:** sway version 1.7
- **Configuration File:** reproducible with default config

Have two output setup (in my case, HDMI-A-1 and DP1). The bug appears with the following steps:

* In tty1, start sway. Have two output active.
* Switch to tty2, login to the same account, start sway again.
* Switch back to tty1. Only one output is active (HDMI-A-1 in my case). The other output is simply frozen with whatever is last there on tty2.

**Comment by w23** [comment] 2022-06-26 06:21
Also been running into this since ~1.6 or 1.7 update. It's 100% reproducible:
1. Have 3 outputs.
2. Log in into account A on tty1, run sway.
4. Switch to tty2, log in into account B, run sway.
5. Exit sway on tty2, log out.
6. Switch back to tty1.
All display will be frozen with whatever they were displaying while on tty2. The only thing that restores them is physically unplugging and plugging back each display.

**Comment by emersion** [comment] 2023-02-01 16:28
Can you try to reproduce with Sway master? I think this has been fixed by https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3967.

**Comment by w23** [comment] 2023-02-01 19:56
I haven't seen this happening for a few months at least, so maybe some other update fixed it already at least on my system.

**Comment by emersion** [comment] 2023-02-01 20:30
Alright, please re-open if you see this again on Sway master.

**Closed by emersion** 2023-02-01 20:30 UTC
Labels: bug
