### ISSUE TITLE
Bemenu does not render

### ISSUE THREAD

**Issue by minus7** [swaywm/sway#5463] opened 2020-06-17 18:06 UTC
Bemenu rendering broke between 45859be0 and e19bd1e4. It will render one frame and then just flicker (due to buffer swaps).

Reproducer: run `bemenu-run`

**Comment by ppascher** [comment] 2020-06-17 21:51
wlroots commit [eb22ae97](https://github.com/swaywm/wlroots/commit/eb22ae97b01e26f2a64f81c0e34ef7ad1f870ac4) seems to be the issue as with the [previous commit](https://github.com/swaywm/wlroots/commit/315bf08733f4bc132a23200df26cb2145ac629b3) bemenu works as expected

**Comment by kchibisov** [comment] 2020-06-18 05:10
wlroots issue https://github.com/swaywm/wlroots/issues/2287

**Comment by emersion** [comment] 2020-06-18 07:06
Can you try https://github.com/swaywm/wlroots/pull/2288?

**Comment by ppascher** [comment] 2020-06-18 10:01
I can confirm the bemenu issue (and a render issue with alacritty) is fixed by swaywm/wlroots#2288

**Closed** 2020-06-18 10:33 UTC
