### ISSUE TITLE
restore cursor location on resume?

### ISSUE THREAD

**Issue by tbm** [swaywm/sway#4745] opened 2019-11-22 14:17 UTC
I noticed when I suspend and resume my laptop, my cursor is in the lower right corner, which is annoying because I've configured a bar area there and hovering over the area results in something to be displayed on the screen so now this happens each time I resume.

So I was wondering: would it make sense for sway to store the cursor location and restore it upon resume?

**Comment by RPigott** [comment] 2019-11-27 06:29
I can't reproduce, actually. Cursor location stays the same after suspend for me.

**Comment by FreeFull** [comment] 2019-11-27 20:08
Just suspending for me also doesn't change the location of the cursor. If I disable my laptop's screen (with swaymsg output eDP-1 disable ) and then reenable it (and without any other screens connected), then the cursor position does get reset. Do you have a hook like that in your config?

**Comment by tbm** [comment] 2019-11-27 20:09
That's an interesting observation.  Yes, I use:

```
bindswitch --locked lid:on output $laptop disable
bindswitch --locked lid:off output $laptop enable
```

**Comment by emersion** [comment] 2019-11-28 01:15
Disabling an output removes it from the output layout, so it's normal that the cursor position gets updated. If you're only doing this for power saving purposes, have a look at the output `dpms` command.

I'll close this as not-a-bug.

**Closed by emersion** 2019-11-28 01:15 UTC

**Comment by tbm** [comment] 2019-11-28 13:37
Thanks for the explanation.  This makes sense.  At the same time, I feel closing the issue isn't the right solution in this case.

So, I use this based on the wiki:

```
bindswitch --locked lid:on output $laptop disable
bindswitch --locked lid:off output $laptop enable
```

I'm using it because I want everything to move to the external screen when I connect the screen and close my lid.

But it also has the effect of disabling the internal screen when closing the lid to suspend my laptop.  And this causes the cursor issue.

So I see a number of options to improve the situation:

1) Save the cursor info of the internal screen even when you disconnect it and restoring it when you connect is.  Is there any downside of doing this?

2) Add an option to the `bindswitch` command so it's only run if there's any external monitor?

**Comment by emersion** [comment] 2019-11-28 13:58
>Save the cursor info of the internal screen even when you disconnect it and restoring it when you connect is. Is there any downside of doing this?

The mouse will jump when re-enabling the screen, which is unexpected.

>Add an option to the bindswitch command so it's only run if there's any external monitor?

Use [kanshi](https://github.com/emersion/kanshi) to execute actions on hotplug/unplug.

**Comment by tbm** [comment] 2019-11-28 13:59
> Use kanshi to execute actions on hotplug/unplug.

Ok, I guess that's the real solution for my use case. Thanks.
