### ISSUE TITLE
Floating windows keep moving after mouse hits screen edge

### ISSUE THREAD

**Issue by tinkerttoy** [swaywm/sway#4402] opened 2019-07-31 07:06 UTC
If you try dragging a floating window to the border of the screen, your cursor will stop at the edge, but the window will keep moving past the border as long as you keep moving the mouse. When you move the cursor the other way, the window will follow at a distance until you reach the other side of the screen, where you can repeat the process in the other direction.

Steps to reproduce:
1. Open a window and make it floating. I used `pavucontrol`, the pulseaudio volume manager.
2. Drag it to the edge of the screen.
3. Continue to drag in the same direction after the cursor reaches the edge of the screen. The window should keep moving in the same direction, past the border of the screen.

`swaymsg -t get_version` returns `sway version 1.0`; package manager says version is `1.1.1-3`. [Debug log is here.](https://gist.github.com/tinkerttoy/0477690c03854b2b51c27eb9a8a5d1e9) I have tested this on the default configuration.

**Comment by RedSoxFan** [comment] 2019-07-31 07:11
Duplicate of #4133

**Closed by RedSoxFan** 2019-07-31 07:11 UTC
