### ISSUE TITLE
Sway crashes right after entering passcode in Telegram Desktop

### ISSUE THREAD

**Issue by danog** [swaywm/sway#6128] opened 2021-03-22 19:45 UTC
### Please fill out the following:
- **Sway Version:** 1.5.1

- **Debug Log:** https://dl.uploadgram.me/6058f3001f1fag

- **Configuration File:** https://dl.uploadgram.me/6058f3baf02a5g

- **Description:** Open the Telegram Desktop beta (QT_QPA_PLATFORM=wayland), insert passcode, press enter

**Comment by emersion** [comment] 2021-03-24 08:40
Duplicate of https://github.com/swaywm/sway/issues/6108

```
00:00:04.015 [DEBUG] [xwayland/server.c:343] sent SIGUSR1 to process 4697
(EE) failed to read Wayland events: Connection reset by peer
```

**Closed by emersion** 2021-03-24 08:40 UTC
Labels: bug
