### ISSUE TITLE
Typing programmatically / substitute for xdotool type

### ISSUE THREAD

**Issue by jeremejevs** [swaywm/sway#4165] opened 2019-05-20 15:43 UTC
I have a simple usecase: I'd like to use a dmenu (or some other type of modal) to select a piece of text out of several options and have it typed into whatever text field was focused before opening it. `xdotool type <text>` works in XWayland windows, but not in regular ones. It appears there's no `swaymsg` that can do this at the moment (tried `seat <seat> press <code>`, but it doesn't accept keyboard events). Other options are root-only. Is there something in motion to accommodate this? If not, may this be considered in the future, or is this a deliberate won't fix?

**Comment by emersion** [comment] 2019-05-20 15:44
Duplicate of https://github.com/swaywm/sway/issues/1779

**Closed by emersion** 2019-05-20 15:44 UTC
