### ISSUE TITLE
Dragging items outside of floating window (nautilus) breaks drag and drop and keyboard input

### ISSUE THREAD

**Issue by sydneymeyer** [swaywm/sway#4137] opened 2019-05-09 19:06 UTC
Dragging an item from a floating nautilus window, to e.g. the desktop area, breaks drag and drop, also keystrokes are getting ignored until switching to another window and back again.

Attached debug log from above described actions.
[sway.log](https://github.com/swaywm/sway/files/3163607/sway.log)

sway version 1.1-rc1-3-g9dca18b6 (May  9 2019, branch 'master')

Perhaps related (or the same) as:
https://github.com/swaywm/sway/issues/3820
https://github.com/swaywm/sway/issues/3932

**Comment by emersion** [comment] 2019-06-24 10:04
Duplicate of https://github.com/swaywm/sway/issues/3932

**Closed by emersion** 2019-06-24 10:04 UTC

**Comment by luispabon** [comment] 2019-10-09 10:43
I don't feel this is a duplicate, at least the symptoms seem different. Drag and drop isn't broken afterwards and the window doesn't need to be floating. Simply open nautilus and gedit side to side, drag a text file into gedit, it drags correctly but input is broken for gedit until it loses focus.

Other scenarios: 
  * nautilus to firefox (for file upload)
  * gedit to firefox (for copying text using d&d)

Drop needs to be successful. If the receiving window doesn't react to the drop, input doesn't break for it.

Once the receiving window loses focus, input works again.

**Comment by kchibisov** [comment] 2019-12-29 01:06
It more feels like a duplicate of #3820 tbh.
