### ISSUE TITLE
Respond to changed modes on DRM connectors (e.g. resized/maximised virtual machine window)

### ISSUE THREAD

**Issue by hedgepigdaniel** [swaywm/sway#5902] opened 2020-12-21 13:22 UTC
When running Sway in a virtual machine (unlike on a physical machine), it is common for the preferred DRM mode to change. This happens when resizing/maximizing the virtual machine window in the host system.

Currently, the DRM backend chooses a mode at startup and never changes it without user intervention [unless the DRM connector is disabled and reenabled](https://github.com/swaywm/wlroots/blob/de896caceb9f6354a99c9435c3a429ff52b6ca4a/backend/drm/drm.c#L1311-L1312), even though there is a udev event and `scan_drm_connectors` is called.

Instead, I think it would be better if the mode was automatically changed when necessary/appropriate as a result of changes to available DRM modes. I'm not sure exactly what the criteria should be for when the mode should change automatically, but I think my case is clearly one where it should:
 - The current mode is no longer in the list of modes on the DRM connector
 - There is no configured mode, and no mode was set manually - the current mode is set only by default because it was the preferred mode at the time

Would this be a welcome improvement?

**Comment by Emantor** [comment] 2020-12-21 13:59
We would need code to detect that we are running in a virtual machine, register for drm invalidation events and than change mode to the new preferred mode.

**Comment by emersion** [comment] 2020-12-21 18:37
Duplicate of https://github.com/swaywm/wlroots/issues/2188, I think.

**Closed** 2021-02-04 02:23 UTC
Labels: enhancement
