### ISSUE TITLE
Mouse focus not switched on workspace changes

### ISSUE THREAD

**Issue by atomnuker** [swaywm/sway#2558] opened 2018-09-02 01:37 UTC
While keyboard focus does get switched, mouse focus does not unless mouse is moved. So scroll wheel events get sent to the client on the other workspace.

**Comment by RyanDwyer** [comment] 2018-09-02 01:58
This was added in the past, but caused issues so it was removed temporarily.

Here's where it was originally added:

    commit 03d49490ccff3c5c81bea73622c8616fa61eb3dd
    Author: emersion
    Date:   Tue Jul 17 23:04:55 2018 +0100
    
        Update cursor on focus change
        
        This allows to send wl_pointer.enter when switching between views
        in a split/tabbed layout for instance. This (1) updates the cursor
        image accordingly (2) makes it unnecessary to move the mouse before
        scrolling. It's harmless to always call cursor_send_pointer_motion
        because in case the focused surface hasn't changed this is a no-op.
        
        The `last_focus != NULL` condition is required otherwise
        cursor_send_pointer_motion will crash when sway starts up (the
        sway_output doesn't yet have a workspace).

Here's where it was attempted to be fixed:

    commit b14bd1b0b1536039e4f46fe94515c7c44e7afc61
    Author: Ryan Dwyer
    Date:   Wed Jul 25 19:26:12 2018 +1000
    
        Fix crash when closing last child of a tabbed container
        
        The crash only occurs if the mouse cursor is above the tabbed container
        when the last child is closed.
        
        Introduced in 03d49490ccff3c5c81bea73622c8616fa61eb3dd, over a week ago
        and unnoticed until now :O
        
        The above commit changes the behaviour of a focus change. When you
        change focus, it sends pointer motion which makes the client set a new
        cursor image. We already had this behaviour for workspace switching, but
        this commit adds it for view switching too, such as in a tabbed
        container or when closing a view.
        
        The sequence of events that leads to the crash is:
        
        * The last child of a tabbed container unmaps, which triggers a
        `destroy` event before we've cleaned up the child or reaped the tabbed
        container.
        * The seat code listens to the `destroy` event and removes the seat
        container from the focus stack. As part of this, it decides to set focus
        to the parent (my fix alters this decision).
        * When setting focus to the new parent, the container motion is sent as
        per the previously mentioned commit.
        * The motion code uses `container_at`, which encounters the tabbed
        container and its child in a half destroyed state, and everything blows
        up from there.
        
        `con->parent` is needed because scratchpad containers don't have parents
        if they're hidden, so this probably fixes a crash when a hidden
        scratchpad container closes too.
        
        The `con->parent->children->length > 1` check should catch any cases
        where the parent is about to be reaped.

Here's where it was removed completely:

    commit 08cfba2192f5770d975c5fe70789a81aaee4dc7e
    Author: Ryan Dwyer
    Date:   Thu Jul 26 18:36:46 2018 +1000
    
        Allow containers to float
        
        Things worth noting:
        
        <snip>
        * My fix (b14bd1b0b1536039e4f46fe94515c7c44e7afc61) for the tabbed child
        crash has a side effect where when you close a floating container, focus
        is not given to the tiled container again. I've removed my fix and
        removed the call to `send_cursor_motion` from `seat_set_focus_warp`. We
        should consider calling it from somewhere earlier in the call stack.

**Comment by emersion** [comment] 2018-09-02 06:40
Duplicate of https://github.com/swaywm/sway/issues/2401

**Closed by emersion** 2018-09-02 06:40 UTC
