### ISSUE TITLE
sway crashes on startup on Intel UHD 630

### ISSUE THREAD

**Issue by bubbleguuum** [swaywm/sway#6398] opened 2021-07-23 10:23 UTC
Full details on the openSUSE Tumbleweed bugtracker:

https://bugzilla.opensuse.org/show_bug.cgi?id=1188640

**Comment by emersion** [comment] 2021-07-23 10:26
This is missing debug logs.

Seems like wlroots is picking the software renderer. Then dies because Sway is missing https://github.com/swaywm/sway/commit/6cad038eea48517b0951259b8eaee836c1d885f1.

**Comment by bubbleguuum** [comment] 2021-07-23 10:47
Here's the log, with some EGL errors:

[sway.log](https://github.com/swaywm/sway/files/6868209/sway.log)

**Comment by emersion** [comment] 2021-07-23 10:51
These are usually caused by an old nvidia driver installation together with an out-of-date libglvnd.

```
00:00:00.100 [ERROR] [wlr] [EGL] command: eglGetPlatformDisplay, error: EGL_BAD_PARAMETER (0x300c), message: "EGL_BAD_PARAMETER error: In internal function: Additional INFO may be available
"
00:00:00.100 [INFO] [wlr] [EGL] command: eglGetPlatformDisplay, error: EGL_BAD_PARAMETER (0x300c), message: "EGL_BAD_PARAMETER error: In function eglGetPlatformDisplay(), unsupported EGL Platform
"
00:00:00.111 [ERROR] [wlr] [EGL] command: eglQueryDevicesEXT, error: EGL_BAD_ALLOC (0x3003), message: "EGL_BAD_ALLOC error: In eglQueryDevicesEXT: Failed to allocate device list.
"
00:00:00.112 [ERROR] [wlr] [EGL] command: eglQueryDeviceStringEXT, error: EGL_BAD_DISPLAY (0x3008), message: "(null)"
00:00:00.112 [ERROR] [wlr] [render/egl.c:272] eglQueryDeviceStringEXT(EGL_EXTENSIONS) failed
00:00:00.112 [ERROR] [wlr] [EGL] command: eglMakeCurrent, error: EGL_BAD_DISPLAY (0x3008), message: "Invalid display (nil)"
00:00:00.113 [ERROR] [wlr] [render/gles2/renderer.c:742] Could not initialize EGL
00:00:00.114 [DEBUG] [wlr] [render/wlr_renderer.c:281] Failed to create GLES2 renderer
```

**Comment by bubbleguuum** [comment] 2021-07-23 10:56
I have indeed the NVIDIA proprietary driver installed (packaged by the distro), although it is the latest version 470.57.
The nvidia modules are also not loaded.
libglvnd package version is 1.3.2, which according to the RPM changelog was updated Aug 31 2020.

**Comment by emersion** [comment] 2021-07-23 10:57
Closing since this is not a Sway bug. Upgrade glvnd or remove nvidia.

**Closed by emersion** 2021-07-23 10:57 UTC
Labels: bug, waiting-on-reporter

**Comment by bubbleguuum** [comment] 2021-07-23 11:06
Ok, thanks for looking into this so quickly. I will see if i can get libglvnd updated in openSUSE TW. I still need the NVIDIA driver because I'm still mainly on Xorg+i3 and just evaluating if Wayland is usable for my purpose. 
It might be useful to have a more descriptive message rather than just crash.

**Comment by bubbleguuum** [comment] 2021-07-23 11:29
Confirming libglvnd 1.3.3 fixes this issue.
