### ISSUE TITLE
Segmentation fault when DPMS is turned on

### ISSUE THREAD

**Issue by Ypnose** [swaywm/sway#4835] opened 2019-12-23 19:22 UTC
Hi there,

* Sway version : <code>sway version 1.2</code>
* wlroots version : <code>0.8.1</code>
* Debug log : [Output](https://gist.github.com/Ypnose/bdb1deb8a454c60470542edb9e57339f)
* Kernel : <code>5.4.5</code>, same with <code>4.19.86</code>
* GPU : <code>AMD/ATI Radeon RX570</code>
* Using <code>elogind</code>

In order to autolock my session and to turn off the screen, I use the following <code>swayidle</code> command :

	# Autolock screen and DPMS
	exec swayidle \
	  timeout 300 'swaylock -f -c FFFFFF' \
	  timeout 420 'swaymsg "output * dpms off"' \
		  resume 'swaymsg "output * dpms on"'

Trying to resume by pressing a key, the screen remains black and after a few seconds, I go back to TTY due to a <code>Segmentation fault</code>. I can reproduce it everytime by just starting sway and waiting for the timeouts.

**Comment by emersion** [comment] 2019-12-25 21:44
Please provide a stack trace. You can do so by compiling from source, reproducing the crash and then running `coredumpctl gdb` and then `bt full`.

**Comment by kchibisov** [comment] 2019-12-26 04:36
>You can do so by compiling from source, reproducing the crash and then running coredumpctl gdb and then bt full.

It's a system with elogind, so there shouldn't be any `coredumpctl`, which is helper for some `systemd` utility.

I feel like it's a duplicate of #4599 , if it's so, @Ypnose , could you test the latest master (I see you're on v1.2)? If you still can repro the issue, then you should manage to get a backtrace somehow (I guess just by running things under gdb or maybe it's in your system logger, idk).

**Comment by Ypnose** [comment] 2019-12-31 05:15
As @kchibisov said it, I'm running ```sway``` without ```systemd```. I'm using ```elogind```.

I built wlroots-git and sway ```version 1.2-1d483c34 (Dec 25 2019, branch 'master')``` and it seems the problem is gone. I also tried to provide a stack trace against ```1.2``` release, but the system freezes when ```sway``` is launched using ```run``` in ```gdb```.

**Comment by emersion** [comment] 2019-12-31 09:09
Feel free to re-open.

**Closed by emersion** 2019-12-31 09:09 UTC
