### ISSUE TITLE
IDon't work sub points steam

### ISSUE THREAD

**Issue by skostrigin** [swaywm/sway#3897] opened 2019-03-14 18:00 UTC
IDon't work sub points steam
Steps to reproduce :
1. Open steam
2. Press menu steam > and example settings, sub points don't work

System : Archlinux
Sway version : sway 1.0-3 in the official repository arch linux
Wlroots version : wlroots 0.5.0-1 in the official repository arch linux

**Comment by RedSoxFan** [comment] 2019-03-14 18:10
Duplicate of #1865

**Closed by RedSoxFan** 2019-03-14 18:10 UTC
