### ISSUE TITLE
`swaymsg reload` doesn't effect already opened workspaces

### ISSUE THREAD

**Issue by vired** [swaywm/sway#5184] opened 2020-04-07 15:52 UTC
Sway Version: sway version 1.4

i have made modification to my config file. when i run `swaymsg reload` the modification doesn't effect already opened workspaces. but it work on newly created workspaces.

**Comment by emersion** [comment] 2020-04-07 15:54
I think this is by design. Does i3 do it differently?

**Comment by vired** [comment] 2020-04-07 16:11
@emersion sorry, i haven't used i3

**Comment by jsamr** [comment] 2020-04-13 17:50
@emersion i3 does behave the same.

**Comment by emersion** [comment] 2020-04-13 17:53
Thanks for confirming. Let's close this issue then.

**Closed** 2020-04-13 17:53 UTC
