### ISSUE TITLE
KDE's SNI implementation is noncompliant

### ISSUE THREAD

**Issue by uberbrodt** [swaywm/sway#1372] opened 2017-09-26 03:15 UTC
Hi, 
I understand that SNI support is enabled in 0.14, but I can't seem to get it to work. I've tried a couple of programs that I know have indicators (transmission-qt, kmix) and neither show up.

sway version  (2017-08-09, branch "")

**Comment by uberbrodt** [comment] 2017-09-26 03:17
```
221
[sway.log](https://github.com/SirCmpwn/sway/files/1331701/sway.log)

**Comment by SirCmpwn** [comment] 2017-09-26 11:46
Do those actually support SNI? Try konversation.

**Comment by SirCmpwn** [comment] 2017-09-26 12:12
>    09/25/17 22:05:21 - [main.c:52] [wlc] unable to lock lockfile /run/user/1000/wayland-0.lock, maybe another compositor is running

Are you running another compositor?

**Comment by uberbrodt** [comment] 2017-09-26 12:33
Hangon, that maybe a bad log.  I started sway a couple of times inside another sway session while trying to get debug logging going.

[sway.log](https://github.com/SirCmpwn/sway/files/1333109/sway.log)

**Comment by SirCmpwn** [comment] 2017-09-26 14:10
I'm not sure how the Fedora package works. Can you try building Sway from source and see if you can reproduce the issue? Post the cmake output as well.

**Comment by uberbrodt** [comment] 2017-09-26 14:52
Cool. Probably won't get to it until tomorrow at the earliest. I'm going
to follow the directions from the README, let me know if I need to do
something different with it.

**Comment by nemanjan00** [comment] 2017-10-11 22:52
Any progress?

**Comment by 4e554c4c** [comment] 2017-10-11 23:31
There isn't enough information to reproduce, so no. However if you've experiencing the problem then maybe you could help out.

**Comment by nemanjan00** [comment] 2017-10-12 07:32
Turns out tray is disabled by default in konversation on Arch... :)
Works for me

**Comment by uberbrodt** [comment] 2017-10-12 12:14
Sorry, been busy with moving to a new place...I'll see if I can build it
and test tonight.

**Comment by cjacker** [comment] 2017-10-19 06:34
SNI support requires a session bus setup before starting sway, if launch sway from TTY, run 'dbus-launch sway', tray should work properly.

**Comment by gnidorah** [comment] 2017-10-20 11:25
Doesn't work for me as well. When I start without dbus-launch, there are tray related errors. When I start with dbus-launch these errors go away, but sni icons don't show up and there are no tray related messages in log except tray_output related. I test the same apps in enlightenment 21 which uses sni too, and they show up correctly there.
@4e554c4c How can I debug this further? I will attach log in a minute.

**Comment by 4e554c4c** [comment] 2017-10-20 18:21
@gnidorah Please attatch a debug log of swaybar. This can be done by killing swaybar after starting sway, and running `swaybar -d --bar_id bar-0 2> swaybar.log`

**Comment by gnidorah** [comment] 2017-10-20 18:52
@4e554c4c Is this a culprit?
```
10/20/17 21:30:58 - [sni_watcher.c:153] RegisterStatusNotifierItem called with "/org/ayatana/NotificationItem/example_simple_client"

10/20/17 21:30:58 - [sni_watcher.c:157] This item is not valid, we cannot keep track of it.
```
This is using sample python code
https://lazka.github.io/pgi-docs/AppIndicator3-0.1/classes/Indicator.html#AppIndicator3.Indicator.new
`AppIndicator3.Indicator.new("example_simple_client", "mail-unread", AppIndicator3.IndicatorCategory.OTHER)`
Works ok in i3 and e21-wayland

**Comment by 4e554c4c** [comment] 2017-10-20 19:11
Yeah, that's it. The problem is that the client is trying to register by object path, which is a "hidden feature" of KDE's SNI implimentation. It's not yet supported because it'd require some deviation from the SNI protocol to make, but it's planned for the future.

**Comment by gnidorah** [comment] 2017-10-20 19:19
@4e554c4c That's libappindicator. So Gnome people don't follow protocol too? What tray library is currently supported?

**Comment by 4e554c4c** [comment] 2017-10-20 19:22
We follow the [specification](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/) plus all the deviations from it that I could find in kde software, eg using org.kde.*, registering by unique name, etc. I'll try to add support for these too, it's just difficult to imagine all the different ways people could impliment the specification.

**Comment by gnidorah** [comment] 2017-10-22 16:24
@4e554c4c Yes, please support someday. Because libappindicator is quite common, even Steam uses it :-)

**Comment by 4e554c4c** [comment] 2017-10-22 22:51
Ok, support is in the works. @gnidorah  if you could link me to your example libappindicator client it'd help a lot.

**Comment by gnidorah** [comment] 2017-10-23 07:49
@4e554c4c Here it is https://gist.github.com/candidtim/2cd33ad40016b918ecf9
If you prefer C https://askubuntu.com/questions/42211/how-to-create-unity-indicators/234204#234204 and here are build instructions on the top of file https://github.com/dorkbox/SystemTray/blob/master/test/example.c
Both worked for me under i3 and plasma5. In python example better to replace 'whatever' bogus icon name with any icon presenting in theme or just direct icon path. In C example 'go-jump' icon should be in theme.

Alternatively you may search the packages that depend on libappindicator-gtk3 in your distro.

**Comment by uberbrodt** [comment] 2017-10-28 17:12
Sorry for being so late to follow up...I was able to build and test the HEAD revision today and I can confirm that the Konversation icon shows up, however I'm unable to make it respond to actions with either right or left mouse button clicks.

**Comment by gnidorah** [comment] 2017-10-30 15:37
Here to note that KStatusNotifierItem works great for me (using pykde4), minor issue is that the right click menu shows in the top right corner, while the bar in my config is at bottom. Needed https://github.com/4e554c4c/sway/pull/1 to do things like https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/master/indicator-test-tool/ksni.py#L18 although as I understand it's a hidden feature there, KStatusNotifierItem docs say we should point to icon name in theme (instead of direct path to icon).

**Comment by 4e554c4c** [comment] 2017-10-30 16:40
Nice catch, I'll fix that.

**Comment by 4e554c4c** [comment] 2017-10-31 18:45
Should be fixed with #1431

**Comment by gnidorah** [comment] 2017-11-01 06:33
@4e554c4c Indeed it fixes, thank you!

**Comment by gnidorah** [comment] 2017-11-15 15:38
@4e554c4c Another little issue is when I click on menu item (kmenu's action entry) under i3, menu auto closes as I expect, but on sway it stay open until I click tray icon again.

**Comment by gnidorah** [comment] 2017-11-20 10:05
@4e554c4c Icon updating doesn't happen on external HDMI monitor but happens on internal eDP with default config. Is this a problem with tray or with something else? Thanks

**Comment by 4e554c4c** [comment] 2017-11-20 14:10
Not sure, it's probably us though. I'm working on the menu right now but I'll check that out.

**Comment by ReK2Fernandez** [comment] 2017-12-22 23:45
Hello I tested this with konversation and icon shows but when I click on it no menu, also Idk how to make konversation window come out.. such is why I was looking for the menu :) since click will not pop it up.

**Comment by 4e554c4c** [comment] 2017-12-23 00:54
@ReK2Fernandez This entire system is being reworked. Please test again once #1431 is merged.

**Comment by ReK2Fernandez** [comment] 2017-12-23 02:00
Hey thanks for responding... hmm and when is this happening? can I compile it myself ?

**Comment by 4e554c4c** [comment] 2017-12-23 03:18
The branch is `sni_sucks` on htps://GitHub.cGitHub.com/4e554c4c/sway. You can compile it and test, but as I said it's still being reworked.

**Comment by ReK2Fernandez** [comment] 2017-12-23 05:56
lol :) ok I may,  as a work around I am running keybase and enpass on their own workspaces .. but that "alsosucks" :)

**Closed** 2018-12-31 20:43 UTC
