### ISSUE TITLE
Crash when running Factorio under very specific circumstances

### ISSUE THREAD

**Issue by raiguard** [swaywm/sway#7934] opened 2024-01-25 19:30 UTC
- **Sway Version:**
  - `sway version 1.9-dev-f202bc84 (Jan 25 2024, branch 'master')`

- **Debug Log:**
  - https://gist.github.com/raiguard/8811e4e539bb5106763bb0c81764b131

- **Configuration File:**
  Requires the display scale to be set to 1.5:
  ```
  include /etc/sway/config
  output * scale 1.5
  ```
  Also included in the gist.

- **Stack Trace:**
  ```
  #0  0x00007d83fc84883c in ??? () at /usr/lib/libc.so.6
  #1  0x00007d83fc7f8668 in raise () at /usr/lib/libc.so.6
  #2  0x00007d83fc7e04b8 in abort () at /usr/lib/libc.so.6
  #3  0x00007d83fc7e03dc in ??? () at /usr/lib/libc.so.6
  #4  0x00007d83fc7f0d26 in __assert_fail () at /usr/lib/libc.so.6
  #5  0x00007d83fd1111b4 in wlr_render_pass_add_texture (render_pass=0x5a3611878790, options=0x7ffd4e1990a0) at ../subprojects/wlroots/render/pass.c:23
          box = 0x7ffd4e1990a8
          __PRETTY_FUNCTION__ = "wlr_render_pass_add_texture"
  #6  0x00007d83fd15dfac in scene_entry_render (entry=0x5a3611864d68, data=0x7ffd4e1992a0) at ../subprojects/wlroots/types/scene/wlr_scene.c:1170
          texture = 0x5a361187bec0
          scene_rect = 0x7d83fd227e20 <surface_addon_impl>
          scene_buffer = 0x5a3611879180
          transform = WL_OUTPUT_TRANSFORM_NORMAL
          sample_event = {output = 0x5a3611429dc0, direct_scanout = 56}
          node = 0x5a3611879180
          render_region = {extents = {x1 = 1722, y1 = 65, x2 = 3438, y2 = 1438}, data = 0x0}
          dst_box = {x = 1724, y = 66, width = 1713, height = 1371}
          opaque = {extents = {x1 = 1722, y1 = 65, x2 = 3438, y2 = 1438}, data = 0x5a36118564f0}
          __PRETTY_FUNCTION__ = "scene_entry_render"
  #7  0x00007d83fd15fc4f in wlr_scene_output_build_state (scene_output=0x5a3611429dc0, state=0x7ffd4e199320, options=0x7ffd4e199150) at ../subprojects/wlroots/types/scene/wlr_scene.c:1839
          entry = 0x5a3611864d68
          i = 3
          default_options = {timer = 0x0}
          timer = 0x0
          start_time = {tv_sec = 9900233248, tv_nsec = 99188260577024}
          output = 0x5a361142ae60
          debug_damage = WLR_SCENE_DEBUG_DAMAGE_NONE
          render_data = {transform = WL_OUTPUT_TRANSFORM_NORMAL, scale = 1.5, logical = {x = 0, y = 0, width = 2293, height = 960}, trans_width = 3440, trans_height = 1440, output = 0x5a3611429dc0, render_pass = 0x5a3611878790, damage = {extents = {x1 = 2, y1 = 65, x2 = 3438, y2 = 1438}, data = 0x5a36113ba1e0}}
          list_con = {box = {x = 0, y = 0, width = 2293, height = 960}, render_list = 0x5a3611429ff0, calculate_visibility = true}
          list_data = 0x5a3611864d20
          list_len = 27
          scanout = false
          now = {tv_sec = 0, tv_nsec = 99188225153312}
          buffer = 0x5a36114c9ec0
          render_pass = 0x5a3611878790
          background = {extents = {x1 = 0, y1 = 0, x2 = 0, y2 = 0}, data = 0x7d83fcadac90}
  #8  0x00007d83fd15f0ea in wlr_scene_output_commit (scene_output=0x5a3611429dc0, options=0x0) at ../subprojects/wlroots/types/scene/wlr_scene.c:1611
          ok = false
          state = {committed = 2, allow_reconfiguration = false, damage = {extents = {x1 = 2, y1 = 65, x2 = 3438, y2 = 1438}, data = 0x5a361150e240}, enabled = false, scale = 0, transform = WL_OUTPUT_TRANSFORM_NORMAL, adaptive_sync_enabled = false, render_format = 0, subpixel = WL_OUTPUT_SUBPIXEL_UNKNOWN, buffer = 0x0, tearing_page_flip = false, mode_type = WLR_OUTPUT_STATE_MODE_FIXED, mode = 0x0, custom_mode = {width = 0, height = 0, refresh = 0}, gamma_lut = 0x0, gamma_lut_size = 0, layers = 0x0, layers_len = 0}
  #9  0x00005a360ee59dfc in output_repaint_timer_handler (data=0x5a361142a010) at ../sway/desktop/output.c:263
          output = 0x5a361142a010
  #10 0x00005a360ee59f9e in handle_frame (listener=0x5a361142a160, user_data=0x5a361142ae60) at ../sway/desktop/output.c:317
          output = 0x5a361142a010
          msec_until_refresh = 0
          delay = 0
          data = {when = {tv_sec = 140725913752816, tv_nsec = 2}, msec_until_refresh = 1310299408, output = 0x20}
  #11 0x00007d83fca3301e in wl_signal_emit_mutable () at /usr/lib/libwayland-server.so.0
  --Type <RET> for more, q to quit, c to continue without paging--c
  #12 0x00007d83fd15701a in wlr_output_send_frame (output=0x5a361142ae60) at ../subprojects/wlroots/types/output/output.c:738
  #13 0x00007d83fd15705e in schedule_frame_handle_idle_timer (data=0x5a361142ae60) at ../subprojects/wlroots/types/output/output.c:746
          output = 0x5a361142ae60
  #14 0x00007d83fca34a23 in wl_event_loop_dispatch_idle () at /usr/lib/libwayland-server.so.0
  #15 0x00007d83fca34b3d in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
  #16 0x00007d83fca352d7 in wl_display_run () at /usr/lib/libwayland-server.so.0
  #17 0x00005a360ee5650a in server_run (server=0x5a360eed4b60 <server>) at ../sway/server.c:439
  #18 0x00005a360ee54ecd in main (argc=2, argv=0x7ffd4e199988) at ../sway/main.c:374
          verbose = false
          debug = true
          validate = false
          config_path = 0x0
          c = -1
  ```
  Also included in the gist.

- **Description:**

The setup for this crash is unfortunately very convoluted. You need a debug build of [Factorio](https://factorio.com/download) running under Wayland (`SDL_VIDEODRIVER="wayland"` in env), invoked from a [Foot](https://codeberg.org/dnkl/foot) terminal running [Kakoune](https://kakoune.org/) from within [Tmux]( https://github.com/tmux/tmux). Changing any of these variables causes the game to be disconnected with `wp_viewport@32: error 2: source rectangle out of buffer bounds` instead of crashing Sway. I am fixing this bug in the game but the debug build shouldn't be able to make Sway crash either.

Unfortunately I cannot provide a debug build of the game to reproduce this with.

**Comment by vyivel** [comment] 2024-01-26 13:17
Duplicate of https://github.com/swaywm/sway/issues/7930

**Closed by vyivel** 2024-01-26 13:17 UTC
Labels: bug

**Comment by raiguard** [comment] 2024-01-26 17:32
Apologies, I guess I didn't search thoroughly enough.
