### ISSUE TITLE
`reload` doesn’t consume key bind

### ISSUE THREAD

**Issue by whtv** [swaywm/sway#5151] opened 2020-03-27 19:33 UTC
When I reload sway with a key bind, the key presses are passed on to the focused window. That is, after reloading, with the default `Mod4+Shift+c` the focused window will accept a ‘C’. Changing the key binding doesn’t help. I moved my user config so sway would start with defaults, and the issue was gone. Then I realised it loaded (some of?) my old i3 config (or am I stupid?), so I moved that out of the way too. Then when I tried my user config again, the issue was gone there as well—but now it is back, without really changing anything in my config (I think). I made logs in all of these cases but they didn’t reveal anything. Any ideas?

**Comment by ianyfan** [comment] 2020-03-27 20:23
Duplicate of #4975

**Closed by ianyfan** 2020-03-27 20:23 UTC
