### ISSUE TITLE
Dragging a scrollbar + moving beyond window boundary, scrolling stops immediately.

### ISSUE THREAD

**Issue by DawidLoubser** [swaywm/sway#2247] opened 2018-07-11 14:48 UTC
Hi,

I'm running on latest git master - there are a fair amount of little issues and crashes, but on the other hand, Sway is also becoming pretty usable! I wanted to report the following usability quirk:

1. When there are two windows side-by-side, e.g. browser on the left
2. When I grab the scroll bar with the mouse and start dragging vertically, and I accidentally move the mouse too much to the right, so that it leaves the browser window,
3. Scrolling stops, and focus is given to the window on the right-hand side.

I'm not sure this is intuitive behaviour. It would be better if scrolling continues while I hold the mouse button, and only if I let go while the mouse is over the other window, should focus go there.

Not sure if the design of wayland makes this difficult, but this definitely struck me as a bug compared to other window managers - tiling or not.

**Comment by emersion** [comment] 2018-07-11 14:49
Duplicate of #1862

**Comment by SirCmpwn** [comment] 2018-07-11 14:49
https://github.com/swaywm/sway/issues/1862

**Closed** 2018-07-11 14:49 UTC
