### ISSUE TITLE
Improve parsing of commands

### ISSUE THREAD

**Issue by sivasama** [swaywm/sway#1631] opened 2018-03-23 14:58 UTC
The main configuration file fails to read block on a new line.

For instance in the bar configuration,

```
bar
{
status_command i3status
} 
```
fails,

whereas,

```
bar {
  status_command i3status
}
```
succeeds.

I guess this issue is due to the following in bar.c :
 

```
if (config->reading && strcmp("{", argv[0]) != 0) 
{
  return cmd_results_new(CMD_INVALID, "bar","Expected '{' at start of bar config definition.");
}
```

I guess it would be better if we remove this constraint of placing blocks ('{') immediately after.

**Comment by minus7** [comment] 2018-03-31 17:50
Duplicate of #1034

**Closed** 2018-03-31 17:59 UTC
