### ISSUE TITLE
Add ability to remove output created by create_output

### ISSUE THREAD

**Issue by glisignoli** [swaywm/sway#6771] opened 2022-01-18 19:07 UTC
- **Description:**
Add ability to remove output created by create_output.

The create output feature is really useful for creating a 'virtual' output that swayvnc can attach to. Once a 'virtual' output is created it is unable to be removed.

**Comment by emersion** [comment] 2022-01-18 19:08
Duplicate of https://github.com/swaywm/sway/issues/5522

**Closed by emersion** 2022-01-18 19:08 UTC
Labels: enhancement
