### ISSUE TITLE
Can't move tabs under Chrome - XWayland if another XWayland application is open in another workspace

### ISSUE THREAD

**Issue by fourstepper** [swaywm/sway#5692] opened 2020-09-16 18:56 UTC
### Please fill out the following:
- **Sway Version: 1.4 and 1.5** 

- **Distribution: Fedora 32 EDIT: and Fedora 33**

- **Description:**
  - It is not possible to move tabs in the same window or from a new window to a different window if a different XWayland application is open at the same time in a different workspace. I used Spotify flatpak to tests this

Steps to reproduce:
1) Open Chrome (observe described functionality working normally)
2) Go to a different workspace, open Spotify (or other XWayland app)
3) Return the Chrome workspace and try to move a tab around.

For me after the above steps any movement on the tab creates a new window, from which the tab cannot be returned to the previous window via drag&drop

**Comment by Algram** [comment] 2020-09-17 13:20
Having the exact same problem here.

`Sway 1.5, nixos-unstable`

**Comment by kellpossible** [comment] 2020-09-20 10:19
I can't move tabs around at all with chromium, trying to drag them just creates a new window, and also seems to induce lag. Seems to be associated with a recent chromium update.

**Comment by jsravn** [comment] 2020-09-27 19:10
I also notice you can no longer drag items, such as in the bookmark manager. And can't drag/drop bookmark folders on the bookmark bar. I assume this is related to not being able to move tabs.

**Comment by roshal** [comment] 2020-10-08 06:48
i experiencing the same problem under sway on archlinux

**Comment by jsravn** [comment] 2020-10-08 09:01
Also can't drag items in the github project view! So it seems drag events are just not working? Possibly something to do w/ focus.

**Comment by efenex** [comment] 2020-10-18 10:25
Same here with brave - no dragging/dropping in the browser at all for i.e. bookmarks, dragging tabs creates new windows and causes massive lag (that's probably a different issue)

**Comment by slyon** [comment] 2020-10-21 07:19
Same here with Chrome 86 on Ubuntu 20.10 and sway 1.5

**Comment by moonbone** [comment] 2020-10-22 11:07
seems to be fixed for me now on arch with:
chromium 86.0.4240.111-2
sway 1:1.5-1

**Comment by fourstepper** [comment] 2020-10-27 21:40
I think I have managed to limit the problem only to other full screen applications under XWayland in a different workspace - I hope this information is of any use

sway v. 1.5
Fedora 33

**Comment by Hubro** [comment] 2021-01-11 15:39
I'm using Sway 1:1.5.1-1 on Arch, and I can't rearrange tabs in Chrome or Chromium. When I click and drag a tab, it immediately pops out into a new window.

Interestingly, dragging tabs in Firefox and Vivaldi works just fine.

(I am running Chrome, Chromium and Vivaldi using xwayland)

**Comment by Vladius25** [comment] 2021-01-18 06:03
I tried to install chrome v89:
```
dnf install google-chrome-unstable
google-chrome-unstable -enable-features=UseOzonePlatform -ozone-platform=wayland
```
But when I try to move tabs, I see this in console and nothing happens:
```
[16588:16588:0118/105919.856636:ERROR:wayland_window_drag_controller.cc(119)] zcr_extended_drag_v1 extension not available! Window/Tab dragging won't be fully functional.
```
Maybe would be useful.

**Comment by Emantor** [comment] 2021-01-18 06:17
> But when I try to move tabs, I see this in console and nothing happens:
> 
> ```
> [16588:16588:0118/105919.856636:ERROR:wayland_window_drag_controller.cc(119)] zcr_extended_drag_v1 extension not available! Window/Tab dragging won't be fully functional.
> ```
> 
> Maybe would be useful.

Looks like chrome requires a custom protocol which is only implemented in their compositor. Highly likely that this is the same protocol they posted for inclusion to [wayland-protocols](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/46/diffs).

**Comment by Vladius25** [comment] 2021-01-18 17:49
> Looks like chrome requires a custom protocol which is only implemented in their compositor. Highly likely that this is the same protocol they posted for inclusion to [wayland-protocols](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/46/diffs).

But Gnome on Wayland somehow works with tabs on any chrome version.

**Comment by fourstepper** [comment] 2021-01-19 08:23
It would be nice  to keep this issue on topic.

The topic here is that on XWayland Chromium-based browers, dragging a tab creates a new window

> When I click and drag a tab, it immediately pops out into a new window.

**Comment by outerpassage** [comment] 2021-01-24 07:46
same issue here

```
sway version 1.5.1
Chromium 86.0.4240.111
Alpine Linux v3.13
```

**Comment by rbutoi** [comment] 2021-01-24 18:59
Trying to toggle the wayland features of chrome, I found turning on native wayland creates this issue, but running on XWayland (as confirmed by `swaymsg -t get_tree`) I can drag tabs without an issue.

```
Sway 1.5.1
Chrome 88.0.4324.96
```

**Comment by fourstepper** [comment] 2021-01-24 19:03
> Trying to toggle the wayland features of chrome, I found turning on native wayland creates this issue, but running on XWayland (as confirmed by `swaymsg -t get_tree`) I can drag tabs without an issue.
> 
> ```
> Sway 1.5.1
> Chrome 88.0.4324.96
> ```

does this work well for you even when having other apps running on XWayland in other workspaces

**Comment by rbutoi** [comment] 2021-01-24 19:09
Yup, I have Signal and Spotify (both XWayland) running in another workspace.

**Comment by mixedCase** [comment] 2021-02-16 20:00
Well I found an issue which might be due to the same underlying bug so I'm dropping it here just in case it helps, but let me know if I should file a new issue:

If I have two VSCode windows (which run on XWayland), running in different workspaces on the same monitor, drag-n-drop breaks on the area where they overlap. If I have a native Wayland app splitting one of the workspaces down the middle, and I go to the VSCode window on the other workspace, drag n drop works fine in the area where the native Wayland app is running, but if I try to drop in the location where the other VSCode window is in the other workspace, *that other instance gets the drop event instead of the window I'm actually focused on*.

**Comment by progandy** [comment] 2021-02-18 17:28
Does sway manage the z-order of (hidden) xwayland surfaces properly? Or maybe it should unmap them when they are on hidden workspaces? Otherwise xwayland could possibly route the events to the wrong window.

**Comment by abmantis** [comment] 2021-03-10 14:57
I can also confirm that if I have only Chrome (or only vscode, which is also affected) on output A, and other XWayland apps on output B, dragging tabs work. It only stops working if more than 1 XWayland app is in the same output and on the same screen coordinates as @mixedCase noted.

**Comment by luispabon** [comment] 2021-03-10 15:29
I can double-confirm what @abmantis just posted above. Dragging tabs only works if chrome is the sole xwayland app on that output.

**Comment by ivankovnatsky** [comment] 2021-03-18 13:28
for me it does not work at all, single chromium instance per output or more, same, can't drag tabs.

**Comment by kennylevinsen** [comment] 2021-03-18 13:44
Please test with master or rc1 of sway, with wlroots master and latest xwayland.

Personally, tab drag seems to mostly work as it should as tested with Google Chrome. I tested shuffling tabs, dragging a tab out, and putting a tab back in, including onto a window on another workspace. The only quirk I noticed is that if there is only one tab, and it is dragged around within the same container to create a new window in the same position, then Chrome appears to temporarily disregard our requested size and instead just draws its default window size.

**Comment by luispabon** [comment] 2021-03-18 13:55
Apologies, I'm not in a position currently to test the very latest as my distro (ubuntu 21.04) does not have wayland 1.19 yet.

**Comment by akiva** [comment] 2021-03-18 17:37
This problem is resolved for me now in Chromium using Wayland directly (not xwayland). Cheers!

**Comment by Xyene** [comment] 2021-04-25 18:17
Going to close this in favor of https://github.com/swaywm/wlroots/issues/2889. (Yes, this issue came first, but it turned out to be a duplicate after headway was already made there.)

In summary:

* This is a Chromium bug and has been a bug for 10 years.
* It happens to work in any WM that specifies `_NET_CLIENT_LIST_STACKING`, which includes GNOME/mutter but does not include wlroots.
* There is a Chrome patch in the thread for those who feel like rebuilding Chrome. I'll try to get the fix upstreamed.

**Closed by Xyene** 2021-04-25 18:17 UTC
Labels: bug

**Comment by paolomainardi** [comment] 2022-04-04 12:47
It seems that i cannot move tabs also using Wayland session, currently using:

Chrome: `Version 100.0.4896.60`
Sway: `1.7-2 (arch)`
Wlroots: `0.15.1-3 (arch)`
