### ISSUE TITLE
External screen is black after upgrade to 1.6

### ISSUE THREAD

**Issue by edkv** [swaywm/sway#6226] opened 2021-04-24 18:27 UTC
**Sway Version:**
1.6

**Debug Log:**
https://gist.github.com/edkv/3aa3f56dc4e5423e97e3155ba51de08e

**Configuration File:**
Default configuration.

**Description:**
After upgrade to sway 1.6 and wlroots 0.13 (from 1.5 and 0.12) my external screen is always black, only the mouse cursor is visible. I tried starting sway with `WLR_DRM_NO_MODIFIERS=1` as suggested in #6167 - then the screen works but I get white flashes/artifacts when I move my mouse or do anything else.

Here is also a log for `WLR_DRM_NO_MODIFIERS=1` just in case: https://gist.github.com/edkv/b13ce2b51c0cebe3a75a3dc2efd59300.

**Comment by emersion** [comment] 2021-04-25 09:15
Duplicate of https://github.com/swaywm/wlroots/issues/2636.

**Closed by emersion** 2021-04-25 09:15 UTC
Labels: bug
