### ISSUE TITLE
Crash in transaction_progress_queue

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#3947] opened 2019-03-20 22:26 UTC
`sway version 1.0-rc1-192-gcdcc2a5b (Mar 20 2019, branch 'master')`

I got this crash immediately upon quitting Firefox nightly running under Wayland. It was also the only program running in a freshly started Sway session.

```
#0  0x00007ff06a0cbd7f in raise () at /usr/lib/libc.so.6
#1  0x00007ff06a0b6672 in abort () at /usr/lib/libc.so.6
#2  0x00007ff06a10e878 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007ff06a11518a in  () at /usr/lib/libc.so.6
#4  0x00007ff06a11697c in _int_free () at /usr/lib/libc.so.6
#5  0x00007ff067e2c0fe in  () at /usr/lib/dri/i965_dri.so
#6  0x00007ff067e37175 in  () at /usr/lib/dri/i965_dri.so
#7  0x00007ff067f4e58a in  () at /usr/lib/dri/i965_dri.so
#8  0x00007ff067f573a1 in  () at /usr/lib/dri/i965_dri.so
#9  0x00007ff067f576a0 in  () at /usr/lib/dri/i965_dri.so
#10 0x00007ff067f57a78 in  () at /usr/lib/dri/i965_dri.so
#11 0x00007ff06a9b248f in gles2_texture_destroy (wlr_texture=0x56068ded4110) at ../subprojects/wlroots/render/gles2/texture.c:128
        texture = 0x56068ded4110
        __func__ = "gles2_texture_destroy"
#12 0x00007ff06a9b3796 in wlr_texture_destroy (texture=0x56068ded4110) at ../subprojects/wlroots/render/wlr_texture.c:16
#13 0x000056068caaaf32 in container_destroy (con=0x56068de583d0) at ../sway/tree/container.c:64
        __PRETTY_FUNCTION__ = "container_destroy"
#14 0x000056068ca7d861 in transaction_destroy (transaction=0x56068de50430) at ../sway/desktop/transaction.c:72
        instruction = 0x56068de7b480
        node = 0x56068de583d0
        i = 1 
        __PRETTY_FUNCTION__ = "transaction_destroy"
#15 0x000056068ca7e505 in transaction_progress_queue () at ../sway/desktop/transaction.c:348
        transaction = 0x56068de50430
#16 0x000056068ca7e5cc in transaction_progress_queue () at ../sway/desktop/transaction.c:371
        transaction = 0x56068de50430
#17 0x000056068ca7e636 in handle_timeout (data=0x56068de05fe0) at ../sway/desktop/transaction.c:379
        transaction = 0x56068de05fe0
#18 0x00007ff06a2de01a in  () at /usr/lib/libwayland-server.so.0
#19 0x00007ff06a2de702 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#20 0x00007ff06a2dd2ac in wl_display_run () at /usr/lib/libwayland-server.so.0
#21 0x000056068ca76449 in server_run (server=0x56068cad8de0 <server>) at ../sway/server.c:216
#22 0x000056068ca75960 in main (argc=1, argv=0x7ffc9cb0a008) at ../sway/main.c:398
        verbose = 0 
        debug = 0 
        validate = 0 
        allow_unsupported_gpu = 0 
        long_options = 
            {{name = 0x56068cabfea0 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x56068cabfea5 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x56068cabfeac "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x56068cabfeb5 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x56068cabfebb "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x56068cabfec3 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x56068cabfecb "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x56068cabfeda "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x56068cabfeea "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0 
        usage = 0x56068cabf968 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```

**Comment by emersion** [comment] 2020-02-08 10:22
Closing because the backtrace is too old, please re-open if you can still reproduce.

**Closed by emersion** 2020-02-08 10:22 UTC
