### ISSUE TITLE
Freeze with fullscreen apps on multi-GPU setups

### ISSUE THREAD

**Issue by mt190502** [swaywm/sway#8404] opened 2024-10-23 21:29 UTC
### Please fill out the following:
- **Sway Version:**
  - `1.10-rc2`

- **Configuration File:**
  - https://github.com/mt190502/swaydotfiles/tree/main/.config/sway

- **Description:**
  - Hi there! I'm using Swaywm on Fedora 41, and I've noticed something a little strange. When I open any game in full-screen mode, it looks like the monitor freezes. 
  - Extras: If I open OBS studio or discord live stream, no freeze on this monitor.
  - Tested games: Half Life, Counter Strike 

- **System Information**
  - OS: Fedora 41
  - Kernel: 6.11
  - CPU: Intel i5 11400
  - GPU1: Intel GPU
  - GPU2: AMD Radeon RX570

**Comment by Nefsen402** [comment] 2024-10-23 21:31
Does running with the environment variable `WLR_SCENE_DISABLE_DIRECT_SCANOUT=1` workaround the problem?

**Comment by emersion** [comment] 2024-10-23 21:33
Seems like a duplicate of https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3910

**Comment by Nefsen402** [comment] 2024-10-23 21:34
This user is running `1.10-rc2` so I would expect they aren't running upstream wlroots?

**Comment by emersion** [comment] 2024-10-23 21:36
Eh right!

Can you obtain debug logs?

**Comment by mt190502** [comment] 2024-10-24 08:52
> Does running with the environment variable `WLR_SCENE_DISABLE_DIRECT_SCANOUT=1` workaround the problem?

I'm not tried this. But I tried `sway -D noscanout` before. The situation has not changed.

**Comment by mt190502** [comment] 2024-10-24 08:58
> Does running with the environment variable `WLR_SCENE_DISABLE_DIRECT_SCANOUT=1` workaround the problem?

I tried this now. This works fine.

**Comment by mt190502** [comment] 2024-10-24 15:38
@emersion @Nefsen402  I collected debug logs

cmdline: `WLR_SCENE_DISABLE_DIRECT_SCANOUT=1 sway &>swaywm-noscanout.log`
[swaywm-noscanout.log](https://github.com/user-attachments/files/17509369/swaywm-noscanout.log)

cmdline: `sway &>swaywm-scanout.log`
[swaywm-scanout.log](https://github.com/user-attachments/files/17509371/swaywm-scanout.log)

**Comment by emersion** [comment] 2024-11-07 10:23
```
00:01:02.492 [ERROR] [wlr] [render/egl.c:705] EGL implementation doesn't support modifiers
00:01:02.492 [ERROR] [wlr] [backend/drm/renderer.c:88] Failed to import source buffer into multi-GPU renderer
00:01:02.492 [ERROR] [sway/desktop/output.c:317] Page-flip failed on output HDMI-A-4
```

**Comment by StefVdHaute** [comment] 2024-11-11 11:22
I can confirm this problem.

- Sway Version:
  - 1.10

- Configuration File:
  - https://github.com/mt190502/swaydotfiles/tree/main/.config/sway

- Description:
  - Hi there! I'm using Swaywm on EndeavourOS, and I've also noticed this issue. When I open warframe, or MPV in full-screen mode, it looks like the monitor freezes. When full screen mode is closed the screen unfreezes.
  - Extras: This only happens on the second screen attached via usb-c dongle or the hdmi port. The issue does not happen on the laptop screen.
  - Tested applications: Warframe via steam + proton-ge 9-18 and 9.20, mpv v0.39.0
  - setting `WLR_SCENE_DISABLE_DIRECT_SCANOUT=1` works.

- System Information
  - OS: EndeavourOS
  - Kernel: 6.6.59-1-lts
  - CPU: AMD Ryzen 7 5800H
  - GPU1: AMD Radeon RX Vega 8
  - GPU2: AMD Radeon Rx 6700M

- Log with issue:
  - [scanout.log](https://github.com/user-attachments/files/17701535/with_scanout.log)

**Comment by Omar007** [comment] 2024-11-13 16:37
Noticed very similar behaviour to the above on a desktop system with iGPU and dGPU.  
The iGPU is running a secondary monitor, the dGPU is running the primary monitor. (I know primary/secondary doesn't strictly exist on Wayland but it best illustrates how I use them).  

I ran into this when I fullscreened LibreOffice on the primary monitor; it suddenly seemed like my system froze up fully. It was only when I saw my mouse cursor move fine onto the secondary monitor that I realized it wasn't actually frozen. When I hit the fullscreen hotkey to de-fullscreen LibreOffice everything went back to normal again on the primary monitor.  
Of note is that fullscreening LibreOffice worked fine when it was located on the secondary monitor instead.  

Because the system is an iGPU+dGPU system I had also attempted to run with `DRI_PRIME=1` to see if that changed the behaviour; it did not.  

Running with `WLR_SCENE_DISABLE_DIRECT_SCANOUT=1` it works fine on the primary monitor.

**Comment by zDEFz** [comment] 2024-11-24 14:10
`WLR_SCENE_DISABLE_DIRECT_SCANOUT=1` also fixes my multi-gpu issue

**Comment by parnavh** [comment] 2024-11-24 14:14
`WLR_SCENE_DISABLE_DIRECT_SCANOUT=1` works for me too

**Comment by emersion** [comment] 2024-11-28 19:44
Does this help? https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4932

**Comment by StefVdHaute** [comment] 2024-11-30 16:56
I'd love to test this but would need some hand holding for how to build the 2 together. Alternatively could I install wlroots-git from the aur and point sway to it?

**Comment by StefVdHaute** [comment] 2024-11-30 19:16
This seems to work yes. I was able to fullscreen mpv in sway built from source while a video was playing. There were no freezing issues.

**Comment by egnappahz** [comment] 2024-12-02 22:35
building wlroots+sway upstream as instructed also yields a version for me without any freezing problems at all on my multiGPU, multidisplay setup, without invoking ```WLR_SCENE_DISABLE_DIRECT_SCANOUT=1```. Infact this is the most stable sway yet for my system.

**Comment by emersion** [comment] 2024-12-02 22:37
Cool, thanks for testing. Closing for now, please re-open if you can reproduce the same issue. The fix will be included in the next bugfix release.

**Closed by emersion** 2024-12-02 22:37 UTC
Labels: bug
