### ISSUE TITLE
Starting XWayland clients crashes Sway

### ISSUE THREAD

**Issue by Reiddragon** [swaywm/sway#8043] opened 2024-03-07 13:20 UTC
- **Sway Version:** 1.9
- **XWayland Version:** 23.2.4

- **Debug Log:** https://gist.github.com/Reiddragon/a6c626b994e4246a5d572cbdf8055616
- **Configuration File:** default config, only change was replacing foot with kitty (doesn't affect the bug)
- **Stack Trace:** https://gist.github.com/Reiddragon/90e8a597a649c33a81c55968a9c9c33d

- **Description:**
Starting an XWayland client crashes Sway, although not consistently (in the above logs, starting the first client went well, the second resulted in a crash)

Explicitly disabling XWayland in the config file (`xwayland disable`) prevents any crashes

**Comment by emersion** [comment] 2024-03-07 16:36
Duplicate of https://github.com/swaywm/sway/issues/7895

**Closed by emersion** 2024-03-07 16:36 UTC
Labels: bug
