### ISSUE TITLE
Black screen on i915 old hardware

### ISSUE THREAD

**Issue by AbyssalBatoidea** [swaywm/sway#6309] opened 2021-06-04 06:46 UTC
sway version 1.6

- **Debug Log:**
https://gist.github.com/AbyssalBatoidea/5e135be76456b4561c204cf566a398e9

- **Configuration File:**
  Default configuration from /etc/sway/config

- **Description:**
Gentoo OpenRC with elogind + GMA 950 graphics card, which has a rather weak OpenGL implementation. After starting sway from tty, the screen hangs, if you switch to another console and back, the display will be completely turned off. Most likely due to incorrect DPMS initialization. I hope this is really a bug, and not a feature of the implementation that does not allow running on old hardware.

**Comment by emersion** [comment] 2021-06-04 06:56
Duplicate of https://github.com/swaywm/wlroots/issues/2506

```
00:00:00.053 [DEBUG] [wlr] [render/egl.c:599] DMA-BUF import extension not present
```

**Closed by emersion** 2021-06-04 06:56 UTC
Labels: bug

**Comment by begss** [comment] 2021-06-04 18:11
Just launched sway on alpine 3.13.5 on 2006 laptop with GMA 950 and it runs fine.
