### ISSUE TITLE
Sway crash on startup Linux 5.10.12

### ISSUE THREAD

**Issue by Eragonfr** [swaywm/sway#5995] opened 2021-02-04 22:16 UTC
### Infos
Output of `swaymsg -t get_version`
`sway version 4.19.1 (2021-02-01)`

Debug Log:
https://gist.github.com/Eragonfr/311337ec7187ab2ce7c5aff23a322fee

Configuration File:
The bug is here with no config file and when my own config file is here. So maybe it's here with every config ?

Stack Trace:
I'm not using systemd as an init. How can I get a stacktrace ?

Description:
I've just launched sway as usual from my tty. And that's all, sway does not start. The only thing I've done was an update of my OS.

**Comment by emersion** [comment] 2021-02-04 22:20
Duplicate of https://github.com/swaywm/sway/issues/5984

**Closed by emersion** 2021-02-04 22:20 UTC
Labels: bug
