### ISSUE TITLE
sway can't set non-default resolution

### ISSUE THREAD

**Issue by tbm** [swaywm/sway#4515] opened 2019-08-30 23:23 UTC
My laptop supports display resolution 1920x1080.

Under X with xrandr I see:

```
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 8192 x 8192
eDP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 293mm x 162mm
   1920x1080     60.03*+  48.03
```

Under sway I see:

```
swaymsg -t get_outputs
Output eDP-1 'Unknown 0x5B2D 0x00000000' (focused)
  Current mode: 1920x1080 @ 60.033001 Hz
  Position: 0,0
  Scale factor: 1.000000
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Available modes:
    1920x1080 @ 48.026001 Hz
    1920x1080 @ 60.033001 Hz
```

When I run GNOME, it defaults to 1920x1080, but it also offers other resolutions, including 1600x900, and this works fine:

```
Screen 0: minimum 320 x 200, current 1600 x 900, maximum 8192 x 8192
XWAYLAND0 connected 1600x900+0+0 (normal left inverted right x axis y axis) 290mm x 160mm
   1600x900      59.82*+
```

However, when I force 1600x900 in sway, I still get 1920x1080:

```
output eDP-1 {
#    resolution 1920x1080 position 0,0
    resolution 1600x900 position 0,0
}
```

```
  Current mode: 1920x1080 @ 60.033001 Hz
```

The sway log shows:

```
2019-08-31 00:18:32 - [sway/config/output.c:262] Set eDP-1 mode to 1600x1200 (-1.000000 GHz)
2019-08-31 00:18:32 - [sway/config/output.c:221] Configured mode for eDP-1 not available
2019-08-31 00:18:32 - [sway/config/output.c:222] Picking default mode instead
2019-08-31 00:18:32 - [backend/drm/drm.c:544] Modesetting 'eDP-1' with '1920x1080@60033 mHz'
```

I can work around it with:

```
output eDP-1 {
    resolution 1920x1080 position 0,0
    scale 1.2
}
```

which I guess pretty much achieves the same (yes?).

Why does GNOME manage to set a non-standard resolution but sway doesn't?

This is with sway 1.1.

**Comment by emersion** [comment] 2019-08-31 11:18
Duplicate of https://github.com/swaywm/sway/issues/3791

**Closed by emersion** 2019-08-31 11:18 UTC

**Comment by tbm** [comment] 2019-08-31 11:58
Sorry for the duplicate.  I searched for "resolution", not "mode".
