### ISSUE TITLE
Waybar temporarily leaves black silhouette when disappearing

### ISSUE THREAD

**Issue by paul-ri** [swaywm/sway#8346] opened 2024-09-15 12:59 UTC
### Please fill out the following:
- Versions:
  * Sway: `sway version 1.10-dev-d7a76d38 (Sep 13 2024, branch 'master')`
  * wlroots: `0.19.0.r7234.7debaced-1`
  * [waybar](https://github.com/Alexays/Waybar): `Waybar v0.11.0-7-g0d02f687 (branch 'master')`

- **Debug Log:** 
[sway_error.log](https://github.com/user-attachments/files/17005792/sway_error_2.log)

- **Configuration File:** 

<details>
<summary>Sway config. Click to expand!</summary>
<p>

```
set $mod Mod4

set $term_no_option foot
set $term $term_no_option --app-id terminal
bindsym $mod+Return exec $term

bindsym --no-repeat $mod+Shift+q kill
bindsym $mod+Shift+e exit

bindsym --no-repeat {
    $mod+b splith
    $mod+v splitv
    $mod+s layout stacking
    $mod+w layout tabbed
    $mod+e layout toggle split
}

bar {
    swaybar_command waybar
    modifier $mod
    hidden_state hide
    mode hide
}
```
</p>
</details>

<details>
<summary>Waybar config in '~/.config/waybar/config'. Click to expand!</summary>
<p>

```
[
{
    "include": [ "~/.config/waybar/default-modules.json" ],
}
]
```
</p>
</details>

<details>
<summary>Waybar modules in '~/.config/waybar/default-modules.json'. Click to expand!</summary>
<p>

```
{
    "ipc": true,
    "layer": "top",
    "position": "bottom",
    "mode": "hide",

    "height": 40,

    "modules-right": [
        "sway/workspaces"
    ],
},
```
</p>
</details>

`~/.config/waybar/style.css`: kept empty

- **Stack Trace:** N.A.

- **Description:** Waybar leaves a black silhouette when hiding under certain conditions. The way I can reproduce it is when focus is changed whilst the bar is visible. It happens a lot for me as I use `Super+Tab` to focus to the next workspace and `Super` will bring up the bar.

The black bar will then disappear eventually (with time or when focusing back on the window)

Here's a video recording of the issue (done on the camera due to wf-recorder creating noise in the logs as in #5987).

https://github.com/user-attachments/assets/a5f0d366-0ce8-44d8-a2a7-9dc9396516de

Note:
* This does not happen on sway 1.9. So I don't think this is a waybar issue
* This does not happen when only the `clock` module of waybar is used. Only when `sway/workspaces` is used. I didn't try other combinations, I just slimmed the config a maximum.

**Comment by Nefsen402** [comment] 2024-09-15 15:18
This is a duplicate of https://github.com/swaywm/sway/issues/8075

It's an upstream waybar issue reported here: https://github.com/Alexays/Waybar/issues/3492

**Closed by Nefsen402** 2024-09-15 15:18 UTC
Labels: bug
