### ISSUE TITLE
Sometimes mouse click has no response

### ISSUE THREAD

**Issue by oluceps** [swaywm/sway#6349] opened 2021-06-27 10:09 UTC
- **Sway Version:**
1.6

- **[Configuration File](https://github.com/Dabrit/dotfile/tree/main/sway)**
- The debug log has no useful information

- **Description:**
 All of applications has no respond to mouse clicks,but dynamic effects still exist while mouse pointer slip between different windows to move focus.  
 once I use $mod+() to move focus,the mouse click begin to work.

**Comment by fluix-dev** [comment] 2021-06-27 22:10
> The debug log has no useful information

Please include a debug log. It very well may contain useful information.

**Comment by Dabrit** [comment] 2021-07-01 07:08
After i running sway -d > ~/sway.log  then catched the problem at least once  
here is sway.log
```
Checking for update  
Update for version 2.21.5 is not available (latest version: 2.21.5, downgrade is disallowed).  
checkForUpdatesAndNotify called, downloadPromise is null  
Opening in existing browser session.  
Checking for update  
Checking for update  
Checking for update  
```

**Comment by emersion** [comment] 2021-07-01 07:23
These logs aren't Sway debug logs.

**Comment by Dabrit** [comment] 2021-07-01 14:13
> These logs aren't Sway debug logs.

I lost some parameters when i catch log  
here is the new one  
https://raw.githubusercontent.com/Dabrit/Debug_files/main/sway.log

**Comment by lae** [comment] 2021-09-12 06:37
This has also been regularly affecting me after I started using Sway recently. The cursor will get "stuck" and not interact with desktop applications until I press a (any) keyboard key.

The log Dabrit provided was pretty similar to mine in general, however I disabled Xwayland and set `WLR_NO_HARDWARE_CURSORS=1` to reduce noise in the log output and see if it helped. While `tail`ing I managed to reproduce it pretty quickly, and here's the log (sanitized for PII) for that: https://gist.githubusercontent.com/lae/2d2d2ac2561321af3806155ee514b177/raw/ed6eba58373551df8e5ca32322e4d05b1911d9f5/gistfile1.txt

I found out shortly afterwards that I'm consistently able to reproduce this now by having Alacritty on one output, Firefox on the other (both in tabbed layout), then moving the cursor back and forth (but I've definitely had it start happening with Firefox on both outputs and just browsing regularly, for example). So I tried a bit more troubleshooting.

```
03:41:32.616 [DEBUG] [sway/input/text_input.c:184] Disabling text input, but no longer focused
```

This line stood out, so I tried closing my IME, fcitx5 (which it seems Dabrit is also using), and I could no longer reproduce the issue. That particular debug line also appears to have disappeared. So I guess this might be a focus issue with input methods?

**Comment by Dabrit** [comment] 2021-09-12 12:24
It's worth to be mentioned that i do use fcitx5 like @lae said,and my fcitx5 had many times of crash experiences without any obvious reason, and i haven't find the cause through the log file because i cannot predict when it happens so that I haven't start logcat.
That may be helpful.

**Closed** 2022-08-07 13:43 UTC
Labels: bug, waiting-on-reporter
