### ISSUE TITLE
Sway crash on lid close/open

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#5320] opened 2020-05-09 19:55 UTC
```
sway version 1.4-7c37e9d0 (May  9 2020, branch 'master')
```
I see this crash on closing and reopening notebook lid with latest sources.
[gdblog.txt](https://github.com/swaywm/sway/files/4604392/gdblog.txt)

**Comment by emersion** [comment] 2020-05-09 20:05
Duplicate of https://github.com/swaywm/wlroots/issues/2145

**Comment by emersion** [comment] 2020-05-09 20:06
Eh, actually this is a different issue it seems.

**Comment by JonnyMako** [comment] 2020-05-09 20:08
Yes, thanks. I was wondering about that since the other fix was merged 8 days ago. :)

**Comment by emersion** [comment] 2020-05-09 20:11
Can you try https://github.com/swaywm/wlroots/pull/2179?

**Comment by JonnyMako** [comment] 2020-05-09 20:56
That fixes the crash, but now, on re-hotplugging the monitor does not bring back the screen. It remains blank. Log attached.
[sway.log](https://github.com/swaywm/sway/files/4604466/sway.log)

**Comment by emersion** [comment] 2020-05-09 20:57
Maybe this one can help? https://github.com/swaywm/wlroots/pull/2167

**Comment by emersion** [comment] 2020-05-10 12:29
Closing because the crash has been fixed.

**Closed by emersion** 2020-05-10 12:29 UTC
