### ISSUE TITLE
input-method popups are duplicated on screen, and then crash

### ISSUE THREAD

**Issue by sam-mccall** [swaywm/sway#8086] opened 2024-03-23 22:12 UTC
[Here is](https://github.com/sam-mccall/bugreports/blob/main/sway-im-popup/src/main.rs) the world's simplest `input-method-unstable-v2`: it shows and hides the input popup panel on alternating keystrokes.

Sway duplicates the panel every time it is shown, rendering the same surface in both the current location and all the previous ones. Then when the input method is deactivated, sway crashes.

This only happens if I reuse the same surface for `get_input_popup_surface`. If I instead destroy it and use a new surface, things work as expected. I don't see anything in the protocol to indicate I need to use a new surface, though.

It should look like this:

https://github.com/swaywm/sway/assets/548993/c887ef0e-d4c3-4c1f-9341-a4e2dd4db264

But instead looks like this:

https://github.com/swaywm/sway/assets/548993/a2bfb8d5-7912-4a54-a26e-223a657a6cf9

cc @Decodetalkers, as #7226 landed recently

- **Sway Version:**
`sway version 1.10-dev-5a7477cb (Mar 23 2024, branch 'master')`

- **Debug Log:**
https://gist.github.com/sam-mccall/d4f6435a769983190e789c0e590631d8

- **Configuration File:**
Reproduces with empty config.

- **Stack Trace:**

<details>
<summary>Stack trace</summary>

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007f398da381cf in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007f398d9ea472 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f398d9d44b2 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007f398d9d43d5 in __assert_fail_base
    (fmt=0x7f398db48dc8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7f398e39653b "node", file=file@entry=0x7f398e396360 "types/scene/wlr_scene.c", line=line@entry=1059, function=function@entry=0x7f398e3967b0 <__PRETTY_FUNCTION__.4> "wlr_scene_node_coords") at ./assert/assert.c:92
#5  0x00007f398d9e33a2 in __assert_fail (assertion=0x7f398e39653b "node", file=0x7f398e396360 "types/scene/wlr_scene.c", line=1059, function=0x7f398e3967b0 <__PRETTY_FUNCTION__.4> "wlr_scene_node_coords") at ./assert/assert.c:101
#6  0x00007f398e30eca9 in wlr_scene_node_coords (node=0x0, lx_ptr=0x7fff127abedc, ly_ptr=0x7fff127abed8) at ../subprojects/wlroots/types/scene/wlr_scene.c:1059
#7  0x000055a485394471 in arrange_popups (popups=0x55a48546f1f0) at ../sway/desktop/transaction.c:615
#8  0x000055a485394915 in arrange_root (root=0x55a48546e9b0) at ../sway/desktop/transaction.c:675
#9  0x000055a485394b42 in transaction_progress () at ../sway/desktop/transaction.c:729
#10 0x000055a48539504d in transaction_commit_pending () at ../sway/desktop/transaction.c:849
#11 0x000055a4853953c2 in _transaction_commit_dirty (server_request=true) at ../sway/desktop/transaction.c:925
#12 0x000055a4853953d8 in transaction_commit_dirty () at ../sway/desktop/transaction.c:929
#13 0x000055a4853a54cd in check_focus_follows_mouse (seat=0x55a485d43000, e=0x55a485d43d50, hovered_node=0x55a486238130) at ../sway/input/seatop_default.c:598
#14 0x000055a4853a556d in handle_pointer_motion (seat=0x55a485d43000, time_msec=47725117) at ../sway/input/seatop_default.c:613
#15 0x000055a4853a36b0 in seatop_pointer_motion (seat=0x55a485d43000, time_msec=47725117) at ../sway/input/seat.c:1577
#16 0x000055a485399c58 in pointer_motion (cursor=0x55a485d43750, time_msec=47725117, device=0x55a485dd3840, dx=7.12890625, dy=1.6953125, dx_unaccel=21, dy_unaccel=5) at ../sway/input/cursor.c:326
#17 0x000055a485399cf5 in handle_pointer_motion_relative (listener=0x55a485d438a8, data=0x7fff127ac2a0) at ../sway/input/cursor.c:335
#18 0x00007f398dc25acc in wl_signal_emit_mutable () at /lib/x86_64-linux-gnu/libwayland-server.so.0
#19 0x00007f398e32a45c in handle_pointer_motion (listener=0x55a485ec02e8, data=0x7fff127ac2a0) at ../subprojects/wlroots/types/wlr_cursor.c:681
#20 0x00007f398dc25acc in wl_signal_emit_mutable () at /lib/x86_64-linux-gnu/libwayland-server.so.0
#21 0x00007f398e2ff184 in relative_pointer_handle_relative_motion (data=0x55a485477c60, relative_pointer=0x55a485475690, utime_hi=11, utime_lo=480476744, dx=1825, dy=434, dx_unaccel=5376, dy_unaccel=1280) at ../subprojects/wlroots/backend/wayland/pointer.c:419
#22 0x00007f398d25c40e in  () at /lib/x86_64-linux-gnu/libffi.so.8
#23 0x00007f398d25b71d in  () at /lib/x86_64-linux-gnu/libffi.so.8
#24 0x00007f398d25bef3 in ffi_call () at /lib/x86_64-linux-gnu/libffi.so.8
#25 0x00007f398d8c5921 in  () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#26 0x00007f398d8c1c09 in  () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#27 0x00007f398d8c35ac in wl_display_dispatch_queue_pending () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#28 0x00007f398e2f80de in dispatch_events (fd=6, mask=1, data=0x55a48546f650) at ../subprojects/wlroots/backend/wayland/backend.c:67
#29 0x00007f398dc27aa2 in wl_event_loop_dispatch () at /lib/x86_64-linux-gnu/libwayland-server.so.0
#30 0x00007f398dc254d5 in wl_display_run () at /lib/x86_64-linux-gnu/libwayland-server.so.0
#31 0x000055a48538e1e4 in server_run (server=0x55a48540bbe0 <server>) at ../sway/server.c:494
#32 0x000055a48538c9a4 in main (argc=1, argv=0x7fff127acb28) at ../sway/main.c:373
```
</details>

**Comment by Decodetalkers** [comment] 2024-03-24 03:58
Emm. video is broken

**Comment by Decodetalkers** [comment] 2024-03-24 03:58
Ok, thanks

**Comment by Decodetalkers** [comment] 2024-03-24 04:02
Emm. seems not the problem of my part..

**Comment by Decodetalkers** [comment] 2024-03-24 04:03
cc @emersion

**Comment by emersion** [comment] 2024-03-28 09:52
cc @Nefsen402 in case you have ideas what's up

**Comment by dgod** [comment] 2024-06-04 05:31
my input method have the likely same problem
labwc bug [1871](https://github.com/labwc/labwc/issues/1871)
they provide more details [1872](https://github.com/labwc/labwc/pull/1872)

**Comment by Nefsen402** [comment] 2024-06-05 02:22
Thanks so much for the test client! The issue is fixed with this PR: https://github.com/swaywm/sway/pull/8196

**Closed** 2024-09-20 17:40 UTC
Labels: bug
