### ISSUE TITLE
Sway crashes when popup is open and pointer is dragged over title bar

### ISSUE THREAD

**Issue by wmww** [swaywm/sway#5389] opened 2020-05-26 17:51 UTC
Sway version: 1.4-d71fed95 (May 26 2020, branch 'master') (just built both sway and wlroots from master)

(this may be a wlroots issue, the stack trace touches both)

To reproduce:
- Open an app (tested with Weston terminal and several GTK apps)
- Set the container to be tabbed so there is a title bar
- Open a popup
- With the popup still open, drag the pointer to the title bar
- Sway crashes

Stack trace (see below for my analysis):
```
Thread 1 "sway" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6b72f00 (LWP 41803)]
0x00007ffff790b566 in xdg_pointer_grab_enter (grab=0x555555fbb368, surface=0x0, sx=0, sy=0) at ../types/xdg_shell/wlr_xdg_popup.c:21
21		if (wl_resource_get_client(surface->resource) == popup_grab->client) {
(gdb) bt
#0  0x00007ffff790b566 in xdg_pointer_grab_enter (grab=0x555555fbb368, surface=0x0, sx=0, sy=0) at ../types/xdg_shell/wlr_xdg_popup.c:21
#1  0x00007ffff78fe736 in wlr_seat_pointer_notify_enter (wlr_seat=0x555555d4d0c0, surface=0x0, sx=0, sy=0) at ../types/seat/wlr_seat_pointer.c:335
#2  0x0000555555591824 in handle_pointer_motion (seat=0x555555d4cee0, time_msec=15752542, dx=0, dy=-0.87890625) at ../sway/input/seatop_default.c:482
#3  0x000055555558fe83 in seatop_pointer_motion (seat=0x555555d4cee0, time_msec=15752542, dx=0, dy=-0.87890625) at ../sway/input/seat.c:1463
#4  0x0000555555585569 in pointer_motion (cursor=0x555555d4d500, time_msec=15752542, device=0x555555e02bb0, dx=0, dy=-0.87890625, dx_unaccel=0, dy_unaccel=-1) at ../sway/input/cursor.c:327
#5  0x00005555555855ff in handle_pointer_motion_relative (listener=0x555555d4d630, data=0x7fffffffd990) at ../sway/input/cursor.c:335
#6  0x00007ffff7938e43 in wlr_signal_emit_safe (signal=0x555555d4d7e8, data=0x7fffffffd990) at ../util/signal.c:29
#7  0x00007ffff7913514 in handle_pointer_motion (listener=0x555555efa620, data=0x7fffffffd990) at ../types/wlr_cursor.c:355
#8  0x00007ffff7938e43 in wlr_signal_emit_safe (signal=0x555555e02a18, data=0x7fffffffd990) at ../util/signal.c:29
#9  0x00007ffff78ef9fa in relative_pointer_handle_relative_motion (data=0x555555e02bb0, relative_pointer=0x555555d9d430, utime_hi=3, utime_lo=2867640112, dx=0, dy=-225, dx_unaccel=0, dy_unaccel=-256)
    at ../backend/wayland/seat.c:469
#10 0x00007ffff6fd2ff5 in  () at /usr/lib/x86_64-linux-gnu/libffi.so.7
#11 0x00007ffff6fd240a in  () at /usr/lib/x86_64-linux-gnu/libffi.so.7
#12 0x00007ffff6f0a3a8 in wl_closure_invoke (closure=closure@entry=0x555555fbb820, flags=flags@entry=1, target=<optimized out>, target@entry=0x555555d9d430, opcode=opcode@entry=0, data=<optimized out>)
    at ../src/connection.c:1018
#13 0x00007ffff6f06c48 in dispatch_event (display=display@entry=0x5555555fb640, queue=<optimized out>) at ../src/wayland-client.c:1445
#14 0x00007ffff6f0821c in dispatch_queue (queue=0x5555555fb710, display=0x5555555fb640) at ../src/wayland-client.c:1591
#15 wl_display_dispatch_queue_pending (display=0x5555555fb640, queue=0x5555555fb710) at ../src/wayland-client.c:1833
#16 0x00007ffff78eb6a1 in dispatch_events (fd=4, mask=1, data=0x5555555fb450) at ../backend/wayland/backend.c:46
#17 0x00007ffff798d65a in wl_event_loop_dispatch (loop=0x5555555f4b30, timeout=timeout@entry=-1) at ../src/event-loop.c:1027
#18 0x00007ffff798bbd5 in wl_display_run (display=0x5555555fb2e0) at ../src/wayland-server.c:1351
#19 0x0000555555576ada in server_run (server=0x5555555ea060 <server>) at ../sway/server.c:225
#20 0x000055555557609a in main (argc=1, argv=0x7fffffffe158) at ../sway/main.c:409
```

It appears `xdg_pointer_grab_enter()` is accessing `surface` without checking if it's null, but `handle_pointer_motion()` is explicitly sending in a null surface in some cases. It's not obvious to me which piece is broken.

**Comment by emersion** [comment] 2020-05-26 18:00
Duplicate of https://github.com/swaywm/sway/issues/5294

**Closed by emersion** 2020-05-26 18:00 UTC
