### ISSUE TITLE
Sway segfaults on startup

### ISSUE THREAD

**Issue by RedBorg** [swaywm/sway#3995] opened 2019-03-29 21:12 UTC
Building with clang from latest commit on master branch (wlroots: 08454adad, sway: g2cae0d5e) and running it on an arch-like distro with linux-libre kernel. Running latest nouveau and mesa drivers.

Sway will segfault very shortly after startup.
I'm only able to launch it from i3, as launching it from the tty will cause to not startup at all with no error message.

Here's the output after running it in i3:
https://ghostbin.com/paste/3d4qe

Here's the output of `coredumpctl gdb sway`:
```Journal file /var/log/journal/db9dc3e813af43e3a4b56f8fb85240ac/system@00057c6d85d74f1a-aa57e7bf7b7f026b.journal~ is truncated, ignoring file.
           PID: 18436 (sway)
           UID: 1000 (user)
           GID: 998 (wheel)
        Signal: 11 (SEGV)
     Timestamp: Fri 2019-03-29 16:39:06 EDT (13min ago)
  Command Line: sway -d
    Executable: /usr/local/bin/sway
 Control Group: /user.slice/user-1000.slice/session-10.scope
          Unit: session-10.scope
         Slice: user-1000.slice
       Session: 10
     Owner UID: 1000 (user)
       Boot ID: 7f2003e5e39b4fbd839ca9e77ad60fec
    Machine ID: db9dc3e813af43e3a4b56f8fb85240ac
      Hostname: hostname
       Storage: /var/lib/systemd/coredump/core.sway.1000.7f2003e5e39b4fbd839ca9e77ad60fec.18436.1553891946000000.lz4
       Message: Process 18436 (sway) of user 1000 dumped core.
                
                Stack trace of thread 18436:
                #0  0x00007f57a11941b0 wl_list_insert (libwayland-server.so.0)
                #1  0x00005596f7349730 wl_signal_add (sway)
                #2  0x00005596f734965c handle_map (sway)
                #3  0x00007f57a114a80b wlr_signal_emit_safe (libwlroots.so.1)
                #4  0x00007f57a1123a8d handle_xdg_surface_commit (libwlroots.so.1)
                #5  0x00007f57a1141b7a surface_commit_pending (libwlroots.so.1)
                #6  0x00007f57a1141df8 surface_commit (libwlroots.so.1)
                #7  0x00007f57a07b06d0 ffi_call_unix64 (libffi.so.6)
                #8  0x00007f57a07b00a0 ffi_call (libffi.so.6)
                #9  0x00007f57a119382f n/a (libwayland-server.so.0)
                #10 0x00007f57a1190193 n/a (libwayland-server.so.0)
                #11 0x00007f57a11917f2 wl_event_loop_dispatch (libwayland-server.so.0)
                #12 0x00007f57a119039c wl_display_run (libwayland-server.so.0)
                #13 0x00005596f733e4b7 server_run (sway)
                #14 0x00005596f733d5ab main (sway)
                #15 0x00007f57a0ea7223 __libc_start_main (libc.so.6)
                #16 0x00005596f732df2e _start (sway)
                
                Stack trace of thread 18438:
                #0  0x00007f57a0e6fafc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f579ebfe104 n/a (nouveau_dri.so)
                #2  0x00007f579ebfde28 n/a (nouveau_dri.so)
                #3  0x00007f57a0e69a9d start_thread (libpthread.so.0)
                #4  0x00007f57a0f7eb23 __clone (libc.so.6)

Failed to invoke gdb: No such file or directory
```

**Comment by emersion** [comment] 2019-03-29 21:51
Please install `gdb`, then do the same thing and type `bt full`. This should give a better stacktrace.

**Comment by RedBorg** [comment] 2019-04-04 21:16
@emersion Sorry I've waited so long, but here's the log:
```plain
#0  0x00007f805cbed1b0 in wl_list_insert () at /usr/lib/libwayland-server.so.0
#1  0x0000555bbc78a6b0 in wl_signal_add (signal=0x555bbdc1ff60, listener=0x555bbdaf78c8) at /usr/include/wayland-server-core.h:435
#2  0x0000555bbc78a5dc in handle_map (listener=0x555bbdaf7970, data=0x555bbd9ff960) at ../sway/desktop/xdg_shell.c:437
        xdg_shell_view = 0x555bbdaf77c0
        view = 0x555bbdaf77c0
        xdg_surface = 0x555bbd9ff960
        csd = false
#3  0x00007f805cba380b in wlr_signal_emit_safe (signal=0x555bbd9ffa58, data=0x555bbd9ff960) at ../util/signal.c:29
        pos = 0x555bbdaf7970
        l = 0x555bbdaf7970
        cursor = {link = {prev = 0x555bbdaf7970, next = 0x7fff45cd0f10}, notify = 0x7f805cba3755 <handle_noop>}
        end = {link = {prev = 0x7fff45cd0ef0, next = 0x555bbd9ffa58}, notify = 0x7f805cba3755 <handle_noop>}
#4  0x00007f805cb7ca8d in handle_xdg_surface_commit (wlr_surface=0x555bbdaf5600) at ../types/xdg_shell/wlr_xdg_surface.c:356
        surface = 0x555bbd9ff960
        __PRETTY_FUNCTION__ = "handle_xdg_surface_commit"
#5  0x00007f805cb9ab7a in surface_commit_pending (surface=0x555bbdaf5600) at ../types/wlr_surface.c:372
        invalid_buffer = true
        subsurface = 0x555bbdaf57e8
#6  0x00007f805cb9adf8 in surface_commit (client=0x555bbdb8b8e0, resource=0x555bbdc34400) at ../types/wlr_surface.c:444
        surface = 0x555bbdaf5600
        subsurface = 0x0
#7  0x00007f805c2096d0 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#8  0x00007f805c2090a0 in ffi_call () at /usr/lib/libffi.so.6
#9  0x00007f805cbec82f in  () at /usr/lib/libwayland-server.so.0
#10 0x00007f805cbe9193 in  () at /usr/lib/libwayland-server.so.0
#11 0x00007f805cbea7f2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#12 0x00007f805cbe939c in wl_display_run () at /usr/lib/libwayland-server.so.0
#13 0x0000555bbc77f477 in server_run (server=0x555bbc7e7d78 <server>) at ../sway/server.c:216
#14 0x0000555bbc77e569 in main (argc=1, argv=0x7fff45cd16e8) at ../sway/main.c:398
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x555bbc7cf5d1 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x555bbc7d291b "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x555bbc7cf5d6 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x555bbc7cf5df "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x555bbc7cfa8e "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x555bbc7ce2c3 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x555bbc7cf5e5 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x555bbc7cf5f4 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x555bbc7cf604 "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x555bbc7cf61f "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```

**Comment by RedSoxFan** [comment] 2019-04-04 21:25
I think #4009 was technically a duplicate of this. Can you please update wlroots and then sway?

**Comment by RedBorg** [comment] 2019-04-04 23:51
@RedSoxFan You are right, this was a problem with me keeping the wlroots-git package.

I build sway+wlroots myself, but waybar required the package, so I kept it without updating (which is absolutely against best practices, I concede). I have made a blank placeholder package and removed the wlroots-git package, so now everything works.

**Closed** 2019-04-04 23:52 UTC
