### ISSUE TITLE
1.5-rc1: Sway uses 100% of a cpu core upon killing Xwayland

### ISSUE THREAD

**Issue by luispabon** [swaywm/sway#5492] opened 2020-06-29 20:23 UTC
* Sway Version:

Sway Version:
Sway 1.5-rc1
wlroots a7f48aab6968ad67ff7eef2828bd6f6e45c18ab5

* Debug Log:

Nothing on the debug logs.

* Configuration File:

https://github.com/luispabon/sway-dotfiles/tree/master/configs/sway

## The issue

When killing Xwayland, Sway uses 100% CPU. This does not happen on 1.4. I can reproduce it 100% of the time if I open a a new sway session, then a Xwayland app then kill Xwayland. Doesn't seem to happen if I never open an Xwayland app first.

Also, Sway seems unable to open any new apps afterwards - they just hang forever.

Demo: https://youtu.be/jQwZ_R-mEr0

* Stack Trace, if sway crashes:
n/a

**Comment by emersion** [comment] 2020-06-29 20:25
I'm going to close this as a dup of https://github.com/swaywm/wlroots/issues/2174 because it's the same root cause.

**Closed by emersion** 2020-06-29 20:25 UTC

**Comment by luispabon** [comment] 2020-06-30 09:03
Roger, thank you.
