### ISSUE TITLE
Sway crashes with Firefox/Thunderbird running when disabling/re-enabling internal screen

### ISSUE THREAD

**Issue by sydneymeyer** [swaywm/sway#3501] opened 2019-01-22 23:25 UTC
1. Start sway (with external display already connected or display connected after sway started)
2. FF/TB launches on internal eDP-1 screen
3. sway output eDP-1 disable
4. sway outpur eDP-1 enable
5. Everything survives
---

1. Start sway (with external display already connected or display connected after sway started)
2. FF/TB launches on internal eDP-1 screen
3. Move FF/TB from window 1 to i.e. window 2 (on external DP-5 display) or start FF/TB on external display window i.e. window 2, same effect) 
3. sway output eDP-1 disable
4. sway outpur eDP-1 enable
5. sway crashes reprodicibly

sway version 1.0-beta.2-264-g9e6c6ce3 (Jan 22 2019, branch 'master')
wlroots commit c41d01306de59235256d96902cced49a8eef15e9
Linux 4.20.3-arch1-1-ARCH

[debug.log](https://github.com/swaywm/sway/files/2784983/debug.log)
[bt_full.txt](https://github.com/swaywm/sway/files/2784985/bt_full.txt)
[stack_trace.txt](https://github.com/swaywm/sway/files/2784986/stack_trace.txt)

**Comment by emersion** [comment] 2019-01-28 09:38
```
#0  0x00005625ae7c4bfe in render_containers_linear (output=0x5625afba1c00, damage=0x7fff81bd2fb0, parent=0x7fff81bd2e70) at ../sway/desktop/render.c:675
        i = 0
#1  0x00005625ae7c51d1 in render_containers (output=0x5625afba1c00, damage=0x7fff81bd2fb0, parent=0x7fff81bd2e70) at ../sway/desktop/render.c:848
#2  0x00005625ae7c537d in render_workspace (output=0x5625afba1c00, damage=0x7fff81bd2fb0, ws=0x5625afbcead0, focused=32) at ../sway/desktop/render.c:890
        data = {layout = L_NONE, box = {x = 0, y = 0, width = 0, height = 0}, children = 0x0, focused = 32, active_child = 0x0}
#3  0x00005625ae7c5ba0 in output_render (output=0x5625afba1c00, when=0x7fff81bd2fa0, damage=0x7fff81bd2fb0) at ../sway/desktop/render.c:1037
        clear_color = {0.25, 0.25, 0.25, 1}
        nrects = 1
        rects = 0x7fff81bd2fb0
        wlr_output = 0x5625afac8870
        renderer = 0x5625afa62cd0
        __PRETTY_FUNCTION__ = "output_render"
        workspace = 0x5625afbcead0
        fullscreen_con = 0x0
        seat = 0x69
        focus = 0x2
        width = -2118308096
        height = 1
        transform = 32767
#4  0x00005625ae7c1dde in damage_handle_frame (listener=0x5625afba1d78, data=0x5625afba1dc0) at ../sway/desktop/output.c:377
        output = 0x5625afba1c00
        now = {tv_sec = 2488, tv_nsec = 331610539}
        needs_swap = true
        damage = {extents = {x1 = 0, y1 = 0, x2 = 1920, y2 = 1080}, data = 0x0}
#5  0x00007f0485f3e7cf in wlr_signal_emit_safe (signal=0x5625afba1e20, data=0x5625afba1dc0) at ../util/signal.c:29
        pos = 0x5625afba1d78
        l = 0x5625afba1d78
        cursor = {link = {prev = 0x5625afba1d78, next = 0x7fff81bd3020}, notify = 0x7f0485f3e719 <handle_noop>}
        end = {link = {prev = 0x7fff81bd3000, next = 0x5625afba1e20}, notify = 0x7f0485f3e719 <handle_noop>}
#6  0x00007f0485f2c28e in output_handle_frame (listener=0x5625afba1eb8, data=0x5625afac8870) at ../types/wlr_output_damage.c:50
        output_damage = 0x5625afba1dc0
#7  0x00007f0485f3e7cf in wlr_signal_emit_safe (signal=0x5625afac8990, data=0x5625afac8870) at ../util/signal.c:29
        pos = 0x5625afba1eb8
        l = 0x5625afba1eb8
        cursor = {link = {prev = 0x5625afba1eb8, next = 0x7fff81bd30c0}, notify = 0x7f0485f3e719 <handle_noop>}
        end = {link = {prev = 0x7fff81bd30a0, next = 0x5625afac8990}, notify = 0x7f0485f3e719 <handle_noop>}
#8  0x00007f0485f2f1c1 in wlr_output_send_frame (output=0x5625afac8870) at ../types/wlr_output.c:417
#9  0x00007f0485ef2914 in page_flip_handler (fd=9, seq=129689, tv_sec=2488, tv_usec=299987, data=0x5625afac8870) at ../backend/drm/drm.c:1314
        conn = 0x5625afac8870
        drm = 0x5625af8e4eb0
        present_time = {tv_sec = 2488, tv_nsec = 299987000}
        present_event = {output = 0x5625afac8870, when = 0x7fff81bd3140, seq = 129689, refresh = 16663333, flags = 7}
#10 0x00007f0484a70705 in drmHandleEvent () at /lib64/libdrm.so.2
#11 0x00007f0485ef2999 in handle_drm_event (fd=9, mask=1, data=0x0) at ../backend/drm/drm.c:1324
        event = {version = 2, vblank_handler = 0x0, page_flip_handler = 0x7f0485ef27ab <page_flip_handler>, page_flip_handler2 = 0x0, sequence_handler = 0x0}
#12 0x00007f0485f83702 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#13 0x00007f0485f822ac in wl_display_run () at /usr/lib/libwayland-server.so.0
#14 0x00005625ae7bed1f in server_run (server=0x5625ae81cc80 <server>) at ../sway/server.c:201
#15 0x00005625ae7be2d4 in main (argc=2, argv=0x7fff81bd39b8) at ../sway/main.c:413
        verbose = 0
        debug = 1
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x5625ae804d24 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x5625ae804d29 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x5625ae804d30 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x5625ae804d39 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x5625ae804d3f "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x5625ae804d47 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x5625ae804d4f "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x5625ae804d5e "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x5625ae804d6e "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x5625ae8048e0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
--Type <RET> for more, q to quit, c to continue without paging--
        c = -1
(gdb) 
```

**Comment by emersion** [comment] 2019-01-28 09:41
Maybe a duplicate of https://github.com/swaywm/sway/issues/3110?

**Comment by sydneymeyer** [comment] 2019-02-21 18:51
I have been running this revision just for a few minutes now, but it appears that commit [https://github.com/swaywm/sway/commit/03dfdb1edbfc445fe30b6456827ae93ef6c18426](url) could have resolved this issue. I cannot reproduce the issue anymore so far. Tested with [https://github.com/swaywm/sway/commit/546b976baa9989676c2fb2aff8c36f42b3d19810](url) and the behaviour is still present. Perhaps, this is intended behaviour, but i have noticed that sway crashes when there is no display "enabled" (via sway output) and i disconnect the laptop from it's docking station.

**Comment by RedSoxFan** [comment] 2019-02-21 19:11
> `#2  0x00005625ae7c537d in render_workspace (output=0x5625afba1c00, damage=0x7fff81bd2fb0, ws=0x5625afbcead0, focused=32) at ../sway/desktop/render.c:890`

> **focused=32**

Based on the above back trace snippet, I'm going to close this via #3743

**Closed by RedSoxFan** 2019-02-21 19:11 UTC
Labels: bug
