### ISSUE TITLE
Support/document scaling behavior of XWayland

### ISSUE THREAD

**Issue by Nikratio** [swaywm/sway#8452] opened 2024-11-13 10:04 UTC
I tried to figure out what happens to X11 clients when configuring output scaling in Sway. I could come up with 3 possible behaviours:

1. The X11 output is shown by Sway as-is, without any scaling (so I have to configure X11 clients separately to render at larger scale)
2. The X11 output is scaled up by Sway exactly by the scaling factor
3. The X11 clients see an apparently larger or smaller output device (corresponding to the integer component of the scaling factor), and if there is a fractional part of the scaling factor, then Sway scales the X11 output accordingly.

I couldn't find any documentation about this, so I tried to determine it experimentally and I think (2) is the case. However, I am not 100% sure (I don't trust my ability to tell exactly when something has been scaled vs rendered at higher resolution). So it would be fantastic if this could be documented.

In addition to that (not sure if I should file a separate bug report), if (2) is indeed the current behaviour, then it would be amazing to also support (1) or (3). At least for me, all legacy X11 apps that I use look better when I set `Xft.dpi` to some higher value and show the output unscaled than when the output is rendered at lower resolution and then scaled up (even if this means that not all parts of the window are scaled).

**Comment by emersion** [comment] 2024-11-16 14:12
(2) is the current behavior and only reliable way to scale X11 clients. (3) is impossible to implement given the X11 protocol. (1) would display some X11 clients incorrectly.

Closing as a duplicate of https://github.com/swaywm/sway/issues/2966. See the discussion there for more background.

**Closed by emersion** 2024-11-16 14:12 UTC
Labels: enhancement
