### ISSUE TITLE
After some time, XWayland clients get incorrect scaling factor

### ISSUE THREAD

**Issue by colemickens** [swaywm/sway#2847] opened 2018-10-16 00:50 UTC
I've been putting off filing this one, hoping I could find a pattern or a reliable hunch of the root cause. Unfortunately, I have none and am filing this since I've seen others report it in IRC.

For whatever reason, after some time, XWayland clients start rendering at 2x (?) more than they should be.

This happens even without multi-monitor or mixed DPI. I haven't discovered a pattern, but generally the following is true:

1. Things are fine after a reboot and starting sway.
2. When it gets "broken", all new applications open at the wrong factor.
3. When it gets "broken", it affects GTK3 and Qt apps similarly. (Not sure about GTK2).
4. There's no way to fix it, that I'm aware of, other than restarting sway.

Also AFAICT, this isn't caused by Chrome's auto-DPI sensing code, as it affects Firefox and GIMP, etc.

I am having to quit and restart `sway` every several hours as I run into this (that is, if I don't crash from  #2846 first).

![xwayland-wrong-dpi](https://user-images.githubusercontent.com/327028/46986131-96517400-d0a2-11e8-966e-ef1be49b5ae4.png)

**Comment by SirCmpwn** [comment] 2018-10-16 00:52
Can you cause this to occur by hotplugging outputs or changing output resolution? Can you correlate these events with a particular part of a debug log?

**Comment by c-edw** [comment] 2018-10-16 03:13
This has occurred with KeePassXC and `gedit` for me, so Qt and GTK respectively. Haven't had anything like this occur with Chromium, though (something to do with the GTK theme in Settings, maybe). Unfortunately my system just crashed while I had the bug present, but I am verbosely logging to a file now, and I'll keep an eye out for when it happens next.

**Comment by c-edw** [comment] 2018-10-16 03:34
I've done some testing, I think a configuration reload (`$mod+Shift+C`) reliably produces this bug. Doing it just once will cause the applications to use what looks like a 2x scale factor. I have also removed my own Sway config to confirm that is not the cause.

**Comment by colemickens** [comment] 2018-10-16 05:41
I found a stranger, 100% consistent repro that doesn't require reloading configuration:

1. Start sway with outputs unconfigured.
2. Launch Chrome.
3. Run keystroke to set output (including `scale=2`).
4. Launch Firefox.

Firefox will be scaled effectively 4x, instead of 2x.

I'll try to get a log tomorrow with this minimal repro if it's needed beyond what @c-edw provided.

**Comment by emersion** [comment] 2018-10-16 06:05
Is this a duplicate of https://github.com/swaywm/wlroots/issues/988?

**Comment by c-edw** [comment] 2018-10-16 16:04
I don't think either scenarios require hotplugging.

**Comment by SirCmpwn** [comment] 2018-10-16 16:04
>Is this a duplicate of swaywm/wlroots#988?

That's what I'm wondering. I think the answer is yes.

**Comment by tsloughter** [comment] 2018-10-16 20:58
It happens any time I reload the sway config (ctrl-shift-c) while running sway. It increases the scale for new windows with each reload.

**Comment by colemickens** [comment] 2018-10-17 01:12
`pkill firefox; pkill X; firefox` seems to "resolve" the issue, so I'm inclined to believe it could be Xwayland's fault.

**Comment by SirCmpwn** [comment] 2018-10-17 01:36
That's enough to convince me. You should report to the freedesktop.org bug tracker.

**Closed** 2018-10-17 01:36 UTC

**Comment by c-edw** [comment] 2018-11-05 17:05
Just noticed that this also happens any time an external monitor is plugged/unplugged. The scale factor doubles.

**Comment by SirCmpwn** [comment] 2018-11-05 17:06
It's still an Xwayland bug. Tell them.

**Comment by colemickens** [comment] 2018-11-16 00:38
Note, for anyone (hopefully xorg folks...) reading this thread from the upstream XWayland bug, @Timidger commented on the wlroots issue with a supposed patch: https://github.com/swaywm/wlroots/issues/988#issuecomment-435382026
