### ISSUE TITLE
Floating window content is drawn one pixel too high on an output with a negative y coordinate after move

### ISSUE THREAD

**Issue by YSelfTool** [swaywm/sway#5064] opened 2020-03-02 16:44 UTC
* Sway Version: sway version 1.4
* Debug Log: https://gist.github.com/YSelfTool/9283eabf5c9d414ea81dc349a3eb7cda
* Configuration File: https://gist.github.com/YSelfTool/eb2d60136cb50442bf1b20ee882049ee

1. Enable an output with a negative y coordinate, i.e. above the normal 0,0 output.
2. Open floating window on that output.
3. Move the window a bit by grabbing the header.

The window content will be drawn one pixel too high, resulting in a white (i.e. background color) line above the bottom decoration and an overlap with the top decoration: ![Screenshot](https://www.rsonn.de/downloads/sway-bug.png)
This matches the attached config file, the bottom window is on an output at 0,0, the top on an output  at 0,-1200.

~~I haven't seen the problem with other programs than alacritty.~~ The problem is independent of te application. I have tested and seen it with alacritty, firefox (wayland) and xclocks (using xwayland). I haven't tested negative x coordinates, but they might be affected as well.

This doesn't happen on outputs with positive positions, and it doesn't happen if the window is moved with key bindings, i.e. grabbing with the mouse is required. The offset only appears when moving the window.

**Comment by dimitris-triantafyllidis** [comment] 2020-09-08 06:16
Hi. I can't reproduce this issue in my branch which is mentioned in this pull request: #5663. The keyboard probably hides this because it moves by an integer amount of pixels.

**Comment by Xyene** [comment] 2021-02-23 02:26
Fixed in https://github.com/swaywm/sway/commit/aac1582ea90897a25408a520b8f3bde0552a69cc.

**Closed by Xyene** 2021-02-23 02:26 UTC
