### ISSUE TITLE
Sway crashes after sending a login form

### ISSUE THREAD

**Issue by ariel-anieli** [swaywm/sway#8510] opened 2024-12-22 23:22 UTC
The same issue is tracked in https://github.com/swaywm/swaybg/issues/81

### Please fill out the following:
- **Sway Version:**
```shell
# sway -v 
sway version 1.10

# uname -a 
Linux arc 6.12.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 19 Dec 2024 21:29:01 +0000 x86_64 GNU/Linux

# chromium --version
Chromium 131.0.6778.204 Arch Linux

# gdb --version 
GNU gdb (GDB) 15.2
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

- **Debug Log:**
https://gist.github.com/ariel-anieli/4c185f0d4978b89a7d145099dd0de0f4#file-sway-debug

- **Configuration File:**
https://gist.github.com/ariel-anieli/0189bf7c900b7535e4e1a470ecc3b678

- **Stack Trace:**
https://gist.github.com/ariel-anieli/8fb00f7821c7ee6e54f0baafa2435cf7

- **Description:**
  - Fill a login form in Chromium
  - Send the form
  - The window manager crashes.

**Comment by emersion** [comment] 2024-12-25 16:59
Duplicate of https://github.com/swaywm/sway/issues/8194

**Closed by emersion** 2024-12-25 16:59 UTC
Labels: bug
