### ISSUE TITLE
Monitor Hotplug Issues

### ISSUE THREAD

**Issue by sydneymeyer** [swaywm/sway#3038] opened 2018-10-31 00:15 UTC
I start sway without any external display connected (Displayport via Thunderbolt Dock), connect the dock, internal and external displays are working, disconnect the dock, sway sporadically leaves the internal display (eDP-1) blank and if i re-connect the external display sway crashes reproducibly.

Sway version 1.0-beta.1-110-gd3a62633
wlroots commit 70ca7daeb232ac591a78111fc2cc31093cbbbc3b
Arch Linux Kernel: 4.18.16-arch1-1-ARCH

Two debug logs and traces from two crashes. 
First: internal display becomes blank after disconnect and sway crashes with re-connect. 
Second: internal display recovers after disconnect and sway crashes after re-connect.

[swayconfig.txt](https://github.com/swaywm/sway/files/2532118/swayconfig.txt)
[swaylog.txt](https://github.com/swaywm/sway/files/2532119/swaylog.txt)
[swaylog2.txt](https://github.com/swaywm/sway/files/2532120/swaylog2.txt)
[swaytrace1.txt](https://github.com/swaywm/sway/files/2532121/swaytrace1.txt)
[swaytrace2.txt](https://github.com/swaywm/sway/files/2532122/swaytrace2.txt)

**Comment by Emantor** [comment] 2018-10-31 06:46
Probably a duplicate of Issue one in #3015

**Comment by sydneymeyer** [comment] 2018-10-31 16:21
FWIW, if the internal (eDP-1) display goes blank and, instead of reconnecting the dock, put the laptop in s3-sleep and back, the internal display also recovers from staying blank.

**Comment by progandy** [comment] 2018-11-01 23:43
Does toggling DPMS with ```swaymsg``` fix the blank monitor?

**Comment by sydneymeyer** [comment] 2018-11-01 23:59
Neither dpms nor disable/enable the display recovers the external screen. I just wanted to try this with the internal screen, as i only have tried executing the swaymsg commands blindly but never verified if these commands are actually executed, and just now after disconnecting and reconnecting the laptop to the dock, sway crashed again:

PID: 1222 (sway)
           UID: 1000 (sydney)
           GID: 1000 (sydney)
        Signal: 11 (SEGV)
     Timestamp: Fri 2018-11-02 00:50:08 CET (1min 36s ago)
  Command Line: sway
    Executable: /usr/local/bin/sway
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (sydney)
       Boot ID: 9d1290f55bf845dfbd2ad9e81e405c80
    Machine ID: 7b45b5080431451fa0aef8ea1018df1f
      Hostname: x1
       Storage: /var/lib/systemd/coredump/core.sway.1000.9d1290f55bf845dfbd2ad9e81e405c80.1222.1541116208000000.lz4
       Message: Process 1222 (sway) of user 1000 dumped core.
                
                Stack trace of thread 1222:
                #0  0x000055e25875e6af node_set_dirty (sway)
                #1  0x000055e25873b979 seat_set_raw_focus (sway)
                #2  0x000055e25873bba0 seat_set_focus (sway)
                #3  0x000055e2587399eb input_manager_set_focus (sway)
                #4  0x000055e258761731 view_map (sway)
                #5  0x000055e258738143 handle_map (sway)
                #6  0x00007f55e11e8e39 wlr_signal_emit_safe (libwlroots.so.0)
                #7  0x00007f55e11c89a9 handle_xdg_surface_commit (libwlroots.so.0)
                #8  0x00007f55e11e071a surface_commit_pending (libwlroots.so.0)
                #9  0x00007f55e11e0981 surface_commit (libwlroots.so.0)
                #10 0x00007f55dfe861c8 ffi_call_unix64 (libffi.so.6)
                #11 0x00007f55dfe85c2a ffi_call (libffi.so.6)
                #12 0x00007f55e122a6ff n/a (libwayland-server.so.0)
                #13 0x00007f55e12270a3 n/a (libwayland-server.so.0)
                #14 0x00007f55e1228702 wl_event_loop_dispatch (libwayland-server.so.0)
                #15 0x00007f55e12272ac wl_display_run (libwayland-server.so.0)
                #16 0x000055e25872d9cb server_run (sway)
                #17 0x000055e25872d022 main (sway)
                #18 0x00007f55e0d54223 __libc_start_main (libc.so.6)
                #19 0x000055e258720b1e _start (sway)
                
                Stack trace of thread 1223:
                #0  0x00007f55e0d1cafc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f55dd6251ac n/a (i965_dri.so)
                #2  0x00007f55dd624ee8 n/a (i965_dri.so)
                #3  0x00007f55e0d16a9d start_thread (libpthread.so.0)
                #4  0x00007f55e0e2bb23 __clone (libc.so.6)

I don't have any debug logs for this specific crash.

**Comment by sydneymeyer** [comment] 2018-11-02 00:42
I start sway without the dock connected connect the dock, disconnect, internal screen becomes blank. When i try to open a new terminal, sway crashes reproducibly.

sway version 1.0-beta.1-128-gb1aec1ef
wlroots commit 675cf8457ef3493112def366d7090731172ee872

[sway_backtrace.txt](https://github.com/swaywm/sway/files/2540623/sway_backtrace.txt)
[sway_debuglog.txt](https://github.com/swaywm/sway/files/2540624/sway_debuglog.txt)
[sway_stacktrace.txt](https://github.com/swaywm/sway/files/2540625/sway_stacktrace.txt)

**Comment by sydneymeyer** [comment] 2018-12-27 00:57
FWIW: With Linux 4.20 i haven't been able to reproduce the issue (~6 dis-/re-connects) so far.

Note: I don't know if this is related, but there has been work [1,2] around the PCI Hotplug subsystem for the 4.20 Kernel.

[1] https://lwn.net/Articles/767885/
[2] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=125450f814418b9f889c9885831467d1b2e25a7d

sway version 1.0-beta.2-60-g9bf1b7a0 (Dec 26 2018, branch 'master')
wlroots commit ed5296c6cf23efa07f78e1657cec1528f638f95e
Linux 4.20.0-arch1-1-ARCH from Arch Linux Testing Repository

**Closed** 2019-01-10 01:17 UTC
Labels: bug
