### ISSUE TITLE
blank screen after suspend

### ISSUE THREAD

**Issue by itapai** [swaywm/sway#4378] opened 2019-07-27 06:20 UTC
Hi,

I am trying to make my pc go to sleep after some time.

```
set $lock swaylock -f -c ff0000
exec swayidle -w \
    timeout 10 '$lock' \
    timeout 20 'swaymsg "output * dpms off"' \
        resume 'swaymsg "output * dpms on"' \
    timeout 30 'systemctl suspend' \
    before-sleep '$lock'
```

The suspend part works, but the waking up part is leaving me with a blank screen. I am including the log (sway -d 2>sway.log)
[sway.log](https://github.com/swaywm/sway/files/3437905/sway.log)

Is there another way to put the system to sleep?
I tried setting the time in /etc/systemd/logind.conf 
```
IdleAction=suspend
IdleActionSec=30
```
but all that does is putting the system to sleep, regardless of activity in sway.

Any help/tips appreciated
Cheers

**Comment by emersion** [comment] 2019-07-27 07:57
Duplicate of https://github.com/swaywm/swayidle/issues/4

**Closed by emersion** 2019-07-27 07:57 UTC

**Comment by utx0** [comment] 2021-07-06 07:49
I am getting this same issue on an up to date archlinux system. Read the dup post and this seams like a totally different issue. When my system comes out of suspend I just get a blank screen??

**Comment by fluix-dev** [comment] 2021-07-07 18:16
You should open a new issue and include the relevant info (config, debug logs).

**Comment by guttermonk** [comment] 2024-07-10 02:23
I agree with @utx0 that there was no mention of a "blank" screen in the thread marked as duplicate. Did anyone ever open a new issue for this?
