### ISSUE TITLE
Disappearing cursor on single display.

### ISSUE THREAD

**Issue by tom5760** [swaywm/sway#6409] opened 2021-07-28 14:40 UTC
- **Sway Version:** sway version 1.6.1
- **wlroots Version:** 0.14.1
- **Debug Log:** [sway.log](https://gist.githubusercontent.com/tom5760/f8cd987aa66599c4fddd14e407adc709/raw/73dea06ad153bcc5c46ce1523b92d1c4c0c2e409/sway.log)
- **Configuration File:** [config](https://gist.githubusercontent.com/tom5760/f8cd987aa66599c4fddd14e407adc709/raw/73dea06ad153bcc5c46ce1523b92d1c4c0c2e409/config)

I have a Dell XPS laptop with Intel graphics connected to an external monitor via a USB-C docking station (Dell D6000).  Using `swayidle`, I turn off the screens after a while.  Regularly when resuming, after the external monitor wakes up, the cursor disappears from my laptop screen.  It continues to be visible on the external monitor, but not on the laptop screen.  Similar to #3617, the cursor is definitely still there, as I see hover effects, and can click things, etc. on my laptop screen.

Main thing that stood out to me in the logs was the following:
```
00:37:16.262 [ERROR] [wlr] [render/swapchain.c:97] No free output buffer slot
00:37:16.262 [ERROR] [wlr] [types/wlr_output.c:1342] Failed to render cursor buffer
00:37:16.262 [DEBUG] [wlr] [types/wlr_output.c:1403] Falling back to software cursor on output 'eDP-1'
```

This is on Arch Linux, with the current versions of sway and wlroots in the repositories.

This does seem similar to #3617, but this only seems to happen under these circumstances for me.  Please feel free to close if you think this is the same issue.  Let me know if I can give any other information, or test anything out.

**Comment by emersion** [comment] 2021-07-28 14:42
Yup, closing as a duplicate, the root cause is the same.

**Closed by emersion** 2021-07-28 14:42 UTC
Labels: bug
