### ISSUE TITLE
Intellij popup window closes instantly

### ISSUE THREAD

**Issue by makepanic** [swaywm/sway#3913] opened 2019-03-15 18:26 UTC
**version**: sway version 1.0-rc1-179-gd8f74e47 (Mar 14 2019, branch 'master') (built from master via aur package `sway-git`
**debug log**: [gist](https://gist.github.com/makepanic/843197f5dfc2022f1e00973992b5a9c8#file-sway-log)
**configuration**: [gist](https://gist.github.com/makepanic/843197f5dfc2022f1e00973992b5a9c8#file-sway-config)

Issue:

Intellij works fine in general but some windows don't.
They seem to appear for an instance and close again.

Steps to reproduce:

1. start Intellij (or [download the free community edition](https://www.jetbrains.com/idea/download/download-thanks.html?platform=linux&code=IIC))
2. click on [Help] -> [Find Action] or [Navigate] -> [File]

Expected behavior would be a small Intellij window with an input.

**Comment by RedSoxFan** [comment] 2019-03-15 20:19
Duplicate of #3007

**Closed by RedSoxFan** 2019-03-15 20:19 UTC
