### ISSUE TITLE
Firefox tab drag + spawn behavior

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#3677] opened 2019-02-14 02:12 UTC
`sway version 1.0-rc1-54-gcc39bbdf (Feb 13 2019, branch 'master')`

When I drag one tab out of a firefox window with multiple tabs, it fails to spawn a new firefox window with just the one tab that has been dragged out. I think this should work (as it does on i3).

**Comment by emersion** [comment] 2019-02-14 10:01
Firefox on Wayland native or in Xwayland?

**Comment by JonnyMako** [comment] 2019-02-14 11:24
> Firefox on Wayland native or in Xwayland?

on Wayland native

**Comment by emersion** [comment] 2019-02-14 11:32
Does it work in Weston?

**Comment by JonnyMako** [comment] 2019-02-14 13:05
> Does it work in Weston?

It does not work in weston or rootston. So I guess this is a firefox bug?

**Comment by emersion** [comment] 2019-02-14 13:06
Yes. Please report it to bugzilla if there's no bug for this yet.

**Comment by JonnyMako** [comment] 2019-02-14 18:26
https://bugzilla.mozilla.org/show_bug.cgi?id=1527976

**Comment by JonnyMako** [comment] 2019-02-20 16:55
@emersion I looks like something the bug has been fixed on Firefox side and drag and detach now works in Weston. It still does not work on sway and the comment in the mozilla bug suggests this is something to be fixed on Sway side. Can we reopen this issue?

**Comment by emersion** [comment] 2019-02-20 17:17
Can you try https://github.com/swaywm/sway/pull/3700 and https://github.com/swaywm/wlroots/pull/1517?

**Comment by JonnyMako** [comment] 2019-02-20 17:38
> Can you try #3700 and [swaywm/wlroots#1517](https://github.com/swaywm/wlroots/pull/1517)?

Still does not work with those branches.

**Comment by 7415963987456321** [comment] 2019-03-06 19:08
This works fine with firefox-nightly on sway on my end.

**Comment by emersion** [comment] 2019-03-06 22:25
Maybe fixed since you reported the issue?

@JonnyMako, can you try again?

**Comment by RX14** [comment] 2019-03-13 23:33
Dragging tabs even inside the same window is broken for me, firefox-nightly 2019-03-12 on wayland native and sway `1.0-rc1-173-g1bab5a95`

**Comment by emersion** [comment] 2019-03-13 23:40
rc1 is too old.

**Comment by RX14** [comment] 2019-03-14 00:57
@emersion it's not rc1, it's `sway-git` from AUR, it's just the version still shows rc1 and somehow the git hash is nonsense. I just built it again and now it shows

```
$ sway -v
sway version 1.0-rc1-177-gacdb4ed7 (Mar 14 2019, branch 'master')
```

**Comment by JonnyMako** [comment] 2019-03-14 02:31
Dragging to detach a firefox tab is still not working for me. Dragging tabs withing a window is working fine.

**Comment by RX14** [comment] 2019-03-14 10:28
Restarted sway and dragging inside firefox and between firefox windows is working now. This was a sway upgrade, but the previous build was on the 12th, so I suspect it was the restart itself which caused the fix, not the upgrade.

If I can get it to reproduce again, O'll restart sway and report if it fixes it.

**Comment by retiform** [comment] 2019-05-03 19:30
Dragging to detach works in fedora 29; however, can not recombine tabs once done

**Comment by Limero** [comment] 2019-09-08 12:58
It's still not possible to drag a tab to detach with Firefox on Wayland. Moving tabs between windows works as intended though.

I have tested with both Sway 1.2 + Firefox 68.0.2 and with latest master Sway/Wlroots/Firefox Nightly.

Dragging a tab to detach works in Gnome Wayland, so I assume it's not a Firefox issue.

**Comment by RX14** [comment] 2019-09-09 09:15
Firefox tab dragging works "for a few days" until it stops. I presume then, it's a low-probability bug which then stops tab dragging working until sway is restarted. Restarting Firefox doesn't bring back tab dragging, you have to restart sway.

**Comment by rvolosatovs** [comment] 2020-04-16 09:11
Dragging Firefox tabs within the window or dragging a tab to another Firefox window works fine for me, however dragging the tab out of the panel does not spawn a new Firefox window containing the dragged tab like it does in X, it just returns to the panel. Any idea what might be going on here?
`sway version 1.4`
`Mozilla Firefox 75.0`

**Comment by WhyNotHugo** [comment] 2020-04-16 10:03
@rvolosatovs Upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1527976

**Comment by rvolosatovs** [comment] 2020-04-16 10:06
> @rvolosatovs Upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1527976
> Apparently, caused by an upstream GTK bug: https://gitlab.gnome.org/GNOME/gtk/issues/2101

Thanks! I'll subscribe to these instead. Guess this issue can be closed then?

**Comment by emersion** [comment] 2020-04-16 10:11
Yeah, let's close this as a Firefox bug. Feel free to re-open if they fix it on the Firefox side and it still doesn't work.

**Comment by WhyNotHugo** [comment] 2020-04-16 10:11
This was fixed on firefox 77 (the stable channel is still at 75). The upstream issue is closed, and there are reports of it working on sway.

I think it's safe to close this issue.

**Closed by emersion** 2020-04-16 10:11 UTC
Labels: bug

**Comment by frangio** [comment] 2020-05-15 21:42
Hi, this is indeed working on the latest Firefox but only partially, and I think this time it may be on Sway's side.

Dragging a tab out of its place in the tabbar and onto another window will correctly spawn a new window with that tab. But dragging that tab onto an empty Sway workspace does not spawn the new window, it just acts as if it continued dragging.

**Comment by WhyNotHugo** [comment] 2020-05-16 22:06
Can confirm this the above. Hint: you can try this with just one screen by making the window float too.
