### ISSUE TITLE
Drag gaps to resize containers (not just borders)

### ISSUE THREAD

**Issue by haselwarter** [swaywm/sway#6787] opened 2022-01-26 09:06 UTC
I can resize windows by dragging their borders. My borders are thin, but I have gaps between my windows. It would be quite convenient to make the gaps "active" like the borders, i.e. to be able to resize windows by dragging gaps as well as borders. 

This fix would particularly improve sway usability on touch devices (tablets, convertibles) that make it difficult to hit that 1-2 pixel border, but would easily allow grabbing a 10 pixel gap.

(the touch input use-case also rules out the workaround of mouse-resizing by entering resize mode and right-clicking; that's too inconvenient on a tablet)

**Comment by vyivel** [comment] 2022-01-26 09:13
Duplicate of https://github.com/swaywm/sway/issues/6745?

**Comment by haselwarter** [comment] 2022-01-26 09:23
Sorry for the noise. Clearly I need another mug of coffee.

**Closed** 2022-01-26 09:23 UTC
Labels: enhancement
