### ISSUE TITLE
Unexpected layout after closing fullscreen window

### ISSUE THREAD

**Issue by pedrocr** [swaywm/sway#4236] opened 2019-06-09 16:46 UTC
I've upgraded to latest sway and wlroots before submitting:

```
$ swaymsg -t get_version
sway version 1.1-rc1-32-g4d93b96b (Jun  9 2019, branch 'master')
```

I also checked on IRC and the two people that tried reproduced it so it doesn't seem to be specific to my config. Here are the simple steps:

1. Open two terminals in a workspace
2. Make one of the terminals fullscreen
3. While fullscreen open a third terminal
4. Exit the fullscreen terminal

The expected result would be to end up with two terminals side by side each half the width of the screen. The actual result is one terminal that's 1/3 and another that's 2/3. It also doesn't seem specific to terminals, I initially found it happening with two Firefox windows and a terminal.

**Comment by pedrocr** [comment] 2019-06-10 21:14
Debug log reproducing the issue with the default config:

https://gist.github.com/pedrocr/3fbff9b2458862af7b85d589fc2a35a9

**Comment by pedrocr** [comment] 2019-06-16 22:44
Just checked and the same sequence in i3 produces the expected result (two equally sized windows).

**Comment by RedSoxFan** [comment] 2019-06-19 04:11
Duplicate of #3547

**Closed by RedSoxFan** 2019-06-19 04:11 UTC
