### ISSUE TITLE
Keystrokes are passed through to application after reload.

### ISSUE THREAD

**Issue by kflak** [swaywm/sway#4994] opened 2020-02-10 13:16 UTC
When reloading sway, which I have bound to $mod+Shift+c, the Shift-c part is passed through to nvim, resulting in me deleting whichever line I'm currently on in (n)vim. I'm not sure if this is a sway, termite (my terminal emulator), or nvim issue, but I'm guessing sway... 

Sway version 1.4, Arch Linux 5.4.17-rt9-1-rt
termite v15
nvim v0.4.3

Interestingly this doesn't happen on the command line or in f.x. LibreOffice, only in nvim and vim.

**Comment by RedSoxFan** [comment] 2020-02-10 13:17
Duplicate of #4975

**Closed by RedSoxFan** 2020-02-10 13:17 UTC
