### ISSUE TITLE
pop-up menus appear at wrong position if display position is set

### ISSUE THREAD

**Issue by dwma** [swaywm/sway#5596] opened 2020-08-01 23:26 UTC
- **Sway Version:**
   - 1.5

- **Debug Log:**
  - [sway.log](https://gist.github.com/dwma/5a04a114b2e86afee036372289e95b7b)

- **Configuration File:**
  - [config](https://gist.github.com/dwma/7505c9be885936fff02609c63abe63af)

- **Description:**
  - If I set the position for a secondary display in the config file, and the first display is disabled, some pop-up menus appear at an incorrect x axis position.
  - I can reproduce it with pavucontrol and the Gnome file picker.
  - If I left the position for the display unset or enable the first display, the menus appear at the right position.
  - Example [picture](https://0x0.st/ixU_.png) and [video](https://0x0.st/ixUp.mp4).

**Comment by oniGino** [comment] 2020-08-02 05:02
I have this same problem, I keep my laptop display (primary) disabled by default and use an external monitor

I mostly notice it in firefox, I can post  my config if its helpful

**Comment by RedSoxFan** [comment] 2020-08-02 06:11
Duplicate of #3135.
See https://github.com/swaywm/sway/issues/3135#issuecomment-448794177 and https://github.com/swaywm/sway/issues/3135#issuecomment-459217564 for more information

**Closed by RedSoxFan** 2020-08-02 06:11 UTC
Labels: bug
