### ISSUE TITLE
firefox does not grab focus when opening urls externally

### ISSUE THREAD

**Issue by MichaelAquilina** [swaywm/sway#4155] opened 2019-05-14 11:14 UTC
sway version 1.0

When running firefox in wayland mode (`GDK_BACKEND=wayland firefox`), firefox does not grab focus when external links are opened from other applications.

An easy way to reproduce this is:
* open firefox in a terminal: `GDK_BACKEND=wayland firefox`
* go to the terminal again and open a url: `GDK_BACKEND=wayland firefox www.google.com`

Notice how firefo's window does not grab focus. 

This does not happen when running firefox in XWayland mode (i.e. you exclude `GDK_BACKEND=wayland`)

I opened a ticket on firefox first thinking it might be a firefox issue - but I was told to open it here instead. Here is the original ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1551255

Not sure if a debug log is useful in this scenario. Let me know if it is and I'll add one to this ticket.

**Comment by emersion** [comment] 2019-05-14 16:41
There is no way for Wayland applications to request focus. This would need a new Wayland protocol. There are a few proposals for this on the mailing list.

**Comment by mdeff** [comment] 2019-06-03 18:04
I'm facing that issue as well. Probably related, applications would set an urgent flag when requesting focus, and I could jump to them with `bindsym $mod+x [urgent=latest] focus`.

**Comment by siikamiika** [comment] 2021-10-16 12:02
One possible workaround is to make external links open in a new browser window

**Comment by sethidden** [comment] 2021-11-21 19:43
Dupe of https://github.com/swaywm/sway/issues/4830 ?

**Comment by AdamantGarth** [comment] 2022-02-03 14:08
As a crude workaround, you can use a custom http(s) scheme handler that will open links in your browser and then will focus it. For example:

#####  `~/.local/share/applications/http-handler.desktop`

```ini
[Desktop Entry]
Type=Application
Name=Custom HTTP scheme handler
Exec=/home/user/Scripts/http-handler.sh %U
StartupNotify=false
MimeType=x-scheme-handler/http;x-scheme-handler/https;
``` 

##### `~/Scripts/http-handler.sh`

```sh
#!/bin/sh
swaymsg exec chromium "$@" && swaymsg '[title="- Chromium$"] focus'
```

Then just set it as default http/https handler:

```sh
$ xdg-mime default http-handler.desktop x-scheme-handler/http
$ xdg-mime default http-handler.desktop x-scheme-handler/https
```

To check run:

```
$ xdg-mime query default x-scheme-handler/http
http-handler.desktop
$ xdg-mime query default x-scheme-handler/https
http-handler.desktop
```

For some reason I couldn't put the script in `Exec=`, line. Probably some quoting issue, but whatever.

For firefox you'll probably want to replace sway message with `[app_id=firefox] focus`. I use title, because chrome's SSB windows have the same app_id, so sometimes they'll get focused if you use `[app_id=chromium]. Firefox doesn't support SSB windows so you probably can just use app_id.

P.S. I haven't used this with multiple browser windows opened much, so cant say if it'll work fine in all situations.

**Comment by joanbm** [comment] 2022-04-19 23:14
AFAICT think this should be possible with the xdg_activation_v1 protocol which is supported by wlroots & sway.
Recent GTK4 has support for it when using functions like `gtk_window_present`.

However, GTK3 which most apps. currently use, doesn't have it. I found an old branch but it doesn't have the latest changes. This is my attempt to backport the changes from GTK4, hopefully I can clean it up and submit it.
[0001-Backport-xdg_activation_v1-to-GTK-3.24.33.patch.zip](https://github.com/swaywm/sway/files/8516950/0001-Backport-xdg_activation_v1-to-GTK-3.24.33.patch.zip)

I also needed to comment the following line from wlroots to get it to focus: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/dd03d839ab56c3e5d7c607a8d76e58e0b75edb85/types/wlr_xdg_activation_v1.c#L122

And set `focus_on_window_activation` as desired in the sway config.

With this, I can get most applications (e.g. Firefox, LibreOffice, Sublime Text, etc.) to focus their existing instance when launching them (e.g. from a terminal or `xdg-open`).

**Comment by UtkarshVerma** [comment] 2022-06-01 12:33
Can confirm this happens with Brave browser as well.

**Comment by JosefLitos** [comment] 2022-10-16 18:35
is there any application thats sets an urgent flag under wayland? Because mpv doesn't take focus either, not anything else I tried so far.

**Comment by emersion** [comment] 2022-10-16 19:18
We now have the xdg-activation protocol, which is implemented in wlroots and Sway.

Closing this as a missing feature in the client.

**Closed by emersion** 2022-10-16 19:18 UTC
Labels: enhancement

**Comment by joanbm** [comment] 2022-11-28 21:46
To add a bit more detail on what works and what doesn't:

xdg-activation-v1 is supported by GTK4 ≥4.7.1 (4 months old) and GTK3 ≥3.24.35 (6 days old). Note that most applications still use GTK3.

With wlroots ≥0.16.0 and Sway ≥1.8-rc1, the single-instance mode of *some* programs (e.g. [(GNOME) Drawing](https://github.com/maoschanz/drawing), [Transmission](https://transmissionbt.com/)) works out-of-the-box when launching them with `swaymsg exec ...`, this works through the `XDG_ACTIVATION_TOKEN` and `DESKTOP_STARTUP_ID` environment variables.

This won't work if launching those programs directly without `swaymsg exec ...`, also for some reason, it doesn't work at all for some programs such as [Sublime Text](https://www.sublimetext.com/) or [Firefox](https://www.mozilla.org/en/firefox/), and also doesn't work with wlroots =0.15.0 and Sway =1.7.

In all those cases you will get a "Rejecting token commit request: surface doesn't have keyboard focus" on the debug logs. You can bypass it to work either by commenting [this line in wlroots](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/dd03d839ab56c3e5d7c607a8d76e58e0b75edb85/types/wlr_xdg_activation_v1.c#L122) or [this line in GTK](https://gitlab.gnome.org/GNOME/gtk/-/blob/22c95cd1e9182a419df37f10e1a6c9e2156d8bdb/gdk/wayland/gdkwindow-wayland.c#L3865).

I believe (but am not 100% sure) that the right fix is to change the call to `xdg_activation_token_v1_set_surface` in GTK, since instead of passing in `NULL` when we don't have a surface, it is passing the to-be-activated surface instead?

Also, while setting the surface to `NULL` is certainly enough to pass the wlroots check *now*, I'm not sure if GTK can do something else to ensure we get the best chances to get the window activated in the future.
