### ISSUE TITLE
monitor disaplay refresh rates support?!

### ISSUE THREAD

**Issue by sk0x1234** [swaywm/sway#4701] opened 2019-11-04 23:56 UTC
in gnome i see the option to setup 120Hz rate , but in swaymsgs output it only recognises 60hz , am i missing anything??

using dell precision 5540.

**Comment by ascent12** [comment] 2019-11-05 00:12
Can you post both the outputs of `swaymsg -t get_outputs` and https://github.com/ascent12/drm_info ?

**Comment by sk0x1234** [comment] 2019-11-05 00:27
https://github.com/sk0x1234/swaydotfiles/blob/master/drm_info.txt
https://github.com/sk0x1234/swaydotfiles/blob/master/swaymsg-output.txt

**Comment by ascent12** [comment] 2019-11-05 01:31
>├───"max bpc": range [6, 12] = 12

I was reading about this a while ago, and apparently this can have an affect on what modes are listed as being supported, due to bandwidth limitations. We probably need to set this to 8, and make it configurable when we actually support >8 bit color formats. But I'm not certain that is the cause of it.

A PR was just merged that allows you to force setting a custom mode, so on master, you could try `output eDP-1 mode --custom 1920x1080@120Hz` in your config and see if that works.

**Comment by sk0x1234** [comment] 2019-11-05 02:03
i just tested with sway-git from arch , its working for 120Hz.. thanks for the help.

**Comment by emersion** [comment] 2019-11-05 06:55
>I was reading about this a while ago, and apparently this can have an affect on what modes are listed as being supported, due to bandwidth limitations.

But I don't think KMS mutates the list of modes depending on this.

**Closed** 2019-12-27 23:35 UTC

**Comment by cmprmsd** [comment] 2021-12-18 11:24
Hey there,

I'm having the very same issue but using the `--custom` flag did not work for me. It adds the refresh rate, but does not switch to it.

The monitor is the 4k120 on a Dell 7760 with Intel Graphics.

```
swaymsg -t get_outputs                                                                                            

Output eDP-1 'Unknown 0x2892 0x00000000' (focused)                                                                     
  Current mode: 3840x2160 @ 60.022 Hz                                                                                  
  Position: 0,0                                                                                                        
  Scale factor: 2.000000                                                                                               
  Scale filter: nearest                                                                                                
  Subpixel hinting: unknown                                                                                            
  Transform: normal                                                                                                    
  Workspace: 0:                                                                                                     
  Max render time: off                                                                                                 
  Adaptive sync: disabled                                                                                              
  Available modes:                                                                                                     
    3840x2160 @ 60.022 Hz
``` 

The output now is:
```
Output eDP-1 'Unknown 0x2892 0x00000000' (focused)
  Current mode: 3840x2160 @ 119.976 Hz
  Position: 0,0
  Scale factor: 2.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 0:     
  Max render time: off
  Adaptive sync: disabled
 Available modes:
    3840x2160 @ 119.976 Hz
    3840x2160 @ 60.022 Hz
```
But it does immediately switch back to 60Hz according to wdisplays and glxgears which is stuck at 60fps.

I tested the monitor with Windows which does allow 4k120 on the integrated GPU. :man_shrugging: 

Shall I open a new issue?
