### ISSUE TITLE
[request feature] titlebar background color

### ISSUE THREAD

**Issue by AdrienLemaire** [swaywm/sway#4977] opened 2020-02-05 02:49 UTC
I don't show titlebars by default on my containers, but when I do (stacked, tabbed), I'd like to be able to use a color code to quickly find the tab I'm interested in.
afaik, Qubes is another OS using color codes on its titlebars, but it's quite opiniated. 

At the moment, I use text prefixes with `swaymsg [con_id=$cid] title_format '[prefix] %title'` (refer #4972). I'd rather not set a prefix but change the background color instead.

When reading man 5 sway, all related commands I can find are:

```
       titlebar_border_thickness <thickness>
       titlebar_padding <horizontal> [<vertical>]
       title_format <format>
       title_align left|center|right
       client.<class> <border> <background> <text> [<indicator> [<child_border>]]
```

Can we have a `titlebar_background` command, that would take priority over `client.<class> background`?

Or can we be allowed to use marks as custom client classes? `client.redMark #f00 #f00 ...` would color the titlebar background to red with `swaymsg -- mark --toggle redMark`.

**Comment by RedSoxFan** [comment] 2020-02-11 00:57
Duplicate of #3177

**Closed by RedSoxFan** 2020-02-11 00:57 UTC

**Comment by dyapan33** [comment] 2025-03-16 16:58
idk how to fix this so shut up.
