### ISSUE TITLE
Sway crashes upon launch of xwayland application

### ISSUE THREAD

**Issue by keleset** [swaywm/sway#6032] opened 2021-02-15 19:50 UTC
Sway version: sway version 1.5.1-f0f6c6ba56

Log:
https://pastebin.com/qSvEywmW

I'm trying to use [libudev-zero](https://github.com/illiliti/libudev-zero) (the issue is not present if I switch to eudev).

Everything that uses wayland works perfectly fine.
As soon as I open any app using x11 (xwayland) - sway crashes.

Here is sway -V -d output.
https://pastebin.com/g2bmmQmc
I launch alacritty and then mpv --gpu-context=x11egl afile.mkv

Setup - Alpine on laptop with integrated and dedicated AMD graphics.
I was unable to detect anything unusual while using gdb with sway, but I'm willing to use gdb again if you tell me how and what should I use it with.

I understand that libudev-zero probably not supposed to run flawlessly with such complex software as sway/wlroots, BUT

- it runs *flawlessly* while only using wayland apps (thank you and libudev-zero devs for that)
- x11-using app connecting to xwayland server and encountering problem probably should not cause whole UI burn up to TTY?

So, I hoped someone could give me (and libudev-zero maintainer) an insight about what should be fixed.

**Comment by Xyene** [comment] 2021-02-15 22:04
Please provide a stack trace. You can do so by compiling from source, reproducing the crash and then running `coredumpctl gdb` and then `bt full`.

Here are some instructions to compile from source: https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by keleset** [comment] 2021-02-16 14:09
@Xyene I'm unable to compile wlroots
`/lib/libelogind.so: undefined reference to `gettid'`
 
doesn't matter if I do `-Dlogind=disabled` or `-Delogind=enabled -Dlogind-provider=elogind`

**Comment by Emantor** [comment] 2021-02-16 15:29
Hm, according to the [musl release notes](http://musl.libc.org/releases.html), `gettid` should be included within the latest alpine [3.13.1 release](https://alpinelinux.org/posts/Alpine-3.13.1-released.html).

**Comment by keleset** [comment] 2021-02-16 16:45
I've manage to build everything after upgrading building environment.
I'm unable to reproduce the issue on master.
Should I just wait for 1.6 or should I try to deduce which commit fixes the issue?

**Comment by Xyene** [comment] 2021-02-16 17:07
Good to hear it's fixed on master. There's no need to find which commit fixed things; there have been a lot of bugfixes all over since 1.5.1. See https://github.com/swaywm/sway/issues/5970 for the rough status of the next release. There's not too much left, but there's also no hard timeline.

**Closed by Xyene** 2021-02-16 17:07 UTC
Labels: bug, waiting-on-reporter
