### ISSUE TITLE
Framework 16 - Output - Unknown make, model and serial

### ISSUE THREAD

**Issue by BCurrell** [swaywm/sway#8203] opened 2024-06-10 19:01 UTC
### Please read the following before submitting:
- Please do NOT submit bug reports for questions. Ask questions on IRC at #sway on Libera Chat.
- Proprietary graphics drivers, including nvidia, are not supported. Please use the open source equivalents, such as nouveau, if you would like to use Sway.
- Please do NOT submit issues for information from the github wiki. The github wiki is community maintained and therefore may contain outdated information, scripts that don't work or obsolete workarounds.
  If you fix a script or find outdated information, don't hesitate to adjust the wiki page.

### Please fill out the following:
- **Sway Version:**
  - sway version 1.9

- **Debug Log:**
  - https://gist.github.com/BCurrell/09351850f9f168ca3fcebcc78ff08784

- **Configuration File:**
  - N/A

- **Stack Trace:**
  - N/A

- **Description:**
  - Framework 16 laptop
  - Looking for output make, model and serial to configure a custom output config for my dotfiles
  - Output make, model and serial are "Unknown"
  - Based on a quick look at Sway and wlroots source code, I assume this is either because the Framework hardware is new and wlroots doesn't know about it, or somehow wlroots is unable to read the serial number for the hardware configuration. However I'm not great with C, so I'm not sure how to run this down.

**Comment by BCurrell** [comment] 2024-06-10 19:04
I've updated my Gist to include the output from `swaymsg -r -t get_outputs` as a separate JSON file.

**Comment by emersion** [comment] 2024-06-10 19:31
Can you upload the contents of `/sys/class/drm/cardN-XXX/edid`, replacing N and XXX with your GPU number and output name?

**Comment by BCurrell** [comment] 2024-06-10 20:05
```none
bcurrell@framework ~ $ cat /sys/class/drm/card0-eDP-1/edid
	�
         0 "x=5PC%PT4p@`0
                          Y�BOE CQ
      NE160QDM-NZ6

p y"
	/?>%	

<r<jBjB/
j       !w
@�=$Q�5T\\�x&	bcurrell@framework ~ $
```

**Comment by emersion** [comment] 2024-06-10 20:15
Please upload this file as an attachment. It contains binary data.

**Comment by BCurrell** [comment] 2024-06-10 20:59
[card0-eDP-1_edid.gz](https://github.com/user-attachments/files/15779038/card0-eDP-1_edid.gz)

Yeah, thought that was the case. There's a limit on filetypes so I've gzipped it. Feel free to suggest an alternative file host if you need the uncompressed file.

**Comment by emersion** [comment] 2024-06-10 22:45
Actually, this is a duplicate of https://gitlab.freedesktop.org/emersion/libdisplay-info/-/issues/42

**Closed by emersion** 2024-06-10 22:45 UTC
Labels: bug
