### ISSUE TITLE
sway sometimes crashes when reloading config / changing outputs

### ISSUE THREAD

**Issue by eaceaser** [swaywm/sway#3739] opened 2019-02-21 00:24 UTC
sway version 1.0-rc3 (Feb 20 2019, branch 'makepkg')
log: https://tehasdf.com/sway-20180220.log
coredump: https://tehasdf.com/sway-20180220.dmp

Stack Trace:

```
#0  0x000055d2b8967cb5 in output_render (output=0x55d2ba9e7950, when=0x7ffc20524f50, damage=0x7ffc20524f60) at ../sway/sway/desktop/render.c:1006
        clear_color = {0, 0, 0, 1}
        nrects = 1
        rects = 0x7ffc20524f60
        wlr_output = 0x55d2ba95f870
        renderer = 0x55d2ba8d8d50
        __PRETTY_FUNCTION__ = "output_render"
        workspace = 0x55d2bac74720
        fullscreen_con = 0x21
        seat = 0x55d2b8964980 <send_presented_iterator>
        focus = 0x83f795ca031d8400
        width = 542265120
        height = 1
        transform = 32764
#1  0x000055d2b89640fd in damage_handle_frame (listener=0x55d2ba9e7ae0, data=0x55d2ba9e7b30) at ../sway/sway/desktop/output.c:386
        output = 0x55d2ba9e7950
        now = {tv_sec = 804, tv_nsec = 641448686}
        needs_swap = true
        damage = {extents = {x1 = 0, y1 = 0, x2 = 1920, y2 = 1080}, data = 0x0}
#2  0x00007f3dd426fa9e in wlr_signal_emit_safe (signal=0x55d2ba9e7b90, data=0x55d2ba9e7b30) at ../util/signal.c:29
        pos = 0x55d2ba9e7ae0
        l = 0x55d2ba9e7ae0
        cursor = {link = {prev = 0x55d2ba9e7ae0, next = 0x7ffc20524fb0}, notify = 0x7f3dd426fa10 <handle_noop>}
        end = {link = {prev = 0x7ffc20524f90, next = 0x55d2ba9e7b90}, notify = 0x7f3dd426fa10 <handle_noop>}
#3  0x00007f3dd426fa9e in wlr_signal_emit_safe (signal=signal@entry=0x55d2ba95f990, data=data@entry=0x55d2ba95f870) at ../util/signal.c:29
        pos = 0x55d2ba9e7c28
        l = 0x55d2ba9e7c28
        cursor = {link = {prev = 0x55d2ba9e7c28, next = 0x7ffc20525020}, notify = 0x7f3dd426fa10 <handle_noop>}
        end = {link = {prev = 0x7ffc20525000, next = 0x55d2ba95f990}, notify = 0x7f3dd426fa10 <handle_noop>}
#4  0x00007f3dd4262bd7 in wlr_output_send_frame (output=output@entry=0x55d2ba95f870) at ../types/wlr_output.c:437
#5  0x00007f3dd42327ef in page_flip_handler (fd=<optimized out>, seq=10852, tv_sec=804, tv_usec=447055, data=0x55d2ba95f870) at ../backend/drm/drm.c:1327
        conn = 0x55d2ba95f870
        drm = 0x55d2ba75acd0
        present_time = {tv_sec = 804, tv_nsec = 447055000}
        present_event = {output = 0x55d2ba95f870, when = 0x7ffc20525070, seq = 10852, refresh = 16685020, flags = 7}
#6  0x00007f3dd2fb6725 in drmHandleEvent () at /usr/lib/libdrm.so.2
#7  0x00007f3dd4235bf6 in handle_drm_event (fd=<optimized out>, mask=<optimized out>, data=<optimized out>) at ../backend/drm/drm.c:1337
        event = {version = 2, vblank_handler = 0x0, page_flip_handler = 0x7f3dd42326d0 <page_flip_handler>, page_flip_handler2 = 0x0, sequence_handler = 0x0}
#8  0x00007f3dd42b2702 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#9  0x00007f3dd42b12ac in wl_display_run () at /usr/lib/libwayland-server.so.0
#10 0x000055d2b8960ffb in server_run (server=0x55d2b89c1d40 <server>) at ../sway/sway/server.c:212
#11 0x000055d2b8960544 in main (argc=2, argv=0x7ffc205258d8) at ../sway/sway/main.c:403
        verbose = 0
        debug = 1
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x55d2b89a8e44 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55d2b89a8e49 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55d2b89a8e50 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55d2b89a8e59 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55d2b89a8e5f "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55d2b89a8e67 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55d2b89a8e6f "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55d2b89a8e7e "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55d2b89a8e8e "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55d2b89a8928 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```

When reloading the sway config, or when switching outputs, sway sometimes segfaults. I haven't tracked down the exact scenario that causes it -- sometimes only X11 apps crash, and sometimes everything works fine.

**Comment by RedSoxFan** [comment] 2019-02-21 00:29
Duplicate of #3658

Thanks for the additional debug log

**Closed by RedSoxFan** 2019-02-21 00:29 UTC
