### ISSUE TITLE
sway uses VR headset as monitor

### ISSUE THREAD

**Issue by yaomtc** [swaywm/sway#6016] opened 2021-02-12 00:46 UTC
### Please fill out the following:
- **Sway Version:**
1.5-b1b10415 (Feb 12 2021, branch 'master')

- **Debug Log:**
https://gist.github.com/yaomtc/0e04e24539e18d023f9ffd595ce34eb7

- **Configuration File:**
[Default config file](https://gist.github.com/yaomtc/7326300ad8f0bb4030984f2e93cf0e98)

- **Description:**
With a Valve Index headset connected, I start sway from either SDDM or from tty2. Either way, the headset lights up and I can see the desktop on it, distorted. An HMD should not be treated as a monitor.

  Examples:
  - [Plasma fix (not yet in stable)](https://invent.kde.org/plasma/kwin/-/merge_requests/378)
  - SDDM ignores the HMD
  - [GDM does not ignore the HMD](https://gitlab.gnome.org/GNOME/gdm/-/issues/500) 

I believe this issue depends on: https://github.com/swaywm/sway/pull/4289

**Comment by emersion** [comment] 2021-02-12 01:42
Duplicate of https://github.com/swaywm/wlroots/issues/1445

**Closed by emersion** 2021-02-12 01:42 UTC
Labels: bug
