### ISSUE TITLE
Proposal: Add save and load input config commands

### ISSUE THREAD

**Issue by Geo25rey** [swaywm/sway#5631] opened 2020-08-18 19:53 UTC
## Motivation
There are a few issues which are caused by the reseting of the input config on TTY switches (#5527, #5456). I have made a systemd service to monitor which TTY is currently active (see [gist](https://gist.github.com/Geo25rey/1583a51e41db2929099feb2f18f83570)). This monitoring requires root privledges, so I don't think it should be added to sway directly. Maybe under `contrib`? With the addition of commands to save, load, and reset input configs at runtime, the before mentioned issues can be solved using an IPC client.

### Save input config
`input <identifier> save-config [name-of-save]`
`[name-of-save]` is an optionally parameter

### Load input config
`input <identifier> load-config [name-of-save]`
`[name-of-save]` is an optionally parameter

### Save input config
Copies the current input config of the identified input device into a new input config, which gets pushed onto a stack with the optional save's name. Each input device has its own stack to avoid loading an invalid input config from another input device. 

### Load input config
If a saved name is passed in as an arguement, the name is searched for in the stack. If the saved name is not in the stack or a saved name isn't passed in as an arguement, then use the top of the stack as the input config to copy to the identified input device. Then, remove the loaded config from the stack.

## Implementation Details
The stack could be implemented as an array with a pointer to the current top and bottom.

Pros:
- Fast
- Easy to get input configs in the middle of the stack

Cons:
- Hard to remove input configs in the middle of the stack

The stack could be implemented as a singlely linked list.

Pros:
- Easy to remove input configs in the middle of the stack
- Each node is independent of the others
- One pointer to the top

Cons:
- More memory allocations and usage
- Slow when traversing to find a named input config

**Comment by RedSoxFan** [comment] 2020-08-18 19:58
I'll expand upon this comment after work, but just as a quick note: the issue is with the xkb state being lost, not the input configs. The input configs are already stored.

**Comment by Geo25rey** [comment] 2020-08-18 20:14
@RedSoxFan Aren't the xkb state and the input config dependant on each other?

**Comment by Geo25rey** [comment] 2020-08-18 21:13
From what I can tell, saving the input_config struct and, for keyboards, running `sway_keyboard_configure` from sway/input/keyboard.c is enough, or, more generally, a Sway reload.

**Comment by RedSoxFan** [comment] 2020-08-18 22:06
> @RedSoxFan Aren't the xkb state and the input config dependant on each other?

No, the xkb_state includes the state of every key, modifiers, and what the effective layout is. None of this information is currently stored in the input config.

> From what I can tell, saving the input_config struct and, for keyboards, running sway_keyboard_configure from sway/input/keyboard.c is enough, or, more generally, a Sway reload.

This is how the code works right now. However, this is not the same thing as a Sway reload. A Sway reload resets ALL settings, outputs, inputs, etc to what they are in the config or their respective defaults.

> There are a few issues which are caused by the reseting of the input config on TTY switches (#5527, #5456)

As mentioned above, the issue is the xkb_state losing information, not the input config. For #5527, the information that is lost from the xkb_state is the locked modifiers. For #5456, it is the group (effective layout).

The issue with storing the xkb_state is that it is unlikely that the state will be the same when switching back from TTY. For example, if you switched to TTY2, then you have likely pressed Control+Alt+F2. When switching back from TTY2, it's extremely unlikely that F2 is still being pressed. This would result in the key appearing to be pressed when it actually is not until you press and release the key again.

For both issues, we would have to only store and restore the information needed. This would also apply to suspend/resume and manual unplug/replug since the cause/reason is not currently available. It may be desirable for the former case, but the latter is possibly a matter of opinion.

_I'm going to close this issue since there is nothing actionable here. There are already issues for the two cases._

**Closed by RedSoxFan** 2020-08-18 22:06 UTC
Labels: enhancement
