### ISSUE TITLE
Pixelated text in OpenStreetMap Java application (josm.jar)

### ISSUE THREAD

**Issue by alanorth** [swaywm/sway#5004] opened 2020-02-11 19:15 UTC
The Java-based OpenStreetMap editor ([josm.jar](https://josm.openstreetmap.de/)) has pixelated text when run under Sway on Arch Linux. For what it's worth, it looks fine under GNOME Mutter Wayland, though it appears to be using Xwayland. Output is 2560x1440 at scale 2.

![20200211_18h54m59s_grim-fs8](https://user-images.githubusercontent.com/191754/74269875-e67e2c00-4d12-11ea-83cd-0c23582e2dc2.png)

* Sway Version: 1.4
* Debug Log: [swag.log](https://gist.github.com/alanorth/a11bb9737a9be45247e2c225f627b3a5)

**Comment by emersion** [comment] 2020-02-11 21:32
Duplicate of https://github.com/swaywm/sway/issues/2966

**Closed by emersion** 2020-02-11 21:32 UTC

**Comment by georgek** [comment] 2020-05-31 20:08
I'm not sure it's a duplicate of that one. My solution to this is to set the following environment variable: `_JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on"`
