### ISSUE TITLE
Render wlr-layer-shell background layer for fullscreen applications

### ISSUE THREAD

**Issue by coderkalyan** [swaywm/sway#5345] opened 2020-05-15 03:57 UTC
I use a semi-transparent background on my terminal emulator (so I can see the sway background behind the terminal) but when I go fullscreen, the background layer isn't drawn.
(Ignore the screen/wallpaper to the left, that's my second monitor.)
![swaybg_1](https://user-images.githubusercontent.com/35181624/82009882-5e673580-9625-11ea-93ea-902186878f71.png)
![swaybg_2](https://user-images.githubusercontent.com/35181624/82009877-59a28180-9625-11ea-96a1-334ca4093fe4.png)

**Comment by RedSoxFan** [comment] 2020-05-15 04:05
Duplicate of #4040

**Closed by RedSoxFan** 2020-05-15 04:05 UTC
