### ISSUE TITLE
Null dereference in xdg_pointer_grab_enter

### ISSUE THREAD

**Issue by kchibisov** [swaywm/sway#5380] opened 2020-05-24 11:50 UTC
I don't have debug log, but backtrace is pretty clear on what happened and where. I can't repro this issue and it just randomly happened. As you can see, there's a null dereference, In theory it could be just checked before doing so, but I guess there could be an invariant, that it can't be null and so there's no check for it in this function.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  xdg_pointer_grab_enter (grab=0x559e5069e568, surface=0x0, sx=0, sy=0) at ../wlroots-9999/types/xdg_shell/wlr_xdg_popup.c:21
21		if (wl_resource_get_client(surface->resource) == popup_grab->client) {
[Current thread is 1 (Thread 0x7fe535f359c0 (LWP 773))]
(gdb) bt full
#0  xdg_pointer_grab_enter (grab=0x559e5069e568, surface=0x0, sx=0, sy=0) at ../wlroots-9999/types/xdg_shell/wlr_xdg_popup.c:21
        popup_grab = 0x559e5069e560
#1  0x0000559e4f54b7a9 in handle_pointer_motion (seat=0x559e505cf810, time_msec=65939824, dx=<optimized out>, dy=<optimized out>)
    at ../sway-9999/sway/input/seatop_default.c:463
        e = 0x559e50632800
        cursor = 0x559e505cfe30
        surface = 0x0
        sx = 4.4188315037342989e+260
        sy = 4.6510569881443009e-310
        node = 0x559e50d7e6e0
        drag_icon = <optimized out>
#2  0x0000559e4f543c6b in pointer_motion
    (cursor=0x559e505cfe30, time_msec=65939824, device=0x559e5079e9b0, dx=0, dy=-14, dx_unaccel=<optimized out>, dy_unaccel=<optimized out>)
    at ../sway-9999/sway/input/cursor.c:327
#3  0x0000559e4f543e3e in handle_pointer_motion_relative (listener=<optimized out>, data=<optimized out>) at ../sway-9999/sway/input/cursor.c:335
        cursor = <optimized out>
        e = <optimized out>
#4  0x00007fe536aeff1c in wlr_signal_emit_safe (signal=<optimized out>, data=0x7ffd7ae88460) at ../wlroots-9999/util/signal.c:29
        pos = 0x559e505cff60
        l = 0x559e505cff60
        cursor = {link = {prev = 0x559e505cff60, next = 0x7ffd7ae883a0}, notify = 0x7fe536aefe90 <handle_noop>}
        end = {link = {prev = 0x7ffd7ae88380, next = 0x559e505d0118}, notify = 0x7fe536aefe90 <handle_noop>}
#5  0x00007fe536aeff1c in wlr_signal_emit_safe (signal=<optimized out>, data=data@entry=0x7ffd7ae88460) at ../wlroots-9999/util/signal.c:29
        pos = 0x559e50eb1620
        l = 0x559e50eb1620
        cursor = {link = {prev = 0x559e50eb1620, next = 0x7ffd7ae88410}, notify = 0x7fe536aefe90 <handle_noop>}
        end = {link = {prev = 0x7ffd7ae883f0, next = 0x559e50c95748}, notify = 0x7fe536aefe90 <handle_noop>}
#6  0x00007fe536abbe53 in handle_pointer_motion (event=<optimized out>, libinput_dev=<optimized out>) at ../wlroots-9999/backend/libinput/pointer.c:41
        wlr_dev = 0x559e5079e9b0
        pevent = 0x559e507675c0
        wlr_event = {device = 0x559e5079e9b0, time_msec = 65939824, delta_x = 0, delta_y = -14, unaccel_dx = 0, unaccel_dy = -7}
#7  0x00007fe536abac8b in handle_libinput_readable (fd=<optimized out>, mask=<optimized out>, _backend=0x559e4ff14000) at ../wlroots-9999/backend/libinput/backend.c:41
        backend = 0x559e4ff14000
        event = 0x559e507675c0
#8  0x00007fe536b33432 in wl_event_loop_dispatch (loop=0x559e4ff07570, timeout=timeout@entry=-1)
    at /usr/src/debug/dev-libs/wayland-1.18.0/wayland-1.18.0/src/event-loop.c:1027
        ep =
              {{events = 1, data = {ptr = 0x559e5077e340, fd = 1350034240, u32 = 1350034240, u64 = 94138443227968}}, {events = 1, data = {ptr = 0x559e4ff075b8, fd = 1341158840, u32 = 1341158840, u64 = 94138434352568}}, {events = 1724981248, data = {ptr = 0x559e760cbd58, fd = 1980546392, u32 = 1980546392, u64 = 94139073740120}}, {events = 1, data = {ptr = 0x559e50f07170, fd = 1357934960, u32 = 1357934960, u64 = 94138451128688}}, {events = 2062058912, data = {ptr = 0x1c00007ffd, fd = 32765, u32 = 32765, u64 = 120259117053}}, {events = 0, data = {ptr = 0x559e50f0a188, fd = 1357947272, u32 = 1357947272, u64 = 94138451141000}}, {events = 1357939064, data = {ptr = 0x7ae885e00000559e, fd = 21918, u32 = 21918, u64 = 8856475864343270814}}, {events = 32765, data = {ptr = 0x7fe536b33a8f <wl_connection_flush+367>, fd = 917715599, u32 = 917715599, u64 = 140622441953935}}, {events = 1, data = {ptr = 0x1c50e69b80, fd = 1357290368, u32 = 1357290368, u64 = 121616374656}}, {events = 0, data = {ptr = 0x7ffd7ae88600, fd = 2062059008, u32 = 2062059008, u64 = 140726665512448}}, {events = 0, data = {ptr = 0x1d35c, fd = 119644, u32 = 119644, u64 = 119644}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 2062058976, data = {ptr = 0x100007ffd, fd = 32765, u32 = 32765, u64 = 4295000061}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x559e50c9c448, fd = 1355400264, u32 = 1355400264, u64 = 94138448593992}}, {events = 1357939924, data = {ptr = 0x1c0000559e, fd = 21918, u32 = 21918, u64 = 120259106206}}, {events = 0, data = {ptr = 0x559e50f08178, fd = 1357939064, u32 = 1357939064, u64 = 94138451132792}}, {events = 12, data = {ptr = 0x1400000000, fd = 0, u32 = 0, u64 = 85899345920}}, {events = 0, data = {ptr = 0x100000001, fd = 1, u32 = 1, u64 = 4294967297}}, {events = 91, data = {ptr = 0x7b00000064, fd = 100, u32 = 100, u64 = 528280977508}}, {events = 138, data = {ptr = 0xa800000099, fd = 153, u32 = 153, u64 = 721554505881}}, {events = 145, data = {ptr = 0xa000000092, fd = 146, u32 = 146, u64 = 687194767506}}, {events = 161, data = {ptr = 0xb0000000af, fd = 175, u32 = 175, u64 = 755914244271}}, {events = 1348266841, data = {ptr = 0x70000559e, fd = 21918, u32 = 21918, u64 = 30064792990}}, {events = 0, data = {ptr = 0x559e505cf810, fd = 1348270096, u32 = 1348270096, u64 = 94138441463824}}, {events = 1355386096, data = {ptr = 0x5077e3400000559e, fd = 21918, u32 = 21918, u64 = 5798352909280236958}}, {events = 21918, data = {ptr = 0x66d12000, fd = 1724981248, u32 = 1724981248, u64 = 1724981248}}, {events = 1341210624, data = {ptr = 0x66d120000000559e, fd = 21918, u32 = 21918, u64 = 7408738046373287326}}, {events = 1980546392, data = {ptr = 0xa, fd = 10, u32 = 10, u64 = 10}}, {events = 1724981248, data = {ptr = 0x50891e20760cbd58, fd = 1980546392, u32 = 1980546392, u64 = 5803202719611927896}}, {events = 21918, data = {ptr = 0x559e4ff07828, fd = 1341159464, u32 = 1341159464, u64 = 94138434353192}}}
        source = <optimized out>
        i = <optimized out>
        count = <optimized out>
        has_timers = <optimized out>
#9  0x00007fe536b31a05 in wl_display_run (display=0x559e4ff07800) at /usr/src/debug/dev-libs/wayland-1.18.0/wayland-1.18.0/src/wayland-server.c:1351
#10 0x0000559e4f52e71c in main (argc=1, argv=0x7ffd7ae88868) at ../sway-9999/sway/main.c:409
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options =
            {{name = 0x559e4f57636b "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x559e4f579b09 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x559e4f576370 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x559e4f576379 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x559e4f5762cf "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x559e4f5753be "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x559e4f57637f "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x559e4f57638e "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x559e4f57639e "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x559e4f576710 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
(gdb)

```

version:  sway version 1.4-848a6fdb (May 23 2020, branch 'HEAD')

**Comment by Xyene** [comment] 2020-05-24 17:08
This is a duplicate of https://github.com/swaywm/sway/issues/5294, and there are currently open PRs https://github.com/swaywm/sway/pull/5368 and https://github.com/swaywm/wlroots/pull/2217 for addressing it. (As you state, the simple fix is to add a null check, but in https://github.com/swaywm/wlroots/pull/2162#issuecomment-625083795 it was discussed that actually preserving that invariant would be better.)

**Closed by Xyene** 2020-05-24 17:08 UTC
