### ISSUE TITLE
Crash when starting ardour

### ISSUE THREAD

**Issue by J0nnyMak0** [swaywm/sway#7725] opened 2023-08-28 19:38 UTC
With the latest sources, I'm getting a Sway crash when I start Ardour:
```
#0  0x00007f820f5d6f5f in wl_list_remove (elm=0x561ea6b42c30) at ../wayland-1.22.0/src/wayland-util.c:56
#1  0x00007f820fd1b3cb in xwayland_surface_dissociate (xsurface=0x561ea6b42ba0) at ../subprojects/wlroots/xwayland/xwm.c:401
#2  0x00007f820fd1d216 in xwm_handle_unmap_notify (xwm=0x561ea6b6b470, ev=0x561ea670d850) at ../subprojects/wlroots/xwayland/xwm.c:1129
        xsurface = 0x561ea6b42ba0
#3  0x00007f820fd1e72e in x11_event_handler (fd=187, mask=1, data=0x561ea6b6b470) at ../subprojects/wlroots/xwayland/xwm.c:1672
        count = 10
        event = 0x561ea670d850
        xwm = 0x561ea6b6b470
#4  0x00007f820f5d8ae2 in wl_event_loop_dispatch (loop=0x561ea5ba7110, timeout=timeout@entry=-1) at ../wayland-1.22.0/src/event-loop.c:1027
        ep = {{events = 1, data = {ptr = 0x561ea60a2720, fd = -1509284064, u32 = 2785683232, u64 = 94689634690848}}, {events = 1, data = {ptr = 0x561ea677d620, fd = -1502095840, u32 = 2792871456, u64 = 94689641879072}}, {events = 1685608192, data = {ptr = 0x561e6588439f, fd = 1703429023, u32 = 1703429023, u64 = 94688552436639}}, {events = 1, data = {ptr = 0x14, fd = 20, u32 = 20, u64 = 20}}, {events = 2797065456, data = {ptr = 0x39d74da00000561e, fd = 22046, u32 = 22046, u64 = 4167885329744811550}}, {events = 32766, data = {ptr = 0x561ea6b80508, fd = -1497889528, u32 = 2797077768, u64 = 94689646085384}}, {events = 2797069560, data = {ptr = 0x39d74de00000561e, fd = 22046, u32 = 22046, u64 = 4167885604622718494}}, {events = 32766, data = {ptr = 0x7f820f5d5500 <wl_connection_flush+304>, fd = 257774848, u32 = 257774848, u64 = 140196580250880}}, {events = 572798756, data = {ptr = 0x14243724bf, fd = 607593663, u32 = 607593663, u64 = 86506939583}}, {events = 0, data = {ptr = 0x7ffe39d74e00, fd = 970411520, u32 = 970411520, u64 = 140729868832256}}, {events = 539762214, data = {ptr = 0x1d44, fd = 7492, u32 = 7492, u64 = 7492}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x4141414141414141, fd = 1094795585, u32 = 1094795585, u64 = 4702111234474983745}}, {events = 2797072956, data = {ptr = 0x140000561e, fd = 22046, u32 = 22046, u64 = 85899367966}}, {events = 0, data = {ptr = 0x561ea6b7e4f8, fd = -1497897736, u32 = 2797069560, u64 = 94689646077176}}, {events = 412, data = {ptr = 0x1400000000, fd = 0, u32 = 0, u64 = 85899345920}}, {events = 0, data = {ptr = 0x100000001, fd = 1, u32 = 1, u64 = 4294967297}}, {events = 192, data = {ptr = 0x1a1a1a1a000000c1, fd = 193, u32 = 193, u64 = 1880844493352075457}}, {events = 437918234, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 538976288, data = {ptr = 0x2020202020202020, fd = 538976288, u32 = 538976288, u64 = 2314885530818453536}}, {events = 538976288, data = {ptr = 0x2020202020202020, fd = 538976288, u32 = 538976288, u64 = 2314885530818453536}}, {events = 538976288, data = {ptr = 0x20202020, fd = 538976288, u32 = 538976288, u64 = 538976288}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 1685608192, data = {ptr = 0x6588439f, fd = 1703429023, u32 = 1703429023, u64 = 1703429023}}, {events = 0, data = {ptr = 0x561ea6b7c8d0, fd = -1497904944, u32 = 2797062352, u64 = 94689646069968}}}
        source = <optimized out>
        i = 0
        count = <optimized out>
        has_timers = <optimized out>
#5  0x00007f820f5d92d7 in wl_display_run (display=0x561ea5ba7020) at ../wayland-1.22.0/src/wayland-server.c:1493
#6  0x0000561ea50fcca8 in server_run (server=0x561ea5182b80 <server>) at ../sway/server.c:359
#7  0x0000561ea50fbb9c in main (argc=2, argv=0x7ffe39d75078) at ../sway/main.c:415
        verbose = false
        debug = true
        validate = false
        allow_unsupported_gpu = false
        config_path = 0x0
        c = -1
```

Not sure if this is the same crash I've been encountering [here.](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3547#note_1694701) At any rate, I can reliably reproduce this crash.

Log is also attached.
[sway.log](https://github.com/swaywm/sway/files/12457708/sway.log)

**Comment by J0nnyMak0** [comment] 2024-01-01 18:34
FWIW, I've seen aroudour crash with vulkan since updating to 8.1.

**Comment by Xiretza** [comment] 2024-03-04 20:40
Happens to me on 1.9 when launching [Bombe Demo](https://store.steampowered.com/app/2262930/Bombe/) from steam. Stacktrace is pretty much the same, with a couple more intermediate frames:

```
#0  0x0000709c89fc0f5f in wl_list_remove (elm=elm@entry=0x58042e7251e8) at ../wayland-1.22.0/src/wayland-util.c:56
#1  0x000058042caf0752 in handle_dissociate (listener=0x58042e7251d0, data=<optimized out>)
    at ../sway-1.9/sway/desktop/xwayland.c:780
        xwayland_view = 0x58042e724f00
#2  0x0000709c89fc101e in wl_signal_emit_mutable (signal=signal@entry=0x58042e78b2c0, data=data@entry=0x0)
    at ../wayland-1.22.0/src/wayland-server.c:2241
        pos = 0x58042e7251d0
        l = 0x58042e7251d0
        cursor = {link = {prev = 0x58042e7251d0, next = 0x7ffc68730560}, notify = 0x709c89fbe110 <handle_noop>}
        end = {link = {prev = 0x7ffc68730580, next = 0x58042e78b2c0}, notify = 0x709c89fbe110 <handle_noop>}
#3  0x0000709c89f44ab7 in xwayland_surface_dissociate (xsurface=xsurface@entry=0x58042e78b0b0)
    at ../wlroots-0.17.1/xwayland/xwm.c:398
#4  0x0000709c89f468f0 in xwm_handle_unmap_notify (ev=0x58042e526c70, xwm=0x58042e405fa0)
    at ../wlroots-0.17.1/xwayland/xwm.c:1124
        xsurface = 0x58042e78b0b0
        xsurface = <optimized out>
#5  x11_event_handler (fd=<optimized out>, mask=<optimized out>, data=<optimized out>)
    at ../wlroots-0.17.1/xwayland/xwm.c:1678
        count = <optimized out>
        event = 0x58042e526c70
        xwm = <optimized out>
        count = <optimized out>
        event = <optimized out>
        xwm = <optimized out>
#6  x11_event_handler (fd=<optimized out>, mask=<optimized out>, data=<optimized out>)
    at ../wlroots-0.17.1/xwayland/xwm.c:1632
        event = <optimized out>
        xwm = <optimized out>
#7  0x0000709c89fc2b8f in post_dispatch_check (loop=0x58042cd3e020) at ../wayland-1.22.0/src/event-loop.c:943
        dispatch_result = <optimized out>
        ep = {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}
        source = <optimized out>
        next = 0x58042cd3e018
        needs_recheck = false
        ep = {events = <optimized out>, data = {ptr = <optimized out>, fd = <optimized out>, u32 = <optimized out>, u64 = <optimized out>}}
        source = <optimized out>
        next = <optimized out>
        needs_recheck = <optimized out>
        dispatch_result = <optimized out>
#8  wl_event_loop_dispatch (loop=0x58042cd3e020, timeout=timeout@entry=-1) at ../wayland-1.22.0/src/event-loop.c:1034
        ep = {{events = 1, data = {ptr = 0x58042db2f7e0, fd = 766703584, u32 = 766703584, u64 = 96774969817056}}, {events = 1, data = {ptr = 0x58042db2f7e0, fd = 766703584, u32 = 766703584, u64 = 96774969817056}}, {events = 292674560, data = {ptr = 0x5804618cf8be, fd = 1636628670, u32 = 1636628670, u64 = 96775839742142}}, {events = 1, data = {ptr = 0x38, fd = 56, u32 = 56, u64 = 56}}, {events = 775890400, data = {ptr = 0x6873077000005804, fd = 22532, u32 = 22532, u64 = 7526367579883984900}}, {events = 32764, data = {ptr = 0x58042e3f55f8, fd = 775902712, u32 = 775902712, u64 = 96774979016184}}, {events = 775894504, data = {ptr = 0x687307b000005804, fd = 22532, u32 = 22532, u64 = 7526367854761891844}}, {events = 32764, data = {ptr = 0x709c89fbf500 <wl_connection_flush+304>, fd = -1979976448, u32 = 2314990848, u64 = 123817632199936}}, {events = 1, data = {ptr = 0x382db2f7e0, fd = 766703584, u32 = 766703584, u64 = 241284872160}}, {events = 0, data = {ptr = 0x7ffc687307d0, fd = 1752369104, u32 = 1752369104, u64 = 140722060855248}}, {events = 1, data = {ptr = 0xa19a98, fd = 10590872, u32 = 10590872, u64 = 10590872}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x9, fd = 9, u32 = 9, u64 = 9}}, {events = 775897216, data = {ptr = 0x3800005804, fd = 22532, u32 = 22532, u64 = 240518191108}}, {events = 0, data = {ptr = 0x58042e3f35e8, fd = 775894504, u32 = 775894504, u64 = 96774979007976}}, {events = 32, data = {ptr = 0x1400000000, fd = 0, u32 = 0, u64 = 85899345920}}, {events = 0, data = {ptr = 0x100000001, fd = 1, u32 = 1, u64 = 4294967297}}, {events = 261, data = {ptr = 0x687308d000000100, fd = 256, u32 = 256, u64 = 7526369091712450816}}, {events = 32764, data = {ptr = 0x7ffc68730800, fd = 1752369152, u32 = 1752369152, u64 = 140722060855296}}, {events = 292674560, data = {ptr = 0x618cf8be, fd = 1636628670, u32 = 1636628670, u64 = 1636628670}}, {events = 0, data = {ptr = 0x58042caabf0f <execute_command+975>, fd = 749387535, u32 = 749387535, u64 = 96774952501007}}, {events = 749736780, data = {ptr = 0x18c00005804, fd = 22532, u32 = 22532, u64 = 1700807071748}}, {events = 0, data = {ptr = 0x58042d9cc620, fd = 765249056, u32 = 765249056, u64 = 96774968362528}}, {events = 7, data = {ptr = 0x2d9deab000000000, fd = 0, u32 = 0, u64 = 3287041344685473792}}, {events = 22532, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 2314985744, data = {ptr = 0x2d8934900000709c, fd = 28828, u32 = 28828, u64 = 3281211596596080796}}, {events = 22532, data = {ptr = 0x58042d9de180, fd = 765321600, u32 = 765321600, u64 = 96774968435072}}, {events = 292674560, data = {ptr = 0x618cf8be, fd = 1636628670, u32 = 1636628670, u64 = 1636628670}}, {events = 0, data = {ptr = 0x58042e715b20, fd = 779180832, u32 = 779180832, u64 = 96774982294304}}}
        source = <optimized out>
        i = <optimized out>
        count = <optimized out>
        has_timers = <optimized out>
#9  0x0000709c89fc32d7 in wl_display_run (display=0x58042cd3df30) at ../wayland-1.22.0/src/wayland-server.c:1493
#10 0x000058042caa4c5e in server_run (server=<optimized out>) at ../sway-1.9/sway/server.c:398
#11 main (argc=<optimized out>, argv=0x7ffc68730ae8) at ../sway-1.9/sway/main.c:415
        config_path = 0x0
        c = <optimized out>
        validate = false
        debug = false
        allow_unsupported_gpu = false
        verbose = false
```

**Comment by emersion** [comment] 2024-03-12 10:50
Duplicate of https://github.com/swaywm/sway/issues/7895

**Closed by emersion** 2024-03-12 10:50 UTC
Labels: bug
