### ISSUE TITLE
High load of sway when drawing long lines with a wacom pen in Xournal++

### ISSUE THREAD

**Issue by bionade24** [swaywm/sway#5815] opened 2020-11-14 14:02 UTC
Xournal++ cross issue: https://github.com/xournalpp/xournalpp/issues/2398
**Used versions :**
- Sway 1.5.1
- Xournal++ 1.0.19
- libgtk 3.24.23
- linux-wacom 5.9.8

**Describe the bug
(Either) Xournal++ or/and Sway get extremely high load increasing with the time you draw a line with a wacom pen under sway.

**To Reproduce**
1. Draw a line in Xournal++ with a pen under sway
2. Don't let the pen loose contact with the surface

**Input Logs**
debug_input.log http://ix.io/2E8t
debug_gdk_input.log http://server2.oscloud.info/debug_gdk_input.log
`libinput list-devices` http://ix.io/2E8x

**Expected behavior**
Expectable loads that don't increase over the time, like on kwin_x11 (screenshot 2)

**Screenshots of Problem**
![screenshot_sway](https://user-images.githubusercontent.com/42534613/99147665-12a05200-2683-11eb-83da-4caf7cf20a73.jpg)
![screenshot_kwinX11](https://user-images.githubusercontent.com/42534613/99147674-18963300-2683-11eb-848e-fb4f83bad5bf.png)

**Additional context**
If someone helps me getting my pen working under weston, I'll test the behaviour.
Write Stylus from http://www.styluslabs.com/ keeps the both loads under 10%.

**Comment by Xyene** [comment] 2020-11-14 20:15
This looks like a duplicate of https://github.com/swaywm/wlroots/issues/2471. I'm unfamiliar with the log format you've provided, but the flood of

```
Gdk-Message: 14:34:28.385: pointer surface of seat 0x55ed5dd32050 left output 0x55ed5dd3fae0
Gdk-Message: 14:34:28.385: pointer surface of seat 0x55ed5dd32050 entered output 0x55ed5dd3fae0
Gdk-Message: 14:34:28.385: pointer surface of seat 0x55ed5dd32050 left output 0x55ed5dd3fae0
```

makes it sound like it's the same issue here. See the issue above for more details.

**Closed by Xyene** 2020-11-14 20:15 UTC
Labels: bug
