### ISSUE TITLE
Is there a way to configure the border transparency?

### ISSUE THREAD

**Issue by bonflintstone** [swaywm/sway#4755] opened 2019-11-26 12:24 UTC
![screenshot_2019-11-26T13:23:08+01:00](https://user-images.githubusercontent.com/15156214/69633044-ea71aa80-104f-11ea-97d5-58b3c557a7a4.png)

I am talking about the actual borders of the windows which are configured by:
```
default_border pixel 5
```

My desired configuration is something where I can actually not see the borders at all, so that it is indistinguishable from only using gaps.

The actual usecase/ motication behind this is that I would like to be able to resize windows by drag/ drop of the borders while maintaining the clean ui that I get from not seeing the borders. Thus, an alternative way to reach the same goal would be with making gaps "draggable".

If there is a way to do either of this, I did not manage to find this with a lot of searching through the docs/ wiki and google, so perhaps it would be good to add this to the wiki.

**Comment by cafehaine** [comment] 2019-11-26 12:39
duplicate of #3642

**Closed** 2019-11-26 12:46 UTC
