### ISSUE TITLE
Borders / size for some popup windows are wrong

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#5811] opened 2020-11-13 15:18 UTC
### Setup information
**Sway Version:**  
`sway version 1.5.1`

**Configuration File:**  
Can't find any config variables that affect this. For completeness sake though, my config file [is here](https://gitlab.com/WhyNotHugo/dotfiles/-/blob/master/home/.config/sway/config).

### Description

Borders for some popup windows are draw wrong:

![2020-11-13T16:11:53,011152059+01:00](https://user-images.githubusercontent.com/730811/99087410-a1996580-25c2-11eb-81d6-0f0dfe096101.png)

![2020-11-13T16:12:56,310737892+01:00](https://user-images.githubusercontent.com/730811/99087501-bd9d0700-25c2-11eb-9dc0-33baae803abb.png)

These two examples are a polkit agent, though I've seen this a few times with `gnome-keyring`, and also `firefox`

It seems that sway is measuring wrong the exact size of the window. If I take a screenshot of the window based on the dimensions that `sway` returns (i.e.: using `grimshot`), I get a cropped image:

![2020-11-13T16:05:09,332550371+01:00](https://user-images.githubusercontent.com/730811/99087693-f806a400-25c2-11eb-9670-7166fdc678a7.png)

![2020-11-13T16:05:54,668660937+01:00](https://user-images.githubusercontent.com/730811/99087622-e6250100-25c2-11eb-9d84-1eb5cf05e68b.png)

### Examples

- Run `/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1` on one terminal.
- Run `pkexec whoami` on another.

I'm giving this example since it presents the error 100% of the times for me. gnome-keyring and firefox only have this problem _sometimes_, so I can't easily reproduce it.

**Comment by emersion** [comment] 2020-11-13 15:27
Duplicate of https://github.com/swaywm/sway/issues/5750

**Closed by emersion** 2020-11-13 15:27 UTC
Labels: bug
