### ISSUE TITLE
Stylus device not seen by xwyaland

### ISSUE THREAD

**Issue by jrbp** [swaywm/sway#3886] opened 2019-03-13 18:13 UTC
If I run 'xinput list' I get the following under sway:
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ xwayland-pointer:26                     	id=6	[slave  pointer  (2)]
⎜   ↳ xwayland-relative-pointer:26            	id=7	[slave  pointer  (2)]
⎜   ↳ xwayland-touch:26                       	id=9	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ xwayland-keyboard:26                    	id=8	[slave  keyboard (3)]
```

While running the same command under gnome gives:
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ xwayland-pointer:15                     	id=6	[slave  pointer  (2)]
⎜   ↳ xwayland-relative-pointer:15            	id=7	[slave  pointer  (2)]
⎜   ↳ xwayland-touch:15                       	id=9	[slave  pointer  (2)]
⎜   ↳ xwayland-stylus:15                      	id=10	[slave  pointer  (2)]
⎜   ↳ xwayland-eraser:15                      	id=11	[slave  pointer  (2)]
⎜   ↳ xwayland-cursor:15                      	id=12	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ xwayland-keyboard:15                    	id=8	[slave  keyboard (3)]
```

Notice that under sway the folling are missing:
```
⎜   ↳ xwayland-stylus:15                      	id=10	[slave  pointer  (2)]
⎜   ↳ xwayland-eraser:15                      	id=11	[slave  pointer  (2)]
⎜   ↳ xwayland-cursor:15                      	id=12	[slave  pointer  (2)]
```

The output of 'libinput list-devices' is identical between both gnome and sway. The output of 'swaymg -t get_inputs' includes:
```
Input device: Wacom Pen and multitouch sensor Pen
  Type: Tablet tool
  Identifier: 1386:20615:Wacom_Pen_and_multitouch_sensor_Pen
  Product ID: 20615
  Vendor ID: 1386
  Libinput Send Events: enabled
```

Since there appears to be no xwayland device, programs like xournal can't use the stylus properly (which does work in gnome).

Is this the intended behavior until #2288 is addressed?

I'm using a Thinkpad X1 Yoga (gen 2)
sway version: 1.0
wlroots version: 0.5

**Comment by emersion** [comment] 2019-03-14 12:38
>Is this the intended behavior until #2288 is addressed?

Yes. The tablet protocol should make the device appear in Xwayland.

**Comment by emersion** [comment] 2019-03-14 12:39
I'm going to close this as a duplicate of #2288

**Closed by emersion** 2019-03-14 12:39 UTC
