### ISSUE TITLE
Text highlight background upon dragging should be transparent.

### ISSUE THREAD

**Issue by c-edw** [swaywm/sway#2902] opened 2018-10-21 01:23 UTC
This is likely to be an adjustment/feature, and may need to be redirected to the wlroots repository. When highlighting text with a coloured background and dragging it, the coloured background will appear as part of the 'halo'. 

It seems this effect isn't present when dragging text in all applications. For example, dragging text around in `gedit` does not have a background halo, but Chrome does. The steps below are the easiest way to produce this effect.

Steps to reproduce:
1. Open this page in Chrome
2. Highlight the blue `sway` in `swaywm/sway` at the top of this page with your cursor
3. Drag the highlighted text around the page
4. Observe that the halo has a solid white background instead of a transparent one

EDIT - Unrelated, but congratulations on 1.0-beta. Sway is the reason I love running Linux.

**Comment by emersion** [comment] 2018-10-21 06:16
Probably related to https://github.com/swaywm/wlroots/issues/348

(Thanks for your support!)

**Comment by emersion** [comment] 2018-10-27 10:15
Can you try https://github.com/swaywm/wlroots/pull/1335?

**Comment by emersion** [comment] 2018-10-27 10:19
@RyanDwyer confirmed this is a duplicate of swaywm/wlroots#348, fixed by swaywm/wlroots#1335.

**Closed by emersion** 2018-10-27 10:19 UTC
