### ISSUE TITLE
Primary screen is black on Sway startup in a dual monitor setup

### ISSUE THREAD

**Issue by maxigaz** [swaywm/sway#8424] opened 2024-11-02 19:25 UTC
### Please fill out the following:

- **Sway Version:**
sway version 1.10

- **Debug Log:**
https://paste.i2pd.xyz/?7bb27d51898b1663#GU2EDmSkokx23NfniZ1woi986NFu1gs6UDtyZ5MpGyxB

- **Configuration File:**
https://paste.i2pd.xyz/?ca973677f7c689bc#3TGY7EN4NUPdu3iahFB7zB3R6pwSkT2C7YusW3Hwkrhi (same as the default one shipped with Sway)

- **Description:**
Steps to reproduce:

1. Have both a VGA monitor and an A/V receiver (connected through HDMI) turned on.
2. Start a Sway session.

Explanation: I have an old AMD graphics card (HD6670) with a VGA and an HDMI output. The VGA output is connected to a monitor while the HDMI output is connected to a Yahama A/V receiver. The latter is only used for audio, not video, although Sway recognizes it as a second monitor.

This used to be perfectly functional with Sway 1.9. With Sway 1.10 running on Arch Linux, when I log in, the monitor is completely black, and it stays that way no matter what I do with the mouse or keyboard.

A workaround to that is to switch channels on my A/V receiver (which Sway interprets as if the second monitor has been switched off, I assume). The result is that the blackness is gone and Sway works again as normal.

Another workaround is to switch to TTY2 and run `pkill sway`.

**Comment by maxigaz** [comment] 2024-11-03 07:58
Here's another scenario, which is likely to be related:

1. Have only the VGA monitor turned on.
2. Start a Sway session.
3. Turn on the A/V receiver or change its input to HDMI.

Result: Sway visually freezes while the rest of the system remains operational.

If I do the first workaround I mentioned in the OP, Sway unfreezes. (If I typed anything in a terminal window while Sway was frozen, it suddenly appears on the screen.)

**Comment by egnappahz** [comment] 2024-11-06 09:55
The order of workspaces (monitors) has changed with the new sway version (other numbers), perhaps you need to redefine the outputs in the sway config?

**Comment by maxigaz** [comment] 2024-11-06 14:32
> The order of workspaces (monitors) has changed with the new sway version (other numbers), perhaps you need to redefine the outputs in the sway config?

If that's the case, I'm not sure what needs to be redefined. (If you have any specific hints, I could give them a try.)

What I do know is that when I first started using this setup (not having configured any outputs at the time), I definitely didn't experience any freezes or black screens. And now, I'm experiencing the issue even with the default Sway configuration (as I mentioned in my first post), which doesn't have any outputs defined.

**Comment by egnappahz** [comment] 2024-11-06 15:54
There are a lot of problems going on at the same time in latest sway, for example

- Output order changed, certain output names changed,  Certain displays not being loaded in on sway start, ....
- Direct scanout not working in certain multiGPU/multiscreen setups on specific monitors ==> apps freeze when they are fullscreen or when they are vulkan apps spanning the entire screen area (you can work aound that with WLR_SCENE_DISABLE_DIRECT_SCANOUT=1)
- Backgrounds no longer working, and just appearing as black, making it all very confusing .
And probably much more.
So to be honest I am lost myself to give you any specific useful advice for the moment I am just trying to give some pointers...

**Comment by maxigaz** [comment] 2024-11-07 08:12
> WLR_SCENE_DISABLE_DIRECT_SCANOUT=1

I've just tried running Sway with this set. It doesn't seem to make any difference. Thank you anyway!

**Comment by emersion** [comment] 2024-11-22 13:39
Sounds like a duplicate of https://github.com/swaywm/sway/issues/8442:

```
00:00:00.370 [ERROR] [wlr] [backend/drm/legacy.c:175] connector HDMI-A-1: drmModePageFlip failed: Device or resource busy
00:00:00.370 [ERROR] [sway/config/output.c:923] Backend commit failed
```

**Closed** 2024-12-06 10:13 UTC
Labels: bug
