### ISSUE TITLE
xkb_option gpr:*switch is ignored in Xwayland clients

### ISSUE THREAD

**Issue by wentasah** [swaywm/sway#5223] opened 2020-04-16 06:51 UTC
- sway version 1.4-525b48ed (Apr 10 2020, branch 'master')

I use the following keyboard setup:

```
input type:keyboard {
      xkb_model pc104
      xkb_layout us,cz
      xkb_variant basic,ucw
      xkb_options grp:caps_switch
}
```

The result is that pressing <kbd>a</kbd> with <kbd>Caps Lock</kbd> pressed down produces `á` character. However, it works this way only in Wayland clients, not in X applications.

The behavior is the same when using any `*switch` option, e.g. `grp:rctrl_switch`. However, using `*toggle` options such as `grp:caps_toggle` works correctly for both Wayland and X clients.

I can work around this problem by running `setxkbmap 'us,cz(ucw)`. Then, the keyboard behaves as expected in X clients. Interestingly, when I run `setxkbmap 'us,cz(ucw)' -option grp:caps_switch` (with added `-option`), switching the layout in X clients does not work.

To illustrate the problem, I include the output of `xev` for pressing (and releasing) <kbd>Caps Lock</kbd>, <kbd>a</kbd>.

Under X.org (without sway) it produces:
```
KeyPress event, serial 34, synthetic NO, window 0x1400001,
    root 0x1a5, subw 0x0, time 3501070, (956,501), root:(960,540),
    state 0x0, keycode 66 (keysym 0xff7e, Mode_switch), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x1400001,
    root 0x1a5, subw 0x0, time 3501374, (956,501), root:(960,540),
    state 0x2000, keycode 38 (keysym 0xe1, aacute), same_screen YES,
    XLookupString gives 2 bytes: (c3 a1) "á"
    XmbLookupString gives 2 bytes: (c3 a1) "á"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x1400001,
    root 0x1a5, subw 0x0, time 3501526, (956,501), root:(960,540),
    state 0x2000, keycode 38 (keysym 0xe1, aacute), same_screen YES,
    XLookupString gives 2 bytes: (c3 a1) "á"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x1400001,
    root 0x1a5, subw 0x0, time 3501950, (956,501), root:(960,540),
    state 0x2000, keycode 66 (keysym 0xff7e, Mode_switch), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

Under sway (before `setxkbmap` work around):

```
KeyPress event, serial 34, synthetic NO, window 0x600001,
    root 0x39e, subw 0x0, time 3380095, (942,532), root:(944,572),
    state 0x0, keycode 66 (keysym 0xff7e, Mode_switch), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x600001,
    root 0x39e, subw 0x0, time 3380519, (942,532), root:(944,572),
    state 0x0, keycode 38 (keysym 0x61, a), same_screen YES,
    XLookupString gives 1 bytes: (61) "a"
    XmbLookupString gives 1 bytes: (61) "a"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x600001,
    root 0x39e, subw 0x0, time 3380663, (942,532), root:(944,572),
    state 0x0, keycode 38 (keysym 0x61, a), same_screen YES,
    XLookupString gives 1 bytes: (61) "a"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x600001,
    root 0x39e, subw 0x0, time 3381247, (942,532), root:(944,572),
    state 0x0, keycode 66 (keysym 0xff7e, Mode_switch), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

Under sway, with `setxkbmap` work around:
```KeyPress event, serial 28, synthetic NO, window 0x600001,
    root 0x1ee, subw 0x0, time 39593749, (698,695), root:(700,735),
    state 0x10, keycode 66 (keysym 0xffe5, Caps_Lock), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x600001,
    root 0x1ee, subw 0x0, time 39594117, (698,695), root:(700,735),
    state 0x2010, keycode 38 (keysym 0xe1, aacute), same_screen YES,
    XLookupString gives 2 bytes: (c3 a1) "á"
    XmbLookupString gives 2 bytes: (c3 a1) "á"
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x600001,
    root 0x1ee, subw 0x0, time 39594301, (698,695), root:(700,735),
    state 0x2010, keycode 38 (keysym 0xe1, aacute), same_screen YES,
    XLookupString gives 2 bytes: (c3 a1) "á"
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x600001,
    root 0x1ee, subw 0x0, time 39594525, (698,695), root:(700,735),
    state 0x2010, keycode 66 (keysym 0xffe5, Caps_Lock), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

Note that here, Caps Lock does not appear as Mode_switch but as Caps_Lock.

**Comment by RedSoxFan** [comment] 2020-04-16 21:49
Duplicate of #4329

This is an XWayland bug, which is reported at https://gitlab.freedesktop.org/xorg/xserver/-/issues/856

**Closed by RedSoxFan** 2020-04-16 21:49 UTC

**Comment by LEdoian** [comment] 2023-12-12 15:41
> I can work around this problem by running `setxkbmap 'us,cz(ucw)`. Then, the keyboard behaves as expected in X clients. Interestingly, when I run `setxkbmap 'us,cz(ucw)' -option grp:caps_switch` (with added `-option`), switching the layout in X clients does not work.

Thank you very much for this insight, it kept me wondering for too long why this actually works, so I dug into it more. Details/observations are at the freedesktop issue, TL;DR: the switch seems to actually work twice and "overflows" back to the first layout. Adding the ucw layout _twice_ is another workaround that does not involve `setxkbmap`.

Without this, I would probably still assume there is an actual bug in group switch handling… (I mean, this is a bug in group switch handling, but seems easier to debug and fix.)
