### ISSUE TITLE
Chromium favorite folders don't open when sliding the cursor over

### ISSUE THREAD

**Issue by mamutal91** [swaywm/sway#5927] opened 2021-01-02 21:08 UTC
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.5.1`

- **Debug Log:**
  - https://raw.githubusercontent.com/mamutal91/dotfiles/master/sway/.config/sway/sway.log

- **Configuration File:**
  - https://raw.githubusercontent.com/mamutal91/dotfiles/master/sway/.config/sway/config

- **Description:**
  - Chromium's favorite folders don't open when sliding the cursor over

https://user-images.githubusercontent.com/32802713/103466451-174cc280-4d24-11eb-97a7-c37c17fbdaef.mp4

**Comment by Xyene** [comment] 2021-01-03 03:09
Looks like this regressed somewhere between Chrome 83 and 87, though it works as expected within Weston. Yet another Xwayland menu issue, I'm afraid.

**Comment by Xyene** [comment] 2021-04-25 20:24
Closing as a duplicate of https://github.com/swaywm/wlroots/issues/2889 (and https://github.com/swaywm/sway/issues/5692).

I've sent a fix upstream: https://chromium-review.googlesource.com/c/chromium/src/+/2844104

**Closed by Xyene** 2021-04-25 20:24 UTC
Labels: client-compat, xwayland
