### ISSUE TITLE
Sway drags windows that set cursor hitthrough/passthrough/input_region

### ISSUE THREAD

**Issue by Cre3per** [swaywm/sway#7990] opened 2024-02-18 10:47 UTC
This is already fixed on master (currently d19810eba8959f052d91fd6609cef6adf36b3951).  
I'm opening this ticket for documentation purposes, because it took me several hours to figure out where this bug was coming from, and to make sure the bug doesn't get reintroduced. Feel free to resolve if you don't feel a need for further action.

- **Sway Version:** master d19810eba8959f052d91fd6609cef6adf36b395 (Fixed)
- **Sway Version:** 1.9-rc4 6cbc83fd67ba796f95e4dca13a8a489fff68661a (Broken)

- **Debug Log:**
  - https://gist.github.com/Cre3per/6b6ae807b92d7b8936bd6af32892bb2d (2 logs)

- **Configuration File:**
  - default configuration (changed `$mod` and `$term`)

- **Stack Trace:**
  - no crash

- **Description:**
  - Create a window (A) with mouse input (e.g. a text editor or browser)
  - Create a window (B) which sets `wl_surface_set_input_region(surface, {0,0,0,0})` (pseudocode)
  - Make window B floating  
  - Try to click/drag through window B into window A
  - **Expect**: window A handles cursor events
  - **Is**: window B is dragged

A sample for window B can be found at https://github.com/Cre3per/sway-hittest-bug/tree/main  
`git clone` + `cargo run`

**Comment by purplg** [comment] 2024-06-14 01:13
This seems to be fixed for me with the `sway-git` package on the AUR. v1.10.r7343.9704152-1

**Comment by mgunyho** [comment] 2024-08-12 19:05
I just came across this (on 1.9), I think this is the same as #6341

**Comment by emersion** [comment] 2024-08-12 19:09
Should be fixed by scene-graph, please re-open if you can reproduce with Sway master.

**Closed by emersion** 2024-08-12 19:09 UTC
Labels: bug
