### ISSUE TITLE
1.0 Switching to a Firefox tab with 🐡 in title resizes titlebars of other windows

### ISSUE THREAD

**Issue by SjonHortensius** [swaywm/sway#4107] opened 2019-04-30 09:06 UTC
Not sure if this is a bug, but when I switch to a Firefox tab which contains a 🐡 in it's title (which this bug-report should now also have), the titlebars of other windows (such as Termite) resize themselves (they become ~ 1 pixel bigger). Switching to another tab in Firefox makes them resize back.

This might be intentional if sway determines the height by taking the highest value from all windows - but especially when text in other windows moves it feels buggy. The firefox tabs themselves don't change

**Comment by RedSoxFan** [comment] 2019-04-30 18:02
Duplicate of #3114

**Closed by RedSoxFan** 2019-04-30 18:02 UTC

**Comment by Tromino** [comment] 2019-05-03 14:18
But the content of one window's title shouldn't affect the size of others', right? Am I missing where that's mentioned in the issue this is supposedly a duplicate of?

**Comment by SjonHortensius** [comment] 2019-05-03 14:26
I think it is actually a more accurate description of what #3719 describes.

I agree #3114 doesn't explicitly mention bars of other windows so I also don't think this issue duplicates that

**Comment by RedSoxFan** [comment] 2019-05-03 16:22
> But the content of one window's title shouldn't affect the size of others', right?

Sway sets the height of all titlebars to the maximum height of any titlebar

> I think it is actually a more accurate description of what #3719 describes.

I still think that's a duplicate of #3114 as well
