### ISSUE TITLE
sway/wlroots fails to apply three-outputs configuration with two 4k monitors (@1440p)

### ISSUE THREAD

**Issue by maxnitze** [swaywm/sway#6326] opened 2021-06-15 00:33 UTC
**Sway Version:** 1.6

**Debug Log:**
https://pastebin.com/Hqe3ut5R

**Configuration File:**
I used the default configuration from `/etc/sway/config` and added some output configuration:

    output DP-4 enable mode 2560x1440@59.951Hz position 0,0
    output DP-5 enable mode 2560x1440@59.951Hz position 2560,0
    output eDP-1 enable mode 1920x1080@59.999Hz position 5120,360
    exec swaymsg workspace 1, move workspace to output DP-4

In the execution I attached above, I added the following line at the end to start the `sway-session` target which which in turn lets the `kanshi` service start:

    exec_always "systemctl --user import-environment; systemctl --user start sway-session.target"

Source: https://wiki.archlinux.org/title/Sway#Manage_Sway-specific_daemons_with_systemd

**Description:**

Setup:
- Lenovo T490
- Lenovo ThinkPad Pro Dock
- 2x Samsung 4K monitor

Activating both monitors beside each other with a resolution of `2560x1440` and the notebook display right of them with a resolution of `1920x1080` stopped working about a week ago.

I tried to set this from the sway config directly, in the `kanshi` configuration and also tried to configure this from `wdisplays` after sway did start already.

In the log above first the `kanshi` config was applied (and failed) and afterwards I tried to apply this from `wdisplays`. `kanshi` fails with _failed to apply configuration for profile 'dock home'_. Error message in `wdisplays` is _The display server was not able to process your changes_.

The following configuration does work:

    output DP-4 enable mode 1920x1080@59.940Hz position 0,360
    output DP-5 enable mode 2560x1440@59.951Hz position 1920,0
    output eDP-1 enable mode 1920x1080@59.999Hz position 4480,360
    exec swaymsg workspace 1, move workspace to output DP-4

**Comment by emersion** [comment] 2021-06-18 08:09
Have you tried `WLR_DRM_NO_MODIFIERS=1`?

**Comment by maxnitze** [comment] 2021-06-18 08:31
I did add it to `~/.config/environment.d/wlroots.conf`. And it had no effect.

I just tried adding it to `/etc/profile.d/wlroots.sh` and it seems to work!

Thanks a a lot!

**Comment by emersion** [comment] 2021-06-18 08:37
Cool. I'm going to close this as a duplicate of https://github.com/swaywm/wlroots/issues/1873.

**Closed by emersion** 2021-06-18 08:37 UTC
Labels: bug
