### ISSUE TITLE
Closing the laptop lid does not disable the output

### ISSUE THREAD

**Issue by philipflohr** [swaywm/sway#3137] opened 2018-11-16 12:00 UTC
Steps to reproduce:
1. connect a monitor to your laptop
2. start sway
3. close your laptop lid.

-> screen is turned off but sway does not disable the output

sway version 1.0-beta.1-108-gb90af335 (Oct 30 2018, branch 'master')
log: https://gist.github.com/philipflohr/91246ffb7f5f2610abd210fe543ed97f

**Comment by emersion** [comment] 2018-11-16 12:03
I'm not sure how we should handle this (and how we _can_ handle this).

**Comment by ascent12** [comment] 2018-11-16 12:07
I think https://github.com/swaywm/wlroots/pull/1377 is a step towards this.

**Comment by emersion** [comment] 2018-11-26 22:01
No, this issue is different, although related.

**Comment by akiva** [comment] 2018-11-26 22:36
See #3198 for related issue.

**Comment by FlorianFranzen** [comment] 2019-02-15 09:47
As soon as #3340 is working and merged, you should be able to bind the lid switch event to toggling the associated output.

**Comment by RedSoxFan** [comment] 2019-03-24 03:28
Since #3340 is merged, this can be accomplished with:
```
set $laptop <laptop-output-name-or-id>
bindswitch lid:off output $laptop disable
bindswtich lid:on output $laptop enable
```

Or if you want it to also trigger while locked, just add the `--locked` flag to bindswitch:
```
set $laptop <laptop-output-name-or-id>
bindswtich --locked lid:off output $laptop disable
bindswtich --locked lid:on output $laptop enable
```

**Closed by RedSoxFan** 2019-03-24 03:28 UTC
Labels: enhancement

**Comment by tristanvvatson** [comment] 2019-06-06 22:27
@RedSoxFan just FYI I copy and pasted this but there's a typo - perhaps rectify it?

```
set $laptop <laptop-output-name-or-id>
bindswitch --locked lid:off output $laptop disable
bindswitch --locked lid:on output $laptop enable
```

(switch vs swtich).  

I can confirm this works, however for some reason I had to have the opposite and 'wrong' configuration to get this working as expected:

```
set $laptop eDP-1
bindswitch lid:on output $laptop disable
bindswitch lid:off output $laptop enable
```

I'll have a look at my system events first to figure out if this is just my laptop having weird events, and secondly I'll put a PR in to document this feature.

**Comment by matt-snider** [comment] 2019-06-06 22:32
It wasn't working for me either, so I just flipped it as you did. It worked so I didn't really think much more about the semantics. But yes, it does seem backwards. 

On June 6, 2019 10:27:16 PM UTC, Tristan Watson <notifications@github.com> wrote:
>@RedSoxFan just FYI I copy and pasted this but there's a typo - perhaps
>rectify it?
>
>```
>set $laptop <laptop-output-name-or-id>
>bindswitch --locked lid:off output $laptop disable
>bindswitch --locked lid:on output $laptop enable
>```
>
>(switch vs swtich).  
>
>I can confirm this works, however for some reason I had to have the
>opposite and 'wrong' configuration to get this working as expected:
>
>```
>set $laptop eDP-1
>bindswitch lid:on output $laptop disable
>bindswitch lid:off output $laptop enable
>```
>
>I'll have a look at my system events first to figure out if this is
>just my laptop having weird events, and secondly I'll put a PR in to
>document this feature.

--
Best regards, 
Matt Snider

**Comment by RedSoxFan** [comment] 2019-06-06 23:04
> FYI I copy and pasted this but there's a typo - perhaps rectify it?

Oops. Sorry, yes that was indeed a typo and I had it backwards. I edited my previous comment.

> secondly I'll put a PR in to document this

In `man 5 sway`, it does say `switches are on when the device lid is shut` under `bindswitch` so it is documented correctly

**Comment by tokyovigilante** [comment] 2019-06-06 23:33
From `man 5 sway`:
> These switches are on when the device lid is shut and when tablet mode is active respectively.


From `libinput` (upstream Wayland input library) `libinput.h`:
```
* The laptop lid was closed when the switch state is @ref
* LIBINPUT_SWITCH_STATE_ON, or was opened when it is @ref
* LIBINPUT_SWITCH_STATE_OFF.
```
Ultimately I think it's an `evdev` curio:

From https://www.kernel.org/doc/Documentation/input/event-codes.txt:
```
EV_SW:
----------
EV_SW events describe stateful binary switches. For example, the SW_LID code is
used to denote when a laptop lid is closed.
```

So it's possibly counter-intuitive but correct as @RedSoxFan suggests.

**Comment by tristanvvatson** [comment] 2019-06-07 10:18
Makes more sense this way! Thanks a lot fo the input guys and for rectifying it. By documentation, I meant on the wiki side of things rather than `man` as I'm sure there's more users that are interested in the clamshell mode. I'll put a PR in later for this and see what happens.

**Comment by tristanvvatson** [comment] 2019-06-07 11:04
I've documented this behaviour within the wiki as promised: https://github.com/swaywm/sway/wiki

**Comment by FreeFull** [comment] 2019-06-07 11:04
Maybe there could be `closed` and `open` aliases for `on` and `off`?

**Comment by emersion** [comment] 2019-06-07 11:05
>Maybe there could be closed and open aliases for on and off?

Not a fan of this.

**Comment by billop** [comment] 2023-01-08 18:40
Seems to be completely broken in v1.8. Currently using this oneliner instead of using bindswitch:
```
exec_always 'if grep -q open /proc/acpi/button/lid/LID/state; then swaymsg output eDP-1 enable; else swaymsg output eDP-1 disable; fi'
```

**Comment by camoz** [comment] 2023-01-08 18:54
It's working fine here. Can someone else confirm this is broken in 1.8?

**Comment by billop** [comment] 2023-01-08 20:00
Just realized that it broke in v1.8 due to names of some outputs changing. Seems fine now.

**Comment by camoz** [comment] 2023-01-14 16:09
@treyssatvincent Have you seen the changes here? https://github.com/swaywm/sway/releases/tag/1.8

**Comment by 8FordPrefect8** [comment] 2023-01-24 19:50
@camoz can you tell then please what the hint and solution is? I don't get it yet.

**Comment by 8FordPrefect8** [comment] 2023-01-24 20:07
> Seems to be completely broken in v1.8. Currently using this oneliner instead of using bindswitch:
> 
> ```
> exec_always 'if grep -q open /proc/acpi/button/lid/LID/state; then swaymsg output eDP-1 enable; else swaymsg output eDP-1 disable; fi'
> ```

That's really strange. If I run this command in terminal, when lid is open or closed, it does what one would expect. However if I have this as exec_always in sway config it doesn't do anything.

**Comment by camoz** [comment] 2023-01-25 03:55
@8FordPrefect8 There are only 5 bullet points under "Changes"...

Those here seem likely to break existing configs:

> - Manufacturer names in output identifiers might have changed: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3541#note_1384124
> - The output dpms command has been deprecated (superseded by output power): https://github.com/swaywm/sway/pull/7083

**Comment by 8FordPrefect8** [comment] 2023-01-25 05:39
Hmm, since I am not using name, but eg eDP-1 and just tryed to configure it first time, the first point seems not relevant to my issue.
Regarding the second bullet. Is `output eDP-1 disable` affected by this?
Ibam using the same oneliner as @billop and it doesn't work for me.

**Comment by chengd42** [comment] 2023-04-17 21:59
> Since #3340 is merged, this can be accomplished with:
> 
> ```
> set $laptop <laptop-output-name-or-id>
> bindswitch lid:on output $laptop disable
> bindswtich lid:off output $laptop enable
> ```
> 
> Or if you want it to also trigger while locked, just add the `--locked` flag to bindswitch:
> 
> ```
> set $laptop <laptop-output-name-or-id>
> bindswtich --locked lid:on output $laptop disable
> bindswtich --locked lid:off output $laptop enable
> ```

It should be `bindswitch`
