### ISSUE TITLE
Crash in handle_xdg_surface_commit

### ISSUE THREAD

**Issue by Luis-Hebendanz** [swaywm/sway#5332] opened 2020-05-12 10:07 UTC
* Sway Version: 1.4

* Reproduce: It crashed while I was doing nothing special, for the first time (like this) after months of usage. I don't know how to reproduce this.

* Configuration File: https://github.com/Luis-Hebendanz/nix-configs/blob/master/resources/sway.conf

* Stack Trace, if sway crashes:
```
(gdb) bt full
#0  0x00007bf0048d4be0 in raise () from /nix/store/wx1vk75bpdr65g6xwxbj4rw0pk04v5j3-glibc-2.27/lib/libc.so.6
No symbol table info available.
#1  0x00007bf0048d5dc1 in abort () from /nix/store/wx1vk75bpdr65g6xwxbj4rw0pk04v5j3-glibc-2.27/lib/libc.so.6
No symbol table info available.
#2  0x00007bf0048cd6e7 in __assert_fail_base () from /nix/store/wx1vk75bpdr65g6xwxbj4rw0pk04v5j3-glibc-2.27/lib/libc.so.6
No symbol table info available.
#3  0x00007bf0048cd792 in __assert_fail () from /nix/store/wx1vk75bpdr65g6xwxbj4rw0pk04v5j3-glibc-2.27/lib/libc.so.6
No symbol table info available.
#4  0x00007bf004b2505a in handle_xdg_surface_commit () from /nix/store/vhg3ca4kiwdwsalsn3y9pqdajc8l2ypi-wlroots-0.10.1/lib/libwlroots.so.5
No symbol table info available.
#5  0x00007bf004b3b22a in surface_commit_pending () from /nix/store/vhg3ca4kiwdwsalsn3y9pqdajc8l2ypi-wlroots-0.10.1/lib/libwlroots.so.5
No symbol table info available.
#6  0x00007bf004b3b538 in surface_commit () from /nix/store/vhg3ca4kiwdwsalsn3y9pqdajc8l2ypi-wlroots-0.10.1/lib/libwlroots.so.5
No symbol table info available.
#7  0x00007bf004479ff0 in ffi_call_unix64 () from /nix/store/13k46bsrkqczmy5vxsqbvvs58jkmha9z-libffi-3.2.1/lib/../lib64/libffi.so.6
No symbol table info available.
#8  0x00007bf00447977a in ffi_call () from /nix/store/13k46bsrkqczmy5vxsqbvvs58jkmha9z-libffi-3.2.1/lib/../lib64/libffi.so.6
No symbol table info available.
#9  0x00007bf004b8cbed in wl_closure_invoke () from /nix/store/zs6fyy5s7yh0pvjh0dxb6ii3dxx8xbl7-wayland-1.17.0/lib/libwayland-server.so.0
No symbol table info available.
#10 0x00007bf004b89689 in wl_client_connection_data () from /nix/store/zs6fyy5s7yh0pvjh0dxb6ii3dxx8xbl7-wayland-1.17.0/lib/libwayland-server.so.0
No symbol table info available.
#11 0x00007bf004b8ac42 in wl_event_loop_dispatch () from /nix/store/zs6fyy5s7yh0pvjh0dxb6ii3dxx8xbl7-wayland-1.17.0/lib/libwayland-server.so.0
No symbol table info available.
#12 0x00007bf004b8987a in wl_display_run () from /nix/store/zs6fyy5s7yh0pvjh0dxb6ii3dxx8xbl7-wayland-1.17.0/lib/libwayland-server.so.0
No symbol table info available.
#13 0x000000000040e6d4 in main ()
No symbol table info available.
```

**Comment by emersion** [comment] 2020-05-12 10:09
Duplicate of https://github.com/swaywm/wlroots/issues/2056

**Closed by emersion** 2020-05-12 10:09 UTC
