### ISSUE TITLE
touchapd tap button map support

### ISSUE THREAD

**Issue by krzyscho** [swaywm/sway#1629] opened 2018-03-22 08:50 UTC
Touchpad tap button mapping would be nice:
[libinput_config_tap_button_map](https://wayland.freedesktop.org/libinput/doc/latest/group__config.html#ga7c7637385eaf0f1f29a812c3e48fdc3f
)

**Comment by RedSoxFan** [comment] 2018-07-14 05:17
Duplicate of #1569

**Closed by RedSoxFan** 2018-07-14 05:17 UTC
