### ISSUE TITLE
swaymsg is incompatible with json-c-0.14

### ISSUE THREAD

**Issue by JusterK** [swaywm/sway#5349] opened 2020-05-16 11:35 UTC
On sway version 1.4 swaymsg -t get_outputs shows no outputs, when it's compiled with json-c-0.14. The version json-c-0.13.1 works fine though.
```
% swaymsg -t get_outputs
Output DP-1 '(null) (null) (null)' (inactive)

Output HDMI-A-1 '(null) (null) (null)' (inactive)
```
Also see this [https://github.com/Alexays/Waybar/issues/709](url) bug.

**Comment by sfar9999** [comment] 2020-05-16 12:00
I just hit this. It causes swaybar to crash on startup inside `ipc_get_workspaces`.

The problem is with the generated JSON from sway. The value of `res` in
```
        char *res = ipc_single_command(bar->ipc_socketfd,
                        IPC_GET_WORKSPACES, NULL, &len);
```
looks like this:
[
  {
    "id": 8,
    "name": "j",
    "rect": {
      "x": 32,
      "y": 32,
      "width": 3776,
      "height": 2096
    },
    "focus": [
      7
    ],
    "border": "none",
    "current_border_width": 0,
    "layout": "splith",
    "orientation": "horizontal",
    "percent": null,
    "window_rect": {
      "x": 0,
      "y": 0,
      "width": 0,
      "height": 0
    },
    "focused": false
  },
  {
    "id": 14,
    "name": "f",
    "rect": {
      "x": 32,
      "y": 32,
      "width": 3776,
      "height": 2096
    },
    "focus": [
      15
    ],
    "border": "none",
    "current_border_width": 0,
    "layout": "splith",
    "orientation": "horizontal",
    "percent": null,
    "window_rect": {
      "x": 0,
      "y": 0,
      "width": 0,
      "height": 0
    },
    "focused": false
  }
  ...
]
("f" and "j" are workspace names)

The JSON object properties aren't anything like what swaybar is expecting. Looks more like a top level container than a workspace perhaps?

**Comment by sfar9999** [comment] 2020-05-16 12:38
https://github.com/json-c/json-c/issues/599
"cannot add more than 11 objects. Is this a known issue?"

Yeah that'll be it :)

**Comment by JusterK** [comment] 2020-05-16 13:13
@sfar9999 Indeed, just compiled sway with json-c master and everything works again.

Sway still needs an update though. A direct access has been deprecated:
`* Added a json_tokener_get_parse_end() function to replace direct access of tok->char_offset.`

which is used in i3bar.c
```
% find -name '*.c' -type f -exec grep -n char_offset {} \+
./swaybar/i3bar.c:198:                                  &status->buffer[buffer_pos + status->tokener->char_offset - 1];
./swaybar/i3bar.c:209:                          buffer_pos += status->tokener->char_offset;
```

**Comment by Xyene** [comment] 2020-05-16 19:21
Thanks for digging and confirming the issue is upstream, I'm going to close this issue since there's not much sway can do about it.

I'm not sure that switching to `json_tokener_get_parse_end` would be a good idea... right now it's still just a shorthand for `tok->char_offset`, and we'd end up requiring json-c 0.14 everywhere as a result. json-c 0.14 was just recently released and not yet packaged everywhere (for instance, Debian Sid still packages 0.13, and that's the _unstable_ channel).

I know Arch packages 0.14 now, and that's where a lot of the recent json-c issues have been coming from (like https://github.com/swaywm/sway/issues/5290, and this). At least until its wrinkles are ironed out, hard-requiring it for a cosmetic improvement sounds like it'd cause more problems than it'd solve.

**Closed by Xyene** 2020-05-16 19:21 UTC

**Comment by prometheanfire** [comment] 2020-05-17 03:11
Gentoo just stablized json-c 0.14 as well, not sure this problem is going to just go away.  Is there an upstream bug?

**Comment by Xyene** [comment] 2020-05-17 03:19
@prometheanfire yes, this is tracked upstream in https://github.com/json-c/json-c/issues/599, and it looks like it's been fixed there, just waiting on package maintainers at this point. There's not much we can do on sway's end.

**Comment by prometheanfire** [comment] 2020-05-17 04:03
ah, thanks, I'll poke the maintianers gentoo side and see if we can get a revbump for that.

**Comment by sfar9999** [comment] 2020-05-17 11:26
https://bugs.gentoo.org/723480
