### ISSUE TITLE
Hotkey keystrokes leak to underlying windows

### ISSUE THREAD

**Issue by colemickens** [swaywm/sway#4395] opened 2019-07-29 09:31 UTC
Let me describe it:

1. Have a video playing on workspace 1.
2. Switch to workspace 2.
3. Imagine `$mod+1` is a hotkey for switching to workspace 1.
4. Press that hotkey.

What happens:

The window on the workspace gets focused and receives a keystroke for 1 resetting the position of the video. To be curt, it's infuriating behavior. I feel like I must be doing something wrong, but I can't figure it out after quite some time.

**Comment by colemickens** [comment] 2019-07-29 09:32
To be more precise, I am switched back to workspace 1, but with only that one keypress, my video playback position also changes. Does sway not swallow the keystroke associated with the hotkey?

**Comment by RedSoxFan** [comment] 2019-07-31 18:00
Duplicate of #3196

**Closed by RedSoxFan** 2019-07-31 18:00 UTC
