### ISSUE TITLE
Non-resizable windows are "slightly" resizable

### ISSUE THREAD

**Issue by yvm** [swaywm/sway#5552] opened 2020-07-15 18:50 UTC
- **Sway Version:**
sway version 1.4

Not sure if this also true for native Wayland windows, but X windows with `min_width` == `max_width` and/or `min_height` == `max_height` hints are resizable to ammount of Sway's border.

Sample X window to reproduce:
```
#include <X11/Xlib.h>
#include <X11/Xutil.h>

int main (int argc, char *argv[]) {
    Display *display = XOpenDisplay("");
    int screen = DefaultScreen(display);
    XSetWindowAttributes win_attr.event_mask = ButtonPressMask;
    unsigned long mask = CWEventMask;
    Window window = XCreateWindow(display, RootWindow(display, screen),
				  0, 0, 640, 480, 2,
				  DefaultDepth(display, screen), InputOutput,
				  DefaultVisual(display, screen), mask, &win_attr);
    XSizeHints size_hints;
    size_hints.min_width = 640;
    size_hints.min_height = 480;
    size_hints.max_width = 640;
    size_hints.max_height = 480;
    XSetWMNormalHints(display, window, &size_hints);
    XMapWindow(display, window);
    XEvent event;
    while (True) {
	XNextEvent(display, &event);
	switch (event.type) {
	case ButtonPress:
	    return 0;
	}
    }
    XUnmapWindow(display, window);
    XDestroyWindow(display, window);
    XCloseDisplay(display);
    return 0;
}
```

**Comment by Xyene** [comment] 2020-07-15 21:48
Is this still reproducible in sway 1.5-rc2? There were a couple of border-related fixes that happened between 1.4 and it that may have addressed this.

**Comment by yvm** [comment] 2020-07-15 22:39
Well, upgraded to last one from https://apt.quantum2.xyz/sway-utils/ debian repository - now sway doesn't startup at all, saying just: 
> sway: symbol lookup error: sway: undefined symbol: wlr_headless_backend_create_with_renderer

**Comment by RedSoxFan** [comment] 2020-07-15 22:55
> sway: symbol lookup error: sway: undefined symbol: wlr_headless_backend_create_with_renderer

The version of wlroots that you are using is too old.

However, I'm going to close this as a duplicate of #5337. There is an open PR #5438 that will resolve this.

**Comment by quantum5** [comment] 2020-07-15 22:55
@yvm should be fixed in the latest build.

**Closed by RedSoxFan** 2020-07-15 22:55 UTC
Labels: bug
