### ISSUE TITLE
Display artifacts when resizing nested sway sessions

### ISSUE THREAD

**Issue by lephe** [swaywm/sway#3231] opened 2018-12-01 23:17 UTC
This might be a question more than a bug. Sway version :
```
sway version 1.0-beta.1-217-g77554f54 (Nov 24 2018, branch 'master')
```

When I start a nested sway session, it shows up as a tiled, split window (as required by my config) but is hard to resize and control. For instance, if I switch layout to tabbed, the window is not properly resized; it should cover the whole screen but remains of half the width (so does the status bar inside it) although the positioning and layout of the background *does* change.

When I switch to floating mode, the border completely disappears and the same kind of buggy resizing occurs. This is what I get after executing `resize set width 320 px height 240 px` with a shortcut:

![out](https://user-images.githubusercontent.com/33732078/49333716-05881680-f5c4-11e8-9738-40c7c9d74439.png)

Note the different times in the status bar, which show that the nested session did get smaller, but its container window did not. After some time the window adopts the correct size but starts flickering until I open something in the nested instance. Also, the nested display only seems to be refreshed when I click inside it or it loses focus (keystrokes don't count).

I'm quite confused about this. Is opening nested sessions supported? Is this a bug?

I'm using a nested session because I want to prepare a sway setup for another platform with a smaller screen size. I'm open to suggestions on the method. :smile: 

I'm attaching the log of a session where I opened a terminal, used it to start a nested sway, floated and resized the nested instance (as in the screenshot), and closed everything.

*Attached file: [sway-nested.log](https://github.com/swaywm/sway/files/2636398/sway-nested.log)*

**Comment by emersion** [comment] 2018-12-02 10:37
Duplicate of https://github.com/swaywm/wlroots/issues/1371

**Comment by lephe** [comment] 2018-12-02 10:54
Sorry about this. Is the disappearance of the window title and border related?

**Closed** 2019-01-07 14:21 UTC
