### ISSUE TITLE
Sway does not start XWayland applications correctly

### ISSUE THREAD

**Issue by jw4js** [swaywm/sway#6097] opened 2021-03-14 21:40 UTC
- **Sway Version:**
- 1.5.1

- **Debug Log:**
  - https://gist.github.com/jw4js/a65720508bb6650c700517aa8b775b53

- **Description:**
 Sway crashes if an XWayland application is started from a GUI terminal within sway. It doesn't crash if at least one XWayland application is started with a TTY first on this sway instance.

**Comment by Geo25rey** [comment] 2021-03-14 21:45
What application are you trying to open from your terminal?

**Comment by jw4js** [comment] 2021-03-14 21:46
Firefox

**Comment by Geo25rey** [comment] 2021-03-14 22:13
I can't reproduce your issue. Does setting `GDK_BACKEND=wayland` mitigate your issue?

**Comment by jw4js** [comment] 2021-03-14 22:24
It does, thanks. However, it is still broken for other X programs not using GDK.

**Comment by Geo25rey** [comment] 2021-03-14 22:32
I don't think this a problem with Sway or wlroots. Are you using a Nvidia graphics card?

Here are some other environment variables I use to avoid using XWayland:
```
    export _JAVA_AWT_WM_NONREPARENTING=1
    export AWT_TOOLKIT=MToolkit

    export GDK_BACKEND=wayland # unset for electron apps
    export QT_QPA_PLATFORM=wayland
    export QT_QPA_PLATFORMTHEME=qt5ct
    export CLUTTER_BACKEND=wayland
    export SDL_VIDEODRIVER=wayland

    export XDG_SESSION_TYPE=wayland
    export XDG_SESSION_DESKTOP=sway
    export XDG_CURRENT_DESKTOP=sway
```

**Comment by jw4js** [comment] 2021-03-14 22:35
I do have a NVIDIA graphics card but the driver's not even loaded. Sway has had a long line of issues relating to SIGUSR1 and XWayland. I think this is just the latest iteration of it.

**Comment by Geo25rey** [comment] 2021-03-14 22:49
What version of wlroots are you on?
`pacman -Q wlroots`

**Comment by Geo25rey** [comment] 2021-03-14 22:57
Also, something to try is using a different mouse. I noticed there's a lot of atypical output regarding your mouse.

**Comment by jw4js** [comment] 2021-03-14 23:00
I'm on wlroots 0.12.0-1. I don't know, this looks a lot like something not catching SIGUSR1 properly than having to do with my mouse but I'll test anyway.

**Comment by Geo25rey** [comment] 2021-03-14 23:14
Can you do `coredumpctl list sway`? If there is a coredump, can you share the stacktrace?

**Comment by jw4js** [comment] 2021-03-14 23:18
Nope, doesn't dump core. Last time it dumped core was a year ago for something unrelated.

**Comment by Geo25rey** [comment] 2021-03-14 23:21
What about Sway's exit code? `echo $?` after running Sway.

**Comment by jw4js** [comment] 2021-03-14 23:30
138

**Comment by Geo25rey** [comment] 2021-03-14 23:42
That means Sway exited due to SIGUSR1

**Comment by Geo25rey** [comment] 2021-03-14 23:44
Can you install wlroots-git and sway-git from the AUR and see if that fixes it?

**Comment by emersion** [comment] 2021-03-15 08:38
Sounds similar to https://github.com/swaywm/sway/issues/6032

**Comment by naseschwarz** [comment] 2021-03-15 10:38
I was experiencing the same issues with sway 1.5.1/wlroots 0.12.0 just now. Switching to wlroots-git/sway-git fixed it.

**Comment by Roboron3042** [comment] 2021-03-15 23:29
I can confirm this was happening to me too until i switched to master. A bugfix release would be appreciated.

**Comment by kennylevinsen** [comment] 2021-03-15 23:31
> A bugfix release would be appreciated.

The next full release is right around the corner - see https://github.com/swaywm/sway/issues/5970. Hang in there until then. :)

**Comment by emersion** [comment] 2021-03-16 06:54
My guess is that a Mesa driver stopped ignoring SIGISR1 on its threads, resulting in this crash when Xwayland becomes ready.

**Comment by emersion** [comment] 2021-03-16 08:45
Closing since it doesn't happen on master.

**Closed by emersion** 2021-03-16 08:45 UTC
Labels: bug

**Comment by adabru** [comment] 2021-03-17 17:56
I'm on v1.5.1-1 and the XWayland applications crash if I don't wait at least 15s (14s: crash, 16s: ok) after starting sway. I'll wait for the next release to see if it gets fixed.

**Comment by mordax777** [comment] 2021-03-27 09:06
My workaround is to remove `XDG_CURRENT_DESKTOP=sway` from my environment variables, after that, all apps start normally without crashing Sway.

**Comment by adabru** [comment] 2021-03-29 11:41
Switched to the master version and don't see the issue anymore.
