### ISSUE TITLE
Primary screen fails to come back after DPMS

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#5872] opened 2020-12-11 14:08 UTC
I use this script to deactivate my screen when locking:

    /usr/bin/swayidle timeout 3 'swaymsg "output * dpms off"'  resume 'swaymsg "output * dpms on"'

And this one to return it to normal after unlocking:

    /usr/bin/swaymsg "output * dpms on"

Recently, however, my primary display (that, is, the primary laptop display) fails to come back from sleep -- it just stays off, and explicitly deactivating the display and re-activating it fails:

```
Dec 11 15:02:13 victory sway[846]: 05:14:01.428 [ERROR] [backend/drm/atomic.c:36] eDP-1: Atomic commit failed (modeset): Invalid argument
Dec 11 15:02:13 victory sway[846]: 05:14:01.443 [ERROR] [backend/drm/atomic.c:36] eDP-1: Atomic commit failed (modeset): Invalid argument
Dec 11 15:02:13 victory sway[846]: 05:14:01.443 [ERROR] [backend/drm/drm.c:744] Failed to initialize renderer on connector 'eDP-1': initial page-flip failed
Dec 11 15:02:13 victory sway[846]: 05:14:01.443 [ERROR] [backend/drm/drm.c:817] Failed to initialize renderer for plane
Dec 11 15:02:13 victory sway[846]: 05:14:01.444 [sway/config/output.c:414] Failed to commit output eDP-1
```

- ArchLinux
- sway 1.5.1
- kernel 5.9.13
- Intel UHD Graphics 620

I'll re-start way in debug mode in a bit and include more detailed logs too.

**Comment by emersion** [comment] 2020-12-11 14:13
Can you obtain DRM debug logs? See https://github.com/swaywm/wlroots/wiki/DRM-Debugging

**Comment by WhyNotHugo** [comment] 2020-12-11 14:15
Debug logs: https://gist.github.com/WhyNotHugo/d2e491b91894a01c33d71c678a1ca906

**Comment by WhyNotHugo** [comment] 2020-12-11 14:25
DRM logs  here: https://gist.github.com/WhyNotHugo/fab29f47258dcade5ffb6246fb9f384c

**Comment by emersion** [comment] 2020-12-11 14:27
```
[   92.427918] i915 0000:00:02.0: [drm:skl_allocate_pipe_ddb [i915]] Requested display configuration exceeds system DDB limitations
[   92.427931] i915 0000:00:02.0: [drm:skl_allocate_pipe_ddb [i915]] minimum required 482/425
```

Duplicate of https://github.com/swaywm/wlroots/issues/1877

**Closed by emersion** 2020-12-11 14:27 UTC
Labels: bug, waiting-on-reporter

**Comment by WhyNotHugo** [comment] 2020-12-11 14:38
Hmm... odd, this started happening this week after a system update (I do recall, among other things, the kernel itself had a minor bump).

But the linked issue is from 2019.

Could this be very similar symptoms but a different issue?

**Comment by WhyNotHugo** [comment] 2020-12-11 14:41
Thanks! I'll follow up on the linked issue.
