### ISSUE TITLE
firefox randomly becomes transparent 

### ISSUE THREAD

**Issue by Relected** [swaywm/sway#6744] opened 2022-01-07 21:17 UTC
sway 1.6.1

- **Debug Log:**
https://www.toptal.com/developers/hastebin/axeviviheh.yaml

- **Configuration File:**
this is the only thing that enables opacity, which applies only to the terminal emulator foot
 for_window [title="foot"] opacity set 0.95
  - Upload the config to a pastebin such as gist.github.com.

**Comment by emersion** [comment] 2022-01-07 21:25
Duplicate of https://github.com/swaywm/sway/issues/3621

**Closed by emersion** 2022-01-07 21:25 UTC
Labels: bug

**Comment by Relected** [comment] 2022-01-07 21:34
@emersion oh thx

**Comment by RPigott** [comment] 2022-01-08 20:03
Are you sure the for_window rule isn't matching firefox? The title value is regex so without anchors it would match the firefox window too whenever "foot" appeared in the title. That could happen if you even google the word "foot", or visit a page about "football" or something.

**Comment by Relected** [comment] 2022-01-09 07:46
@RPigott OOOOH MY GO

I forgot to say that this happens more frequently when I visit the foot terminal repo

well, how can I make it so it excludes Firefox and other apos

**Comment by RPigott** [comment] 2022-01-09 07:50
You should add regex anchors to the match, e.g. "^foot$" so that it only accepts a full match. Also, more importantly, you probably wanted to match by app_id (which identifies the application) instead of window title.

**Comment by Relected** [comment] 2022-01-09 07:57
@RPigott I did that and now it's solved! tkank you
