### ISSUE TITLE
connector VGA-1: drmModePageFlip failed: Device or resource busy

### ISSUE THREAD

**Issue by yuki0iq** [swaywm/sway#8266] opened 2024-07-27 15:04 UTC
# Sway version
- sway version `1.10-dev-4d4c88f0 (Jul 23 2024, branch 'master')` from AUR
- wlroots-git `0.19.0.r7131.015bb8512-1` from AUR
- `Linux reimu 6.10.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 24 Jul 2024 22:25:43 +0000 x86_64 GNU/Linux`
- default config
- `nouveau` videodriver with NVC9 (Fermi) card

# Description

Recently I started noticing a lot of errors in logs that happen only if the display is powered off.
```
00:00:10.920 [ERROR] [wlr] [backend/drm/legacy.c:175] connector VGA-1: drmModePageFlip failed: Device or resource busy
00:00:10.920 [ERROR] [sway/desktop/output.c:280] Page-flip failed on output VGA-1
```

Steps to reproduce:
```
sudo dmesg -C # Clear kernel logs
echo 0x19F | sudo tee /sys/module/drm/parameters/debug # Enable verbose DRM logging
sudo dmesg -w >dmesg.log & # Continuously write DRM logs to a file, in the background
sway -c/etc/sway/config -d >sway.log 2>&1 # Reproduce the bug, then exit sway
# super + enter: open foot
# swaymsg output VGA-1 power off
# (wait about 20 seconds)
# swaymsg output VGA-1 power on
# swaymsg exit
fg # Kill dmesg with Ctrl+C
echo 0 | sudo tee /sys/module/drm/parameters/debug # Disable DRM logging
```

[dmesg.log](https://github.com/user-attachments/files/16400638/dmesg.log)
[sway.log](https://github.com/user-attachments/files/16400639/sway.log)

**Comment by emersion** [comment] 2024-12-06 10:13
Duplicate of https://github.com/swaywm/sway/issues/8442

**Closed by emersion** 2024-12-06 10:13 UTC
Labels: bug
