### ISSUE TITLE
GTK dropdowns are invisible

### ISSUE THREAD

**Issue by setpill** [swaywm/sway#4865] opened 2020-01-02 15:52 UTC
* Versions:
    * Sway: 1.2
    * Wlroots: 0.8.1
    * Pavucontrol: 4.0
    * Pavucontrol-qt: 0.14.1
    * Weston: 7.0.0

* To reproduce:
    1. Have at least 2 audio outputs.
    2. Play some audio in whatever application.
    3. Open pavucontrol
    4. Under the "Playback" tab, click the button with the audio device name next to the audio stream.
    5. Expected behaviour: a dropdown opens allowing to select a different audio output.
    6. Actual behaviour: dropdown opens and can be interacted with via keyboard, but is not drawn.

* Additional info:
    * This also applies to dropdowns in firefox (native wayland backend), though before I ran across the problem in pavucontrol I had assumed it to be a firefox bug.
    * The dropdown in pavucontrol-qt works fine.
    * The dropdown in pavucontrol under weston also works fine.

**Comment by RedSoxFan** [comment] 2020-01-02 21:31
Duplicate of #3135

If your top-leftmost output is at 0,0 feel free to reopen with a debug log and `env WAYLAND_DEBUG=1 pavucontrol 2> pavucontrol.log` (this is verbose so quickly replicate and exit)

**Closed by RedSoxFan** 2020-01-02 21:31 UTC

**Comment by setpill** [comment] 2020-01-03 12:49
Pavucontrol's dropdowns work when the top-left-most monitor is 0,0 or negative (as expected from the  Firefox's dropdowns *only* work on whatever monitor is at 0,0.

[Here](https://gist.github.com/setpill/a990bfa8065e0e780cdd0f505cffb535)'s a log, produced by:

1. Starting firefox with `env WAYLAND_DEBUG=1 firefox 2> firefox.log` on a monitor with position -1920,0.
2. Loading a site with a dropdown element.
3. Tailing the log file to a different file with `tail -f firefox.log > firefox2.log`.
4. Switching to firefox, clicking the dropdown, then clicking somewhere else within firefox.
5. Switching to console, stopping the `tail`.

**Comment by RedSoxFan** [comment] 2020-01-03 13:08
Yes, that is #3135. It's an application bug and caused by use of a deprecated gtk function. See https://github.com/swaywm/sway/issues/3135#issuecomment-448794177

**Comment by setpill** [comment] 2020-01-03 13:11
I was under the impression that firefox's usage of `gtk_menu_popup()` was [fixed in 68.0](https://bugzilla.mozilla.org/show_bug.cgi?id=1423598); I am on 71.0.

**Comment by setpill** [comment] 2020-01-03 15:31
I grepped through the [firefox 71.0 source](https://archive.mozilla.org/pub/firefox/releases/71.0/source/) and the only occurences of `gtk_menu_popup` seem to be in `widget/gtk/gtk3drawing.cpp`, and only because there's a function defined (and used) there named `moz_gtk_menu_popup_paint`.

**Comment by RedSoxFan** [comment] 2020-01-04 01:52
Sorry. I read the comment on my phone and missed the pavucontrol to firefox transition. The pavucontrol issue is #3135.

For Firefox, there is the following in your log:
```
2533119.520]  -> xdg_wm_base@24.create_positioner(new id xdg_positioner@156)
[2533119.531]  -> xdg_positioner@156.set_size(491, 2)
[2533119.558]  -> xdg_positioner@156.set_anchor_rect(609, 219, 491, 2)
```

That's a popup with a width of 491 and a height of 2. From the log, it looks like it is being displayed, but it is too small to notice or possibly the 2 pixel high buffer is completely transparent. Either way, this is an application issue.

FWIW I *can* replicate this with Firefox 71.0, but I *cannot* with Firefox Nightly 73.0a1 (2020-01-03)
