### ISSUE TITLE
[Feature request] Extended mouse support

### ISSUE THREAD

**Issue by brzegorz** [swaywm/sway#3298] opened 2018-12-16 21:06 UTC
Hi, I'd like to request a couple of new features, which would make sway more usable with mouse. While I enjoy the keyboard-driven navigation, sometimes I like to switch to mouse. None of the tiling WM's I've tried matches my vision. Sway is the closest, but it would need 2 or 3 things still:

- 1 The way you can drag  windows with $mod + mouse is awesome. Is there a way to do it without $mod key, but purely by dragging the titlebar?

- 2 A close button on the titlebar, usable with mouse

- 3 (less important) A maximize/minimize button on the titlebar

Is there a chance those could be implemented?

Best,
brzegorz

**Comment by emersion** [comment] 2018-12-16 21:10
>1 The way you can drag windows with $mod + mouse is awesome. Is there a way to do it without $mod key, but purely by dragging the titlebar?

This should already be possible. There's a bug that makes it impossible for tiled windows right now, though.

>2 A close button on the titlebar, usable with mouse

Sorry, I don't think we want this feature.

>3 (less important) A maximize/minimize button on the titlebar

Same as (2), though note that Sway doesn't have maximized/minimized windows.

**Comment by RyanDwyer** [comment] 2018-12-16 22:19
You might be interested in mouse button bindsyms. For example, you can set up a bindsym so it closes the window when you right click anywhere on the title bar.

**Comment by tokyovigilante** [comment] 2018-12-17 02:15
Related but might have to wait for touch gestures, a double click in the window or another gesture to switch a window to full-screen would be great for tablets etc, but I'm not sure if this could be reliably intercepted. I know mpv does this, but that's presumably specific to that app. 

The other issue with using title bars is that a number of apps can be either configured to or by default don't have title bars.

**Comment by brzegorz** [comment] 2018-12-17 07:58
1. Great. Could you give me a link to the issue? I guess once it`s solved I have no more incentives to stick with X

2. Care to elaborate why? Is it to much hassle for low priority feature? Or is it against the vision?

Both touch gestures and bindsyms seem helpful to my case. Thank you.

**Comment by emersion** [comment] 2018-12-17 08:17
1. Just merged the fix: https://github.com/swaywm/sway/pull/3303
2. I don't think buttons would fit nicely in sway's workflow, and I believe using button bindings as @RyanDwyer suggested is a reasonable workaround. Also, the maintenance cost would be high, especially considering the rendering code is already pretty complex. Last, I don't think a lot of sway users would like to enable this feature.

**Closed by emersion** 2018-12-17 08:17 UTC

**Comment by brzegorz** [comment] 2018-12-17 12:47
Ok. Thank you for the answers and the fix. Now I must take the time to replace my lxqt+i3 config :D.

On December 17, 2018 9:17:38 AM GMT+01:00, emersion <notifications@github.com> wrote:
>1. Just merged the fix: https://github.com/swaywm/sway/pull/3303
>2. I don't think buttons would fit nicely in sway's workflow, and I
>believe using button bindings as @RyanDwyer suggested is a reasonable
>workaround. Also, the maintenance cost would be high, especially
>considering the rendering code is already pretty complex. Last, I don't
>think a lot of sway users would like to enable this feature.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/swaywm/sway/issues/3298#issuecomment-447758174

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by moljac024** [comment] 2019-09-02 21:51
> 2. I don't think buttons would fit nicely in sway's workflow, and I believe using button bindings as @RyanDwyer suggested is a reasonable workaround. Also, the maintenance cost would be high, especially considering the rendering code is already pretty complex. Last, I don't think a lot of sway users would like to enable this feature.

Using button bindings is not really a substitute. Why close the issue outright if you don't personally find the feature useful? I would like this sort of attitude to go away from open source. There are already at least two issues open for this feature so people obviously want it. Sway already has quite a bit more mouse support than most other tiling window managers - I assume they would say the same as you just did to most of those. And yet, here they are in sway, and they're great.

And to be honest, if you are telling me a simple feature such as a clickable button to invoke an action that already exists would be too hard a change to make and maintain, it doesn't really give me much confidence in the quality of the codebase.

**Comment by RyanDwyer** [comment] 2019-09-02 23:02
> Why close the issue outright if you don't personally find the feature useful?

Because one of sway's goals is to be a minimalistic, keyboard driven compositor for power users. Adding buttons to the title bar does not align with these goals because the interface is no longer simple (it adds clutter), and it would encourage mouse use via a visual means.

> I would like this sort of attitude to go away from open source. There are already at least two issues open for this feature so people obviously want it.

Just because people want it doesn't mean it's wise for the project to implement it. If we added every feature that was asked for then we'd eventually have a complicated machine that nobody wants to touch.

Sway is not trying to reach a wide user base. It is simply solving a problem for power users. You are welcome to use it if it helps you. And you are also welcome to fork it and add buttons if that's what you want. That is the beauty of open source.

> And to be honest, if you are telling me a simple feature such as a clickable button to invoke an action that already exists would be too hard a change to make and maintain, it doesn't really give me much confidence in the quality of the codebase.

It's not hard to make, nor is it hard to maintain. The problem is that it's not fun to support a feature if it's not being used by many people. It is not fun to contribute an unrelated feature, only to find you've broken an existing one that almost nobody uses and have to spend time learning how it works and fixing it.

> Would you accept a pull request for this feature?

Not likely.
