### ISSUE TITLE
Reproducible bug in cursor.c causes SIGSEGV in Sway version 1.8 ( latest ) 

### ISSUE THREAD

**Issue by froeberger** [swaywm/sway#7372] opened 2023-01-10 06:16 UTC
Sway version: 1.8

Attached is the gdb debug output.  The problem did not exist in the previous version of Sway: 1.7.  The bug is reproducible within Bitwig Studio, by clicking on the timer resolution regarding beats on the lower right of the window.  A pop up menu appears, allowing one to select the type of note-resolution and subdivision of a beat timing they wish to see represented in the visual layout of a scene or track portion above.  I often compose using triplet timing, and so when I click-and-drag the portion of the popup menu that says 'default' in order to select { triole, quintole, septole, etc. } timing, BOOM!  SIGSEGV, and an abrupt end to my login session, bouncing me back to the login screen, and leaving my Bitwig Studio still running, yet now without a display session attached.  The headless horseman, as it were...

I hope that this helps...

F.

[sway.gdb.txt](https://github.com/swaywm/sway/files/10379428/sway.gdb.txt)

**Comment by chrissygem42** [comment] 2023-01-10 08:21
[thanks]

**Comment by guildem** [comment] 2023-01-31 15:54
Exactly the same pattern on my hosts, One on AMD GPU, the other on Intel iGPU, I switched to multiple java versions to test it, always the same result on the 2 hosts. Tried to see the logs, but nothing helpful. Confirmed since sway 1.8, not present on sway 1.7 and before.

**Comment by emersion** [comment] 2023-01-31 15:57
Relevant part of the backtrace:

```
Thread 1 (Thread 0x7fc632e48980 (LWP 1781)):
#0  0x000055615e3b1efb in warp_to_constraint_cursor_hint (cursor=cursor@entry=0x55615f70c840) at ../sway-1.8/sway/input/cursor.c
:1325
        sy = <optimized out>
        lx = <optimized out>
        sx = <optimized out>
        view = 0x0
        con = <optimized out>
        ly = <optimized out>
        constraint = 0x55615ffda420
#1  0x000055615e3b1fc0 in handle_constraint_destroy (listener=0x55615ff60108, data=0x55615ffda420) at ../sway-1.8/sway/input/cur
sor.c:1348
        sway_constraint = 0x55615ff600e0
        constraint = 0x55615ffda420
        cursor = 0x55615f70c840
#2  0x00007fc633e78f6e in wl_signal_emit_mutable (signal=signal@entry=0x55615ffda528, data=data@entry=0x55615ffda420) at ../wayl
and-1.21.0/src/wayland-server.c:2179
        pos = 0x55615ff60108
        l = 0x55615ff60108
        cursor = {link = {prev = 0x55615ffda528, next = 0x7ffc7dda4d40}, notify = 0x7fc633e76110 <handle_noop>}
        end = {link = {prev = 0x7ffc7dda4d60, next = 0x55615ffda528}, notify = 0x7fc633e76110 <handle_noop>}
#3  0x00007fc633deff17 in pointer_constraint_destroy (constraint=0x55615ffda420) at ../wlroots-0.16.1/types/wlr_pointer_constraints_v1.c:49
#4  0x00007fc633e7a8ba in destroy_resource (element=0x55615ffe4c10, data=data@entry=0x0, flags=0) at ../wayland-1.21.0/src/wayland-server.c:730
        resource = 0x55615ffe4c10
#5  0x00007fc633e7c6a9 in wl_resource_destroy (resource=<optimized out>) at ../wayland-1.21.0/src/wayland-server.c:747
        client = 0x55615fceb530
        id = 144
        flags = <optimized out>
```

**Comment by bl4ckb0ne** [comment] 2023-01-31 15:57
Fixed by https://github.com/swaywm/sway/commit/88c17ece3b2617762c3f5f1c1fa79fe8f4df0082 in master

**Closed by bl4ckb0ne** 2023-01-31 15:57 UTC
Labels: bug
