### ISSUE TITLE
Display freezing and graphical glitches since update

### ISSUE THREAD

**Issue by ThatCraws** [swaywm/sway#6363] opened 2021-07-02 18:56 UTC
Hi there, 
ever since the newest update, sway seems to have problems with refreshing the screen and some graphical glitches appear kinda frequently. Downgrading to `sway 1.6` and `wlroots 1.3.0-1` "solves" the issue.
The display will almost completely freeze, especially when I start xwayland programs. And there will be graphical glitches, especially when closing windows (shown in video). All inputs are correctly processed in the background, the problem is exclusively in the way things are displayed.

https://user-images.githubusercontent.com/45998082/124317463-81311200-db77-11eb-99f2-f8d15c70a91d.mp4

Sorry, didn't record it freezing up, when I start firefox for example (let me know if you need to see that).

It's bad enough to make it unusable (at least when using xwayland programs), but I'll gladly use the old version for now. Just wanted to let you guys know. I am using a `Asus nvidia`(i know)` geForce gtx970`, that is probably somehow related. 
**This might as well be a wlroots issue though.** I wouldn't know.

If you need any more information, don't hesitate to ask.

### Hopefully relevant information:
- **Sway Version:**
  - `sway 1.6.1`
- **wlroots version:**
  - `wlroots 0.14.0` 

- **Debug Log:**
  [https://gist.github.com/ThatCraws/33d74cce58bdd0e273b412993b3062dc](https://gist.github.com/ThatCraws/33d74cce58bdd0e273b412993b3062dc) 

And there's this:
![f1eaafeb-d46a-4f0b-8093-e3e36f6556a2](https://user-images.githubusercontent.com/45998082/124317540-a1f96780-db77-11eb-9163-4ea72e757e30.jpg)

- **Description:**
  - Update sway and wlroots
  -  Start sway

**Comment by fluix-dev** [comment] 2021-07-02 20:22
Duplicate of https://github.com/swaywm/wlroots/issues/2991 I believe.

**Comment by emersion** [comment] 2021-07-02 20:49
Yup! Closing as a duplicate.

**Closed by emersion** 2021-07-02 20:49 UTC
Labels: bug
