### ISSUE TITLE
Drag & drop stops working on some apps

### ISSUE THREAD

**Issue by luispabon** [swaywm/sway#4285] opened 2019-06-24 10:02 UTC
* Sway Version:
1.1.1 (reported by sway as 1.1-rc1-35-g7a11b58a for some reason, but it's built from the 1.1 branch)
wlroots 0.6.0
nautilus 3.32.1 (Ubuntu 19.04)
firefox nightly (on wayland)

* Debug Log:
When trying to drag a file in Nautilus
```
2019-06-24 10:48:52 - [types/data_device/wlr_data_offer.c:87] Ignoring wl_data_offer.accept request on a non-drag-and-drop offer
2019-06-24 10:48:52 - [types/wlr_surface.c:609] New wlr_surface 0x5559590851e0 (res 0x555959038b40)
2019-06-24 10:48:52 - [types/seat/wlr_seat_pointer.c:418] Pointer grab serial validation failed: button_count=5 grab_serial=90 (got 4873)
2019-06-24 10:48:52 - [types/seat/wlr_seat_touch.c:371] Touch grab serial validation failed: num_points=0 grab_serial=0 (got 4873)
2019-06-24 10:48:52 - [sway/input/seat.c:349] Ignoring start_drag request: could not validate pointer or touch serial 4873
```

When trying to drag a tab within a firefox window
```
2019-06-24 10:55:11 - [types/wlr_surface.c:609] New wlr_surface 0x555959041b00 (res 0x55595904c270)
2019-06-24 10:55:11 - [types/seat/wlr_seat_pointer.c:418] Pointer grab serial validation failed: button_count=5 grab_serial=90 (got 6259)
2019-06-24 10:55:11 - [types/seat/wlr_seat_touch.c:371] Touch grab serial validation failed: num_points=0 grab_serial=0 (got 6259)
2019-06-24 10:55:11 - [sway/input/seat.c:349] Ignoring start_drag request: could not validate pointer or touch serial 6259
```
* Configuration File:

https://github.com/luispabon/sway-dotfiles/tree/master/configs/sway

Looks similar to https://github.com/swaywm/sway/issues/3801. Doesn't look like that commit is on my build though but some of the code has changed so much since then I wouldn't be able to patch 1.1 with it.

Long story short, drag & drop will stop working at some point. Sometimes on a fresh sway session, sometimes a couple of days into a session.

**Comment by emersion** [comment] 2019-06-24 10:03
Duplicate of https://github.com/swaywm/sway/issues/4235

**Closed by emersion** 2019-06-24 10:03 UTC

**Comment by luispabon** [comment] 2019-06-24 10:06
Thank you, I'll add info here in there
