### ISSUE TITLE
"Reload sway" hotkey also sends "C"  to system with german layout

### ISSUE THREAD

**Issue by fleaz** [swaywm/sway#5432] opened 2020-06-08 07:57 UTC
## Sway Version:
sway version 1.4-c632d47b (May 25 2020, branch 'master')

## Configuration File:
```
input "1241:8211:daskeyboard" {
    xkb_layout "de"
    xkb_options caps:escape
}
```

## Problem description
When pressing `$mod+Shift+c` to reload the config, the config gets reloaded but also there is a "C" (capital c) send to the system after the reload, which can be seen when focus is in a terminal or editor.

Because this doesn't happen with the default config, I compared them line by line and tried removing one after another and it boils down to the `xkb_layout "de"` in my input configuration. As soon as I remove this line, the bug is gone. It doesn't appear to be a keyboard specific problem because I can reproduce this with the internal as well as with an external keyboard.

Let me know if I can provide more information to debug this.

Best regards,
Felix

**Comment by emersion** [comment] 2020-06-08 08:41
Duplicate of https://github.com/swaywm/sway/issues/4975

**Closed by emersion** 2020-06-08 08:41 UTC
