### ISSUE TITLE
[wlr] [xwayland/xwm.c:937] Failed to get window property

### ISSUE THREAD

**Issue by AndreiSva** [swaywm/sway#8038] opened 2024-03-05 20:07 UTC
### Please fill out the following:
- **Sway Version:**
  - sway version 1.9

- **Debug Log:**
Interestingly, when redirecting the stderr the error doesn't happen anymore, so I had to copy the output manually:
```
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
2024-03-05 12:06:15 - [main.c:293] Found config * for output WL-1 ((null))
Failed to acquire service name: File exists
Is a notification daemon already running?
[2024-03-05 12:06:15.223] [info] Using configuration file /home/andrei/.config/waybar/config
[2024-03-05 12:06:15.224] [info] Discovered appearance 'dark'
[2024-03-05 12:06:15.224] [info] Using CSS file /home/andrei/.config/waybar/style.css

(waybar:79334): Gtk-WARNING **: 12:06:15.224: Theme parsing error: style.css:88:14: Not using units is deprecated. Assuming 'px'.
basic_string::_M_create
[2024-03-05 12:06:15.235] [warning] module temperature: Disabling module "temperature", Can't open /sys/class/thermal/thermal_zone0/temp
[2024-03-05 12:06:15.237] [error] media stopped unexpectedly, is it endless?
[2024-03-05 12:06:15.356] [info] Bar configured (width: 1280, height: 30) for output: WL-1
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
00:00:02.326 [wlr] [xwayland/xwm.c:937] Failed to get window property
(EE) failed to read Wayland events: Connection reset by peer
[2024-03-05 12:06:17.838] [error] Workspaces: Unable to receive IPC header
[2024-03-05 12:06:17.838] [error] Mode: Unable to receive IPC header
[2024-03-05 12:06:17.838] [error] Scratchpad: Unable to receive IPC header
Gdk-Message: 12:06:17.838: Error reading events from display: Broken pipe
[2024-03-05 12:06:17.838] [error] Window: Unable to receive IPC header
[2024-03-05 12:06:17.838] [error] Workspaces: Unable to receive IPC header
Segmentation fault (core dumped)
X connection to :2 broken (explicit kill or server shutdown).
```

- **Configuration File:**
  - Able to reproduce with default config

- **Stack Trace:**
```
#0  0x00007f98e2ca14ab in wl_list_remove () from /nix/store/1iixlnbx1rh7mrwdr5javns99cylgikr-wayland-1.22.0/lib/libwayland-server.so.0
No symbol table info available.
#1  0x000000000045dd3d in handle_dissociate ()
No symbol table info available.
#2  0x00007f98e2c9ca0c in wl_signal_emit_mutable ()
   from /nix/store/1iixlnbx1rh7mrwdr5javns99cylgikr-wayland-1.22.0/lib/libwayland-server.so.0
No symbol table info available.
#3  0x00007f98e2c1fd45 in xwayland_surface_dissociate ()
   from /nix/store/bj51qzlvs4kx97bgnj8682ppf064n577-wlroots-0.17.1/lib/libwlroots.so.12
No symbol table info available.
#4  0x00007f98e2c2296f in x11_event_handler () from /nix/store/bj51qzlvs4kx97bgnj8682ppf064n577-wlroots-0.17.1/lib/libwlroots.so.12
No symbol table info available.
#5  0x00007f98e2c9e99f in wl_event_loop_dispatch ()
   from /nix/store/1iixlnbx1rh7mrwdr5javns99cylgikr-wayland-1.22.0/lib/libwayland-server.so.0
No symbol table info available.
#6  0x00007f98e2c9c455 in wl_display_run () from /nix/store/1iixlnbx1rh7mrwdr5javns99cylgikr-wayland-1.22.0/lib/libwayland-server.so.0
No symbol table info available.
#7  0x0000000000412034 in main ()
No symbol table info available.
```

- **Description:**
  - install The Powder Toy flatpak https://flathub.org/apps/uk.co.powdertoy.tpt
    - `flatpak install uk.co.powdertoy.tpt` 
  - Run `flatpak run uk.co.powdertoy.tpt`

**Comment by emersion** [comment] 2024-03-05 20:12
Duplicate of https://github.com/swaywm/sway/issues/7895

**Closed by emersion** 2024-03-05 20:12 UTC
Labels: bug
