### ISSUE TITLE
Output config reloads with 'swaymsg reload'

### ISSUE THREAD

**Issue by jasperro** [swaywm/sway#4305] opened 2019-07-05 13:14 UTC
NVIDIA: no
version: 1.1-rc1-47-gb59139c2 (Jun 22 2019, branch 'master')
configuration file: https://gist.github.com/jasperro/aa237e0201885970f5cec45d513f11f5

When I run `swaymsg reload` and my laptop lid is closed, the laptop display is enabled again, which is not what I want. I don't know if this is a bug, or an intended feature.

I tried adding `exec_always cat /proc/acpi/button/lid/LID0/state | awk '{print $2}' | grep -q 'closed' && swaymsg output 'Unknown 0x1E3D 0x00000000' toggle &` to the end of my config file, which works, but crashes alacritty (terminal) and breaks right-click menus in firefox.

My proposal is to only load output configuration on first start and not reload it after that.

**Comment by RedSoxFan** [comment] 2019-07-06 03:05
Resetting the output configs on reload is intended behavior and is not going to change.

However, I think allowing bindswitch bindings to be re-executed on reload would be acceptable. 

> crashes alacritty

That would probably be #3625 

> breaks right-click menus in firefox

Based on your config, it looks like that's a firefox bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1423598). It's fixed in nightly and looks like it should ship with firefox 68.

**Comment by jasperro** [comment] 2019-07-06 05:57
Yes, that would be good as well. I already have my bindswitches set up correctly and it would fix the issue.

**Closed** 2019-07-09 07:00 UTC
