### ISSUE TITLE
Sway crashes when using drag and drop in Qt5 applications

### ISSUE THREAD

**Issue by p-hamann** [swaywm/sway#3768] opened 2019-02-24 10:52 UTC
I've built sway with the current head (d4b1e71b) and since then Sway crashes everytime using drag and drop in Qt5 applications. wlroots is built based on the current head, too.

Sway's debug output:
2019-02-24 11:38:53 - [types/wlr_surface.c:609] New wlr_surface 0x55e342181c30 (res 0x55e342180a80)
2019-02-24 11:38:53 - [sway/sway/input/cursor.c:1162] denying request to set cursor from unfocused client
2019-02-24 11:38:54 - [types/wlr_surface.c:609] New wlr_surface 0x55e342182760 (res 0x55e3421803a0)
2019-02-24 11:38:54 - [types/xdg_shell/wlr_xdg_surface.c:438] new xdg_surface 0x55e342182a80 (res 0x55e34217e2a0)
2019-02-24 11:38:54 - [sway/sway/desktop/xdg_shell.c:480] New xdg_shell popup
(EE)2019-02-24 11:38:55 -  failed to read Wayland events: Broken pipe
[sway/common/ipc-client.c:80] Unable to receive IPC response

... and the corresponding dmesg output:
[ 1420.249392] pcmanfm-qt[5469]: segfault at 30 ip 00007f189c4dc1d6 sp 00007fffa1230100 error 4 in libQt5Core.so.5.12.1[7f189c2e7000+2ca000]
[ 1419.949618] sway[5443]: segfault at 20 ip 00007f94a75bef90 sp 00007fff41ba80e8 error 4 in libwlroots.so.0.0.0[7f94a75a1000+4a000]

... and the coredump:
Stack trace of thread 5443:
#0  0x00007f94a75bef90 data_offer_dnd_finish (libwlroots.so.0)
#1  0x00007f94a75bf2d5 data_offer_destroy (libwlroots.so.0)
#2  0x00007f94a75e7bce wlr_signal_emit_safe (libwlroots.so.0)
#3  0x00007f94a75bf80b wlr_data_source_destroy (libwlroots.so.0)
#4  0x00007f94a75bfae8 data_source_handle_resource_destroy (libwlroots.>
#5  0x00007f94a7628c7f n/a (libwayland-server.so.0)
#6  0x00007f94a7628cef wl_resource_destroy (libwayland-server.so.0)
#7  0x00007f94a688e6d0 ffi_call_unix64 (libffi.so.6)
#8  0x00007f94a688e0a0 ffi_call (libffi.so.6)
#9  0x00007f94a762c6ff n/a (libwayland-server.so.0)
#10 0x00007f94a76290a3 n/a (libwayland-server.so.0)
#11 0x00007f94a762a702 wl_event_loop_dispatch (libwayland-server.so.0)
#12 0x00007f94a76292ac wl_display_run (libwayland-server.so.0)
#13 0x000055e3413a21b7 server_run (sway)
#14 0x000055e3413a16f1 main (sway)
#15 0x00007f94a7362223 __libc_start_main (libc.so.6)
#16 0x000055e341393e6e _start (sway)

**Comment by emersion** [comment] 2019-02-24 11:08
Duplicate of https://github.com/swaywm/wlroots/issues/1570

**Closed by emersion** 2019-02-24 11:08 UTC
