### ISSUE TITLE
Sway 1.4: Something causes terminal command with redirect, piping and tee to malfunction. Bug?

### ISSUE THREAD

**Issue by scott092707** [swaywm/sway#5529] opened 2020-07-09 00:14 UTC
I use the browser SlimJet, whose output I sometimes need to file bugs for it.
Therefore, I launch it from a terminal, and if I need something from the output, I cut/paste it into a text editor, after I quit SJ.

I wanted to automate the operation, so that I could both look at the output, and also have it saved to a file.

Research led me to the following command, which when launched from a non-Sway session (Debian testing LXQt), works fine:

flashpeak-slimjet 2>&1 | tee -i /home/scott/Desktop/$(date +"%Y%m%d:%H%M%S_")SlimJetFromTerminal.txt

However, when I tried the following in Sway's config file:

exec $term -e 'flashpeak-slimjet 2>&1 | tee -i /home/scott/Desktop/$(date +"%Y%m%d:%H%M%S_")SlimJetFromTerminal.txt'

The terminal opens, SlimJet opens, but somehow SlimJet has appropriated the rest of the line, and attempts to load various pieces of it in separate tabs (will [attempt to] attach various screenshots).  
The tee is not accomplished, and no file is stored. ('tee' is one of the tabs SJ tries to open).

(By the way, is there any way of having the terminal stick around after the command invoked with it is ended?)

scott@ASUS-Prime-B350M-A-CSM:~$ apt-cache policy sway
sway:
  Installed: 1.4-2
  Candidate: 1.4-2
  Version table:
 *** 1.4-2 500
        500 https://deb.debian.org/debian testing/main amd64 Packages
        100 /var/lib/dpkg/status

The terminal invoked is $term which (unchanged in config) is x-terminal-emulator, which invokes Qterminal, the same term that
I use in LXQt. (i.e. the same terminal where I have success in LXQt session, and failure in Sway session).

scott@ASUS-Prime-B350M-A-CSM:~$ apt-cache policy qterminal
qterminal:
  Installed: 0.14.1-1+b1
  Candidate: 0.14.1-1+b1
  Version table:
 *** 0.14.1-1+b1 500
        500 https://deb.debian.org/debian testing/main amd64 Packages
        100 /var/lib/dpkg/status

FWIW:
scott@ASUS-Prime-B350M-A-CSM:~$ apt-cache policy slimjet
slimjet:
  Installed: 26.0.3.0
  Candidate: 26.0.3.0
  Version table:
 *** 26.0.3.0 100
        100 /var/lib/dpkg/status

When I was researching the situation, I tried to abstract out the date command into a variable, SJdatetime, which you will see in the first screenshot.  
#set $SJdatetime eval $(date +"%Y%m%d:%H%M%S_")
#set $SJfile /home/scott/Desktop/${SJdatetime}SlimJetFromTerminal.txt
#exec $term -e 'flashpeak-slimjet 2>&1 | tee $SJfile &'

When I did that, SJ reached the end of the filename.  With the command as above (2nd/3rd screenshots), SJ ends its tabs with the text 'date'.
![20200702_190258_Grimshot](https://user-images.githubusercontent.com/7544310/86982207-b9fdfd00-c156-11ea-9e96-71f90432c055.png)
![20200708_195913_Grimshot](https://user-images.githubusercontent.com/7544310/86982208-b9fdfd00-c156-11ea-90b2-4a47704e5c9d.png)
![20200708_200040_Grimshot](https://user-images.githubusercontent.com/7544310/86982210-ba969380-c156-11ea-9cd8-f86284608ecb.png)

**Comment by distek** [comment] 2020-07-09 01:47
Is there a particular reason you need to run it with an actual terminal application?

If not, this seems to work:
```
bindsym exec ls -al /doesntexist 2>&1 | tee -i /home/distek/Desktop/`date +%Y%m%d:%H%M%S`_SlimJetFromTerminal.txt
```

`date` wasn't working with `$(this)` so I opted for the backtick/grave's instead.

**Comment by scott092707** [comment] 2020-07-10 00:13
Well, I guess we're getting closer...

Altering the command to use `` instead of $()

flashpeak-slimjet 2>&1 | tee -i /home/scott/Desktop/`date +"%Y%m%d:%H%M%S_"`SlimJetFromTerminal.txt

now works from qterminal in my Sway session, as well as from my LXQt session.

However, embedding it in the config file exec command:

exec $term -e 'flashpeak-slimjet 2>&1 | tee -i /home/scott/Desktop/`date +"%Y%m%d:%H%M%S_"`SlimJetFromTerminal.txt'

exhibits the same symptoms as before: no tee, and SJ attempts to load the rest of the line (only up to "date") as tabs.

**Comment by scott092707** [comment] 2020-07-10 01:31
>Is there a particular reason you need to run it with an actual terminal application?

I like to be able to refer to the output while SJ is running, to compare what it is doing with what it is outputting to the terminal,
in case it is doing something strange.
This way, I don't have to wait until I close SJ, and then edit the file, to see what it printed.

**Comment by progandy** [comment] 2020-07-10 07:32
That is not a sway bug, but probably wrong arguments for your $term. xterm for example uses -e differently than gnome-terminal.

**Comment by Geo25rey** [comment] 2020-07-10 18:16
`exec '$term --hold -e bash -norc -c "ls /doesnotexist 2>&1 | tee -i ~/$(date +\"%Y%m%d:%H%M%S_\")SlimJetFromTerminal.txt"'`

@scott092707 This produces the desired behavior, but it only works with alacritty and not qterminal. And I can confirm this isn't a bug in Sway. It's actually a bug in Qterminal.

**Comment by scott092707** [comment] 2020-07-12 23:32
>It's actually a bug in Qterminal.

Well, then its actually ALSO a bug in Sakura, which I have used before, and have just installed.

exec sakura --hold -e 'flashpeak-slimjet 2>&1 | tee -i /home/scott/Desktop/`date +"%Y%m%d:%H%M%S_"`SlimJetFromTerminal.txt'

and

flashpeak-slimjet 2>&1 | tee -i /home/scott/Desktop/`date +"%Y%m%d:%H%M%S_"`SlimJetFromTerminal.txt'

launched directly from Sakura 

pruduce exactly the same result as before - no tee, and SJ trying to launch parts of the exec line as tabs.

[I see that the comment system has been eating the backticks, and displaying the interior in a light grey background - they ARE actually there...
(...and NO, I did NOT choose to make this paragraph huge and boldface...)]
------------------------------------------
I will try: Sakura's OTHER execute parameter, -x
and your 'bash -norc -c ... ' style
and then perhaps the other default installed [Debian?]/[LXQt]? terms, xterm, uxterm, and Thai X term (?!?),
and see how universal this bug is...

**Comment by scott092707** [comment] 2020-07-13 00:31
Manually, from the terminal, calling:

With the same command, but with -x instead of -e ---- same result.

sakura --hold -e bash -norc -c "flashpeak-slimjet 2>&1 | tee -i /home/scott/Desktop/`date +\"%Y%m%d:%H%M%S_\"`SlimJetFromTerminal.txt"

does not result in SJ trying to open the filename as a series of tabs, but neither does the tee work...

I will next try the same thing, but with the original $() syntax, instead of backticks...

**Comment by scott092707** [comment] 2020-07-13 00:47
sakura --hold -e bash -norc -c "flashpeak-slimjet 2>&1 | tee -i /home/scott/Desktop/$(date +\"%Y%m%d:%H%M%S_\")SlimJetFromTerminal.txt"

did the same thing as with backticks surrounding the date command.

HOWEVER, if I surround the bash command with single quotes:

sakura --hold -e 'bash -norc -c "flashpeak-slimjet 2>&1 | tee -i /home/scott/Desktop/$(date +\"%Y%m%d:%H%M%S_\")SlimJetFromTerminal.txt" '

... then I finally get the right result: no funny browser tabs trying to load parts of the filename, and the tee worked.

I will try this from the config file, after logging out/in...

**Comment by scott092707** [comment] 2020-07-13 01:04
Well, that's OK then...

I will next (probably not today), try the original command:

$term -e 'flashpeak-slimjet 2>&1 | tee -i /home/scott/Desktop/$(date +"%Y%m%d:%H%M%S_")SlimJetFromTerminal.txt'

with sakura from my LXQt session.

**Comment by emersion** [comment] 2020-07-13 15:44
Closing because this isn't a Sway bug.

**Closed by emersion** 2020-07-13 15:44 UTC
