### ISSUE TITLE
Display configuration not reapplied after unplugging and replugging dock

### ISSUE THREAD

**Issue by cherti** [swaywm/sway#7062] opened 2022-06-10 18:33 UTC
### Description/steps to reproduce:
  1. Start sway on a multimonitor setup where the screens are attached via dock.
  2. Unplug dock. -> sway moves all workspaces onto the Laptop display.
  3. Replug dock.

**What should happen:**
  4. Sway reapplies display configuration for the attached displays and moves all workspaces accordingly, at the very latest when the configuration is reloaded.

**What actually happens:**
  4. sway keeps the automatically assigned layout (i.e. just placing displays on the Laptop's display's right, no scaling or rotation applied) (log1, see below)
  5. Reload sway config -> should apply display configuration, nothing happens
  6. exit sway completely, go back to tty, start sway again from scratch -> display layout as configured is not applied, even though all displays are present, they are sorted as if there wasn't any config, i.e. to the Laptop's display's right. (log2, see below)

### Details:
- **Sway Version:** 1.7`

- **Debug Log:**
  - log 1: https://gist.github.com/cherti/40258401763ec7d6b1c1a757f2b2aaa7
  - log 2: https://gist.github.com/cherti/42e0a623512e0496eeab4043dcba3a73

- **Configuration File:** https://gist.github.com/cherti/84984fbc933ab8a6847dd2ac7c181afe

**Comment by YellowOnion** [comment] 2022-06-10 20:49
Something I've noticed is that XWayland creates a new display, instead of reusing the old one, Not sure if it's related to this, but it hints at it.

**Comment by bascht** [comment] 2022-07-27 07:50
Stumbled across the same thing - not sure if it's related but it shows the same symptoms. After unplugging / replugging my laptop a few times, I accumulated an impressive number of displays in XWayland:

This is what it is supposed to look like:

![Screenshot-2022-07-27-094801](https://user-images.githubusercontent.com/51264/181192112-2926335f-4289-47b8-a822-1b47cacc1fcd.png)

After unplugging / replugging a few times:

![Screenshot-2022-07-26-162011](https://user-images.githubusercontent.com/51264/181191416-5f0a0040-ea90-4558-a79d-ab9d2ce1a3ed.png)

**Comment by emersion** [comment] 2022-07-27 07:51
What does `wayland-info` show? As many outputs as Xwayland, or less?

**Comment by spagootie** [comment] 2022-08-17 07:41
> What does `wayland-info` show? As many outputs as Xwayland, or less?

Different user here, but I reproduced the issue. The following files contain the outputs of xrandr and wayland-info respectively, right after turning off one of my monitors and turning it off again. 

Here is the part of my Sway config that sets up my monitors:
```
output HDMI-A-1 pos 0 0
output DP-3 mode 1920x1080@165Hz pos 1920 0 # this is the one I want to be primary
output DP-3 adaptive_sync on
workspace 1 output DP-3
workspace 2 output DP-3
workspace 3 output DP-3
workspace 4 output HDMI-A-1
workspace 5 output HDMI-A-1
workspace 6 output HDMI-A-1
exec_always xrandr --output $(xrandr | grep -m 1 XWAYLAND | awk '{print $1;}') --primary # sets the XWAYLAND display with the lowest number as the primary 
```
And here are the outputs:

[xrandr.log](https://github.com/swaywm/sway/files/9357486/xrandr.log)
[wayland-info.log](https://github.com/swaywm/sway/files/9357490/wayland-info.log)

**Comment by ackstorm23** [comment] 2022-11-06 18:50
Have you run `swaymsg -t get_outputs` to verify they came back as the same device names?

I am having a problem my dock as well where unplugging and replugging my dock causes DP-4 and DP-5 to become DP-6 and DP-7.   Since they show up as new displays, they don't use the configuration for the original device names.

While I can add a DP-6 and DP-7 to my config which appears to work when this happens, they do not re-detect the same every time (sometimes one device *does* use the old name, whole the second does not)

**Comment by smlx** [comment] 2022-11-07 05:53
I also see `DP-n` output numbers incremented on plug/unplug. However you can fix this behaviour using [kanshi](https://sr.ht/~emersion/kanshi/) and output descriptions instead of names. e.g. my `~/.config/kanshi/config` looks similar to this:

```
profile {
	output eDP-1 enable scale 2
}
profile {
	output eDP-1 disable
	output 'Samsung Electric Company LU28R55 H4XYZ00321' enable scale 2 position 0,0
	output 'Samsung Electric Company LU28R55 H4XYZ00123' enable scale 2 position 1920,0
}
```

**Comment by ackstorm23** [comment] 2023-01-09 18:59
> I also see `DP-n` output numbers incremented on plug/unplug. However you can fix this behaviour using [kanshi](https://sr.ht/~emersion/kanshi/) and output descriptions instead of names. e.g. my `~/.config/kanshi/config` looks similar to this:
> 
> ```
> profile {
> 	output eDP-1 enable scale 2
> }
> profile {
> 	output eDP-1 disable
> 	output 'Samsung Electric Company LU28R55 H4XYZ00321' enable scale 2 position 0,0
> 	output 'Samsung Electric Company LU28R55 H4XYZ00123' enable scale 2 position 1920,0
> }
> ```

The problem with this is that they don't always increment and sometimes I end up with one  incrementing and the other not, which then causes me to have conflicting display settings because two monitors have both become the 'left' monitor. 

Ultimately it should not be incrementing at all. It should let go of a monitor if it is removed so that when it is re-attached it detects as the same display again instead of leaving a dead, unused monitor that will never show up again that causes the offset in the first place.

So the real question is - why doesn't it let go of the monitor when it disconnects? Why does it hang onto it and then create a NEW one when the same hardware reconnects?

**Comment by ackstorm23** [comment] 2023-01-09 21:59
Someone is making traction on this for AMD chipsets

1. https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3560
2. https://gitlab.freedesktop.org/drm/amd/-/issues/2340

I hope to post one in the Intel issues list soon as I am not using AMD

**Comment by smlx** [comment] 2023-01-10 00:51
> The problem with this is that they don't always increment and sometimes I end up with one incrementing and the other not, which then causes me to have conflicting display settings because two monitors have both become the 'left' monitor.

Sorry, I don't understand. Even if the output name increments this config should work because it uses the output description which is static?

**Comment by ackstorm23** [comment] 2023-01-10 02:48
> > The problem with this is that they don't always increment and sometimes I end up with one incrementing and the other not, which then causes me to have conflicting display settings because two monitors have both become the 'left' monitor.
> 
> Sorry, I don't understand. Even if the output name increments this config should work because it uses the output description which is static?

1. The initial config has DP-4 (Left) and DP-5 (Right).  
2. The alternative config has DP-6 (Left) and DP-7 (Right)
3. If I unplug and replug my dock,  and DP-5 changes to DP-6, I have two Left configurations.   (This has actually happened!)

**Comment by emersion** [comment] 2023-01-24 15:52
The connectors are created and destroyed on-the-fly with DP-MST. This behavior for connector names is by design.

The solution here is to improve Sway and make it possible to configure outputs by port path (which would contain GPU path + KMS PATH prop).

**Comment by YellowOnion** [comment] 2023-01-25 02:33
> I suppose I could buy an EDID emulator for one port that creates a different static name.

perhaps try software method: https://wiki.archlinux.org/title/kernel_mode_setting#Forcing_modes_and_EDID

**Comment by ackstorm23** [comment] 2023-02-02 20:12
The result of [my issue filed for the Intel driver ](https://gitlab.freedesktop.org/drm/intel/-/issues/7827) is [a proposed merge into wlroots](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3979) that seems promising as a way to prevent this problem.

**Comment by ackstorm23** [comment] 2023-02-02 20:14
> > I suppose I could buy an EDID emulator for one port that creates a different static name.
> 
> perhaps try software method: https://wiki.archlinux.org/title/kernel_mode_setting#Forcing_modes_and_EDID

The kernel increments device numbers each time a device is unplugged and plugged, and not necessarily in order, which would not work around the problem as the devices could still end up backwards.

**Comment by Guy-Chan** [comment] 2023-05-10 06:18
Hi Guys,
I think the section of sway-output(5) could be the answer if we can tell the differences between monitors by make, model and serial:
```
DESCRIPTION
...
Some outputs may have different names when disconnecting and reconnecting. To identify
these, the name can be substituted for a string consisting of the make, model and serial
which you can get from swaymsg -t get_outputs. Each value must be separated by one space.
For example:

    output "Some Company ABC123 0x00000000" pos 1920 0
```

**Comment by ackstorm23** [comment] 2023-05-10 16:23
> Hi everyone,
> 
> I believe the solution to our problem might be found in the sway-output(5) section, specifically in using a string consisting of the make, model, and serial of the monitor to identify it, as described below:
> 
> ```
> DESCRIPTION
> ...
> Some outputs may have different names when disconnecting and reconnecting. To identify
> these, the name can be substituted for a string consisting of the make, model and serial
> which you can get from swaymsg -t get_outputs. Each value must be separated by one space.
> For example:
> 
>     output "Some Company ABC123 0x00000000" pos 1920 0
> ```
> 
> However, I'm unsure if there is a way to create an alias for this string, which would be very useful when defining shortcuts to move workspaces between the different outputs. If anyone has any insights into this, it would be greatly appreciated.grinning

Unfortunately this only works if the displays have serial numbers in get_outputs. My displays do not  have a serial number, so it does not work.

**Comment by radrow** [comment] 2023-08-01 09:41
Having the same issue. To add a quirk to it, after re-plugging one of the screens is always set to `inactive` and it is impossible to activate it.

**Comment by ackstorm23** [comment] 2023-08-12 21:55
> Having the same issue. To add a quirk to it, after re-plugging one of the screens is always set to `inactive` and it is impossible to activate it.

Most of the time my displays come back functional but as the wrong device names.  But sometimes one of them will refuse to come back and I have no choice but to restart sway.  (the device names don't go back to normal until I reboot the box, but at least I get both displays back in sway)

**Comment by ackstorm23** [comment] 2023-08-12 21:57
> > Hi everyone,
> > I believe the solution to our problem might be found in the sway-output(5) section, specifically in using a string consisting of the make, model, and serial of the monitor to identify it, as described below:
> > ```
> > DESCRIPTION
> > ...
> > Some outputs may have different names when disconnecting and reconnecting. To identify
> > these, the name can be substituted for a string consisting of the make, model and serial
> > which you can get from swaymsg -t get_outputs. Each value must be separated by one space.
> > For example:
> > 
> >     output "Some Company ABC123 0x00000000" pos 1920 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, I'm unsure if there is a way to create an alias for this string, which would be very useful when defining shortcuts to move workspaces between the different outputs. If anyone has any insights into this, it would be greatly appreciated.grinning
> 
> Unfortunately this only works if the displays have serial numbers in get_outputs. My displays do not have a serial number, so it does not work.

Also,  if you are using a bar like swaybar and have configurations specific to your display *names*, the serial number trick only partially helps.

**Comment by vertigo65536** [comment] 2023-08-26 21:36
I'm also having this issue. I'm using hybrid GPU on a laptop, with displays connecting directly to my dGPU. The dGPU will activate when I connect external monitors, but not deactivate again when I disconnect them again, which makes me think the old connections are not being let go of when the displays are disconnected. I'm also connecting them via a usb c dock.

**Comment by radrow** [comment] 2023-10-03 11:57
I have set up `kanshi` to use device names. Everything always works straight after a reboot and also when the dock is plugged for the first time after a reboot. It *sometimes* works on replug with no reboots in between, but in most cases it does not. 

I have the same issue with direct HDMI output too (and same "rules" apply). I tried using `wdisplays` and `swaymsg` to directly set outputs with no success — if it stops working, there is no cure but to reboot.

**Comment by pati-ni** [comment] 2023-10-03 16:50
Many problems arise when I switch off an output, like a projector. It never comes back. What works is killing sway altogether and I get a login prompt in login.d with my output working. I think some of the output managing in swaywm does not manage well powering off an output, or I have a misconfigured something

**Comment by radrow** [comment] 2023-11-08 12:18
I don't know what happened but I don't have this issue anymore. At least I haven't experienced it for the last month or something like that.

**Comment by bl4ckb0ne** [comment] 2023-11-08 13:00
Closing, reopen if it occures again.

**Closed by bl4ckb0ne** 2023-11-08 13:00 UTC
Labels: bug

**Comment by barak-enso** [comment] 2023-12-11 11:24
Happening to me as well.

**Comment by pati-ni** [comment] 2023-12-11 14:44
@barak-enso Check what kernel you run, I think this behavior may be improved with newer kernels.

**Comment by mfeif** [comment] 2024-12-25 03:51
Still happening here too.

Kernel 6.1.0-28-amd64
Sway 1.7
libwlroots v 0.15.1-6

Full crashlog is [over here at reddit](https://www.reddit.com/r/swaywm/comments/1fiftsk/comment/m0dqiu6/).

**Comment by emersion** [comment] 2024-12-25 16:58
That sounds like a completely separate issue, and seems like a client bug not a Sway bug.

**Comment by mfeif** [comment] 2025-01-02 22:12
Do you see the part where Sway crashes completey?

```
ERROR: ../src/main.c: 228: Selected output went away. Exiting...
ERROR: ../src/main.c: 228: Selected output went away. Exiting...
```

**Comment by devguyio** [comment] 2025-03-12 07:34
@bl4ckb0ne this issue is still happening to me on sway 1.10.1

**Comment by emersion** [comment] 2025-03-12 07:40
Please open a separate issue.
