### ISSUE TITLE
Tiny cursor when outside of  a window

### ISSUE THREAD

**Issue by bemeurer** [swaywm/sway#3687] opened 2019-02-15 03:05 UTC
Running the latest Sway RC under Gentoo, I observe some weird behaviour with the cursor scaling. Whenever the cursor is on a window, the scaling is perfect:
![normal_1](https://user-images.githubusercontent.com/7243783/52831602-11935880-308a-11e9-81dc-ffcfc31e2500.png)
Even in a nagbar or on the statusbar the cursor still looks fine:
![normal_3](https://user-images.githubusercontent.com/7243783/52831648-40113380-308a-11e9-86b8-a1c53c02210c.png)
![normal_4](https://user-images.githubusercontent.com/7243783/52831691-62a34c80-308a-11e9-9167-0c3917028cbf.png)

If, however I move the cursor outside one of those, in particular to the gaps between windows, it becomes tiny, unscaled, like such
![abnormal_2](https://user-images.githubusercontent.com/7243783/52831727-88305600-308a-11e9-8e71-d49f5d6b649e.png)
(Notice the tiny cursor above the `buffers` line on the vim window. It's hard to find!

I have a 4K display, and I have set it up to 2X scaling, and except for those regions it works flawlessly. Here is my [sway config](https://gist.github.com/bemeurer/bffd260b993469f5880f42abd894b7ea). Also of note maybe is that it used to be, in some of the alpha/beta releases that Neither nagbars or statusbars had the proper cursor scaling, but that went away.

**Comment by RedSoxFan** [comment] 2019-02-15 06:37
Duplicate of #3014

**Closed by RedSoxFan** 2019-02-15 06:37 UTC
