### ISSUE TITLE
Moving focus away from monitor via hotkey freezes output on it until it's focused again

### ISSUE THREAD

**Issue by TimoFreiberg** [swaywm/sway#5390] opened 2020-05-26 21:00 UTC
* sway version 1.4-d71fed95 (May 26 2020, branch 'master')
I also have the same issues with sway 1:1.4-9 (packaged in the arch linux repos)

* Debug Log, configuration file: https://gist.github.com/TimoFreiberg/c47e2611aaeff0ae02afcc7736654794

Steps:
I have two monitors connected, DP-2 and HDMI-A-1.
After starting sway, DP-2 is focused.
I focus HDMI-A-1 via $mod+left, and the cursor on DP-2 is still visible, the output is frozen (it gets unfrozen as soon as I focus it again)
If i switch focus by moving the mouse over from DP-2 to HDMI-A-1, DP-2 continues working (it's a bit unreliable though, sometimes it freezes while I'm keeping HDMI-A-1 focused. I haven't noticed a cause for that and it's rare.)
The freezing seems to be accompanied by the following message being logged:
`[ERROR] [backend/drm/atomic.c:36] DP-2: Atomic commit failed (pageflip): Invalid argument`
In the minimal reproduction, this error message is logged twice, in my usual setup I get about 75 of these log messages for each freeze.

I also noticed the following log message in the debug output of the minimal reproduction, it sounds like it could have something to do with my issues: `[sway/input/cursor.c:860] denying request to set cursor from unfocused client`

**Comment by emersion** [comment] 2020-05-26 21:04
Duplicate of https://github.com/swaywm/wlroots/issues/2216

**Comment by TimoFreiberg** [comment] 2020-05-26 21:05
Ah my bad, I only searched in this repo. Thanks!

**Closed by emersion** 2020-05-26 21:04 UTC
