### ISSUE TITLE
swaybar is not working (git master - 1.4-9b5895be (May 15 2020, branch 'HEAD'))

### ISSUE THREAD

**Issue by prometheanfire** [swaywm/sway#5353] opened 2020-05-17 01:57 UTC
* Sway Version: sway version 1.4-9b5895be (May 15 2020, branch 'HEAD')

* Debug Log: https://gist.github.com/caa9bdae55cb42e841560050c04418da

* Configuration File: default (and what's in the log above) both show the issue.

* Stack Trace, if sway crashes: N/A

* Issue:

Sway bar is not displayed. I can't see anything in the log to show the reason nor does using a default config help.  Further instructions on debugging the issue if applicable would be appreciated.

**Comment by Xyene** [comment] 2020-05-17 02:43
Closing as a duplicate of https://github.com/swaywm/sway/issues/5349, see that issue for more details.

**Closed by Xyene** 2020-05-17 02:43 UTC
