### ISSUE TITLE
Assertion `wlr_egl_is_current(renderer->egl)` fails

### ISSUE THREAD

**Issue by Diegovsky** [swaywm/sway#5855] opened 2020-12-02 14:59 UTC
- **Sway Version:**
  - sway version 1.5-32b93ef6 (Nov 30 2020, branch 'master')

- **Debug Log:**
  - https://gist.github.com/Diegovsky/c576a44345d3da6f2c9cc0964b54012a

- **Stack Trace:**
  https://gist.github.com/Diegovsky/f88a05aaf82493686762531d0e57c029
- **Description:**
  - [swaybar] Upon start, move mouse from one monitor to another, then back to the first, and move the cursor towards the bar on the top.
  - [waybar] touch it.

- **Context:**
  - As suggested by #5849, installing libglvnd from master (the patch was already merged) worked.

**Comment by emersion** [comment] 2020-12-02 15:02
The backtrace you provided doesn't contain debug symbols. This most likely happens because the Sway binary you're using doesn't have debug information bundled.

Can you try again with a manually compiled Sway binary? See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by Diegovsky** [comment] 2020-12-02 15:15
There: https://gist.github.com/Diegovsky/b6d355a3ef51ed7e68c23d7883142c9a

**Comment by emersion** [comment] 2020-12-04 10:26
Duplicate of https://github.com/swaywm/wlroots/issues/2479

**Closed by emersion** 2020-12-04 10:26 UTC
Labels: bug
