### ISSUE TITLE
swayidle does not turn off screen

### ISSUE THREAD

**Issue by kaedwen** [swaywm/sway#6259] opened 2021-05-05 20:44 UTC
sway version 1.6

Using this does lock the screen after 10 seconds. 
But it does not turn off the screen after 20 seconds.

```
set $lock swaylock --screenshots --effect-blur 7x5 --fade-in 0.4
exec swayidle -w timeout 10 '$lock' timeout 20 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' before-sleep '$lock'
```

But after unlocking the screen it goes black first and comes up unlocked.

Executing this does lock the screen
```
swaymsg "output * dpms off"
```

**Comment by kennylevinsen** [comment] 2021-05-05 20:57
You are using the swayidle `-w` argument which waits for execution to finish before proceeding, but you are not using the `-f` daemonizing argument to swaylock, and so swaylock blocks swayidle.

The example config contains a valid swayidle/swaylock example. Closing as not a bug.

**Closed by kennylevinsen** 2021-05-05 20:57 UTC
