### ISSUE TITLE
segfault when plugging in a new monitor

### ISSUE THREAD

**Issue by sanga** [swaywm/sway#4759] opened 2019-11-27 10:56 UTC
I don't have a log for this sorry but steps when this happened were:

1. laptop is connected through dock to external monitor and working just fine.
2. unplugged from dock
3. plugged hdmi cable into new monitor
=> crash
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f43baf04aa0 in gbm_bo_get_user_data () from /usr/lib/x86_64-linux-gnu/libgbm.so.1
[Current thread is 1 (Thread 0x7f43ba4a59c0 (LWP 28251))]
#0  0x00007f43baf04aa0 in gbm_bo_get_user_data () at /usr/lib/x86_64-linux-gnu/libgbm.so.1
#1  0x00007f43bbc0d27d in get_fb_for_bo (bo=0x0, drm_format=875713089, with_modifiers=true) at ../backend/drm/util.c:183
        id = 0
        gbm = 0x7f43bbc0bee2 <swap_drm_surface_buffers+122>
        fd = 32579
        width = 2250448256
        height = 32767
        handles = {0, 0, 1196391224, 22036}
        strides = {2250448336, 32767, 3149971396, 32579}
        offsets = {1198294592, 22036, 1196391224, 22036}
        modifiers = {3761159080184585648, 94645097300928, 0, 4575657221408423936}
#2  0x00007f43bbc0794f in drm_connector_pageflip_renderer (conn=0x5614476c8610, mode=0x5614476c86a8) at ../backend/drm/drm.c:518
        drm = 0x5614474f8eb0
        crtc = 0x5614474f91a8
        plane = 0x5614474f7b30
        bo = 0x0
        fb_id = 12592
#3  0x00007f43bbc07b73 in drm_connector_init_renderer (conn=0x5614476c8610, mode=0x5614476c86a8) at ../backend/drm/drm.c:565
        drm = 0x5614474f8eb0
        crtc = 0x5614474f91a8
        plane = 0x5614474f7b30
        width = 12592
        height = 0
        format = 875713089
#4  0x00007f43bbc07f34 in drm_connector_set_mode (output=0x5614476c8610, wlr_mode=0x5614476c86a8) at ../backend/drm/drm.c:658
        conn = 0x5614476c8610
        drm = 0x5614474f8eb0
        mode = 0x5614476c86a8
#5  0x00007f43bbc521c3 in wlr_output_set_mode (output=0x5614476c8610, mode=0x5614476c86a8) at ../types/wlr_output.c:176
#6  0x0000561445d5b716 in apply_output_config (oc=0x0, output=0x5614477f2e40) at ../sway/config/output.c:283
        mode = 0x5614476c86a8
        wlr_output = 0x5614476c8610
        modeset_success = false
        output_box = 0x7f43bba07dba <__libc_calloc+954>
#7  0x0000561445d84f36 in output_enable (output=0x5614477f2e40, oc=0x0) at ../sway/tree/output.c:118
        __PRETTY_FUNCTION__ = "output_enable"
        wlr_output = 0x5614476c8610
        len = 4
        ws = 0x1bbcaa53e
#8  0x0000561445d433aa in handle_new_output (listener=0x561445da9018 <server+88>, data=0x5614476c8610) at ../sway/desktop/output.c:907
        server = 0x561445da8fc0 <server>
        wlr_output = 0x5614476c8610
        output = 0x5614477f2e40
        oc = 0x0
#9  0x00007f43bbc6317a in wlr_signal_emit_safe (signal=0x5614474e2238, data=0x5614476c8610) at ../util/signal.c:29
        pos = 0x561445da9018 <server+88>
        l = 0x561445da9018 <server+88>
        cursor = {link = {prev = 0x561445da9018 <server+88>, next = 0x7fff86231ff0}, notify = 0x7f43bbc630c4 <handle_noop>}
        end = {link = {prev = 0x7fff86231fd0, next = 0x5614474e2238}, notify = 0x7f43bbc630c4 <handle_noop>}
#10 0x00007f43bbc12d83 in new_output_reemit (listener=0x56144767a358, data=0x5614476c8610) at ../backend/multi/backend.c:143
        state = 0x56144767a330
#11 0x00007f43bbc6317a in wlr_signal_emit_safe (signal=0x5614474f8ed8, data=0x5614476c8610) at ../util/signal.c:29
        pos = 0x56144767a358
        l = 0x56144767a358
        cursor = {link = {prev = 0x56144767a358, next = 0x7fff86232090}, notify = 0x7f43bbc630c4 <handle_noop>}
        end = {link = {prev = 0x7fff86232070, next = 0x5614474f8ed8}, notify = 0x7f43bbc630c4 <handle_noop>}
#12 0x00007f43bbc0a992 in scan_drm_connectors (drm=0x5614474f8eb0) at ../backend/drm/drm.c:1438
        conn = 0x5614476c8610
        i = 1
        res = 0x5614476a6bb0
        seen_len = 0
#13 0x00007f43bbc052c2 in backend_start (backend=0x5614474f8eb0) at ../backend/drm/backend.c:26
        drm = 0x5614474f8eb0
#14 0x00007f43bbc03a22 in wlr_backend_start (backend=0x5614474f8eb0) at ../backend/backend.c:39
#15 0x00007f43bbc12983 in multi_backend_start (wlr_backend=0x5614474e2210) at ../backend/multi/backend.c:31
        backend = 0x5614474e2210
        sub = 0x56144767a330
#16 0x00007f43bbc03a22 in wlr_backend_start (backend=0x5614474e2210) at ../backend/backend.c:39
#17 0x0000561445d3def7 in server_start (server=0x561445da8fc0 <server>) at ../sway/server.c:198
#18 0x0000561445d3d500 in main (argc=1, argv=0x7fff86232448) at ../sway/main.c:388
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options =
            {{name = 0x561445d8e008 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x561445d8e00d "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x561445d8e014 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x561445d8e01d "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x561445d8e023 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x561445d8e02b "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x561445d8e033 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x561445d8e042 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x561445d8e052 "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x561445d8dae0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```
version info

```
sway version 1.2-ba8586e2 (Nov 20 2019, branch 'master')
wlroots=16e5e9541b3de49e397a3d2caa3212db25487648
```

**Comment by emersion** [comment] 2019-11-27 10:58
Duplicate of #4717

**Closed by emersion** 2019-11-27 10:58 UTC
