### ISSUE TITLE
sway: types/wlr_buffer.c:198: wlr_buffer_from_resource: Assertion `resource && wlr_resource_is_buffer(resource)' failed.

### ISSUE THREAD

**Issue by shoober420** [swaywm/sway#6494] opened 2021-09-07 04:48 UTC
### Please fill out the following:
- **Sway Version:**
  - sway version 1.6-ae80bded (Sept 6 2021, branch 'HEAD')
 
- **WLRoots Version:**
- https://github.com/swaywm/wlroots/commit/ba0525c5c08b31ade48368df4d2fd1bbefd1304a

- **Debug Log:**
  - [sway.log](https://github.com/swaywm/sway/files/7118917/sway.log)

- **Configuration File:**
  - https://github.com/shoober420/rootscripts/blob/main/home/shoober420/.config/sway/config

- **Description:**
  - open a terminal
  - press a key
  - sway crashes

```
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
00:00:03.187 [DEBUG] [wlr] [xwayland/selection/selection.c:147] not handling selection events: no seat assigned to xwayland
00:00:03.187 [DEBUG] [wlr] [xwayland/xwm.c:1505] unhandled X11 event: 34
00:00:03.187 [DEBUG] [wlr] [xwayland/selection/selection.c:147] not handling selection events: no seat assigned to xwayland
00:00:03.187 [DEBUG] [wlr] [xwayland/xwm.c:1505] unhandled X11 event: 34
sway: types/wlr_buffer.c:198: wlr_buffer_from_resource: Assertion `resource && wlr_resource_is_buffer(resource)' failed.
00:00:06.195 [INFO] [wlr] [libseat] [seatd/seat.c:394] No clients on seat0 to activate
[[31merror[m] wl_display_dispatch_pending() failed(EE)
 failed to read Wayland events: Broken pipe
00:00:06.438 [INFO] [wlr] [libseat] [seatd/seat.c:500] Closed client 1 on seat0
00:00:06.438 [INFO] [wlr] [libseat] [seatd/seat.c:179] Removed client 1 from seat0
The process was killed by SIGABRT: Aborted
```

**Comment by emersion** [comment] 2021-09-07 06:13
Thanks, closing as a duplicate of https://github.com/swaywm/wlroots/issues/3173.

**Closed by emersion** 2021-09-07 06:13 UTC
Labels: bug
