### ISSUE TITLE
gtk/qt tooltip/menu appear with offset when using `output $foo position x y` argument

### ISSUE THREAD

**Issue by chron-isch** [swaywm/sway#4362] opened 2019-07-23 09:06 UTC
# Problem
When you give a second output a fixed position and turn off the first output tooltips/menus appear with an offset.

caja:
![image](https://user-images.githubusercontent.com/1332352/61697837-9cf2d300-ad27-11e9-9fb8-495c4461e081.png)
pavucontrol:
![image](https://user-images.githubusercontent.com/1332352/61697861-a67c3b00-ad27-11e9-851e-78397f4c89be.png)
keepassxc:
![image](https://user-images.githubusercontent.com/1332352/61697874-af6d0c80-ad27-11e9-8c5f-43800a7812d6.png)
keepassxc:
![image](https://user-images.githubusercontent.com/1332352/61697886-b4ca5700-ad27-11e9-8830-6027e5d0306e.png)
evolution:
![image](https://user-images.githubusercontent.com/1332352/61698087-070b7800-ad28-11e9-840d-2b4cea62a7ad.png)

I use a docking-station at home/work, with multiple monitors attached. In order to configure/position all screens correctly I need the `output $foo position x y` argument, but as soon as I turn the laptop screen(position 0,0) off, menus and tooltips appear with an offset.

Hardware: Thinkpad x240 running ArchLinux with:
- community/sway 1.1.1-3
- community/wlroots 0.6.0-1

Normal behaviour without using `output HDMI-A-1 position x y` argument:

HDMI-A-1 connected, it is positioned(at 1366,0) right of eDP-1 (my laptop screen):
```
# swaymsg -t get_outputs
Output eDP-1 'Unknown 0x04E3 0x00000000' (focused)
  Current mode: 1366x768 @ 59.993000 Hz
  Position: 0,0
  Scale factor: 1.000000
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 2:www
  Available modes:
    1366x768 @ 59.993000 Hz

Output HDMI-A-1 'Unknown HP E243 CNK9030QM3'
  Current mode: 1920x1080 @ 60.000000 Hz
  Position: 1366,0
  Scale factor: 1.000000
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 4
  Available modes:
    [ removed for readability ]
    1920x1080 @ 60.000000 Hz
```
Disable Laptop screen eDP-1
```
# swaymsg output eDP-1 disable
```
HDMI-A-1 is moved to position 0,0
```
# swaymsg -t get_outputs
Output HDMI-A-1 'Unknown HP E243 CNK9030QM3' (focused)
  Current mode: 1920x1080 @ 60.000000 Hz
  Position: 0,0
  Scale factor: 1.000000
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 3:files
  Available modes:
    [ removed for readability ]
    1920x1080 @ 60.000000 Hz

Output eDP-1 'Unknown 0x04E3 0x00000000' (inactive)
  Available modes:
    1366x768 @ 59.993000 Hz
```
Tooltips work just fine:
![image](https://user-images.githubusercontent.com/1332352/61697966-db888d80-ad27-11e9-95bc-590d0a1a611c.png)

![tooltip_offset4](https://user-images.githubusercontent.com/1332352/61699864-f82ec080-ad3b-11e9-910b-f793688ddbb2.png)

![image](https://user-images.githubusercontent.com/1332352/61697998-e6432280-ad27-11e9-87ed-8beea55df989.png)

# How to reproduce:
Assign a second output a fixed position and disable the first output.
```
# swaymsg output HDMI-A-1 position 1366 0
# swaymsg output eDP-1 disable
```
```
# swaymsg -t get_outputs
Output HDMI-A-1 'Unknown HP E243 CNK9030QM3' (focused)
  Current mode: 1920x1080 @ 60.000000 Hz
  Position: 1366,0
  Scale factor: 1.000000
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 3:files
  Available modes:
    [ removed for readability ]
    1920x1080 @ 60.000000 Hz

Output eDP-1 'Unknown 0x04E3 0x00000000' (inactive)
  Available modes:
    1366x768 @ 59.993000 Hz
```
Output eDP-1 is disabled, HDMI-A-1 stays at position 1366,0.

Tooltips and menus appear with an offset:

caja:
![image](https://user-images.githubusercontent.com/1332352/61697837-9cf2d300-ad27-11e9-9fb8-495c4461e081.png)
pavucontrol:
![image](https://user-images.githubusercontent.com/1332352/61697861-a67c3b00-ad27-11e9-851e-78397f4c89be.png)
keepassxc:
![image](https://user-images.githubusercontent.com/1332352/61697874-af6d0c80-ad27-11e9-8c5f-43800a7812d6.png)
keepassxc:
![image](https://user-images.githubusercontent.com/1332352/61697886-b4ca5700-ad27-11e9-8830-6027e5d0306e.png)
evolution:
![image](https://user-images.githubusercontent.com/1332352/61698087-070b7800-ad28-11e9-840d-2b4cea62a7ad.png)

I skipped the debug log considerung the problem is easy to reproduce and not hardware specific.

If anything else is needed I'll be happy to supply it.

**Comment by RedSoxFan** [comment] 2019-07-23 17:13
Duplicate of #3135 

This is the result of applications using deprecated GTK/QT functions/methodologies that are not Wayland compatible. The applications need to be updated.

GTK: https://github.com/swaywm/sway/issues/3135#issuecomment-448794177
QT: https://github.com/swaywm/sway/issues/3135#issuecomment-459217564

**Closed by RedSoxFan** 2019-07-23 17:13 UTC

**Comment by chron-isch** [comment] 2019-07-23 21:57
Oh, sorry I did't find that one before posting this. Thank you for the information.

**Comment by chron-isch** [comment] 2019-09-06 13:41
Just FYI, in case anyone else is having this problem, pavucontrol is/was fixed here: 

Bug: https://gitlab.freedesktop.org/pulseaudio/pavucontrol/issues/63 
Commit: https://gitlab.freedesktop.org/tanuk/pavucontrol/commit/e91da3e6680f0444edf64d4209c645087848ab68

QT Bugreport is here: https://bugreports.qt.io/browse/QTBUG-53813
