### ISSUE TITLE
Can't use the webpage on iOS 14

### ISSUE THREAD

**Issue by anohren** [swaywm/sway#6279] opened 2021-05-17 21:58 UTC
- **Description:**
  - Navigate to swaywm.org with safari
  - Disable content blockers
  - Tap the top right menu button 
  - Nothing happens

iPhone 8
iOS 14.5

**Comment by fluix-dev** [comment] 2021-05-18 04:10
Duplicate of https://github.com/swaywm/sway/issues/4322

**Closed** 2021-05-18 06:37 UTC
Labels: bug
