### ISSUE TITLE
Kill command crashes sway

### ISSUE THREAD

**Issue by natesymer** [swaywm/sway#1036] opened 2017-01-07 17:55 UTC
Hey,

Before you read any farther, this bug isn't specifically reproducible. I am using sway built from commit `baa84a0`.

I got errors about not being able to access display ":0". In Journalctl, I found this stack trace from the crash:

    Stack trace of thread 30405:
    #0  0x000000000041bdae container_map (sway)
    #1  0x000000000040ffa1 cmd_kill (sway)
    #2  0x000000000040c62a handle_command (sway)
    #3  0x000000000041ee1d n/a (sway)
    #4  0x000000000041f911 n/a (sway)
    #5  0x00007f8dc2c28719 wlc_keyboard_request_key (libwlc.so.0)
    #6  0x00007f8dc2c25a3c wl_signal_emit (libwlc.so.0)
    #7  0x00007f8dc25bbd32 wl_event_loop_dispatch (libwayland-server.so.0)
    #8  0x00007f8dc25ba1da wl_display_run (libwayland-server.so.0)
    #9  0x00007f8dc2c3ab9c wlc_run (libwlc.so.0)
    #10 0x000000000040b4ad main (sway)
    #11 0x00007f8dc1123291 __libc_start_main (libc.so.6)
    #12 0x000000000040b5da _start (sway)

Looking in the code, the bug seems to be a NULL dereference on line 633 of sway/container.c. `get_focused_container()`, when called with `&root_container` seems to always lead to a segfault because when the argument is NULL, it defaults to calling swayc_active_workspace() to return a container, which in turn uses `root_container` (which is NULL).

This bug could also be caused by either a race condition in which `root_container` is set to NULL before `get_focused_container()` is called, OR it could just be an assignment bug somewhere - I don't have enough information to properly debug this, and I'm sure some of you would be more adept at this than I am.

My idea is to wrap access to root_container in a mutex or other synchronization primitive and provide accessor functions to avoid conditions like this, potentially printing a debug/warning statement when root_container is NULL.

**Comment by SirCmpwn** [comment] 2017-01-07 18:52
Are you absolutely certain root_container is null? I highly doubt it would be.

**Comment by SirCmpwn** [comment] 2017-01-07 18:56
In fact it's impossible for root_container to be null. Not just unlikely, but impossible.

**Comment by fhsjaagshs** [comment] 2017-01-07 19:23
Are you sure? Since you know more about the codebase than I, double check. I'd have more sanity checks in some of the functions I mentioned.

If it's not NULL, what could be causing this bug?

**Comment by SirCmpwn** [comment] 2017-01-07 19:24
Like I said, it's impossible for it to be NULL. It's a global statically allocated swayc_t. It isn't even NULL during initialization, it has a constant address.

**Comment by fhsjaagshs** [comment] 2017-01-08 13:33
Maybe line 927 in container.c where the argument is not checked for NULL?

**Comment by WebFreak001** [comment] 2017-04-11 17:50
For me reproducing this works by starting `mpv` and then using the kill command to kill the mpv window. Segfaults sway then. Hitting q or ctrl-c inside the terminal just closes it without segfaulting. I tried running sway with gdb but it just freezes my PC if I do that (switching to TTYs doesn't even work)

**Comment by SirCmpwn** [comment] 2018-07-25 15:51
I'm closing issues that are resolved by the yet-unreleased sway 1.0.

**Closed by SirCmpwn** 2018-07-25 15:51 UTC
