### ISSUE TITLE
Windows not rendered when using negative y output position

### ISSUE THREAD

**Issue by IMFTC** [swaywm/sway#3333] opened 2018-12-26 15:12 UTC
Adding the lines
```
output LVDS-1 resolution 1600x900  position 0,0
output VGA-1  resolution 1920x1080 position 1600,-400
```
to the default config file results in windows not being rendered when using tabbed or stacked layout, no matter if it's a single window or a container. The tabs in the tabbed layout and all title bars for the stacked layout are rendered correctly, but the space below only shows the background image.  Switching to split layout makes the window(s) visible.

Using the alternative configuration
```
output LVDS-1 resolution 1600x900  position 0,400 
output VGA-1  resolution 1920x1080 position 1600,0
```
everything works correctly.

sway version 9bf1b7a029afe2fdb07cb2bfe35cca4ad76098f9
wlroots version ed5296c6cf23efa07f78e1657cec1528f638f95e

**Comment by jeffa5** [comment] 2019-01-06 09:46
I've had the same issue with this but also Firefox and Qutebrowser (so potentially X applications?) become unresponsive to mouse interactions when in tiling layout. They still accept key presses though. Moving the applications back to a display without negative positions makes them work again until moved to a display with negative pos.

**Comment by emersion** [comment] 2019-01-06 09:50
>I've had the same issue with this but also Firefox and Qutebrowser (so potentially X applications?) become unresponsive to mouse interactions when in tiling layout. They still accept key presses though. Moving the applications back to a display without negative positions makes them work again until moved to a display with negative pos.

This is an Xwayland bug.

**Comment by edrex** [comment] 2019-01-15 01:31
When this issue is triggered on my setup (primary display scale 2, negative y on scale 1 display) the tab text is rendered 2x normal (like the tabs think they are on the scale 2 display). 

![negative-output-position-corruption](https://user-images.githubusercontent.com/14615/51149434-f9c07e80-1816-11e9-9a8a-b25b0cac658a.png)

![negative-output-position-corruption-stacked](https://user-images.githubusercontent.com/14615/51149352-99314180-1816-11e9-91c3-5e298d0d30b9.png)

It could be a separate issue but I'm guessing they have the same root cause.

**Comment by ThomasLeister** [comment] 2019-02-17 09:39
I'm having similar issues with negative display positions. if I use this configuration:

```
output eDP-1 {
        pos 0 0
}

output DP-4 {
	scale 1.2
        pos 1 -1800
        res 3840x2160
}
```

Some applications on DP4 (to one with the negative position argument) do not respond to mouse pointer, e.g. Mozilla Firefox, Mozilla Thunderbird and VirtualBox (Qt 5.6.1).

Other applications do work as expected: Gnbome Terminal, Nautilus, Dino XMPP Client, KeePassXC (Qt 5.11.3), Virt-Manager and Firefox Nightly with Native wayland supported.

All in all: 

> This is an Xwayland bug.

Can confirm. Maybe there should be a warning about that issue on the Sway wiki in the "Outputs" section? :-)

**Comment by emersion** [comment] 2019-02-17 09:44
>Maybe there should be a warning about that issue on the Sway wiki in the "Outputs" section? :-)

The better solution would be an Xwayland patch.

**Comment by RedSoxFan** [comment] 2019-03-11 03:32
@edrex are you able to reproduce the tab scaling issue on master? If so, can you provide a minimal config for reproduction?

If the scaling bug is not reproducible, I'm going to close this issue. The tabbed/stacked children not being rendered bug is fixed by #3848 and the input issue is a xwayland bug, not a sway bug.

**Comment by edrex** [comment] 2019-03-11 04:52
I can reproduce it with a single display just by setting the y coord negative:

```swaymsg output eDP-1 pos "0 -3000"```

**Comment by edrex** [comment] 2019-03-11 04:54
Oops, I see your change, need to test on master

**Comment by edrex** [comment] 2019-03-11 04:59
Still reproducable on master

**Comment by edrex** [comment] 2019-03-11 05:02
Seems fixed on master. I forgot to install the binary before I ran sway. Long day+sick.

**Comment by edrex** [comment] 2019-03-11 05:06
I haven't tested the weird tab size issue I previously reported since I don't have my display dongle with me, will test once I have it and report a new issue if it still happens.

**Closed** 2019-03-25 03:53 UTC

**Comment by HerrBerg** [comment] 2020-11-27 15:30
When I understood @edrex correctly, this should hav been fixed.
But I have the same issue as OP in current version (sway 1.5.1).

After `swaymsg output eDP-1 pos "0 -3000"` e.g. google chrome isn't responsive to mouse events enymore.

**Comment by TheAvidDev** [comment] 2020-11-27 22:55
> google chrome isn't responsive to mouse events anymore.

> the input issue is a xwayland bug, not a sway bug
