### ISSUE TITLE
Crash on application launch

### ISSUE THREAD

**Issue by HardDie** [swaywm/sway#6172] opened 2021-04-09 11:09 UTC
- **Sway Version:**
  - `sway version 1.5.1`

- **Debug Log:**
https://gist.github.com/HardDie/c0d4e36595e5a62d0303554827076bd8

- **Configuration File:**
`bindsym --to-code Ctrl+Mod1+t exec termite`

- **Stack Trace:**
https://gist.github.com/HardDie/1518afe71cf4ef019f541e692f2c26f4

- **Description:**
1) Run the application immediately after starting the system.
I am using an application inside a docker container.
The crash can only be reproduced on one of my machines.

**Comment by kennylevinsen** [comment] 2021-04-09 11:19
Please test sway 1.6

**Comment by XDjackieXD** [comment] 2021-04-15 12:20
I can confirm this with sway on arch with sway 1.5.1.
For me it happens with thunderbird when starting it in the first minute or so.

**Comment by emersion** [comment] 2021-04-15 12:21
Fixed in 1.6, this is due to Xwayland sending SIGUSR1.

**Closed by emersion** 2021-04-15 12:21 UTC
Labels: bug
