### ISSUE TITLE
Running chromium with ozone flags ends up in memory dump

### ISSUE THREAD

**Issue by nwg-piotr** [swaywm/sway#6524] opened 2021-09-15 23:11 UTC
- **Sway Version:**
  - `sway version 1.6-8d0a84f3 (Sep 15 2021, branch 'master')`

- **Debug Log:**
  - https://gist.github.com/nwg-piotr/6acf04fc325a4d336fe3cc540c07c7be

- **Description:**
  - Chromium won't start:
```text
$ /usr/bin/chromium --enable-features=UseOzonePlatform --ozone-platform=wayland
[76851:76873:0916/005821.641754:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[76851:76873:0916/005821.642834:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[76851:76873:0916/005821.668156:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[76851:76873:0916/005821.668205:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[76888:76888:0916/005821.743991:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is egl
[76888:76888:0916/005821.747552:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[76851:76851:0916/005821.991329:ERROR:platform_shared_memory_region_posix.cc(47)] Descriptor access mode (0) differs from expected (2)
[76889:76901:0916/005822.933787:ERROR:ssl_client_socket_impl.cc(981)] handshake failed; returned -1, SSL error code 1, net_error -3
Pułapka debuggera/breakpoint (zrzut pamięci)
```

**Comment by tokyovigilante** [comment] 2021-09-16 01:36
Also seeing this with the latest Vivaldi (Chromium 93) with ozone enabled on amdgpu (Radeon VII).

**Comment by nwg-piotr** [comment] 2021-09-16 01:42
Just in case: I'm on amdgpu (hybrid) as well.

**Comment by tokyovigilante** [comment] 2021-09-16 02:03
It has only been happening to me in the last week or so too, will try a bisect from that commit if I can confirm.

**Comment by emersion** [comment] 2021-09-16 06:39
Duplicate of https://github.com/swaywm/wlroots/issues/3168

**Closed by emersion** 2021-09-16 06:39 UTC
Labels: bug
