### ISSUE TITLE
Firefox won't show context menus on scaled monitor (and stop rendering)

### ISSUE THREAD

**Issue by rodrigoramos** [swaywm/sway#6464] opened 2021-08-26 23:55 UTC
Hi there, 

When I try to open a context menu on Firefox like alternative-mouse-click over a tab or even options from installed Firefox plugin, the menu it self doesn't show up. And sometimes Firefox stop to be rendered. If I switch workspace, it renders the last action and then stops again.

However, this occurs only if I am using Firefox in a scaled monitor like the following configuration:
```
output HDMI-A-1 resolution 3840x2140 scale 1.4
```
That's the video on scaled monitor:
https://user-images.githubusercontent.com/1568265/131050418-3814d800-4528-46ba-9f1b-70db3e7a6417.mp4

That's the video on *non-scaled* monitor:
https://user-images.githubusercontent.com/1568265/131050452-5370aa22-ba8e-425f-b66d-4ca009486619.mp4

I'm using sway version 1.6.1 and Mozilla Firefox 91.0.2.

****

**Comment by RPigott** [comment] 2021-08-28 00:08
Closing as dupe of #6426. Despite the title FF91 is partially affected, and the patch there should apply too.

**Closed by RPigott** 2021-08-28 00:08 UTC
Labels: bug
