### ISSUE TITLE
Double cursor after connecting and disconnecting an external display

### ISSUE THREAD

**Issue by klardotsh** [swaywm/sway#2497] opened 2018-08-20 01:33 UTC
Not sure if this is directly related to some of the existing cursor tickets or not, so I figured I'd open a new one and hope this is the right call.

The laptop I'm testing Sway (1.0-alpha.5) on has a HiDPI display which I've scaled 1.75. I plugged in an external display (1.0 scaling), then unplugged it and noticed I had two mouse cursors. One is huge, the other is the size I'd expect.

Some windows open are native Wayland (termite, waybar), others are Xwayland (Firefox, Steam).

If I can provide any log or config output to help diagnose this, give me a holler, and if this is a duplicate ticket, sorry! I tried taking a screenshot of this, but apparently only the correct cursor ends up in the image - the huge cursor is only on my display?

**Comment by emersion** [comment] 2018-08-20 07:01
Duplicate of https://github.com/swaywm/sway/issues/2486

**Closed by emersion** 2018-08-20 07:01 UTC
