### ISSUE TITLE
Gimp menu stays visible on workspace change

### ISSUE THREAD

**Issue by mxmilkb** [swaywm/sway#3722] opened 2019-02-19 02:15 UTC
sway version 1.0-rc1-85-gc939453b (Feb 19 2019, branch 'master')

1. Open Gimp
2. Click on a menu
3. With the menu open, change workspace with a hotkey

Result: the menu remains visible on the new workspace

**Comment by RedSoxFan** [comment] 2019-02-19 02:25
Duplicate of #2529. It is the same core issue, just a different way of producing it

**Closed by RedSoxFan** 2019-02-19 02:25 UTC
