### ISSUE TITLE
Screensharing does not work if output monitor has `render_bit_depth 10` set

### ISSUE THREAD

**Issue by skykanin** [swaywm/sway#8227] opened 2024-06-30 18:33 UTC
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.9`

- **Debug Log:**
  - [debug log](https://bpa.st/AVEQ)

- **Configuration File:**
  - All that is required is setting `render_bit_depth 10` for an output monitor. Here is my [sway config](https://bpa.st/XVIA) as well.

- **Stack Trace:**
  - N/A (not a crash)

- **Additional Info:**
    - OS: `NixOS 24.11.20240624.2893f56 (Vicuna) x86_64`
    - GPU: `AMD Radeon RX 7800 XT @ 0.06 GHz`
    - pipewire version: `1.0.7`
    - xdg-desktop-portal version: `1.18.4`
    - xdg-desktop-portal-wlr version: `0.7.1`
    -  xdg-desktop-portal-gtk version: `1.15.1`
    
- **Description:**
  - Configure an output monitor with `render_bit_depth 10`
  - Test screen sharing at https://mozilla.github.io/webrtc-landing/gum_test.html by clicking "Screen capture" and selecting the monitor configured with a `render_bit_depth` of `10`.
  - I expect to see a preview of the screen on the website, but instead I see nothing. Changing the `render_bit_depth` to `8` resolves this issue (screenshots below)
  
 Expected:
 
![image](https://github.com/swaywm/sway/assets/3789764/156902db-0c4d-461b-8050-47462bc87219)

Actual:

![image](https://github.com/swaywm/sway/assets/3789764/d12679e8-a102-4997-abe4-b00c45fac6fc)

**Comment by emersion** [comment] 2024-06-30 18:46
Probably an issue with Firefox no supporting high bit depth formats.

**Comment by skykanin** [comment] 2024-06-30 20:49
> Probably an issue with Firefox no supporting high bit depth formats.

I experience the same issue when screen sharing with `vesktop` (a discord client)

**Comment by ChrisLane** [comment] 2024-10-21 09:06
Duplicate of https://github.com/swaywm/sway/issues/7898?

**Comment by emersion** [comment] 2024-10-21 14:07
Indeed.

**Closed by emersion** 2024-10-21 14:07 UTC
Labels: bug
