### ISSUE TITLE
Parent surface not properly damaged when subsurface gets destroyed

### ISSUE THREAD

**Issue by afrantzis** [swaywm/sway#7327] opened 2022-12-15 10:30 UTC
- **Sway Version:**
  - sway version 1.8-rc3 (but can reproduce with 1.7 also)

- **Description:**
  - Run the attached example program [subsurface.tar.gz](https://github.com/swaywm/sway/files/10236051/subsurface.tar.gz) (`tar xzf subsurface.tar.gz; cd subsurface; make; ./subsurface`)
  - You should see a white toplevel window.
  - Each click in the window should create a smaller blue subsurface, while destroying any previous blue subsurface, effectively moving the subsurface around.
  - Under sway, the contents of previous subsurfaces persist (despite the client destroying the (sub)surface), likely due to incorrect damage of parent surface:
![sway-subsurfaces](https://user-images.githubusercontent.com/495575/207833181-6b0c512b-1f94-4a2c-8d57-1ba87fc01e36.png).
  - This example program works fine in weston, mutter and kwin.
  - This issue affects Wine Wayland which uses subsurfaces for some types of transient windows:
![sway-notepad](https://user-images.githubusercontent.com/495575/207836152-497329b8-e18f-4ad2-b798-8e1537d3c39b.png)

Thanks!

**Comment by emersion** [comment] 2022-12-15 10:37
This sounds like a duplicate of https://github.com/swaywm/sway/issues/6960

**Comment by afrantzis** [comment] 2022-12-15 10:47
@emersion Seems like the same issue, indeed. Feel free to close as a duplicate. Thanks!

**Closed** 2022-12-15 11:01 UTC
Labels: bug
