### ISSUE TITLE
Firefox crashes while launching it when the clipboard has contents

### ISSUE THREAD

**Issue by uwqwxing886** [swaywm/sway#3170] opened 2018-11-21 18:44 UTC
* Sway Version: sway version 4.16 (2018-11-04)
commit cecf00b924a76feb503d58113462acb4e14e53bf
compiled without xwayland (meson -Denable-xwayland=false)
xorg-server-xwayland does not exist on the system

* Firefox Version: firefox-wayland-hg-r497673.dc3687bbb5a3-1-x86_64.pkg.tar.xz
compiled with wayland support (ac_add_options --enable-default-toolkit=cairo-gtk3-wayland)

* Debug Log: https://gist.github.com/uwqwxing886/8e34b5d4d0d31a74db4817d8a4e1fe9b
  * [file-firefox-that-launches-log](https://gist.github.com/uwqwxing886/8e34b5d4d0d31a74db4817d8a4e1fe9b#file-firefox-that-launches-log)
  * [file-firefox-that-crashes-because-the-clipboard-has-contents-log](https://gist.github.com/uwqwxing886/8e34b5d4d0d31a74db4817d8a4e1fe9b#file-firefox-that-crashes-because-the-clipboard-has-contents-log)

Firefox crashes while launching it when the clipboard has contents. There is a `Gdk-Message: 10:24:50.114: Error reading events from display: Invalid argument` error in the logs before the app crashes and the window doesn't even display.

**Comment by emersion** [comment] 2018-11-21 19:04
Duplicate of https://github.com/swaywm/wlroots/issues/1041

**Closed by emersion** 2018-11-21 19:04 UTC

**Comment by uwqwxing886** [comment] 2018-11-21 19:10
Fixed in https://github.com/swaywm/wlroots/pull/1380.

**Comment by emersion** [comment] 2018-11-21 19:34
This PR only fixes it for the primary selection. The clipboard still has this issue, I'm working on a patch.
