### ISSUE TITLE
Crash when many resize events happen on a workspace with a single window if workspace_layout=tabbed

### ISSUE THREAD

**Issue by balsoft** [swaywm/sway#4438] opened 2019-08-09 21:43 UTC
* Sway Version: sway version 1.0
* Debug Log: http://ix.io/1Rav

* Configuration File: 
```
bindsym Mod4+z exec sh -c 'GDK_BACKEND=x11 /nix/store/xrywrdw6kl6a2h9am23dgxfk93yrs6mw-lambda-launcher-0.1.0.0/bin/lambda-launcher'
workspace_layout tabbed
```

Start up sway, on an empty workspace open a launcher (or some other window that resizes a lot) [in my case it's lambda-launcher] and then make it resize a lot. Sway crashes. 

The GDK_BACKEND thing doesn't matter a single bit, it's just that GTK fonts are broken for me with wayland backend.

* Stack Trace, if sway crashes: http://ix.io/1Raw

EDIT: smaller config

**Comment by balsoft** [comment] 2019-08-09 22:03
A minimal example:
```
bindsym Mod4+z exec sh -c 'GDK_BACKEND=x11 /nix/store/xrywrdw6kl6a2h9am23dgxfk93yrs6mw-lambda-launcher-0.1.0.0/bin/lambda-launcher'
workspace_layout tabbed
```

The GDK_BACKEND thing doesn't matter a single bit, it's just that GTK fonts are broken for me with wayland backend.

* Debug log: http://ix.io/1Rav
* Backtrace: http://ix.io/1Raw

**Comment by kennylevinsen** [comment] 2019-08-09 22:08
Duplicate of https://github.com/swaywm/sway/issues/3870, fixed by https://github.com/swaywm/sway/pull/3875.

Always try at least the latest stable (1.1 at the time of writing) when encountering issues.

**Closed** 2019-08-09 22:09 UTC
