### ISSUE TITLE
[1.10-rc3] swaynag overlay is rendered below swaybar

### ISSUE THREAD

**Issue by ikalnytskyi** [swaywm/sway#8388] opened 2024-10-15 14:08 UTC
- **Sway Version:**
  - sway version 1.10-rc3
  - swaynag version 1.10-rc3
  - wlroots version 0.18.1

- **Debug Log:**
  - [debug log file](https://github.com/user-attachments/files/17379372/sway-bug.txt)

- **Configuration File:**
  - I can reproduce this issue with the default configuration.

- **Description:**
  - `swaynag -y overlay -t info -m "?" -z "Yes" "" -s "No"`
  - the swaynag layer appears below swaybar
    ![image](https://github.com/user-attachments/assets/8c40fde8-6804-4438-b85f-798ba34733f1)
  - the swaynag layer overlays the fullscreen window, but is not readjusted
    ![image](https://github.com/user-attachments/assets/7de0bac7-410b-41e2-a081-743d50faa5e8)
  - In Sway 1.9, the swaynag layer (when invoked with `-y overlay`) always appears above swaybar and is at the top when a window is in full screen

**Comment by Nefsen402** [comment] 2024-10-15 14:11
I think this is a duplicate of https://github.com/swaywm/sway/issues/8368

**Comment by ikalnytskyi** [comment] 2024-10-15 14:27
@Nefsen402 Thanks for the swift response. I saw this issue, but I wasn't sure it's the same. I applied your patch but it didn't help me. Maybe I screwed somewhere along the way, or maybe it's something different. :man_shrugging: 

I don't know whether it's a bug or not, but just wanted to report that I'm observing a change in swaynag's behaviour when invoked with `-y overlay` or `-y background` between Sway 1.9 and 1.10-rc3.

**Comment by ikalnytskyi** [comment] 2024-10-16 10:08
I noticed that **Sway 1.9** used to arrange surfaces in the following order ([link](https://github.com/swaywm/sway/blob/1a3cfc50c15124c2be18c025e609112ee15de4aa/sway/desktop/layer_shell.c#L218-L225)):

- `ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY`
- `ZWLR_LAYER_SHELL_V1_LAYER_TOP`
- `ZWLR_LAYER_SHELL_V1_LAYER_BOTTOM`
- `ZWLR_LAYER_SHELL_V1_LAYER_BACKGROUND`

while Sway 1.10-rc3 (and master) is used to arrange them in a different order ([link](https://github.com/swaywm/sway/blob/dc8f5338be5a1fb504ca39337c52fb0baf839f83/sway/desktop/layer_shell.c#L81-L84)):

- `ZWLR_LAYER_SHELL_V1_LAYER_BACKGROUND`
- `ZWLR_LAYER_SHELL_V1_LAYER_BOTTOM`
- `ZWLR_LAYER_SHELL_V1_LAYER_TOP`
- `ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY`

FWIW, I believe this is the reason why the behavior I'm observing has changed. Once I changed the order of arrangements in **1.10-rc3** to be the same as in **1.9**, the swaynag layer started to appear above swaybar (at least when `top` and `overlay` layers are used).

**Comment by ikalnytskyi** [comment] 2024-10-18 15:08
Got addressed in https://github.com/swaywm/sway/pull/8385

**Closed** 2024-10-18 15:29 UTC
Labels: bug
