### ISSUE TITLE
List all keybindings in running session

### ISSUE THREAD

**Issue by pati-ni** [swaywm/sway#6774] opened 2022-01-19 14:37 UTC
I keep forgetting my binded keys to sway functions and struggle to find new keys that are not bounded. I am slowly getting better in the tiling WM game.

Is there a feature to show all `bindsym` dynamically in a session and list their associated function too?

If there is not such function already, could I ask if this is a reasonable feature to be added?

happy to help

**Comment by emersion** [comment] 2022-01-19 14:48
Duplicate of https://github.com/swaywm/sway/pull/5561

**Closed by emersion** 2022-01-19 14:48 UTC
