### ISSUE TITLE
sway SEGFAULT when connecting a mouse

### ISSUE THREAD

**Issue by lexa** [swaywm/sway#6793] opened 2022-01-27 21:21 UTC
### Please fill out the following:
- **Sway Version:**
sway version 1.7

- **Debug Log:**
https://gist.github.com/lexa/ead2d577a63ae50c650d1b56a7414c27

- **Configuration File:**
https://gist.github.com/lexa/7f5728388a6e796b895a0fe36f86c607

- **Stack Trace:**
https://gist.github.com/lexa/0c4e63267fc506032ef5045527f5ff9a

- **Description:**
Sway crashes when i switch from a VT to a running Sway session or plug the mouse. To reproduce this issue two changes for the default config required:

1. Adding a specific configuration for the mouse device.
```
input 1390:269:ELECOM_TrackBall_Mouse_HUGE_TrackBall {
    scroll_button BTN_EXTRA
    scroll_method on_button_down
}
```

2. Using waybar *with language indicator*. Example of waybar config 
```
{
    "height": 24, // Waybar height (to be removed for auto height)
    "modules-left": [],
    "modules-center": [],
    "modules-right": ["sway/language"],
    "sway/language": {
        "format": "{short}",
        "max-length": 50
    },
}
```

--

About the input device.

libinput list-device tells me about device:
```
Device:           ELECOM TrackBall Mouse HUGE TrackBall
Kernel:           /dev/input/event8
Group:            5
Seat:             seat0, default
Capabilities:     keyboard pointer
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   button
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   flat *adaptive
Rotation:         0.0
```

swaymsg -t get_inputs says:
```
Input device: ELECOM TrackBall Mouse HUGE TrackBall
  Type: Mouse
  Identifier: 1390:269:ELECOM_TrackBall_Mouse_HUGE_TrackBall
  Product ID: 269
  Vendor ID: 1390
  Libinput Send Events: enabled

Input device: ELECOM TrackBall Mouse HUGE TrackBall
  Type: Keyboard
  Identifier: 1390:269:ELECOM_TrackBall_Mouse_HUGE_TrackBall
  Product ID: 269
  Vendor ID: 1390
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled
```

**Comment by emersion** [comment] 2022-01-28 16:35
Duplicate of https://github.com/swaywm/sway/issues/6502

**Closed by emersion** 2022-01-28 16:35 UTC
Labels: bug
