### ISSUE TITLE
if swaylock is opened, the session closes/crashes(?)

### ISSUE THREAD

**Issue by bigrand** [swaywm/sway#7388] opened 2023-01-14 18:23 UTC
**Issue**
  When entering idle/suspend mode with `systemctl suspend` or simply waiting for the lock screen to appear, you get logged out(?) and everything closes in the process. 
  
  As explained in my [EOS Forum's thread](https://forum.endeavouros.com/t/when-my-pc-is-idle-it-closes-everything-and-logs-me-out/35985) It's somewhat consistent; If you don't open any program (e.g., Firefox), the screen lock appears, the system suspends, and you can resume your work after waking it up, but if you open any program, the session closes. Using `systemctl suspend` causes the same problem, but it actually suspends my PC, whereas executing `swaylock` in the terminal doesn't suspend my PC and just closes/crashes the session. 
  
  I'm using EndeavourOS, and while I can't 100% confirm this is a swaylock bug, I believe this issue may help someone else who is experiencing this or a similar problem. 

**Version**
`swaylock version 1.7`

**"Workaround"**
  Uninstall the `swaylock` package, and the system will suspend properly, allowing you to resume your work normally (without the lock screen though).

**Comment by bigrand** [comment] 2023-01-18 01:42
I'm willing to help, but I don't know how to debug it. If you could provide some explanation or guide on what you need and how I can get it, I'm more than willing to help.

**Comment by bl4ckb0ne** [comment] 2023-01-18 15:44
Compile sway/wlroots from source in debug to have the debug symbols. Alternatively if your distro ships the debug symbols you shoud get them.

**Comment by Luiz-Ferandes** [comment] 2023-01-21 23:59
I don't know if this also applies to Brigand, but Swaylock is working normally once again on my machine, I did not change anything on Sway or Swaylock, the bug might have been caused by some dependency that has been fixed.

**Comment by ernestask** [comment] 2023-01-22 14:37
Dupe of #7347.

**Comment by Luiz-Ferandes** [comment] 2023-01-22 16:32
> Dupe of #7347.

I just want to add that, what is said on that issue about the drawing tablet is what is causing my problem, when I said that the problem had been solved on my computer I did not have my drawing tablet connected to my it, but after reading the issue I did some tests connecting and disconnecting my drawing tablet and activating Swaylock, I can confirm that Swaylock crashes my Sway session only when I have the drawing tablet connected.

**Comment by bl4ckb0ne** [comment] 2023-01-23 18:34
@Luiz-Ferandes can you try sway/wlroots master to see if the issue has been fixed

**Comment by bl4ckb0ne** [comment] 2023-02-09 18:31
Closing, reopen if it occurs again

**Closed by bl4ckb0ne** 2023-02-09 18:31 UTC
