### ISSUE TITLE
XWayland app scaling by themselves

### ISSUE THREAD

**Issue by okhsunrog** [swaywm/sway#7331] opened 2022-12-17 13:49 UTC
KDE has an option in Display & Monitor to make Legacy Applications (X11) "Apply scaling themselves". Can we have the same option for sway? Seems like a solution for blurry JetBrains apps.

**Comment by emersion** [comment] 2022-12-17 13:50
Duplicate of https://github.com/swaywm/sway/issues/5917

**Closed by emersion** 2022-12-17 13:50 UTC
Labels: enhancement
