### ISSUE TITLE
wacom pen sensitivity not working

### ISSUE THREAD

**Issue by yannick** [swaywm/sway#3140] opened 2018-11-16 13:46 UTC
➜ ~ swaymsg -t get_version
sway version 1.0-beta.1-195-gc36665bc (Nov 15 2018, branch 'master')
➜ ~ pacman -Q wlroots
wlroots-git 0.1.r79.g040d62de-1

e.g. in krita/gimp on xwayland under gnome it works but not if i start krita in sway

**Comment by emersion** [comment] 2018-11-16 13:48
Duplicate of https://github.com/swaywm/sway/issues/2288

**Closed by emersion** 2018-11-16 13:48 UTC
