### ISSUE TITLE
AUR sway-git Compilation error from manpage generation failure

### ISSUE THREAD

**Issue by norcalli** [swaywm/sway#3524] opened 2019-01-28 06:07 UTC
Cleanbuild of commit 783fadab284c79c8e13625e5e2a2eefae02c75d3

```
❯ yay -S sway-git
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 1]  sway-git-r5522.70637b40-1

  1 sway-git                         (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 1
:: Deleting (1/1): /home/a/.cache/yay/sway-git
:: Downloaded PKGBUILD (1/1): sway-git
  1 sway-git                         (Installed) (Build Files Exist)
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> Diffs to show?
==>
:: Parsing SRCINFO (1/1): sway-git
==> Making package: sway-git r5522.70637b40-1 (Sun 27 Jan 2019 09:56:59 PM PST)
==> Retrieving sources...
  -> Cloning sway git repo...
Cloning into bare repository '/home/a/.cache/yay/sway-git/sway'...
remote: Enumerating objects: 116, done.
remote: Counting objects: 100% (116/116), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 34796 (delta 60), reused 44 (delta 24), pack-reused 34680
Receiving objects: 100% (34796/34796), 26.98 MiB | 9.28 MiB/s, done.
Resolving deltas: 100% (25460/25460), done.
==> Validating source files with sha1sums...
    sway ... Skipped
==> Cleaning up...
==> Making package: sway-git r5522.70637b40-1 (Sun 27 Jan 2019 09:57:03 PM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating sway git repo...
Fetching origin
==> Validating source files with sha1sums...
    sway ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of sway git repo...
Cloning into 'sway'...
done.
==> Starting prepare()...
The Meson build system
Version: 0.49.1
Source dir: /home/a/.cache/yay/sway-git/src/sway
Build dir: /home/a/.cache/yay/sway-git/src/build
Build type: native build
Project name: sway
Project version: undefined
Native C compiler: ccache cc (gcc 8.2.1 "cc (GCC) 8.2.1 20181127")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.6.0)
Dependency json-c found: YES 0.13.1
Dependency libpcre found: YES 8.42
Dependency wayland-server found: YES 1.16.0
Dependency wayland-client found: YES 1.16.0
Dependency wayland-cursor found: YES 1.16.0
Dependency wayland-egl found: YES 18.1.0
Dependency wayland-protocols found: YES 1.17
Dependency xkbcommon found: YES 0.8.2
Dependency cairo found: YES 1.16.0
Dependency pango found: YES 1.42.3
Dependency pangocairo found: YES 1.42.3
Dependency gdk-pixbuf-2.0 found: YES 2.38.0
Dependency pixman-1 found: YES 0.36.0
Dependency libevdev found: YES 1.6.0
Dependency libinput found: YES 1.12.6
Dependency libsystemd found: YES 240
Found CMake: /usr/bin/cmake (3.13.3)
Dependency libelogind found: NO (tried pkgconfig and cmake)
Dependency xcb found: YES 1.13.1
Library m found: YES
Library rt found: YES
Program git found: YES (/usr/bin/git)

Subproject  subprojects/wlroots is buildable: NO (disabling)

Dependency wlroots found: YES 0.2.0
Fetching value of define "WLR_HAS_XWAYLAND" with dependency wlroots: 1
Program scdoc found: YES (/usr/bin/scdoc)
Program sh found: YES (/usr/bin/sh)
Configuring config.h using configuration
Program wayland-scanner found: YES (/usr/bin/wayland-scanner)
Configuring config using configuration
Configuring 00-defaults using configuration
Build targets in project: 17
Option werror is: False [default: true]
Found ninja-1.8.2 at /usr/bin/ninja
==> Starting pkgver()...
==> Updated version: sway-git r5597.783fadab-1
==> Sources are ready.
==> Making package: sway-git r5597.783fadab-1 (Sun 27 Jan 2019 09:57:06 PM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
ninja: Entering directory `/home/a/.cache/yay/sway-git/src/build'
[11/267] Generating sway.5 with a custom command.
FAILED: sway.5
/usr/bin/sh -c '/usr/bin/scdoc < ../sway/sway/sway.5.scd > sway.5'
Error at 61:9: Cannot nest inline formatting (began with * at 61:1)
[12/267] Generating sway-bar.5 with a custom command.
FAILED: sway-bar.5
/usr/bin/sh -c '/usr/bin/scdoc < ../sway/sway/sway-bar.5.scd > sway-bar.5'
Error at 13:8: Cannot nest inline formatting (began with * at 13:1)
[13/267] Generating sway-input.5 with a custom command.
FAILED: sway-input.5
/usr/bin/sh -c '/usr/bin/scdoc < ../sway/sway/sway-input.5.scd > sway-input.5'
Error at 10:70: Cannot nest inline formatting (began with * at 10:55)
[14/267] Generating sway-output.5 with a custom command.
FAILED: sway-output.5
/usr/bin/sh -c '/usr/bin/scdoc < ../sway/sway/sway-output.5.scd > sway-output.5'
Error at 13:56: Cannot nest inline formatting (began with * at 13:41)
[44/267] Compiling C object 'common/92a5dc0@@sway-common@sta/pango.c.o'.
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
Error making: sway-git
```

Seems to be related to the recently merged cd22d555e8a665c3f2a8e2c07e7d54beb6ac254c "Remove unnecessary underscores in man pages" which happened to fail the exact same way https://builds.sr.ht/~sircmpwn/job/24528

**Comment by RyanDwyer** [comment] 2019-01-28 06:08
Update the scdoc package.

**Comment by RedSoxFan** [comment] 2019-01-28 06:09
Duplicate of #3521 

As RyanDwyer said, update scdoc

**Closed by RedSoxFan** 2019-01-28 06:09 UTC

**Comment by norcalli** [comment] 2019-01-28 06:16
Thanks for the speedy response, that did work. It would be a good idea to add a requirement on `scdoc 1.8` to the AUR package then.
