### ISSUE TITLE
sway-1.0 - more windows floating by default

### ISSUE THREAD

**Issue by mithodin** [swaywm/sway#2963] opened 2018-10-24 13:33 UTC
I have just upgraded to 1.0-beta.1 on two devices. I have noticed that more programs start in a floating window than before. Is there a new default? Something that could be controlled in the config? Or is it up to the client to declare whether it wants to be floating?

Examples that were not floating before:
 - st
 - spotify

**Comment by SirCmpwn** [comment] 2018-10-24 13:34
Can you try the master branch?

**Comment by mithodin** [comment] 2018-10-24 13:35
I will maybe have time tonight to test this.

**Comment by Moelf** [comment] 2018-10-24 17:11
I'm using Kitty terminal, and it's also floating for no reason

**Comment by mithodin** [comment] 2018-10-24 19:44
I cannot reproduce this on my notebook, so I will have to wait until monday for further testing.

**Comment by Marteon** [comment] 2018-10-24 19:55
In my case Spotify does not only start in floating but it also has a title bar even through `border none` is set.

**Comment by emersion** [comment] 2018-10-24 19:57
Please say whether you're using the latest commit from master or sway 1.0-beta.1.

**Comment by progandy** [comment] 2018-10-24 20:00
If you are using a new git build of wlroots with the sway beta-1, then the floating logic may be broken because of swaywm/wlroots#1327
It is fixed in the sway master branch with swaywm/sway#2926 .

**Comment by Marteon** [comment] 2018-10-24 20:00
Will edit the version in here later. But I'm pretty sure that I'm some commits ahead of 1.0-beta.1.

**Comment by emersion** [comment] 2018-10-24 20:02
Yeah, please upgrade wlroots to the latest commit too.

**Comment by 7415963987456321** [comment] 2018-10-24 22:47
> I'm using Kitty terminal, and it's also floating for no reason
I also use kitty but it does not float by default. I'm on version 1.0-beta ga918844e.

**Comment by Moelf** [comment] 2018-10-25 03:46
> 
> 
> > I'm using Kitty terminal, and it's also floating for no reason
> 
> I also use kitty but it does not float by default. I'm on version 1.0-beta ga918844e.

What version of wlroots?

**Comment by RyanDwyer** [comment] 2018-10-27 10:29
Closing this because no one has confirmed that there's an issue in the latest masters.

If anyone continues to have windows opening as floating and they believe they shouldn't, please confirm you're running the latest masters of both sway and wlroots. If you are and it still occurs, please reply here and we'll reopen the issue.

**Closed by RyanDwyer** 2018-10-27 10:29 UTC

**Comment by mithodin** [comment] 2018-10-29 13:17
I have now had time to test things with the latest master. The problem is fixed.
