### ISSUE TITLE
Segfault in layer_shell.c : popup_damage when laptop output is disabled

### ISSUE THREAD

**Issue by keis** [swaywm/sway#6120] opened 2021-03-20 11:22 UTC
### Please fill out the following:
- **Sway Version:**
 sway version v1.5

- **Debug Log:**
Sorry, not available from the crash

- **Configuration File:**
A mostly default configuration https://gist.github.com/keis/9cc6e1cb9ab56a991a48f757e683be97#file-sway-config
Most notably with a bit to disable laptop screen when lid is closed.

- **Stack Trace:**
https://gist.github.com/keis/9cc6e1cb9ab56a991a48f757e683be97#file-bt-full

- **Description:**
Turned on external monitors and resumed from suspend. One is connected with HDMI the other is DisplayPort on usb-c hub.
Sometimes the HDMI screen is not activating correctly until I open and close the laptop lid once (I'm guessing cycling the enabled state is what does it), so I did
Sway crashed
Both external screens are now on and I'm looking at the gdm login screen.

**Comment by eddsalkield** [comment] 2021-04-09 11:43
As much as I don't like adding "me too" comments, I just wanted to report that I'm experiencing the same crash on `sway v1.5`.

**Comment by fluix-dev** [comment] 2021-04-09 16:48
Does this happen on Sway [1.6](https://github.com/swaywm/sway/releases/tag/1.6) or, preferably, master? Instructions for compiling from source are available [here](https://github.com/swaywm/sway#compiling-from-source).

**Comment by keis** [comment] 2021-04-09 16:53
I'll give 1.6 a try. I'll probably have to make it my daily driver and run for a while to say with any certainty. I don't have a good way of reproducing and it has happened maybe once or twice since I posted this 20 days ago.

**Comment by keis** [comment] 2021-04-10 13:09
I got sway running with wlroots and sway built from master (@ 1a0f86be) I'll keep you posted.

Btw I also ended up upgrading to the fedora 34 beta as master and 1.6 tag has dependencies on later version than what was in fedora 33

**Comment by keis** [comment] 2021-04-24 10:41
I've not run into this again so far but I've also not faced the issues with screens not turning as much lately. Not sure if that's related to sway or the something else in the fedora 34 update

**Comment by LaserEyess** [comment] 2021-05-05 13:00
I received a similar crash on `sway version 1.6-7c74f01f (May  1 2021, branch 'master')`.

https://0x0.st/-aCz.txt

I don't know what caused it but essentially what happened was
1. opened gdb to investivate a crash
2. let the screen go idle (swayidle)
3. dpms goes off
4. shake mouse to turn dpms on
5. crash

gdb *may* be relevant due to the error, but I'm not sure.

**Comment by tchebb** [comment] 2022-01-27 12:46
I can reproduce this on sway+wlroots master by disabling an output while an xdg_popup from a layer surface exists. For example, by running the following command and then immediately hovering over a [Waybar](https://github.com/Alexays/Waybar) widget to show its tooltip before the first `sleep` completes:
sleep 3 ; swaymsg 'output * disable' ; sleep 1 ; swaymsg 'output * enable'

The direct cause is that the `wlr_layer_surface_v1`'s `output` is `NULL` here when we dereference it in `popup_damage()`, which has been called by `popup_handle_unmap()`:
https://github.com/swaywm/sway/blob/ebfe432ec3064094faebe0913b2d98932d590bfd/sway/desktop/layer_shell.c#L502-L503

**Comment by arbrauns** [comment] 2022-02-28 12:19
Is this a duplicate of #5804?

**Comment by tchebb** [comment] 2022-03-02 00:47
> Is this a duplicate of #5804?

Yep, looks like it is. The stack trace in that issue is the same code path that I fixed here.

**Closed** 2022-04-13 08:05 UTC
Labels: bug
