### ISSUE TITLE
Some XWayland windows do not get focused

### ISSUE THREAD

**Issue by rhysperry111** [swaywm/sway#5374] opened 2020-05-22 20:16 UTC
# Info:
- Sway version: 1.4
- Wlroots version: 0.10.1
- xorg-server-xwayland version: 1.20.8
- Debug log and config: https://gist.github.com/rhysperry111/8857df55d507081a4c595b14437617eb

# Issue:
Certain XWayland windows are:
- Not being focused
- Not obeying workspaces (stay on screen even when change workspaces)
- Not receiving any input
- "Invisible" (I can focus other windows through them)

Windows that have this problem (that I could find) are:
- Some steam popups
- Microsoft FSX Menu (running with Steam Proton)

This does not happen to the same window run in a standard Xorg server.

Recording of issue (not working, sway): https://youtu.be/V7Kcl6jCTp8
Recording of issue (working, Xorg): TODO SOON

**Comment by emersion** [comment] 2020-05-22 20:26
Duplicate of https://github.com/swaywm/sway/issues/5373

**Closed by emersion** 2020-05-22 20:26 UTC
