### ISSUE TITLE
Vertical position for output offsets dialogs in firefox

### ISSUE THREAD

**Issue by wernerb** [swaywm/sway#3233] opened 2018-12-02 11:36 UTC
Context menu's, popups etc don't show up in firefox as they are perhaps rendered offscreen. 

When you have your output in a vertical positTion such as:

``` 
output eDP-1 {
 position 01400
}  
```

Horizontal position does not seem to affect anything though.

See ![2018-11-30-140045_grim](https://user-images.githubusercontent.com/4366274/49290956-cf09a900-f4a8-11e8-87c9-c4fb94b18cea.png)

Related to #3115

**Comment by RedSoxFan** [comment] 2018-12-19 20:55
Duplicate of #3135

**Closed by RedSoxFan** 2018-12-19 20:55 UTC
