### ISSUE TITLE
Restart swaybar on exit

### ISSUE THREAD

**Issue by OJFord** [swaywm/sway#7558] opened 2023-05-01 22:32 UTC
My config:
```
bar {
    position top
    swaybar_command waybar
}
```

When `waybar` crashes, I have to reload sway (`swaymsg reload`) to get it back.

I think it would make sense for sway to try to restart an exited bar, since it's not ever (?) expected to happen.

**Comment by emersion** [comment] 2023-05-01 22:58
I'd rather not. It would be easy to enter infinite loop, and then we need a more complicated logic to restart the bar. Not worth it since the bar should really just get fixed instead of trying to work around the root cause.

**Comment by OJFord** [comment] 2023-05-03 11:51
How about some sort of `swaymsg reload-bar` then?

I agree root cause should be fixed, and surely any bar maintainer would too, but in the mean time it's frustrating to have to reload sway entirely to get it back.

**Comment by emersion** [comment] 2023-05-03 11:53
Nope, doesn't make sense to me, sorry.

**Closed by emersion** 2023-05-03 11:53 UTC
Labels: enhancement
