### ISSUE TITLE
Crash on scratchpad move

### ISSUE THREAD

**Issue by thepenguinthatwants** [swaywm/sway#4065] opened 2019-04-17 17:10 UTC
This has happened to me quite many times. 

So if I use few times.

`    bindsym $mod+Shift+minus move scratchpad`

It just logs me out.

**Comment by RedSoxFan** [comment] 2019-04-17 17:48
Sway is probably segfaulting. If you are using sway 1.0, it may be fixed on master depending on the issue.

After sway crashes, can you try running `coredumpctl gdb sway` followed by `bt full` and posting the results? If you are not using systemd, consult your distros documentation on how to obtain a core dump and use gdb to get the back trace

Also, can you provide a debug log? Start sway with `sway -d >sway.log 2>&1`, reproduce the issue (as quick as possible), and post the log.

**Comment by norcalli** [comment] 2019-04-18 13:46
Also, make sure to post the version of sway that you were using at the time of the crash. `sway -v` and copy the output.

**Comment by thepenguinthatwants** [comment] 2019-04-20 06:29
Sorry I had no clue how to copy terminal in wayland and without mouse on alacritty.
[logs](https://snag.gy/WVOcSh.jpg)

sway version 1.0

**Comment by thepenguinthatwants** [comment] 2019-04-20 06:35
If I start sway with  `sway -d >sway.log 2>&1 ` 
it just open it in wlroots? But i cant reproduce the bug in it?

only way to reproduce is to things up and quickly move multiple things to scratchpad and then it logs me out.

`    bindsym $mod+Shift+minus move scratchpad`

**Comment by RedSoxFan** [comment] 2019-04-20 07:12
Unfortunately, it looks like sway and wlroots were not compiled with debug symbols so the backtrace is useless. If you could rebuild with debug symbols, that would be helpful.

> If I start sway with `sway -d >sway.log 2>&1` it just open it in wlroots? But i cant reproduce the bug in it?

I'm guessing you are running that from within sway and getting a nested session. It would probably be easier to reproduce from a TTY instead

**Comment by RedSoxFan** [comment] 2019-07-18 19:06
Is this still an issue?

**Comment by edrex** [comment] 2019-09-18 22:27
I've been seeing an infrequent crash for the past couple weeks under similar circumstances, while interacting with the scratchpad (showing it, at least the last time). Here's the last few minutes of log for the last crash:

https://clbin.com/NjrHr

`sway version 1.2-rc1-48-ga085e649 (Sep 15 2019, branch 'master')`

**Comment by zsugabubus** [comment] 2019-12-15 09:26
Seems related, but different stack trace and log to @edrex.

* Sway Version: 1.2

* Debug Log: https://gist.github.com/zsugabubus/22e77e3b02b0bb5d6907cc129345878b

```
Stack trace of thread 494:
#0  0x000055fcbd1a70ad n/a (sway + 0x130ad)
#1  0x000055fcbd1d17b1 n/a (sway + 0x3d7b1)
#2  0x00007f99cc8aab0e n/a (libwlroots.so.3 + 0x70b0e)
#3  0x00007f99cc13c69a ffi_call_unix64 (libffi.so.6 + 0x669a)
#4  0x00007f99cc13bfb6 ffi_call (libffi.so.6 + 0x5fb6)
#5  0x00007f99cc8f382f n/a (libwayland-server.so.0 + 0xc82f)
#6  0x00007f99cc8f0193 n/a (libwayland-server.so.0 + 0x9193)
#7  0x00007f99cc8f17f2 wl_event_loop_dispatch (libwayland-server.so.0 + 0xa7f2)
#8  0x00007f99cc8f039c wl_display_run (libwayland-server.so.0 + 0x939c)
#9  0x000055fcbd1a2592 n/a (sway + 0xe592)
#10 0x00007f99ccef3153 __libc_start_main (libc.so.6 + 0x27153)
#11 0x000055fcbd1a28be n/a (sway + 0xe8be)

Stack trace of thread 528:
#0  0x00007f99cc7acc45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
#1  0x00007f99c5bef60c n/a (i965_dri.so + 0x4e060c)
#2  0x00007f99c5bef208 n/a (i965_dri.so + 0x4e0208)
#3  0x00007f99cc7a64cf start_thread (libpthread.so.0 + 0x94cf)
#4  0x00007f99ccfcb2d3 __clone (libc.so.6 + 0xff2d3)
```

**Comment by RedSoxFan** [comment] 2019-12-16 03:17
@edrex I think #4816 addresses your crash

@zsugabubus Can you please try compiling sway and wlroots from source and provide a backtrace with debug symbols?

**Comment by zsugabubus** [comment] 2019-12-16 06:59
Can try, but I don't expect too much. It occurred only once in my lifetime and since than I tried moving the same application to scratchpad one hundred times and of course it worked fine.

**Comment by edrex** [comment] 2019-12-17 21:39
@RedSoxFan that certainly looks like my trace, and I can repro the crash and confirm fix. I didn't connect fullscreening the descendants before hiding with the crash, but that's about what I was doing. Thanks!

**Comment by visika** [comment] 2020-01-19 09:42
My session crashed right now.
I can reproduce the event doing this on a window:
M+S+-, M+-, M+v, M+-
Hope this helps: https://pastebin.com/snKR2EHw
Sway version 1.0

**Comment by Emantor** [comment] 2020-01-19 09:51
Theis hast been fixed on master, either update wlroots and sway to master or wait for the version 1.3 release.

**Closed** 2020-01-19 09:53 UTC
