### ISSUE TITLE
When on 4k@60hz HDMI audio sounds like chipmunks

### ISSUE THREAD

**Issue by lorendias** [swaywm/sway#4022] opened 2019-04-07 01:15 UTC
AMD RX VEGA 64 over HDMI Audio
Vizio M43-C1

Arch Linux
linux 5.1.0-rc2-mainline [AUR]
mesa 19.0.1-2
pulseaudio12.2-2
alsa-lib 1.1.8-1
pulseaudio-alsa 2-4
sway 1.0 (Arch 1.0-8 [community])

On Chrome 73.0.3683.103-1, Firefox 66.0.2-1 and Rhythmbox 3.4.3-1, Videos and MP3's play at at least 200% the normal video speed increases and the audio pitch changes to sound like chipmunks

For me, the bug happens when I include this in my `~/.config/sway/config`

`output HDMI-A-1 resolution 3840x2160@60Hz`

**Comment by ddevault** [comment] 2019-04-07 01:17
The odds of this being a sway bug are negligible.

**Comment by emersion** [comment] 2019-04-13 08:50
Closing because we don't do anything about audio.

May be an underrun/bandwidth issue with the graphics driver. Check your `dmesg`.

**Closed by emersion** 2019-04-13 08:50 UTC

**Comment by C0rn3j** [comment] 2019-12-06 15:46
This happens for me on KDE and I believe it happened on Cinnamon, so indeed shouldn't be related to sway.

@lorendias Did you end up fixing this, other than working around it by dropping down to 1080p?

This seems to be an issue on RX 580 also, here's an Arch thread I found about it - 
https://bbs.archlinux.org/viewtopic.php?id=244907

**Comment by Pico-Dragon** [comment] 2020-01-17 15:16
I found this to be an issue with some TVs that have 4k HDR support, and an RX 580 as mentioned. In my case, I was using the LG LG 49SK8000PLB. Relatively new Radeonn RX cards using the amdgpu driver should be able to reproduce this.

It's usually the fault of some TVs which report their display capabilities poorly. The fix for me was to enable HDR on the TV itself, even if it doesn't get utilized by the Wayland compositor. So yes, it's not specifically a window manager issue - although, it might be worth poking around to see why this happens in Wayland but not X11
