### ISSUE TITLE
bindsym behaviour not the same as i3

### ISSUE THREAD

**Issue by whoizit** [swaywm/sway#3988] opened 2019-03-28 15:33 UTC
I ran the sway yesterday and found that the navigation keys in the sway only work in the en layout. But in i3, all the keys for me also worked in layout on my native language without any changes in the config, with bindsym keyword. But in sway I should manually rewrite everything key bindings to bindcode, for getting i3-quality

Is it i3-compatible behaviour as you wrote in description in github page?

**Comment by emersion** [comment] 2019-03-28 15:41
Duplicate of https://github.com/swaywm/sway/issues/2999

**Comment by whoizit** [comment] 2019-03-28 23:44
workaround https://gist.github.com/whoizit/ff0cb8a070702e6f969a5fa7727af65f

**Closed** 2019-04-11 04:45 UTC
