### ISSUE TITLE
Cursor doesn't scale correctly when nothing is focused

### ISSUE THREAD

**Issue by twoertwein** [swaywm/sway#3148] opened 2018-11-18 04:02 UTC
The mouse courser doesn't seem to scale correctly to the display scale (I use a scale factor of 1.25). When I'm on an empty workspace and nothing is in focus, the courser is larger than usual. When I move the courser to window or to the bar, the courser becomes smaller again.
It feels to me as if the courser has a wrong scale when nothing is in focus (or it is the other way round).

```
$ swaymsg -t get_version
sway version 1.0-beta.1-203-geda3bfee (Nov 18 2018, branch 'master')

$ swaymsg -t get_outputs
Output eDP-1 'Sharp Corporation 0x1449 0x00000000'
  Current mode: 1920x1080 @ 59.933998 Hz
  Position: 0,0
  Scale factor: 1.250000
  Transform: normal
  Workspace: 2
  Available modes:
    1920x1080 @ 59.933998 Hz
```

**Comment by vberger** [comment] 2018-12-09 20:55
I can confirm. On my output with a scale factor of 2, the cursor has a correct size when over a window (both native wayland and xwayland), but is very small when over an empty desktop or over the UI elements (titlebars) drawn by sway.

**Comment by bitthief** [comment] 2019-01-17 02:10
Can confirm also. I use two screens with different scales [1.0 (2560x1440) and 2.0 (3840x2160)]. The cursor size is inconsistent between the screens and also between the swaybar / empty desktop, apps and XWayland apps. The cursor theme and size appear to be overridden in the code:

https://github.com/swaywm/sway/blob/4879d40695047a4c493bd8871d810c543978a869/sway/server.c#L144-L154

I've written this patch which improves things:

```
--- a/sway/server.c	2019-01-15 13:55:14.869123884 +0200
+++ b/sway/server.c	2019-01-15 13:54:10.251126412 +0200
@@ -142,15 +142,15 @@ void server_fini(struct sway_server *ser
 }
 
 bool server_start(struct sway_server *server) {
-	// TODO: configurable cursor theme and size
-	int cursor_size = 24;
-	const char *cursor_theme = NULL;
-
-	char cursor_size_fmt[16];
-	snprintf(cursor_size_fmt, sizeof(cursor_size_fmt), "%d", cursor_size);
-	setenv("XCURSOR_SIZE", cursor_size_fmt, 1);
-	if (cursor_theme != NULL) {
-		setenv("XCURSOR_THEME", cursor_theme, 1);
+    int cursor_size = (int) strtoul(getenv("XCURSOR_SIZE"), NULL, 10);
+    if (cursor_size < 0 || cursor_size > 64) {
+        char cursor_size_fmt[16];
+        snprintf(cursor_size_fmt, sizeof(cursor_size_fmt), "%d", 24);
+        setenv("XCURSOR_SIZE", cursor_size_fmt, 1);
+    }
+    char *cursor_theme = getenv("XCURSOR_THEME");
+	if (!cursor_theme) {
+		setenv("XCURSOR_THEME", "whiteglass", 1);
 	}
 
 #if HAVE_XWAYLAND
```
 
Also make sure to define the XCURSOR_PATH env variable to a correct location containing your cursor themes. I'm running Gentoo and the xcursor-themes package installs all X11 cursors to **/usr/share/cursors/xorg-x11**, which does not fall under the wlroots/xcursor search paths, so I need to define it manually before I start sway.

https://github.com/swaywm/wlroots/blob/a22311ec76802d2d8eb4bc3fcb3e9b713f7cd1c6/xcursor/xcursor.c#L612-L637

**Comment by RedSoxFan** [comment] 2019-01-20 05:00
Duplicate of #3014

**Closed by RedSoxFan** 2019-01-20 05:00 UTC
