### ISSUE TITLE
Sway displays black screen on startup with legacy DRM interface

### ISSUE THREAD

**Issue by askiiart** [swaywm/sway#8442] opened 2024-11-09 23:35 UTC
- **Sway Version: 1.10**
- **Debug Log:**
  - [Sway logs](https://paste.centos.org/view/1b36f528)
  - [DRM logs](https://paste.centos.org/view/a76bdd34), according to [wlroots's DRM debugging page](https://gitlab.freedesktop.org/wlroots/wlroots/-/wikis/DRM-Debugging)
  - https://gitlab.freedesktop.org/wlroots/wlroots/-/wikis/DRM-Debugging
- **Configuration File:**
  - Likely not applicable, but [here](https://paste.centos.org/view/1b7d819d); it's a `.tar.gz` file in base64, sorry for the odd format.

- **Stack Trace:**
Sway didn't crash, so I'm not gonna go through the trouble of doing this upfront, but I can provide it if needed.

- **Description:**
  - Reproduction: Just run Sway. This has been tested with Sway 1.10 on both Arch and the Fedora 41 Sway spin installation live iso, with the same results. The logs were from Fedora.
    - This is most likely related to my GPU, which is a Firepro W4100/Cape Verde.
  - Upon running Sway, it just shows a black screen, and I can't get out of it; I have to switch to another tty.

**Comment by askiiart** [comment] 2024-11-10 06:16
If I had to guess, I'd say it's probably related to this: 

> The legacy `wl_drm` protocol is now disabled by default (superseded by the standard linux-dmabuf-v1 protocol). This causes breakage in xorg-xwayland < 24.1.0, libva < 2.22.0 and amdvlk < 2024.Q4.1, and can be re-enabled manually via `-Dlegacy-wl-drm`

I'll try compiling it with that flag when I've got time, maybe tomorrow.

**Comment by emersion** [comment] 2024-11-10 11:43
Sounds like a duplicate of https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3918:

```
00:00:00.310 [ERROR] [wlr] [backend/drm/legacy.c:175] connector DP-1: drmModePageFlip failed: Device or resource busy
00:00:00.310 [ERROR] [sway/config/output.c:923] Backend commit failed
```

> If I had to guess, I'd say it's probably related to this:

That's unrelated, that one is about some GPU-accelerated clients failing to start up or falling back to software rendering. Also this flag is a runtime Sway flag, not a build flag.

**Comment by askiiart** [comment] 2024-11-10 15:44
Ah alright. I tried it at runtime already in case that actually was the case, and it made no difference, so that doesn't seem to be the issue. I've got no idea where to go from here, but if you've got any suggestions or want anything logged, I'll give it a shot.

**Comment by askiiart** [comment] 2024-11-10 15:48
Also, Sway *does* work when being started from a GNOME session. It doesn't work when being run from a console/by a greeter, though.

Also, wlroots issue 3918 doesn't mention the screen(s) being black, showing nothing, and not functioning, so maybe the issues are related, but I don't think it's the same problem.

**Comment by manio** [comment] 2024-11-22 14:24
Regarding my duplicate issue #8465:
I was trying to start sway with:
`WLR_DRM_NO_ATOMIC=1 sway`
no change

**Comment by emersion** [comment] 2024-11-23 14:37
Can you try https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4923?

**Comment by manio** [comment] 2024-11-23 15:33
I don't know whether I built it wrong or maybe it is just not working but it ended up with:
`sway: symbol lookup error: sway: undefined symbol: wlr_scene_set_gamma_control_manager_v1`
Full log: https://skyboo.net/temp/sway/sway-not-starting2.log

How I did it:
cloned your tree: https://gitlab.freedesktop.org/emersion/wlroots
checked out to your branch `legacy-disable-crtc-page-flip`
compiled, build, installed
ldd on old sway is not using libwlroots-0.19 but 0.18 so I cloned additionaly:
https://github.com/swaywm/sway
compiled, build, installed
ldd is correctly showing that it is linked to libwlroots-0.19

**Comment by manio** [comment] 2024-11-23 16:45
btw: similarly as @askiiart one of my card is also `AMD Cape Verde GL [FirePro W4100]`

**Comment by emersion** [comment] 2024-11-23 16:51
Here's a guide to compile latest Sway commit with a local wlroots: https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by manio** [comment] 2024-11-23 17:15
@emersion Thanks for the guide, helped a lot :)
Now it started, but only one graphic card is available from two (2 monitors working, 4 are black)
Log: https://skyboo.net/temp/sway/sway-not-starting3.log

If it matters to you: recent ArchLinux hyprland version also have the same problem (exactly same two monitors are working, rest is black)

**Comment by emersion** [comment] 2024-11-24 22:49
@manio, sounds like a separate issue, could you open a new one?

**Closed** 2024-11-24 22:48 UTC
Labels: bug

**Comment by manio** [comment] 2024-11-25 04:53
@emersion Another one? It is the one you closed: #8465 :)

**Comment by askiiart** [comment] 2024-11-26 02:48
I'm not sure how this is a separate issue; I'm not lost on Hyprland having the same issue for @manio , but the symptoms at least are the exact same as far as I've tested (haven't compiled Sway or tested Hyprland), so I'm not sure it's quite right to split that into a new issue, but maybe I'm missing something.

**Comment by askiiart** [comment] 2024-11-26 17:45
Ah alright, thank you.
