### ISSUE TITLE
Touchpad randomly gets ignored

### ISSUE THREAD

**Issue by zsugabubus** [swaywm/sway#4778] opened 2019-12-02 20:57 UTC
I'm on laptop (without any external mouse) and I recently noticed that touchpad randomly gets ignored for an uncertain time. I cannot reproduce it, but I guess it's related to window openings/closings.

Config related to touchpad:
```cfg
input type:touchpad {
    left_handed enabled
    tap enabled
    dwt enabled
    # events disabled_on_external_mouse
}
```

`swaymsg -t get_inputs` shows the exact same output. [Debug log](https://gist.github.com/zsugabubus/789700749819e2da539e7d9c3762c4cf) from last time it occurred, one minute.

**Comment by FreeFull** [comment] 2019-12-02 23:24
`dwt enabled` will mean that your touchpad won't work while you're writing, but it should work otherwise.

If `dwt enabled` isn't the problem, could you check `dmesg` to make sure it's not actually the touchpad disconnecting/disappearing for a time (The relevant lines will likely contain `psmouse`)? If that's the case, there isn't really anything sway can do, it's either a driver or a hardware fault.

**Comment by zsugabubus** [comment] 2019-12-03 00:09
> dwt enabled will mean that your touchpad won't work while you're writing, but it should work otherwise.

Don't think it causes (if works correctly). Long minutes (maybe 1-10-20-30) used to elapse when it magically starts working again.

> could you check dmesg to make sure it's not actually the touchpad disconnecting/disappearing for a time

Couldn't find anything interesting in `dmesg`. Everything is silent there.

> If that's the case, there isn't really anything sway can do, it's either a driver or a hardware fault.

According to `evtest` the touchpad sends the events meanwhile. That's why I thought it's not a problem with the touchpad.

**Comment by RedSoxFan** [comment] 2019-12-03 00:36
Can you please also try `sudo libinput debug-events` when it's not working and see if the events are registering there?

**Comment by zsugabubus** [comment] 2019-12-03 00:44
Of course.

**Comment by zsugabubus** [comment] 2019-12-03 21:05
@RedSoxFan, libinput receives events.

**Comment by RedSoxFan** [comment] 2019-12-06 02:00
Is the cursor still visible when this happens?

**Comment by mlaferrera** [comment] 2019-12-13 19:27
I'm running into the same issue with my laptop touchpad (no external mouse). The cursor does remain and libinput is still receiving events. Nothing in dmesg.

**Comment by zsugabubus** [comment] 2019-12-16 07:21
@RedSoxFan, could you give me some hints where to place debug messages or where things could go wrong? If I compile `sway` from source because of my other issue it would be great if I could (try) solve it too.

**Comment by RedSoxFan** [comment] 2019-12-16 13:11
@zsugabubus You can try starting off with logging the events in the `handle_cursor_*` functions in `sway/input/cursor.c` to see if the events are coming through correctly. After that, the handlers in the seatop files would be the next place to look

**Comment by zsugabubus** [comment] 2019-12-16 15:10
Just now look that I forgot to mention that it's true that I have no external mouse but I have a [pointing stick](https://en.wikipedia.org/wiki/Pointing_stick) that always works.

**Comment by RedSoxFan** [comment] 2019-12-17 00:47
> Just now look that I forgot to mention that it's true that I have no external mouse but I have a [pointing stick](https://en.wikipedia.org/wiki/Pointing_stick) that always works.

I'd recommend adding the input identifier to any logs you add then. I'd also be curious to know if disabling events from the pointing stick changes anything

**Comment by zsugabubus** [comment] 2020-02-11 22:33
I think I have something. Now it occurred again but it's interesting because… I was using `i3`.

Reading through my previous comments…
- libinput receives events so it's not a hardware fault (although it's a 6-7-years-old laptop);
- it's not an issue with `sway` or `X` (or both misbehaves the same?).

I don't know how input handling is done in depth, but I guess there is nothing above libinput that could block the events. So maybe this “disable-while-typing” thing is faulty in libinput? Is it possible?

…But previously I said that `sudo libinput debug-events` shows events so it can't be an issue with libinput?

What do you think?

**Comment by RedSoxFan** [comment] 2020-02-11 23:49
You can try: `sudo libinput debug-events --enable-dwt` and see if that makes a difference in what libinput reports (without any flags, `libinput debug-events` uses the default configs for the devices. mirroring your full config may show a difference).

Since this is reproducible in i3, I'm going to close this as it doesn't appear to be a Sway issue. Feel free to reopen if further investigation proves otherwise.

**Closed by RedSoxFan** 2020-02-11 23:49 UTC
