### ISSUE TITLE
in rox, creating a new folder operation causes Sway to freeze

### ISSUE THREAD

**Issue by wxg4net** [swaywm/sway#7824] opened 2023-11-18 00:45 UTC
[arch:~] sway -v
sway version 1.9-dev-5c99b988 (Nov 17 2023, branch 'makepkg')

1、process of sway use  100% cpu
2、some logs as bellow

```
Thread 1 (Thread 0x7f41e85449c0 (LWP 35836) "sway"):
#0  0x00007f41e9346724 in  () at /usr/lib/libc.so.6
#1  0x00007f41e937148e in  () at /usr/lib/libc.so.6
#2  0x00007f41e940fd14 in __snprintf_chk () at /usr/lib/libc.so.6
#3  0x00005598aa190928 in  ()
#4  0x00007f41e95fc2a9 in _wlr_log (verbosity=<optimized out>, fmt=<optimized out>) at ../wlroots-git/util/log.c:102
#5  0x00007f41e960cd90 in xwm_selection_send_data (mime_type=0x5598b1a98f40 "text/plain;charset=utf-8", req=0x5598b215da00, selection=<optimized out>) at ../wlroots-git/xwayland/selection/outgoing.c:311
#6  xwm_handle_selection_request (req=0x5598b215da00, xwm=0x5598ac1b9420) at ../wlroots-git/xwayland/selection/outgoing.c:438
#7  xwm_handle_selection_event (event=0x5598b215da00, xwm=0x5598ac1b9420) at ../wlroots-git/xwayland/selection/selection.c:162
#8  x11_event_handler (fd=<optimized out>, mask=<optimized out>, data=<optimized out>) at ../wlroots-git/xwayland/xwm.c:1649
#9  x11_event_handler (fd=<optimized out>, mask=<optimized out>, data=<optimized out>) at ../wlroots-git/xwayland/xwm.c:1631
```

[sway-sway version 1.9-dev-5c99b988.log](https://github.com/swaywm/sway/files/13398530/sway-sway.version.1.9-dev-5c99b988.log)

**Comment by emersion** [comment] 2023-11-18 09:27
Duplicate of https://github.com/swaywm/sway/issues/6974

**Closed by emersion** 2023-11-18 09:27 UTC
Labels: bug
