### ISSUE TITLE
Unexpected shutdown of the laptop when the screen is turned off

### ISSUE THREAD

**Issue by ghost** [swaywm/sway#6110] opened 2021-03-18 14:27 UTC
Laptop: 20Q0000MRT ThinkPad X390
OS: Arch Linux
Linux kernel: 5.11.6-arch1-1

$ pacman -Q | grep sway
sway 1:1.5.1-1
swaybg 1.0-4
swayidle 1.6-1
swaylock 1.5-1

swaymsg -t get_version
sway version 1.5.1

My sway [config](https://gist.github.com/dgpat/b725c22d4401af71b61270f492f7346d)

I have a very strange behavior of the screen off mode.

When I run swayidle with the following script:
```
#!/bin/bash
swayidle -w \
  timeout  5 'swaylock -f -i ~/.bin/lock.png' \
  timeout  10 'swaymsg "output * dpms off"' \
      resume  'swaymsg "output * dpms on"' \
  before-sleep 'swaylock -f -i ~/.bin/lock.png'
```
my laptop (after turning off the screen) shuts down unexpectedly in the interval (5-15 minutes).

There are no shutdown events in the journald log.

This behavior started with kernel 5.10 and continues to this day.
There was no such behavior on linux-lts kernel 5.4.

**Comment by emersion** [comment] 2021-03-18 15:52
Maybe related to logind automagically doing stuff behind our back. Or could also be a kernel bug, I suppose.

**Comment by kennylevinsen** [comment] 2021-03-18 16:01
Yeah, I'd also suspect logind actions, possibly combined with a failed suspend/hibernate attempt. Start out by setting all actions in /etc/systemd/logind.conf to Ignore, including those that might not seem relevant, and see if that makes a difference.

**Comment by dgpat** [comment] 2021-03-18 16:07
I also thought about logind at first. But I have default settings:
```
cat /etc/systemd/logind.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it under the
#  terms of the GNU Lesser General Public License as published by the Free
#  Software Foundation; either version 2.1 of the License, or (at your option)
#  any later version.
#
# Entries in this file show the compile time defaults. Local configuration
# should be created by either modifying this file, or by creating "drop-ins" in
# the system.conf.d/ subdirectory. The latter is generally recommended.
# Defaults can be restored by simply deleting this file and all drop-ins.
#
# See logind.conf(5) for details.

[Login]
#NAutoVTs=6
#ReserveVT=6
#KillUserProcesses=no
#KillOnlyUsers=
#KillExcludeUsers=root
#InhibitDelayMaxSec=5
#UserStopDelaySec=10
#HandlePowerKey=poweroff
#HandleSuspendKey=suspend
#HandleHibernateKey=hibernate
#HandleLidSwitch=suspend
#HandleLidSwitchExternalPower=suspend
#HandleLidSwitchDocked=ignore
#HandleRebootKey=reboot
#PowerKeyIgnoreInhibited=no
#SuspendKeyIgnoreInhibited=no
#HibernateKeyIgnoreInhibited=no
#LidSwitchIgnoreInhibited=yes
#RebootKeyIgnoreInhibited=no
#HoldoffTimeoutSec=30s
#IdleAction=ignore
#IdleActionSec=30min
#RuntimeDirectorySize=10%
#RuntimeDirectoryInodes=400k
#RemoveIPC=yes
#InhibitorsMax=8192
#SessionsMax=8192```

And when I use this script (without turning off the screen, just lock) - everything is ok. No shutdown 
```#!/bin/bash
swayidle -w \
  timeout  5 'swaylock -f -i ~/.bin/lock.png' \
  before-sleep 'swaylock -f -i ~/.bin/lock.png'```

**Comment by kennylevinsen** [comment] 2021-03-18 16:29
> I also thought about logind at first. But I have default settings

The defaults tend to cause problems.

**Comment by dgpat** [comment] 2021-03-18 18:46
@kennylevinsen which of the default values of the /etc/systemd/logind.conf (in your opinion) can have such an effect?

I remind you that if the screen does not turn off (dpms), then everything is fine.

In addition, if the shutdown had been caused by logind, it would have been displayed in the journald log.

**Comment by kennylevinsen** [comment] 2021-03-19 13:29
> @kennylevinsen which of the default values of the /etc/systemd/logind.conf (in your opinion) can have such an effect?

Any that isn't "ignore". Things like external monitor detection tend to break when displays go to sleep for example, leading to unexpected rule execution. There isn't really a point in having logind do any of this anyway.

Point is - it's known to be fragile, so ruling it out would be useful.

**Comment by dgpat** [comment] 2021-03-20 14:32
I don't connect any external monitors

I tried to specify this value:
`IdleAction=ignore`

But the problem continues.

But, when I set "CPU power management" to "disable" in the BIOS, the problem was solved.

I don't understand where the problem is yet :(

**Comment by kennylevinsen** [comment] 2021-03-20 14:41
Are you undervolting perhaps? I imagine you're either crashing in a lower power state, or failing a suspend attempt. Remember that the journal is useless if you're crashing, as you can't rely on writes being flushed.

> I tried to specify this value

All the Handle* and *Action fields please. :)

**Comment by dgpat** [comment] 2021-03-21 17:48
@kennylevinsen 

I set the following parameters:
`
HandlePowerKey=ignore
HandleSuspendKey=ignore
HandleHibernateKey=ignore
HandleLidSwitch=ignore
HandleLidSwitchExternalPower=ignore
HandleLidSwitchDocked=ignore
HandleRebootKey=ignore
IdleAction=ignore
`
And that didn't solve the problem.
The laptop continues to shut down unexpectedly when the screen is turned off :(

**Comment by neurlang** [comment] 2021-03-27 10:35
@dgpat

I had a similar unexpected shutdown problem, but on desktop pc.

It happened only on Linux, Windows ran fine.

The cause turned out to be not 100% attached cpu heat sink.

**Comment by dgpat** [comment] 2021-03-27 16:15
@neurlang thanks for reply!
But I already wrote that the computer shutdown in IDLE mode. And shutdown happens when the screen turns off (DPMS). 
When the screen remains on, the laptop DOES NOT UNEXPECTED SHUTDOWN.

**Comment by languitar** [comment] 2021-08-18 19:59
One think I noticed: I have my laptop under my desk with its lid closed, only using external monitors. If swayidle turns of the external screens, the lid detection kicks in and starts to suspend the laptop.

**Comment by sachinchaudhary1808** [comment] 2024-06-19 10:52
same issue lol

**Comment by kennylevinsen** [comment] 2024-06-19 11:38
I'll close this as it is unrelated to sway and swayidle.

**Closed by kennylevinsen** 2024-06-19 11:38 UTC
Labels: bug

**Comment by sachinchaudhary1808** [comment] 2024-06-19 12:39
> I'll close this as it is unrelated to sway and swayidle.

well  for now i have installed hyprlock and if i encounter that issues again i will report you

**Comment by kennylevinsen** [comment] 2024-06-19 12:46
Even if it happens with hyprlock it is still unrelated to sway and swayidle. The most likely cause is logind configuration, other system configuration, or a kernel panic.

The only way sway or swayidle would ever shut down your computer is if you explicitly tell them to run "poweroff" or similar command.

**Comment by sachinchaudhary1808** [comment] 2024-06-19 13:32
> Even if it happens with hyprlock it is still unrelated to sway and swayidle. The most likely cause is logind configuration, other system configuration, or a kernel panic.
> 
> The only way sway or swayidle would ever shut down your computer is if you explicitly tell them to run "poweroff" or similar command.

ok u are right i found the cuz it was dpms miss configuration sorry
