### ISSUE TITLE
fullscreen game not displaying properly with 'scaling 2'

### ISSUE THREAD

**Issue by bbigras** [swaywm/sway#3338] opened 2018-12-28 05:45 UTC
sway version d440468d2deb31d311564a5b796608136cf99e49

My resolution is 3200x1800 . With 'scale 2' the game is not displayed properly. It's fine if I remove 'scale 1'. Is there a way to set 'scale 1' per window? Like with `for_window`?

![image](https://user-images.githubusercontent.com/24027/50504153-a50cbd80-0a39-11e9-8cb8-3618f9534fcf.png)

**Comment by terminalnode** [comment] 2018-12-28 14:01
I've had the same issue with Stellaris. Furthermore when I have two screens connected and start the game on the non-scaled screen it still has problems displaying as shown in the screenshot below.

![screenshot](https://user-images.githubusercontent.com/2683344/50517600-513dbb00-0ab1-11e9-9532-7c0a2b8760c1.png)

**Comment by emersion** [comment] 2019-01-14 08:10
>Is there a way to set 'scale 1' per window?

No, this is too complicated.

**Comment by GoodClover** [comment] 2024-07-29 19:11
Problem is still around in sway 1.9.

Running Osu in full-screen with scale 2, the game is pixelated, being rendered at half the resolution and then nearest-neighbor up-scaled.  In windowed mode, it is working correctly at full window resolution.  However, this is with it set to "Default" resolution, the game detects an option for my full display resolution and selecting it works.  (For completion, changing between OpenGL and Vulkan changes nothing.  Osu is an SDL game.)

This mirrors what happens to XWayland programs.  However those always have the issue, including in windowed mode, and don't have an option for correct full resolution.  (I have double-checked Osu is running direct to Wayland SDL_VIDEODRIVER=wayland, not via X.)

I would not be surprised if this is related to XWayland's problem, that sway is messing up negotiating resolution & scaling.

**Comment by Nefsen402** [comment] 2024-07-29 19:14
This is an issue with all xwayland clients. the Xwayland server needs changes to properly support this and those improvements are unfortunately at a standstill. It might be worth asking OSU developers to release a build with native wayland support.

Closing as a duplicate of https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/1635

**Closed by Nefsen402** 2024-07-29 19:14 UTC
Labels: bug

**Comment by GoodClover** [comment] 2024-07-29 19:18
I explicitly pointed out in my message that Osu was running in Wayland mode, not via XWayland.

**Comment by Nefsen402** [comment] 2024-07-29 19:19
This is a bug with OSU then.

**Comment by Nefsen402** [comment] 2024-07-29 19:22
IIRC correctly HIDPI scaling with SDL clients is optional and disabled by default.
