### ISSUE TITLE
keyboard not work sometimes if i login

### ISSUE THREAD

**Issue by kristoferus75** [swaywm/sway#4028] opened 2019-04-08 11:47 UTC
Hi !

Version:

with sway 1.08

I have sometimes the problem that the keyboard doesn't work if i login !

If i disconnect the usb keyboard and connect it again it work :-(

config
```
input 1133:49941:Logitech_Logitech_USB_Keyboard {
    xkb_layout de
    xkb_model logitech_base
    xkb_variant nodeadkeys
    #xkb_options grp:alt_shift_toggle
    #repeat_delay 250
    #repeat_rate 50
```

this is in the log file:

log file
```
glamor: No eglstream capable devices found
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
Errors from xkbcomp are not fatal to the X server
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 374, clipping.
>                   X11 cannot support keycodes above 255.
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
Errors from xkbcomp are not fatal to the X server
xkbcommon: ERROR: Unrecognized RMLVO variant "nodeadkeys" was ignored
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 374, clipping.
>                   X11 cannot support keycodes above 255.
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
Errors from xkbcomp are not fatal to the X server
2019-04-07 18:26:31 - [wlroots-0.5.0/xwayland/xwm.c:1267] xcb error: op ChangeProperty (no minor), code Window (no 
extension), sequence 244, value 6291457

```
kind regards

**Comment by RedSoxFan** [comment] 2019-04-11 03:35
Can you post a full debug log (`sway -d >sway.log 2>&1`)?

Also, if you run `sudo libinput debug-events` when the keyboard is not working, do the events show up?

**Comment by kristoferus75** [comment] 2019-04-12 07:50
ok now the full  log file 
if the keyboard not work i cant press keys ?!

[sway2.log](https://github.com/swaywm/sway/files/3072158/sway2.log)

**Comment by RedSoxFan** [comment] 2019-04-12 08:17
> if the keyboard not work i cant press keys -

Right... The device isn't showing up in the log anyway so the debug events output wouldn't be useful anyway.

Are you logging in from a TTY or a display manager?

**Comment by kristoferus75** [comment] 2019-04-12 12:18
i have started sway with lightdm with a startup script with your command : sway -d >sway.log 2>&1 -> display manager !

**Comment by RedSoxFan** [comment] 2019-04-12 17:11
> lightdm

Then this is a duplicate of #3843 and a lightdm bug

**Closed by RedSoxFan** 2019-04-12 17:11 UTC
