### ISSUE TITLE
Build fail on get_current_time_msec

### ISSUE THREAD

**Issue by LeForjeron** [swaywm/sway#6087] opened 2021-03-07 20:48 UTC
Building sway master with wlroots master gives the following error :

/usr/lib/libwlroots.a : in function get_current_time_msec : Multiple definition of get_current_time_msec.

This is on a machine running kiss linux, with musl.

**Comment by LeForjeron** [comment] 2021-03-07 20:52
The fonction is defined in sway/sway/common/util.c and wlroots/util/time.c

**Comment by emersion** [comment] 2021-03-07 20:54
Fixed in master.

**Comment by emersion** [comment] 2021-03-07 20:54
Ah, it's not?

**Comment by emersion** [comment] 2021-03-07 20:54
Ref https://github.com/swaywm/wlroots/issues/1892

**Comment by LeForjeron** [comment] 2021-03-07 21:05
> Ah, it's not?

Doesn't look like it. And I can confirm sway build fine when building wlroots as shared

**Comment by Xyene** [comment] 2021-03-07 21:42
Yeah, sway-side this is a duplicate of https://github.com/swaywm/sway/issues/5514. I agree we should do _something_ about it, not sure what.

Perhaps just renaming the sway function here is enough, even if it's not the "principled" approach. Alternatively, we could make `get_current_time_msec` be `wlr_get_current_time_msec`, since it's more generally useful.

**Closed by Xyene** 2021-03-07 21:42 UTC
Labels: bug

**Comment by emersion** [comment] 2021-03-07 21:43
I'd rather not make the wlroots function public.

**Comment by kennylevinsen** [comment] 2021-03-07 21:47
It's rather annoying that we can't filter/resolve symbols on .o/.a, only on .so...

Who's up for writing a linker/object filter?

**Comment by jbeich** [comment] 2021-03-12 12:02
> Who's up for writing a linker/object filter?

Why not just mark wlroots symbol as  `__attribute__((weak))`?

**Comment by emersion** [comment] 2021-03-12 12:04
That sounds pretty dangerous. If a compositor comes up with a different function which has the same name as one of wlroots' internal functions, then everything breaks pretty badly.
